### ISSUE TITLE
Diagnostic for usage of A<T> outside a call specification

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1005]
It would be useful to add a diagnostic to the analyzer for incorrect argument constraint usage. For instance, usage of `A<T>` outside a call specification could trigger an error (it will fail at runtime anyway, but it's even better to tell the user immediately).

**Comment by adamralph** [comment]
I think this could be split into two issues, one for the `A<T>` outside a spec, and another for the nullable type parameter concern.

> This syntax could also be achieved if we had a "bottom type" in C#.

I've been saying for years that `void` should have been type. I wonder that would fill the role of a bottom type?

**Comment by thomaslevesque** [comment]
> I think this could be split into two issues, one for the A<T> outside a spec, and another for the nullable type parameter concern.

Makes sense.

> I've been saying for years that void should have been type. I wonder that would fill the role of a bottom type?

Maybe. There was a proposal for a "Never" type (https://github.com/dotnet/roslyn/issues/1226), but I don't see it on the [new repo](https://github.com/dotnet/csharplang) for C# language design.

**Comment by blairconrad** [comment]
Reopening, since we forgot docs.

**Comment by blairconrad** [comment]
This issue was fixed in [Release 3.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/3.3.0).
