### ISSUE TITLE
stop requiring event arguments to extend EventArgs in event raisers for .NET 4.5

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#1008]
Equivalent of #361, for .NET 4.5.

Depends on #991.

**Comment by thomaslevesque** [comment]
Now that we have switched to the new csproj format, we can easily add a net45 target and make this change. Removing the `on-hold` tag.

**Comment by blairconrad** [comment]
I was thinking about this. I couldn't figure out how to test it, since our
specs will target 461, no? Unless we use a file reference instead of
project. Of course there is probably some way that I just don't know about.

**Comment by thomaslevesque** [comment]
Good point, I didn't think about that. To be honest, I'm not sure there's
much value in testing this specific feature for net40. Unless we can find a
way to force a reference to net40 instead of net45, but then we wouldn't be
testing net45... We'd need a way to add a target without adding a new
target framework, and I don't think that's possible with the current
tooling.

**Comment by blairconrad** [comment]
> Good point, I didn't think about that. To be honest, I'm not sure there's
much value in testing this specific feature for net40.

Yeah, I could support not testing that one feature, but as you say, it's likely either test all of net40 or all of net45, but not both.

**Comment by thomaslevesque** [comment]
net45 is 5 years old, and many libraries no longer support net40. I think it's acceptable not to test net45, especially when the only difference with net45 is this small `EventArgs` matter.

**Comment by blairconrad** [comment]
> net45 is 5 years old, and many libraries no longer support net40. I think it's acceptable not to test net40,

I thought you were going to end with "acceptable to not test net45", since net40 is the old one.
How do you feel about _that_?

**Comment by thomaslevesque** [comment]
> I thought you were going to end with "acceptable to not test net45", since net40 is the old one.
> How do you feel about that?

Well, I'd rather test the new one... and anyway, since the test project targets net461, it will pick the net45 library, not the net40 one. I don't think we *could* test the net40 one even if we wanted to (unless there's no net45 version)

**Comment by blairconrad** [comment]
HA! There was the word **not** in there. Which I should've seen at least when I copied and replied.

:blush:

Yes. I would rather test net45 as well. Sorry!

**Comment by adamralph** [comment]
I'm wondering whether we should do away with the complexity and increase the minimum required framework to 4.5.

**Comment by thomaslevesque** [comment]
> I'm wondering whether we should do away with the complexity and increase the minimum required framework to 4.5.

It's always an option, if it becomes too much of a burden, but I don't think we're there yet. It's only an issue for unit testing. For the library itself, adding a net45 target is a no-brainer now.

**Comment by adamralph** [comment]
> adding a net45 target is a no-brainer now.

True, but we'll still need to `#if` some code in order to provide extra capabilities in the net45 assembly in comparison with the net40 assembly. Given the age of net45, I'd have no problem with us dropping support for net40 now.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).
