### ISSUE TITLE
Use single quotes consistently in messages

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#1011]
Sometime we use double quotes, sometimes single, sometimes none. Let's make this consistent.

See https://github.com/FakeItEasy/FakeItEasy/pull/1001/files#r104390257

**Comment by thomaslevesque** [comment]
And there are also places where we use no quotes at all.

**Comment by blairconrad** [comment]
So...

Double? Single?

I kind of like single. If nothing else, they're easier to search for and easier to write inside double-quoted strings.

**Comment by thomaslevesque** [comment]
I like single quotes too

**Comment by adamralph** [comment]
👍 to singles.

**Comment by thomaslevesque** [comment]
BTW, quotes aren't the only thing that's inconsistent when we include type names in messages. Sometimes we use `.FullNameCSharp()`, but sometimes not. So we sometimes have things like `IFoo<Bar>`, and sometimes ``IFoo`1[Bar]``.

Even though the C# format looks nicer, I don't think we should use it. FakeItEasy can be consumed from VB.NET too, not just C#, so there's no reason to use the C# format over the VB format. For consistency, we should probably stick to the CLR format.

**Comment by blairconrad** [comment]
I'm fine with dropping the C# formatting.

Unfortunately, I'm now wondering whether we shouldn't also drop the quotes altogether. It's not like we're going to have a space in the middle of a type name or anything. Nor would a type be `null`. There should be no difficulty interpreting which type we're talking about when reading a message.
I guess I'm raising the spectre of "no quotes" again. But if you still prefer single, that's fine too.

**Comment by thomaslevesque** [comment]
Well, we considered whether to use single or double quotes, but I guess we forgot about the "no quotes" option... Now that you mention it, I think I like it.

**Comment by blairconrad** [comment]
> I guess we forgot about the "no quotes" option.

I had.

**Comment by adamralph** [comment]
- CLR formattting rather than C# formatting: 👍 agreed.
- Dropping quotes for terms which _we know will **never** contain spaces_: 👍 agreed

**Comment by blairconrad** [comment]
I can pick this up, but wonder if it shouldn't be two issues after the last comment.

1. single (or no) quotes
2. CLR formatting

**Comment by adamralph** [comment]
👍 to two issues.

**Comment by thomaslevesque** [comment]
Yes, it makes sense to split

**Comment by blairconrad** [comment]
This issue was fixed in [Release 3.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/3.3.0).
