### ISSUE TITLE
Get rid of ITaggable

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1012]
This interface is intended for internal use only, but due to an issue in Castle.Core, it has to be exposed publicly. As @blairconrad suggested in the chat, we could probably get rid of it and use a `ConditionalWeakTable<object, FakeManager>` instead.

**Comment by thomaslevesque** [comment]
Added `breaking` tag because we would be removing a public interface.

**Comment by blairconrad** [comment]
Note that we already use a `ConditionalWeakTable` [in TaggableAdapter])(https://github.com/FakeItEasy/FakeItEasy/blob/f6532b13e26e1c588dd4f7d2257316a3e5366df4/src/FakeItEasy/Core/DefaultFakeManagerAccessor.cs#L73) for Fake delegates. One option would just be to use it for all Fakes.

There's potentially a performance concern, as we keep adding things to the table and looking things up, but I was never completely comfortable with [adding an additional interface to our Fakes](https://github.com/FakeItEasy/FakeItEasy/blob/d182be4e2b678c976031972107ac7c9a4677546b/src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs#L183) anyhow.

**Comment by thomaslevesque** [comment]
> There's potentially a performance concern, as we keep adding things to the table and looking things up

Well, it's a *weak* table, so the objects in it will stay there only until they're GC'd. I'm not overly worried about this, but I can try to benchmark it.

**Comment by blairconrad** [comment]
I agree that it's probably not a big deal.

**Comment by thomaslevesque** [comment]
This might be a little harder than we thought...

I can make everything work with a `ConditionalWeakTable`, except two tests:

- `FakingClassesTests.Should_be_able_to_change_the_configuration_of_a_fake_after_binary_deserializing_it`
- `FakingClassesTests.Should_be_able_to_use_a_fake_after_binary_deserializing_it`

Maybe it could be fixed, but in my current solution, the `ObjectMemberRule` has a reference to the `DefaultFakeManagerAccessor`, which can't be serialized because a `ConditionalWeakTable` is (obviously) not serializable.

I'm not sure what we could do about it, or even why it's important that a fake can be serialized...

**Comment by adamralph** [comment]
> why it's important that a fake can be serialized

Some test runners, e.g. xunit, serialize the arguments to data-driven test methods. It's conceivable that these arguments could be fakes, specially when using one of the automatic fixture libraries that extend FIE. The advantage of the xunit runner being able to serialize the arguments is that all the test cases can be evaluated during test discovery and reported to runners _before_ execution. If the arguments cannot be serialized, xunit falls back to run-time discovery but this results in a degraded experience when using a test runner UI since you cannot see or select individual test cases before running them.

**Comment by thomaslevesque** [comment]
Thanks for the explanation @adamralph. I wouldn't have thought of it. So yeah, it's pretty important to keep serialization working (on full .NET at least)

**Comment by blairconrad** [comment]
... Except for fake delegates, I think.

**Comment by blairconrad** [comment]
My last comment doesn't come across clearly. The point I was trying to make is that serialization will already not work for faked delegates, because we attach the `ITaggable` using the `ConditionalWeakTable`.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.0.0).
