### ISSUE TITLE
Drop resource files and move message strings to the code

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1017]
As discussed in #1013 

Error messages are currently in a resource file (.resx), but are not localized and there's no plan to localize them.

Also, the custom tool that generates code from the resource files produces code that is not compatible with .NET Standard 1.6, so it's currently disconnected. This means that adding a string to the resource file no longer updates the corresponding code file.

Since we don't need the features provided by resx files and can't use the built-in custom tool, it would make sense to convert the resources to string constants in a class. We could also use the approach suggested by @blairconrad in https://github.com/FakeItEasy/FakeItEasy/pull/1013#issuecomment-285865877

**Comment by blairconrad** [comment]
This issue was fixed in [Release 3.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.2.0).
