### ISSUE TITLE
Mono debugger crash : malloc: *** error for object 0xa5029c: pointer being freed was not allocated

### ISSUE THREAD

**Issue by sushihangover** [FakeItEasy/FakeItEasy#1019]
`<package id="FakeItEasy" version="3.1.0" targetFramework="net45" />`
```
mono(25462,0xb039b000) malloc: *** error for object 0x7be530e0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Stacktrace:
Native stacktrace:

	0   mono                                0x0010da66 mono_handle_native_sigsegv + 342
	1   mono                                0x00164561 sigabrt_signal_handler + 145
	2   libsystem_platform.dylib            0x9ebdd79b _sigtramp + 43
        ~~~~
```
Re: https://bugzilla.xamarin.com/show_bug.cgi?id=53266

Wondering if everyone has seen this crash under Mono (OS-X/v4.8.0) while inspecting a `A.Fake`-based object. I do not have a Window box available at the moment but "*assuming*" VS/.Net does not crash the debugger while inspecting `A.Fake` instances(?).

```c#
public interface IContact
{
	string Foo { get; set; }
}

[Test]
public void MonoCrash()
{
	var contact = A.Fake<IContact>();
}
```

**Comment by blairconrad** [comment]
Thanks for raising this, @sushihangover.

I don't think this is a problem on Windows:

![image](https://cloud.githubusercontent.com/assets/3275797/23831436/712193d4-06f7-11e7-8973-5f0094f5cf5d.png)

Unfortunately, I'm not sure how to proceed from here. I'm not a mono person at all, and wouldn't begin to know how to proceed. Perhaps some of the other owners know more.

**Comment by thomaslevesque** [comment]
Well, I didn't even *know* FakeItEasy worked on Mono... but I guess it makes sense, since Castle.Core does.

It's likely that the bug is in either Castle.Core or the Mono debugger. Here are a few things you can do to narrow down the problem:
- do the same test with FakeItEasy 2.x (which uses an older version of Castle.Core)
- do the same test with a proxy object created directly from Castle.Core, without using FakeItEasy

**Comment by sushihangover** [comment]
Thanks for the quick reply.

* FakeItEasy 2.x = Same crash...
* Proxy object created directly from Castle.Core = No hard crash, but the Mono soft debugger throws an error and disconnects...

Some more research:
 
* Moq 4.x = Same crash... but it used to work also...

I would need to roll back Mono to a prior version, but I need the recent changes in Mono... *Between a rock and a hard place* 👿 ... the life of an x-plat developer... 😭 

Mono JIT compiler version 4.8.0 (mono-4.8.0-branch/0494d70 Thu Mar  2 21:19:48 EST 2017)

**Comment by adamralph** [comment]
@sushihangover thanks for the update. Good luck with the Mono fix!
