### ISSUE TITLE
Overload for A<>.That.Matches() allowing to access other arguments

### ISSUE THREAD

**Issue by drauch** [FakeItEasy/FakeItEasy#1020]
It would be nice to have an overload of A<>.That.Matches() which allows me to access other arguments passed in, e.g. something like this:

```c#
A.CallTo( ()=>myObj.Foo(
    A<Param1Type>._,
    A<Param2Type>.That.Matches( (arg, ctx) => arg.ID == ctx.Arguments[0].Param2ID )
```

This would help if you want to assert that a parameter is passed correctly if it depends on another one (yes, I know, a good API should not have parameters which are transitively dependent on each other, but we are not living in an ivory tower).

Currently, the only workaround seems to be:

```c#
A.CallTo( myObj ).Where( ... )
```

Unfortunately you must specify the method name in the Where() as well, and do no longer have refactoring safety for method name and number of arguments.

I'd like to provide a PR too, but I do not have time at the moment. So I thought, I'll just post a feature request.

Best regards,
D.R.

**Comment by thomaslevesque** [comment]
Hi @drauch,

Thanks for the suggestion.

> Currently, the only workaround seems to be:
> 
>     A.CallTo( myObj ).Where( ... )

Actually you can also do this:

    A.CallTo(() => obj.Foo(A<Param1Type>._, A<Param2Type>._))
        .WhenArgumentsMatch(args => args.Get<Param2Type>("param2").ID == args.Get<Param1Type>("param1").Param2ID)

It's a bit verbose, but it works...

It would probably be useful to add helper overloads for `WhenArgumentsMatch` to enable this syntax:

    A.CallTo(() => obj.Foo(A<Param1Type>._, A<Param2Type>._))
        .WhenArgumentsMatch((Param1Type param1, Param2Type param2) => param1.Param2ID == param2.ID)

(we already do this for `Invokes`, `Throws` and `ReturnsLazily`)

**Comment by blairconrad** [comment]
Ha, @thomaslevesque! Good one. I did not remember this.

**Comment by blairconrad** [comment]
… possibly because of the [help around this feature](https://readthedocs.org/search/?q=WhenArgumentsMatch&check_keywords=yes&area=default&project=fakeiteasy&version=stable&type=file).

**Comment by thomaslevesque** [comment]
> … possibly because of the help around this feature.

Oops!

**Comment by thomaslevesque** [comment]
> … possibly because of the help around this feature.

In fact, the search feature on ReadTheDocs looks completely broken... It doesn't give any results for any search term.

**Comment by blairconrad** [comment]
@drauch, @thomaslevesque found [Overriding argument matchers](http://fakeiteasy.readthedocs.io/en/stable/argument-constraints/#overriding-argument-matchers), which describes (among other things) `WhenArgumentsMatch`.

If this works for you, I suggest using it, and would like to pursue #1021 instead of this issue. Objections to closing this?

**Comment by drauch** [comment]
Yeah, that will do 👍

**Comment by adamralph** [comment]
Added "wontfix" - is that correct?

**Comment by thomaslevesque** [comment]
> Added "wontfix" - is that correct?

Yes. We did #1021 instead, which achieves the same result.
