### ISSUE TITLE
Add strongly typed overloads for WhenArgumentsMatch

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1021]
As discussed in https://github.com/FakeItEasy/FakeItEasy/issues/1020#issuecomment-286133698

Currently we have strongly typed overloads for `Invokes`, `Throws` and `ReturnsLazily`. It would be helpful to add similar overloads for `WhenArgumentsMatch`, so that instead of this:

    .WhenArgumentsMatch(args => args.Get<T1>(0).Id == args.Get<T2>(1).OtherId)

we can write this:

    .WhenArgumentsMatch((T1 p1, T2 p2) => p1.Id == p2.OtherId)

**Comment by blairconrad** [comment]
I wonder if this shouldn't supersede #1020.
If we implement it, and it's not enough power, then I'd be inclined to say "just use the sledgehammer of `A.CallTo(fake, call=>predicate(call))`.

**Comment by thomaslevesque** [comment]
> I wonder if this shouldn't supersede #1020.

👍

**Comment by blairconrad** [comment]
This issue was fixed in [Release 3.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.2.0).
