### ISSUE TITLE
Deprecate FakeObjectCallExtensions.Write and .WriteToConsole

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1030]
From https://github.com/FakeItEasy/FakeItEasy/pull/1029#discussion_r107910202.

They don't really seem to fit here.

Once they're deprecated, we should

- [ ] create an issue for removing them in the next major release

**Comment by adamralph** [comment]
There is an unchecked item in the description:

> create an issue for removing them in the next major release

Was this issue raised?

**Comment by blairconrad** [comment]
Nice catch, @adamralph.

**Comment by blairconrad** [comment]
This issue was fixed in [Release 3.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.2.0).
