### ISSUE TITLE
Migrate to VS2017 and new csproj

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1059]
project.json is obsolete; it has never been very well supported in VS215, and is not supported at all in VS2017. We can probably expect support for it to be progressively dropped by most tools. VS2017 can't open the project.json projects in the FakeItEasy solution, which forces us to keep using VS2015.

We should migrate to the new csproj format, which has many benefits:
- no need to maintain separate projects for net40/netstd (see #991)
- easy to add new targets (e.g. net45, see #1008)
- much more concise than current csproj
- no need to list all source files in the project
- get rid of FakeItEasy.nuspec, packages.config and most of AssemblyInfo.cs; everything is in the csproj

**Comment by blairconrad** [comment]
I thought we already had one of these issues. Shows what I know.

> get rid of FakeItEasy.nuspec, packages.config and most of AssemblyInfo.cs; everything is in the csproj

I am not entirely sold on these benefits. For my money, the versioning and packaging support is still weak in VS2017, but I'm willing to be convinced otherwise. And even if I'm right, we can still make the switch.

Oh. How's StyleCop/FxCop support? I had issues with StyleCop.Analyzers under VS2017 for SelfInitializingFakes, as you know…

Other than these concerns, I'm for the change.

Oh. I don't think this counts an "enhancement", as it should be transparent to users, no?

**Comment by thomaslevesque** [comment]
> For my money, the versioning and packaging support is still weak in VS2017

How so? What doesn't work as you'd like?

> Oh. How's StyleCop/FxCop support? I had issues with StyleCop.Analyzers under VS2017 for SelfInitializingFakes, as you know…

No idea... I guess that's something we'll need to investigate.

> Oh. I don't think this counts an "enhancement", as it should be transparent to users, no?

True. I'll remove the tag.

**Comment by blairconrad** [comment]
> > For my money, the versioning and packaging support is still weak in VS2017

> How so? What doesn't work as you'd like?

I was unable to find a solution where I could change versions in one place and have the assemblies and nuget packages both be generated with the correct versions. I think interpolation of other variables also did not work well. Specifically where I set the FakeItEasy dependency in the SelfInitializingFakes nupkg to match the reference in the csproj.

**Comment by thomaslevesque** [comment]
Well, maybe it's just because I didn't try any advanced scenario, but for instance in [Linq.Extras](https://github.com/thomaslevesque/Linq.Extras/blob/master/Linq.Extras/Linq.Extras.csproj) I found that just setting the version in the csproj worked pretty well. The version is only in one place, and affects both the assembly and the NuGet package. If you need more flexibility, you can specify a version prefix or suffix: https://github.com/dotnet/sdk/blob/94a3f2856cb09e66ee7472820b4e26fb576b4686/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.DefaultAssemblyInfo.targets#L18-L22

**Comment by blairconrad** [comment]
Ah, maybe the version-setting is fine then.
I have fears that if you combine with GitVersion, you'll end up modifying your committed csproj, though. That always gives me [the willies](https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjlg4PRibPTAhVL6oMKHbcuDRgQFgglMAA&url=http%3A%2F%2Fwww.urbandictionary.com%2Fdefine.php%3Fterm%3DThe%2520Willies&usg=AFQjCNHp1G379UWiUPUp5DbNhFq26ny2Xg&sig2=7z4x6M-8ABFxtMjVMMjIzA).
And that's even assuming GitVersion even knows how to modify the new style csproj. Which I'm too lazy to check.

Anyhow! Enough worrying from me. I'm sure it'll all be fine!

**Comment by thomaslevesque** [comment]
> I have fears that if you combine with GitVersion, you'll end up modifying your committed csproj, though. That always gives me the willies.

Don't you [modify AssemblyInfo.cs in SelfInitializingFakes](https://github.com/blairconrad/SelfInitializingFakes/blob/c51c94b1819c7ea02f35edc9b56b98d2e3c418e6/build.csx#L44)? I don't think modifying the csproj is worse...
Anyway, that's not how I would use GitVersion. I think I'd prefer to get the version from the output, and pass it as a parameter to dotnet build. This way, there's no need to modify any file

**Comment by blairconrad** [comment]
Actually I _generate_ the AssemblyInfo.cs. It's not committed, so I'm less offended by the approach.
It's the modification of a committed file that really galls me. 

I agree that passing a parameter would be preferable. I'd love to rip off such an approach.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).
