### ISSUE TITLE
Add That.IsNotNull convenience overload

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1062]
As @thomaslevesque points out in https://github.com/FakeItEasy/FakeItEasy/issues/1060#issuecomment-295483516

> > (interestingly, we have a IsNull constraint, which isn't very useful since we can just say null, but no IsNotNull...)

> Of course, I forgot about `Not`... we can do `A<T>.That.Not.IsNull()`. But it doesn't read very well...

**Comment by blairconrad** [comment]
Marking as **up-for-grabs**, although if we pursue #1060, we'll probably want to do this first.

**Comment by thomaslevesque** [comment]
While we're at it, we should also add `IsNull`/`IsNotNull` for nullable value types (currently the `where T : class` doesn't support this use case)

**Comment by blairconrad** [comment]
This issue was fixed in [Release 3.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/3.3.0).
