### ISSUE TITLE
Don't expose Not after Not in argument constraint

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1063]
With the current API it's possible to write argument constraint like this:

    A<int>.That.Not.Not.Not.Not.Not.Not.IsEqualTo(42)

Of course, it's a stupid thing to do, and presumably nobody would do this, but it's annoying that `Not` is even valid and shows up in Intellisense after `Not`. We could easily prevent it.

Suggested solution: introduce a `INegatableArgumentContraintManager<T>` interface that inherits from `IArgumentConstraintManager<T>` and exposes the `Not` property, and return it only from `A<T>.That`.

This is a breaking change, so it will have to wait until the next major release.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.0.0).
