### ISSUE TITLE
Identify precise mismatch when a complex argument constraint fails to match an argument

### ISSUE THREAD

**Issue by alexjamesbrown** [FakeItEasy/FakeItEasy#1078]
From http://stackoverflow.com/a/43781563/131809

Consider the following assertion

```c#
var fake = A.Fake<ICustomerService>();

A.CallTo(() => fake.Add(
    A<Customer>.That.Matches(c =>
        c.Property == "123" &&
        c.OtherProperty == "345" &&
        c.AnotherProperty == "456" &&
        c.YetAnotherProperty == "567"
    )
)).MustHaveHappened();
```

This gets a bit messy.

If `c.AnotherProperty` is infact "890" my unit test will not tell me. 
It won't tell me that `AnotherProperty` is wrong. It'll just fail (correctly)

To work around this, I quite often do this:

```c#
var fake = A.Fake<ICustomerService>();

Customer addedCustomer;
A.CallTo(() => fake.Add(A<Customer>._))
    .Invokes(c => addedCustomer = c.GetArgument<Customer>(0));

Assert.IsNotNull(addedCustomer);
Assert.AreEqual("123", addedCustomer.Property);
Assert.AreEqual("345", addedCustomer.OtherProperty);
Assert.AreEqual("456", addedCustomer.AnotherProperty);
Assert.AreEqual("567", addedCustomer.YetAnotherProperty);
```

I guess it'd be nice if the exception `MustHaveHappened` throws if the matcher does not validate, somehow includes which property or properties didn't match

**Comment by thomaslevesque** [comment]
Hi @alexjamesbrown,

It's an interesting idea. However it would be extremely difficult to achieve, if not outright impossible. The example you gave is pretty straightforward, but what if you had a more complex constraint? Keep in mind that the predicate passed to `Match` can be *anything*; it can be arbitrarily complex, have multiple branches, loops, calls to other methods, etc. There's no way to say exactly why the constraint failed, at least not for arbitrarily complex predicates.

**Comment by MistyKuu** [comment]
@thomaslevesque  what if 'Matches' would accept multiple predicates? This way you can at least response to a caller which one failed.

**Comment by alexjamesbrown** [comment]
@MistyKuu multiple predicates *could* end up in multiple places to be a problem...
Multiple multiple matchers for example?

Or, you could "name" the predicates?

   .That.Matches(c=> c.Property == "123", "Property")
   .That.Matches(c=> c.AnotherProperty == "345", "AnotherProperty ")

**Comment by MistyKuu** [comment]
@alexjamesbrown  I would say that naming matchers will increase complexity unnecessarily. 
I would prefer to use it like that:
.That
.Matches(c=> c.PropertyA == "123", c=> c.PropertyB == "124")
Or 
.That
.Matches(c=> c.PropertyA == "123")
.Matches(c=> c.PropertyB == "124")

**Comment by thomaslevesque** [comment]
@MistyKuu that would work, but we also need to provide a description of the predicate that failed (`Matches` accepts a `Func<T, bool>`, not an expression, so we can't get a string representation of it).

The API could look like this:

    A<Customer>.That.Matches(c => c.Property == "123", "Property is 123")
           .And(c => c.OtherProperty == "345", "OtherProperty is 345")
           .And(c => c.AnotherProperty == "456", "AnotherProperty is 456")
           .And(c => c.YetAnotherProperty == "567", "YetAnotherProperty is 567")

But it would be much more tedious to write...

**Comment by thomaslevesque** [comment]
> Or, you could "name" the predicates?

You can name the predicate already:

    A<Customer>.That.Matches(c => c.IsActive, "active customer")

**Comment by alexjamesbrown** [comment]
@thomaslevesque yes, I saw that just after I'd posted ;)

I mean, this isn't a bug, or an issue as such, it's a bit of a feature idea.

My workaround works fine on the many projects I've used it on.
Just a 'nice-to-have' I guess

**Comment by blairconrad** [comment]
@alexjamesbrown, thanks for making this.

I may be missing something, but are not the calls output when `MustHaveHappened` fails to match?
e.g.

```
Assertion failed for the following call:
    FakeItEasyQuestionsVS2015.MustHaveHappened+ICustomerService.Add(c: <c => ((((c.Property == "123") AndAlso (c.OtherProperty == "345")) AndAlso (c.AnotherProperty == "456")) AndAlso (c.YetAnotherProperty == "567"))>)
  Expected to find it at least once but found it #0 times among the calls:
    1: FakeItEasyQuestionsVS2015.MustHaveHappened+ICustomerService.Add(c: FakeItEasyQuestionsVS2015.MustHaveHappened+Customer)
```

If you can't tell what's wrong, have you considered augmenting the `Customer` rendering? Either a ToString or a argumentformatter like

```c#
public class CustomerFormatter : ArgumentValueFormatter<Customer>
{
    protected override string GetStringValue(Customer c)
    {
        return
            $"Property: {c.Property}, OtherProperty: {c.OtherProperty}, YetAnotherProperty: {c.YetAnotherProperty}, AnotherProperty: {c.YetAnotherProperty}";
    }
}
```

yields

```
FakeItEasy.ExpectationException : 

  Assertion failed for the following call:
    FakeItEasyQuestionsVS2015.ICustomerService.Add(c: <c => ((((c.Property == "123") AndAlso (c.OtherProperty == "345")) AndAlso (c.AnotherProperty == "456")) AndAlso (c.YetAnotherProperty == "567"))>)
  Expected to find it at least once but found it #0 times among the calls:
    1: FakeItEasyQuestionsVS2015.ICustomerService.Add(c: Property: 123, OtherProperty: 345, YetAnotherProperty: 567, AnotherProperty: 567)
```

**Comment by thomaslevesque** [comment]
@alexjamesbrown yes, I agree it's a nice idea, and if we find a way to make argument matchers better, we certainly will. I just don't want to give you false hopes ;)

**Comment by thomaslevesque** [comment]
> (Matches accepts a Func<T, bool>, not an expression, so we can't get a string representation of it).

Scratch that. There's an extension method that takes an `Expression<Func<T, bool>>`, so we could do just this:

```
A<Customer>.That.Matches(c => c.Property == "123")
       .And(c => c.OtherProperty == "345")
       .And(c => c.AnotherProperty == "456")
       .And(c => c.YetAnotherProperty == "567")
```

**Comment by blairconrad** [comment]
@alexjamesbrown, I took the liberty of renaming the issue. To my mind, the original title suggested that there were multiple argument constraints, but we are talking about one matcher that combines several conditions.

Apologies if I've not captured the spirit of the issue.

**Comment by blairconrad** [comment]
@thomaslevesque, I think that

```c#
A<Customer>.That.Matches(c => c.Property == "123")
       .And(c => c.OtherProperty == "345")
       .And(c => c.AnotherProperty == "456")
       .And(c => c.YetAnotherProperty == "567")
```

will not be achievable, since `Matches` returns `<T>`, which we wouldn't be able to hang an `And` on.
I think another syntax would be necessary.

**Comment by thomaslevesque** [comment]
@blairconrad, currently `Matches` returns `T`, but we could change it to return something that's implicitly convertible to `T`.

**Comment by blairconrad** [comment]
This will not work when `T` is `object` or an interface, though.

**Comment by thomaslevesque** [comment]
> This will not work when T is object or an interface, though.

True. I keep forgetting about this limitation...

**Comment by blairconrad** [comment]
I spiked something. I may have accidentally fixed #796 while I was doing it, and it's very rough, but I was able to write this test

```c#
[Scenario]
public static void ArgumentConstraintConjunction(IFoo fake, Exception exception)
{
    "Given a fake"
        .x(() => fake = A.Fake<IFoo>());

    "And a method is called on the fake"
        .x(() => fake.Bar(7));

    "When I assert that the method was called, specifying a complex constraint on an argument"
        .x(() => A.CallTo(() => fake.Bar(A<int>.That.Matches(
            i => i > 6 && i%2 == 0
        ))).MustHaveHappened());
}
```
and got this result

```
FakeItEasy.ExpectationException


  Assertion failed for the following call:
    FakeItEasy.Specs.ArgumentMatchingSpecs+IFoo.Bar(a: <(i > 6) AndAlso *((i % 2) == 0)*>)
  Expected to find it at least once but found it #0 times among the calls:
    1: FakeItEasy.Specs.ArgumentMatchingSpecs+IFoo.Bar(a: 7)
```

Note the "*"s.
Of course, I didn't spend much time on the formatting—the messaging could definitely be improved.
And the spike only works for `&&` right now, But we could achieve similar results for common logical operators.

**Comment by thomaslevesque** [comment]
Nice! How did you do it?

Also, what happens if there are two recorded calls, but none match (e.g. one call with  `a: 7` and one with `a: 4`)? How would it look like?

**Comment by blairconrad** [comment]
By parsing the expression and building  a matcher that understands `&&`. 
https://github.com/blairconrad/FakeItEasy/commit/896b5d929b8a37ab0f99755d6d3507137ffbbf92
The code is terrible and would need lots of cleanup. I think portion for the "fix" for #796 would also need work.

Here's what I get from your suggested test

```
  Assertion failed for the following call:
    FakeItEasy.Specs.ArgumentMatchingSpecs+IFoo.Bar(a: <*(i > 6)* AndAlso *((i % 2) == 0)*>)
  Expected to find it at least once but found it #0 times among the calls:
    1: FakeItEasy.Specs.ArgumentMatchingSpecs+IFoo.Bar(a: 7)
    2: FakeItEasy.Specs.ArgumentMatchingSpecs+IFoo.Bar(a: 4)
```

You raise a good point though, and one that affects this issue regardless of implementation. How to report failures for multiple calls?
To fully support this, we'd need to attach the "what went wrong" portion of the message to the recorded call down in the list.

**Comment by thomaslevesque** [comment]
Ah, I see. But if you go down this road, things can get hairy when the expression gets more complex... The C# compiler doesn't know how to generate block expressions, so we can't have completely arbitrary code, but even a single-expression lambda can get quite complex, with and/or/parentheses etc.

To be honest, I'm not sure it's worth the trouble. The string representation of the predicate usually makes it easy to see why the call didn't match.

**Comment by blairconrad** [comment]
I'm not completely worried about the complexity of the expressions, but that could be because I don't see as far as you.
But I am inclined to agree that probably the best tack is to just say that the objects and/or constraints are so complex, the next step should be improving the object rendering such as in https://github.com/FakeItEasy/FakeItEasy/issues/1078#issuecomment-299209403.

**Comment by blairconrad** [comment]
>  block expressions

do you mean lambdas with a statement body? I don't think they can be used in the constraints anyhow.

**Comment by thomaslevesque** [comment]
> do you mean lambdas with a statement body? I don't think they can be used in the constraints anyhow.

Yes ([BlockExpression](https://msdn.microsoft.com/en-us/library/system.linq.expressions.blockexpression(v=vs.110).aspx)). And no, they can't be used in constraints, because the compiler doesn't support it.

**Comment by blairconrad** [comment]
Ah! I misunderstood your comment. I thought you meant that my spike couldn't be extended to BlockExpressions, but you were saying that even though my fix would never have have to deal with BlockExpressions, it might still have to deal with very complicated situations. Yes.

**Comment by thomaslevesque** [comment]
No objection from me 👍

**Comment by alexjamesbrown** [comment]
Same here.
I blogged about the workaround in depth here - http://www.alexjamesbrown.com/blog/development/asserting-multiple-properties-argument-fakeiteasy
