### ISSUE TITLE
Suppress console output from TypeCatalogueTests

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1093]
As discussed in #1097

Sometimes warnings appear on the console when running `TypeCatalogueTests`, because the type catalogue is loaded after fakes are created by other tests, which causes it to scan `DynamicProxyGenAssembly2`. This doesn't happen under normal conditions, so we should just suppress the output.

Not scanning `DynamicProxyGenAssembly2` at all has been considered, but would be a breaking change (unlikely to affect anyone, but who knows...)

**Comment by blairconrad** [comment]
I think this issue is now inaccurately named. And described.
I think the only thing that still is accurate is the PR link. Maybe close this issue as well, and make a new one talking about the sporadic warning when we run integration tests?

**Comment by thomaslevesque** [comment]
I was just editing it ;)

**Comment by adamralph** [comment]
Added to 3.4.0 milestone.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).
