### ISSUE TITLE
Generate external assembly with extension points for integration tests

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1094]
As noted in https://github.com/FakeItEasy/FakeItEasy/pull/1090#issuecomment-300454071, the current assembly will not be compiled if a user runs the integration tests from the IDE without doing a command-line build, and then the tests would fail.

We could generate the assembly as part of the test fixture setup.

**Comment by blairconrad** [comment]
Assigning to myself and marking **in-progress** because I've started working on it.
If there's an objection to this, I'm happy to stop.

**Comment by thomaslevesque** [comment]
> Assigning to myself and marking in-progress because I've started working on it.

👍

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).
