### ISSUE TITLE
The packaged PDB doesn't contain source server information

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1100]
This is because `dotnet xunit` rebuilds all the assemblies before testing, which overwrites the PDB enriched by PdbGit.

We should run PdbGit *after* the tests, right before making the NuGet package, and/or update to `dotnet-xunit` 2.3.0-beta2, which has a `-nobuild` option.

**Comment by thomaslevesque** [comment]
An additional benefit of the `-nobuild` option is that it makes the build significantly faster.

**Comment by blairconrad** [comment]
One nice thing about keeping the order of the targets is that it means we're testing the DLLs that we'd be exporting, instead of  a version of them without pdbgitlinking.
I think we should get (and use) the new dotnet-xunit.

**Comment by thomaslevesque** [comment]
> One nice thing about keeping the order of the targets is that it means we're testing the DLLs that we'd be exporting, instead of a version of them without pdbgitlinking.

PdbGit only modifies the PDB, not the DLL, so it shouldn't change anything.

> I think we should get (and use) the new dotnet-xunit.

We can, and should. It doesn't really affect wether or not we change the target order.

**Comment by blairconrad** [comment]
> PdbGit only modifies the PDB, not the DLL, so it shouldn't change anything.

HA! Yes. Ahem.

**Comment by thomaslevesque** [comment]
OK, so apparently `dotnet-xunit 2.3.0-beta2` requires that we also use xunit 2.3.0-beta2. Are we willing to do that?

If not, just reordering the targets should also fix the problem. We can still upgrade xunit later.

**Comment by blairconrad** [comment]
Upgrade away!

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).
