### ISSUE TITLE
Deprecate automatic fake injection into systems under test (InitializeFixture)

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1102]
In preparation of #992

**Comment by blairconrad** [comment]
Once we go through with this, I think we can close #964 and #578.
(Up 'til then, the removal won't feel real!)

**Comment by blairconrad** [comment]
It's funny. My first step was to convert all _our_ tests away from using `InitializeFixture`. I like the new ones versions better. 😐

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.0.0).
