### ISSUE TITLE
What is the difference between Autofac Mock and FakeItEasy unit testing fameworks 

### ISSUE THREAD

**Issue by PAAutofac** [FakeItEasy/FakeItEasy#1107]
Can anyone suggest the difference between Autofac unit testing frame works : Mock and FakeItEasy. they both create a dummy instances automatically when we install the test frameworks. Apart from different commands I could not see any difference. I would like to know do they both do same job or which is better and why.

Thank you

**Comment by thomaslevesque** [comment]
Hi @PAAutofac, could you clarify? Are you referring to [Autofac.Extras.FakeItEasy](http://docs.autofac.org/en/latest/integration/fakeiteasy.html) and [Autofac.Extras.Moq](http://docs.autofac.org/en/latest/integration/moq.html)?

If you ask "which is better", don't expect an unbiased answer... of course FakeItEasy is better :wink:. In fact, the features are very similar, basically the main difference is how you configure the fakes/mocks. The FakeItEasy API tries to be as close to natural language as possible. But it's mostly a matter of personal preference; you should be able to achieve the same results with either library.

**Comment by PAAutofac** [comment]
Hi @thomaslevesque, Yes, I was referring to Autofac.Extras.FakeItEasy and Autofac.Extras.Moq. Ok Thanks for your reply. I was not sure which was better or was there any specific purpose using either of it as they both seem very similar.
