### ISSUE TITLE
Build script doesn't work on a machine without VS2015

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1113]
This is because the path to csi.exe is hard-coded as `"%ProgramFiles(x86)%\MSBuild\14.0\Bin\csi.exe"` in build.cmd.

**Comment by thomaslevesque** [comment]
Actually, there are other issues... If I fix the path to csi.exe, I get another error during NuGet restore:

> Failed to load msbuild Toolset
>  Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

There must be another reference to MSBuild 14.0 somewhere...

**Comment by blairconrad** [comment]
Removing "Bug" because it's not a user-visible bug in the package. It might prevent us from producing a package, but that's a different story!

**Comment by thomaslevesque** [comment]
The NuGet restore issue is fixed by upgrading to NuGet 4.1.0

Last issue: ILMerge fails with return code 1, whatever this means. At some point I was prompted to install .NET 3.5, and it started working after that. No idea why, since ILMerge targets .NET 4.0...

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).
