### ISSUE TITLE
Document ref argument matching

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1123]
We recently had [a question about matching `ref` parameters](https://github.com/FakeItEasy/FakeItEasy/issues/18#issuecomment-308413232), and I couldn't find any docs to point at.

We talk about [matching `out` parameters](http://fakeiteasy.readthedocs.io/en/stable/argument-constraints/#out-parameters), but never `ref`.

We should show how to use the default equality matcher as well as some [fancier matching,](http://fakeiteasy.readthedocs.io/en/stable/argument-constraints/#other-matchers) such as `Ignored`. A pointer to [assigning out and ref parameters](http://fakeiteasy.readthedocs.io/en/stable/assigning-out-and-ref-parameters/) to simulate changing the value is probably not a bad idea.

**Comment by thomaslevesque** [comment]
> A pointer to assigning out and ref parameters to simulate changing the value is probably not a bad idea.

This page probably needs to be updated as well. It always talks about "out and ref parameters", but only gives examples with `out`.
