### ISSUE TITLE
Could not load file or assembly Castle.Core, Version=4.1.0.0

### ISSUE THREAD

**Issue by holytshirt** [FakeItEasy/FakeItEasy#1126]
The current nuget package for FakeItEasy is reference the wrong version of Castle.Core and you get this error when you run tests.
`System.IO.FileNotFoundException : Could not load file or assembly 'Castle.Core, Version=4.1.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc'. The system cannot find the file specified.`

The nupsec say to use 4.0.0
https://github.com/FakeItEasy/FakeItEasy/blob/develop/src/FakeItEasy.nuspec#L23

The project file is using 4.1.0
https://github.com/FakeItEasy/FakeItEasy/blob/develop/src/FakeItEasy/FakeItEasy.csproj#L46

The workaround is to add Castle.Core 4.1.0 directly to the project via nuget.

When I `dotnet pack` now days I just use the project references instead of trying to manage them in the nuspec.

**Comment by blairconrad** [comment]
Bother. Thanks, @holytshirt.

**Comment by blairconrad** [comment]
We don't `dotnet pack`. We nuget pack. As far as I know, `dotnet pack` doesn't allow us to include the symbols. (Or multiple assemblies?)

**Comment by holytshirt** [comment]
No worries :)
you can do `dotnet pack --include-symbols` 
and with nuget `nuget pack -IncludeReferencedProjects` for dependencies.

**Comment by blairconrad** [comment]
Ah. Good tip about `--include-symbols`.

For our multiple projects, it's that we have 2 analyzer projects (C# and VB) and want them in one package.

**Comment by thomaslevesque** [comment]
> you can do dotnet pack --include-symbols

I think it creates a separate symbols package, which isn't what we want... It think this is the only reason we still have a .nuspec file, otherwise we could do everything in the .csproj

**Comment by blairconrad** [comment]
This was fixed in [version 3.4.1](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.1).

Look for you name in the release notes, @holytshirt! :trophy:

**Comment by blairconrad** [comment]
This was closed in #1128, but I don't see the issue being closed. Am I missing something?

**Comment by thomaslevesque** [comment]
I think it's because it was merged into hotfix-3.4.1, not develop.

**Comment by blairconrad** [comment]
OH! That makes sense. Otherwise any weird merging we do would close who knows what.

**Comment by holytshirt** [comment]
👍 Thanks all!

**Comment by blairconrad** [comment]
A pleasure, @holytshirt. We appreciate the bug report. Happy FakeItEasying.
