### ISSUE TITLE
Allow AssignsOutAndRefParameters on a non-void member without first specifying Returns

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1134]
The return value should remain a `Dummy`.

This was spun off from https://github.com/FakeItEasy/FakeItEasy/issues/854#issuecomment-308392749.

Labelled **breaking** because we'll change the signature on some of the API methods.

**Comment by thomaslevesque** [comment]
Should we expose `AssignsOutAndRefParameters` only before `Returns`, or also after?

One one hand, allowing both would be a little inconsistent, and probably awkward to implement if we want to avoid things like `.AssignsOutAndRefParameters(...).Returns(...).AssignsOutAndRefParameters(...).Returns(...)...`.

On the other hand, *not* allowing both would force current users to modify their code to make it work. There's nothing wrong in introducing breaking changes in major versions, but we usually try to keep them small enough to affect as few users as possible. I don't think `AssignsOutAndRefParameters` is very widely used, but it's not a very advanced/obscure feature either.

**Comment by blairconrad** [comment]
I'm not sure why not allowing both would force current users to modify their code. If we allow  
`.Returns(…).AssignsOutAndRefParameters(…)` that should match existing code, and  
`.AssignsOutAndRefParameters` with no `Returns` ever could be an addition, no?

I probably haven't thought it through…

**Comment by thomaslevesque** [comment]
Ah, I see. I thought you wanted to allow `.AssignsOutAndRefParameters(…).Returns(…)` instead of `.Returns(…).AssignsOutAndRefParameters(…)`

**Comment by blairconrad** [comment]
Ah, no. Sorry. I'm not sure how to update the title to fix that. Please feel free, if you have an improvement!

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.0.0).
