### ISSUE TITLE
Find replacement for FxCop (VS "Code Analysis")

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1144]
The current Visual Studio "Code Analysis" feature
- doesn't support SDK-style projects
- doesn't support .NET Standard & .NET Core assemblies

Apparently there won't be a short-term fix to make FxCop support these scenarios.

~~So, right now it's only working for the two VB projects, which haven't been migrated to SDK-style projects.~~ (they have now be migrated as well)

Checking and fixing code analysis warnings is part of the release checklist, and it should probably stay this way, so we need a solution.

**Comment by thomaslevesque** [comment]
Possible solution: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/) NuGet package

This package seems to be a mess. It's actually a meta-package that groups several code analysis packages, some of which don't seem to work (e.g. the analyzer from System.Runtime.Analyzers fails to load due to a strong-naming issue). It's unclear which rules are contained in which package.

**Comment by thomaslevesque** [comment]
Possible solution: [Microsoft Code Analysis 2017] VS extension.

From the extension's page:

> - 100+ live diagnostics for API design, performance, security, and best practices for C# and Visual Basic.
> - Quick fixes for applicable diagnostics (using Ctrl+.).
> - Diagnostics appear in the editor, Error List, and scroll bar.
> - All diagnostics are suppressible. 

Pros:
- immediate feedback during development and compilation (no need to explicitly run analysis)

Cons:
- no easy way to run analysis during CI build, since the CI environment won't have the extension
- supports only a subset of FxCop rules

**Comment by thomaslevesque** [comment]
In fact, both the extension and the NuGet package are based on the same analyzers: https://github.com/dotnet/roslyn-analyzers

**Comment by thomaslevesque** [comment]
I installed the extension, but I haven't been able to get it to report a single warning...

**Comment by thomaslevesque** [comment]
> I installed the extension, but I haven't been able to get it to report a single warning...

This is because it requires VS 2017.3, which hasn't been released yet... See https://github.com/dotnet/roslyn-analyzers/issues/1238

**Comment by thomaslevesque** [comment]
Well, it was supposed to work with VS2017 15.3, but it doesn't... I'm still unable to get any warning.

**Comment by thomaslevesque** [comment]
The NuGet package doesn't work any better. It either fails to load (v1.1.0, "strong name validation failed") or throws exceptions during build (later betas, "Feature 'IOperation' is disabled").

**Comment by thomaslevesque** [comment]
OK, IOperation is a feature that needs to be enabled at the project level. Now I'm able to get warnings, but it's reporting tons of warnings that weren't there before, some of which don't make any sense to me...

**Comment by thomaslevesque** [comment]
OK, I just spent 2 hours trying to fix or suppress the many new warnings, but there are pretty serious bugs in this analyzer package (https://github.com/dotnet/roslyn-analyzers/issues/1292, https://github.com/dotnet/roslyn-analyzers/issues/1293, https://github.com/dotnet/roslyn-analyzers/issues/1294)... Maybe we should wait for it to be more stable.

**Comment by blairconrad** [comment]
I'm sorry you spent so much time on it. I agree on the "waiting".
Nice new issues you made, though.

**Comment by onyxmaster** [comment]
"Legacy" CA (FxCop) works fine for us with SDK-style projects. What issues are you encountering?
Take note that FxCop needs full PDBs instead of portable ones (the new default).

**Comment by thomaslevesque** [comment]
> What issues are you encountering?

It doesn't seem to analyze anything, it just rebuilds the solution... If I write some code that should trigger a warning, it doesn't report anything.

**Comment by onyxmaster** [comment]
Try the non-portable PDB format for CA (we have separate solution/project config for that):
```xml
<DebugType>pdbonly</DebugType>
```

**Comment by thomaslevesque** [comment]
We already use `full` or `pdbonly` for some of the projects, it doesn't seem to change anything.

I noticed something strange, though... If I build from the command line with ` /p:RunCodeAnalysis=true`, it does produce warnings (and some errors due to .NET Standard / .NET Core assemblies that are not supported) ... It's only when I run analysis from Visual Studio that I have nothing.

**Comment by thomaslevesque** [comment]
This change has been released as part of [FakeItEasy 4.5.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.5.0).
