### ISSUE TITLE
Use dotnet pack to generate NuGet package

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1146]
This will make the nuspec completely unnecessary (everything will be in the csproj). The dependencies are generated automatically, so we can no longer have dependency version inconsistencies between csproj and nuspec (see #1126).

Better solution to #1133

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.0.0).
