### ISSUE TITLE
Split C# and VB.NET analyzers into two separate packages

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1148]
We can't use `dotnet pack` to create the analyzer package, because it doesn't support packaging multiple projects into a single package. However, we don't actually need to have the two analyzers in a single package, because the vast majority of users will only ever need one. So we could use `dotnet pack` to build a package for each analyzer.

Since current users of the analyzer have installed the `FakeItEasy.Analyzer` package, we need to keep generating this package so that current users still get the updates. However, it will now be a meta-package, with no content, and dependencies on the two language-specific packages.

So the packages would look like this:

- FakeItEasy.Analyzer.CSharp
  - contains: FakeItEasy.Analyzer.CSharp.dll/pdb
  - depends on: Roslyn
- FakeItEasy.Analyzer.VisualBasic
  - contains: FakeItEasy.Analyzer.VisualBasic.dll/pdb
  - depends on: Roslyn
- FakeItEasy.Analyzer
  - contains: nothing
  - depends on: FakeItEasy.Analyzer.CSharp, FakeItEasy.Analyzer.VisualBasic

**Comment by blairconrad** [comment]
> Since current users of the analyzer have installed the FakeItEasy.Analyzer package, we need to keep generating this package so that current users still get the updates. 

Or, and this is terrible, but we replace it with a single diagnostic that hates every statement and directs the users to pick up one of the others?
It means we only have to maintain 3 packages instead of 4!

**Comment by thomaslevesque** [comment]
> Or, and this is terrible, but we replace it with a single diagnostic that hates every statement and directs the users to pick up one of the other packages?

I don't know about that... it seems a bit harsh. We could create a package with no dependencies and just a README.txt file that tells the user to use either the C# or VB package, but why bother them if we can easily implement a solution that works seamlessly?

> It means we only have to maintain 3 packages instead of 4!

The metapackage is not a big hassle to maintain; as you can see in the PR, there's nothing that needs to change frequently in the nuspec. The only thing that bothers me is the duplication of metadata between the nuspec and csprojs, but it doesn't change often. If we really want to, we could generate the metapackage nuspec, or use placeholders that we pass on the command line, but it's probably overkill.

**Comment by blairconrad** [comment]
> I don't know about that... it seems a bit harsh. We could create a package with no dependencies and just a README.txt file that tells the user to use either the C# or VB package, but why bother them if we can easily implement a solution that works seamlessy?

I 'd've suggested this, but I think the real effect is that they wouldn't be bothered - they'd just stop getting warnings.

> The metapackage is not a big hassle to maintain; as you can see in the PR, there's nothing that needs to change frequently in the nuspec. 

Yeah, I know. The only bother (and it's not much) is copying the extra file to the release.
And I'm interested in automating that step anyhow, so I really do expect it to be no bother.

I'm for the change.

**Comment by thomaslevesque** [comment]
> And I'm interested in automating that step anyhow, so I really do expect it to be no bother.

Yes, I wanted to experiment with it too. I already created a deployment environment for it, but didn't try to use it yet.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.0.0).
