### ISSUE TITLE
Remove Raise.With<TEventHandler> in 5.0.0

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1152]
From https://github.com/FakeItEasy/FakeItEasy/pull/1150/files#r123444441.
It's been superseded by `Raise.FreeForm.With`.

**Comment by thomaslevesque** [comment]
Will be deprecated in 4.0.0
To be removed in 5.0.0

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
