### ISSUE TITLE
Creating Dummy respecting model validations

### ISSUE THREAD

**Issue by thiagomajesk** [FakeItEasy/FakeItEasy#1157]
Hi, I'd like to know if there is a simple way to fake a model respecting its validations constraints. 
For example, if I have a custom validation defined (like fluent validations `AbstractValidator`). Is there a simple way to achieve this behavior?

**Comment by thomaslevesque** [comment]
Hi @thiagomajesk,

I'm not sure I understand what you want to do... Could you be more specific? Maybe provide an example?

**Comment by thiagomajesk** [comment]
@thomaslevesque Suppose I have a model called `Person` and a series of validation rules specified with fluent validation (like a name max lenght or a age range). Now if I want to "fake" a `Person`, I'd like to have those rules respected (generating a name with a maximum lengh or a age in between a range). Is there any way to integrate FakeItEasy with custom validation rules so that when I'm generating (faking) the class I cant get those values exactly like I would expect?

**Comment by thomaslevesque** [comment]
So, if I understand correctly, you'd like FakeItEasy to generate values that follow your validation rules? That's not what FakeItEasy does. FakeItEasy lets you configure behaviors; it doesn't generate data (for that you could use something like [Bogus](https://github.com/bchavez/Bogus)).. If you want the `Person` to have valid property values, you'll have to configure these values yourself.
