### ISSUE TITLE
Sometimes an expectation fails, but the error message lists the expected call.

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1159]
From StackOverflow: https://stackoverflow.com/q/44884418/98713

Consider this code:

```csharp
void Main()
{
	var foo = A.Fake<IFoo>();
	
	Task.Run(() => foo.Bar("hello"));
	
	A.CallTo(() => foo.Bar(A<string>._)).MustHaveHappened();
}

public interface IFoo
{
	void Bar(string s);
}
```

Sometimes the expectation will succeed, sometimes it will fail, which is expected because there's a race condition, but when it fails, it will sometimes include the expected call in the error message:

```
  Assertion failed for the following call:
    UserQuery+IFoo.Bar(s: <Ignored>)
  Expected to find it at least once but found it #0 times among the calls:
    1: UserQuery+IFoo.Bar(s: "hello")
```

This is inconsistent; the call must have happened after we checked the expectation, but before we generated the error message.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.0.0).

[milo.farrell on StackOverflow](https://stackoverflow.com/users/7019343/milo-farrell), look for your name in the release notes! :trophy:
