### ISSUE TITLE
investigate coverity build failures

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1164]
@thomaslevesque pointed out that the coverity build has been failing. We still get the e-mails, though.

The last successful build is [build 334](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/334).
The first failing build is [build 337](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/337).

Aside from differences in package restore order, here's the first build difference:

```diff
- Emitted 963 C# compilation units (100%) successfully
- 963 C# compilation units (100%) are ready for analysis
- The cov-build utility completed successfully.
+ build.cmd : Emitted 959 C# compilation units (99%) successfully
+ At line:2 char:5
+ +     & .\build.cmd coverity
+ +     ~~~~~~~~~~~~~~~~~~~~~~
+     + CategoryInfo          : NotSpecified: (Emitted 959 C# ...%) successfully:String) [], RemoteException
+     + FullyQualifiedErrorId : NativeCommandError
+  
+ 959 C# compilation units (99%) are ready for analysis
```

**Comment by blairconrad** [comment]
The only [changes to the repo](https://github.com/FakeItEasy/FakeItEasy/compare/2b63a9069cad7cba39640b37ed3e5fe511a28b22...3dfc6013aa84a089093bfda6041fbc35a6588d06) were from #1161 and #1162.

**Comment by thomaslevesque** [comment]
> We still get the e-mails, though

Which e-mails? I only get the AppVeyor build failure emails

**Comment by blairconrad** [comment]
I just forwarded to you. They're delivered to fakeiteasyfx@gmail.com, which I forward to me. Perhaps you don't those e-mails?
(Maybe there's a better way to monitor the account, but I'm not sophisticated.)

**Comment by thomaslevesque** [comment]
> They're delivered to fakeiteasyfx@gmail.com, which I forward to me. Perhaps you don't those e-mails?

No, I don't get them

**Comment by blairconrad** [comment]
Based on an announcement on the Coverity page, I suspected that the error might be fixed by a newer version of the cov-build tool. Here's the announcement

> Coverity 2017.07 has been released!
>
>There are an number of checker additions and improvements for node.js as well as updated language support.
>
>The following improvements have been made:
>
> * Support for C# 7.
> * Support for VS 2017 compiler (version 19.10).
> * Support for clang 4.0.
> * Support for gcc 7.
>
> All users who are experiencing build issues should upgrade to this version; a number of bugs have been fixed with this release.

at home, with the latest cov-build, I see
```
Emitted 947 C# compilation units (98%) successfully

947 C# compilation units (98%) are ready for analysis
The cov-build utility completed successfully.
```
and no errors. The files produced were uploaded for analysis and scanned.

My cov-build reports version 2017.07. AppVeyor's reports 8.7.0. I'll approach AppVeyor and ask if they've made any changes to their compiler and also ask about an upgrade to cov-build.

**Comment by blairconrad** [comment]
[AppVeyor discussion](http://help.appveyor.com/discussions/problems/7048-coverity-build-failing-since-5-july-2200-utc)

**Comment by thomaslevesque** [comment]
Thanks for the investigation @blairconrad.
I'd like to try to repro the issue locally with cov-build 8.7.0, but it doesn't seem possible to download older versions...

**Comment by blairconrad** [comment]
Yeah, I'd hoped to as well. :(

**Comment by blairconrad** [comment]
Ilya at AppVeyor has [created an issue to upgrade Coverity](https://github.com/appveyor/ci/issues/1648).

In the meantime, he's [asked us to rerun the last successful and first failing builds](http://help.appveyor.com/discussions/problems/7048-coverity-build-failing-since-5-july-2200-utc#comment_42963732). It will mean temporarily modifying the appveyor.yml. Any objection?

**Comment by thomaslevesque** [comment]
> In the meantime, he's asked us to rerun the last successful and first failing builds. It will mean temporarily modifying the appveyor.yml. Any objection?

I don't mind, if there's no other way, but can't you make a branch off the last successful state, and change appveyor.yml on that branch?

**Comment by blairconrad** [comment]
* Retrying build 334. New build is [350](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/350). It passes.
* Retrying build 337. New build is [351](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/351). It's queued.

**Comment by blairconrad** [comment]
At Ilya's urging, I also tried running the build under cmd instead of PowerShell. Success!

Well, there was a failure because one of the coverity config tokens wasn't read from the PR branch (or something), but [the previously-failing step succeeded](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/359-dtjjacyi).

**Comment by thomaslevesque** [comment]
Well, that's weird... but if it solves the issue, I guess I can live with it ;)
