### ISSUE TITLE
automatically attach artifacts to GitHub release

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1171]
Much like how we automatically publish nupkgs to nuget.org, it'd be nice to, on tagged builds, automatically attach our nupkgs to the GitHub release.

I experimented and found that the AppVeyor GitHub release deployment option overwrites the release description (where we keep the release notes), and potentially the pre-release and published statuses.

We may need to implement a workaround like described in  [the Upload release build artefacts discussion topic](http://help.appveyor.com/discussions/problems/5548-upload-release-build-artefacts) or perhaps just use the GitHub API's [Upload a release asset](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) call directly.

**Comment by blairconrad** [comment]
Even with the workaround described above, I find that when using the AppVeyor "attach artifacts",

1. a new release is always created, duplicating the draft release we already had, and
2. multi-line descriptions are truncated to one line

I've added these findings to the AppVeyor discussion, but no response yet (it hasn't been long). I'll probably investigate just calling the GitHub API endpoints directly.

**Comment by thomaslevesque** [comment]
> I'll probably investigate just calling the GitHub API endpoints directly.

That's probably the best option. It can be a while before AppVeyor fixes the issue on their side.

**Comment by blairconrad** [comment]
Okay. I've a thing. [attach.ps1](https://github.com/blairconrad/FakeItEasy/blob/252b9487d29b8fc888b392955256cc6acded469d/attach.ps1).

Too long to shove in the `appveyor.yml`?

**Comment by thomaslevesque** [comment]
Nice!

> Too long to shove in the appveyor.yml?

Probably too long to include it directly, but we can invoke it as a separate script.

**Comment by blairconrad** [comment]
> Probably too long to include it directly, but we can invoke it as a separate script.

Whoop! I read this as "Probably **not** too long". What a moron.

Okay. Happy to move to another location. Makes editing easier anyhow. Where do we want it? Top level?
I'd be inclined to move the nuget publishing in as well and call the whole thing `deploy.ps1`, if that doesn't bother anyone.

**Comment by thomaslevesque** [comment]
> Where do we want it? Top level?

Sounds good to me 👍 

> I'd be inclined to move the nuget publishing in as well and call the whole thing deploy.ps1, if that doesn't bother anyone.

Sure, that makes sense.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).
