### ISSUE TITLE
[Analyzer] Update FakeItEasy.Analyzer description to point toward C#/VB.NET packages

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1174]
Most people will need either FakeItEasy.Analyzer.VisualBasic or FakeItEasy.Analyzer.CSharp, but not both. Tell them they could save a few bytes on the download by relying on one of the language-specific packages.

**Comment by thomaslevesque** [comment]
Note that we can already update the description on nuget.org without actually modifying the source.

**Comment by blairconrad** [comment]
That's a good point. But it'll revert on republish, no?
While we're talking about the message, how's

> A convenience package that installs the FakeItEasy Analyzer for both C# and Visual Basic.
> Clients using FakeItEasy from only one of the two languages should prefer
> FakeItEasy.Analyzer.CSharp or FakeItEasy.Analyzer.VisualBasic.
> 
> Provides diagnostic analyzers to warn about incorrect usage of FakeItEasy.
> Works in Visual Studio 2015 Update 1 or later.

**Comment by thomaslevesque** [comment]
> That's a good point. But it'll revert on republish, no?

Yes, but at least we don't have to wait until the next release to update the description.

> While we're talking about the message, how's

Perfect 👍

**Comment by blairconrad** [comment]
I've already updated the description on [the nuget.org page](https://preview.nuget.org/packages/FakeItEasy.Analyzer/4.0.0) to match this PR.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).
