### ISSUE TITLE
Faking Confluent .NET Kafka consumers

### ISSUE THREAD

**Issue by nkanand** [FakeItEasy/FakeItEasy#1176]
Hi,

Environment: .NET 4.5.
FakeItEasy : 4.0.0

I am trying to create a fake object of Kafka consumer, below is the syntax I use:
```c#
var fakeconsumer = A.Fake<Consumer<Null, string>>(
    (x => x.WithArgumentsForConstructor(
        () => new Consumer<Null, string>(A.Dummy<IEnumerable<KeyValuePair<string, object>>>(),
        A.Dummy<IDeserializer<Null>>(),
        A.Dummy<StringDeserializer>()))));
```

The code for Kafka client is here: https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Consumer.cs

As you can see, I am invoking the Fake call with correct parameters required for the constructor. However I keep getting the follow error message : "No constructor matches the passed arguments for constructor.".

Any help is greatly appreciated.

Thank you

**Comment by blairconrad** [comment]
Also asked on StackOverflow as  [Faking Confluent .NET Kafka consumers](https://stackoverflow.com/questions/45395898/faking-confluent-net-kafka-consumers/45398881#45398881), where I've provided an answer.
Pending a successful outcome there, I'll close this.
