### ISSUE TITLE
Detect errors during automatic deployment

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1183]
From https://github.com/FakeItEasy/FakeItEasy/pull/1182#issuecomment-320929391.

If the deployment script fails, it may continue on, and claim that it succeeded. Potential failure points:

* syntax error in the script
* failure to find artifacts (very unlikely)
* failure to attach artifacts to GitHub release
* failure to push artifacts to Nuget
* ???

**Comment by thomaslevesque** [comment]
> failure to find artifacts (very unlikely)

The deploy script doesn't run if the build fails, right?

**Comment by blairconrad** [comment]
It does not. I really don't think we'll ever fail to find the artifacts (if they're there), but I suppose we could accidentally change the path to the outputs, or mess up the path that Get-ChildItem uses.
This is the least likely of all failures, I think. Sadly, the easiest to guard against. :wink:

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).
