### ISSUE TITLE
Migrate VB.NET projects to SDK-style projects

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1185]
Now that VS2017 15.3 is released, we should be able to migrate the VB.NET projects, which weren't supported by the .NET Core tooling until now.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).
