### ISSUE TITLE
Build failure is no longer reported as failed by AppVeyor

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1189]
Examples:
- https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/407-lbqhlucq
- https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/407-yckjlhwr

In these builds, the build script clearly failed, but AppVeyor didn't detect the failures and marked the builds as successful.

**Comment by thomaslevesque** [comment]
Apparently this is caused by [this line](https://github.com/FakeItEasy/FakeItEasy/blob/93397f58eda1ea8eba70eee8963a9100a1b54535/appveyor.yml#L19)

    - cmd: if defined APPVEYOR_SCHEDULED_BUILD (build.cmd coverity) else (build.cmd)

According to [this page](https://ss64.com/nt/errorlevel.html), some commands, including `if`, don't set the `ERRORLEVEL`, which is why AppVeyor doesn't detect the failure.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).
