### ISSUE TITLE
Improve consistency of argument value formatting

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1196]
As mentioned in https://github.com/FakeItEasy/FakeItEasy/pull/1195#issue-254495781

We have (at least) 3 different ways to format argument values:

- In `That` constraints, we use `DefaultOutputWriter.WriteArgumentValue`, which:
    - formats null values as `NULL`
    - formats empty strings as `string.Empty`
    - formats everything else using `ToString()`
(The whole constraint description is enclosed in `< >`.)
- In `EqualityArgumentConstraint`, the formatting for the expected value is as follows:
    - formats null values as `<NULL>`
    - formats empty strings as `""`
    - formats everything else using `ToString()`
- In the list of calls in the error message for failed assertions, we use `DefaultFakeObjectFormatter`, which in turns uses `ArgumentValueFormatter`, which:
    - formats null values as `<NULL>`
    - formats empty strings as `string.Empty`
    - formats everything else using user-defined formatters or `ToString()` if there's no formatter for the type
- In `CastleInvocationCallAdapter.ToString()` (not sure where exactly it is used), we use yet another approach which:
    - formats null as `<NULL>`
    - formats empty strings as `<string.Empty>`
    - formats everything else using `ToString()`

Ideally, we should always use `ArgumentValueFormatter` so that we take user-defined formatters into account.

**Comment by blairconrad** [comment]
> In `CastleInvocationCallAdapter.ToString()` (not sure where exactly it is used)

Nowhere that we hit during our tests. I wonder if it can be removed (and `GetDescription`).

**Comment by thomaslevesque** [comment]
Yes, I tried to remove the `ToString()` override, and everything still works. `GetDescription` is used only in unit tests. I guess we could remove it.

**Comment by thomaslevesque** [comment]
Or maybe not... The end user can manipulate fake call objects, so having a nice string representation can be useful. We could, however, try to use the same code as when rendering lists of calls.

**Comment by blairconrad** [comment]
Ah, good point.
