### ISSUE TITLE
Improve WhenArgumentsMatch documentation

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1200]
Recently @drauch had questions about the interaction between `WhenArgumentsMatch` and inline argument constraints. He'd often been tripped up, thinking that _both_ would be applied when matching calls. Instead when `WhenArgumentsMatch` is invoked, nothing that appears inside the `A.CallTo(() => fake.Method(…))` is considered. I think this is the intent, and would not want to change it, but we should augment:

1. the XML-docs, and
2. the readthedocs docs

to make this explicit.

**Comment by blairconrad** [comment]
We could also consider trapping mixed use of `WhenArgumentsMatch` and `A<T>.…` constraints and throwing an error (and if we do that, @thomaslevesque will want an analyzer :wink:). If there's interest, I can spin off another issue.

**Comment by drauch** [comment]
👍

**Comment by blairconrad** [comment]
Thanks, @drauch.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).
