### ISSUE TITLE
False positive for FakeItEasy0003 (argument constraint not valid outside call specification)

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1202]
This code incorrectly triggers the FakeItEasy0003 diagnostic:

            A.CallTo(() => foo.Foo(A<long>.That.Matches(x => Test(x)))).DoesNothing();

> Argument constraint 'A<long>.That.Matches(x => Test(x))' is not valid outside a call specification.

**Comment by thomaslevesque** [comment]
Interestingly, this code does *not* trigger the warning:

        A.CallTo(() => foo.Foo(A<long>.That.Matches(x => true))).DoesNothing();

**Comment by thomaslevesque** [comment]
Oh, wait. Actually, it only happens if there's a compiler error in the expression. In this case, I was in a static method, and `Test` was not static. It also happens if you change `A<int>` to `A<long>` and `Test` accepts an `int`.

Maybe we should suppress diagnostics if there are compiler errors in the expression we're analyzing.

BTW, I notice that FakeItEasy0003 is a warning; it should probably be an error.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).
