### ISSUE TITLE
Update severity of analyzer diagnostics

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1203]
The current severity of out analyzer diagnostics is probably less than ideal:

_(updated after discussion)_

| Id             | Summary                                  | Current severity | Suggested severity |
|----------------|------------------------------------------|------------------|--------------------|
| FakeItEasy0001 | Unused call specification                | Error            | Error        |
| FakeItEasy0002 | Non-virtual member configuration         | Warning          | **Error**          |
| FakeItEasy0003 | Argument constraint outside call spec    | Warning          | Warning          |
| FakeItEasy0004 | Argument constraint nullability mismatch | Warning          | Warning            |
| FakeItEasy0005 | Argument constraint type mismatch        | Error            | Error              |

~~FakeItEasy0001: it's almost certainly a mistake, but it won't cause an error at runtime (it might make the test fail, though).~~
FakeItEasy0002: we know for a fact that it will throw at runtime, since we can't fake a non-virtual method
~~FakeItEasy0003: we know for a fact that it will throw at runtime, since we're not in a call spec~~
~~FakeItEasy0005 (not merged yet): if we follow the same reasoning, it should be a warning.~~

I'm not sure if this strategy is sound, but in any case, we should try to be have consistent rules for choosing the diagnostic severity.

**Comment by blairconrad** [comment]
> FakeItEasy0001: [Error is] almost certainly a mistake, but it won't cause an error at runtime (it might make the test fail, though).

I don't think there's any "almost certainly about it. It's a mistake. There's no reason at all to say `A.CallTo(() => fake.Method())` and not specify a behaviour or assert that the call has been made. For me, this is a definite error.

> FakeItEasy0002: we know for a fact that it will throw at runtime, since we can't fake a non-virtual method

Agreed. Error sounds good to me. I am not sure why we picked Warning, but the discussion in #723 was long and meandering. Maybe we just confused ourselves.

> FakeItEasy0003: we know for a fact that it will throw at runtime, since we're not in a call spec

I refer you to #1076. I think the reasoning there stands: since we may use the constraint inside a helper method, always screaming "Error" seems harsh.

> FakeItEasy0005 (not merged yet): if we follow the same reasoning, it should be a warning.

I am not sure which reasoning you refer to. The same as for FakeItEasy0001? If we're displaying FakeItEasy0005, someone has made a constraint that they think could possibly match, but it never can, and the FakeItEasy runtime will not tell them of their mistake. Me, I want red lights to pop out of the top of the user's computer in this situation.

**Comment by thomaslevesque** [comment]
> I don't think there's any "almost certainly about it. It's a mistake. There's no reason at all to say A.CallTo(() => fake.Method()) and not specify a behaviour or assert that the call has been made. For me, this is a definite error.

OK. My reasoning when I wrote this was something like "if it's going to throw at runtime, the analyzer should report an error; if not, it should report a warning". But it's probably overly simplistic.

> I refer you to #1076. I think the reasoning there stands: since we may use the constraint inside a helper method, always screaming "Error" seems harsh.

Ah, yes. Thanks for the reminder.


> I am not sure which reasoning you refer to. The same as for FakeItEasy0001? If we're displaying FakeItEasy0005, someone has made a constraint that they think could possibly match, but it never can, and the FakeItEasy runtime will not tell them of their mistake. Me, I want red lights to pop out of the top of the user's computer in this situation.

I see your point. I guess you're right.

So, maybe the heuristic for error vs. warning should be this:
- if we're certain that it can't possibly do what the user want => error
- if we're unsure, or if there are legitimate situations for doing this => warning

**Comment by blairconrad** [comment]
> "if it's going to throw at runtime, the analyzer should report an error; if not, it should report a warning"

I understand the thinking, but I've always thought in a different direction. If we're going to throw at runtime, I think we don't even _need_ a diagnostic.
They're nice in this situation, and can provide quicker feedback, so I wouldn't turn them down, but to me, the real power of the analyzer is when it provides feedback that the compiler and the runtime can't.

> So, maybe the heuristic for error vs. warning should be this:
>
> * if we're certain that it can't possibly do what the user want => error
> * if we're unsure, or if there are legitimate situations for doing this => warning

Yes. I think this matches my (unstated, perhaps even internally) thinking.

**Comment by thomaslevesque** [comment]
OK, I updated the table. I guess the only one that needs to be changed eventually is *FakeItEasy0002*.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).
