### ISSUE TITLE
Use MSBuild binary logger

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1205]
https://github.com/Microsoft/msbuild/wiki/Binary-Log

The binary log has many advantages:
- smaller log file (a bit smaller than the detailed log we currently have, *much* smaller than the diagnostic log)
- contains even more information than the diagnostic log
- structured
- can include projects and their imports, so we can easily see exactly  what was being built, including .targets files from the build server
- can be opened with [MSBuild Structured Log Viewer](https://github.com/KirillOsenkov/MSBuildStructuredLog)

Downside: the file isn't human-readable. But the current text log is pretty hard to read too, so it's not a big loss... MSBuild Structured Log Viewer is much more convenient IMO.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).
