### ISSUE TITLE
Upgrade to Castle.Core 4.2.0

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1210]
To avoid future assembly binding issues (see #1208)

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).

Thanks for alerting us to the need, @fir3pho3nixx. Look for your name in the release notes! :trophy:
