### ISSUE TITLE
Automate release branch creation

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1218]
From https://github.com/FakeItEasy/FakeItEasy/issues/1170#issuecomment-334441840.

This is one of several automation steps suggested in that comment.

How fancy do we want to get?

1. Just create the release branch from where we are and push upstream?
2. Number 1 and create PRs to master and develop? (assumes that we're not releasing a hot fix after we've already created a release branch, but our workflow typically involves no commits on the release branch, so I think this is safe)
3. Create release branch, merge to master and develop and push both branches?
4. Number 3 and tag master before pushing? This will trigger a full release - deploying to NuGet and what not. But it's not safe for hotfixes. Nor would it actually release the hotfix. Now that I type it, I think we'll need special logic for hotfixes anyhow.

I'm a bit of a maverick and would consider number 4.

**Comment by blairconrad** [comment]
As far as accidents go, we can always include an [annoying confirmation step](https://github.com/blairconrad/AgfaJiraChromeExtension/blob/7fc8c01479284605b7695528b5de77d36b5b9455/release-version.ps1#L31-L37) to scare us off.

Regardless, I don't mind 2. We can always change our minds later.

**Comment by thomaslevesque** [comment]
> As far as accidents go, we can always include an annoying confirmation step to scare us off.

True. But I like the fact that we create a PR for the release.

**Comment by blairconrad** [comment]
Struggling with providing credentials to GitHub. octokit.rb was nice enough to read the `.netrc` file for us. If we want to continue using that file as the source of our personal access tokens, I may need to write some parsing code. One alternative would be an agreed-upon environment variable. (This is how AppVeyor uses the GitHub API.)

Do you have a preference? Or other idea?

**Comment by thomaslevesque** [comment]
Having the credentials in a file is a bit more convenient for, but not very convenient for AppVeyor... Supporting both would be ideal, I think.

**Comment by blairconrad** [comment]
I didn't think we'd have overlap between user-initiated actions and AppVeyor actions, so I'm not sure we need to build in support for both.
Or did you think we'd trigger this task via AppVeyor? I don't know how to add such special tasks. Oh. Unless you can make a deployment or something. I could look into that!

**Comment by blairconrad** [comment]
A cursory search suggests there are no parameterized deployments or environments. I'd think we'd be creating the release branch from our own machines. I will pursue a mechanism for loading tokens from `.netrc`.

**Comment by thomaslevesque** [comment]
> I didn't think we'd have overlap between user-initiated actions and AppVeyor actions, so I'm not sure we need to build in support for both.

You're right of course... I wasn't thinking straight. We don't need to support this in AppVeyor.

> Or did you think we'd trigger this task via AppVeyor? I don't know how to add such special tasks. Oh. Unless you can make a deployment or something. I could look into that!

No, I didn't have that in mind.

**Comment by thomaslevesque** [comment]
> I will pursue a mechanism for loading tokens from .netrc.

👍

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0).
