### ISSUE TITLE
prepare_release copies all release issue labels, even ready

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1226]
And since the source issue is **ready** when we run `prepare_release`, the new issue gets that label, and we have to remove it.

We should either:

- exclude **ready**, or
- be explicit about what labels to apply

**Comment by thomaslevesque** [comment]
Being explicit is probably better

**Comment by blairconrad** [comment]
We should add labels

* [build](https://github.com/FakeItEasy/FakeItEasy/labels/build)
* [documentation](https://github.com/FakeItEasy/FakeItEasy/labels/documentation)

**Comment by thomaslevesque** [comment]
This change has been released as part of [FakeItEasy 4.1.1](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.1).
