### ISSUE TITLE
Unnecessary reference causes compilation error in prepare_release.csx

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1242]
`prepare_release.csx` has the following reference:

    #r ".\packages\system.runtime.interopservices.runtimeinformation\4.0.0\lib\net45\System.Runtime.InteropServices.RuntimeInformation.dll"

But this package isn't in `packages.config`, so it's not restored, so the script fails to compile. Apparently this reference isn't necessary anyway, the script works fine if I remove it.

@blairconrad I think it worked for you because you already had the package in your packages folder.

**Comment by blairconrad** [comment]
@thomaslevesque, I think you're right. It's probably a holdover from when I was invoking git instead of relying on octokit.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.2.0).
