### ISSUE TITLE
Remove requirement for two people to participate in release activities

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1244]
As @thomaslevesque points out, requiring a second human to be present (to merge a pull request) while releasing a new version of FakeItEasy is sometimes inconvenient.
Perhaps we should create a bot account, under which the release preparations will be done. Then any owner (even the one who initiated the release) can merge the pull request.

An alternative would be to configure the repo so owners could override the "must have an approved review" requirement at need.

**Comment by thomaslevesque** [comment]
> An alternative would be to configure the repo so owners could override the "must have an approved review" requirement at need.

Yes, but I didn't see any way to configure that... An alternative would be to unprotect the branch, merge and reprotect it, but it's impractical, and we could easily forget to reprotect it.

**Comment by blairconrad** [comment]
Oh. I'm pretty sure I have a repo that's so configured. Stay tuned.

**Comment by blairconrad** [comment]
![image](https://user-images.githubusercontent.com/3275797/31900017-26b90f3e-b7eb-11e7-90ac-4adaccde5f63.png)


It's the "Include administrators" checkbox on the [branch protection page](https://github.com/FakeItEasy/FakeItEasy/settings/branches/develop) that can be cleared to allow the behaviour. Then, if I recall correctly, it takes _2_ clicks to merge a request with no approved pull request review. I can quick send one and see.

Yes. Like this:

![image](https://user-images.githubusercontent.com/3275797/31900202-b149299a-b7eb-11e7-9307-037f57126701.png)

Then after I hit "merge pull request", the confirmation:
![image](https://user-images.githubusercontent.com/3275797/31900176-a50b8df8-b7eb-11e7-9dd5-698de99deea5.png)

**Comment by thomaslevesque** [comment]
Yes, I've seen this checkbox, but it will apply to all PRs, not just the release ones... Maybe it doesn't matter, though. The red button should be enough of a warning to remind us that we should get a review before merging.

**Comment by blairconrad** [comment]
I think we're all three of us responsible enough that setting is safe. We'll do the right thing.

**Comment by blairconrad** [comment]
Given our apparent openness to allowing merge of "release PRs" (and consequently all PRs) by having owners confirm the merge (with big red angry buttons), I've renamed this issue to be about "what we want" rather than "how we want to achieve it".

Shall we just change the "Include administrators" setting on the [branch protection page](https://github.com/FakeItEasy/FakeItEasy/settings/branches/develop)?
One (minor) advantage of this approach over using a bot is that it's a lot easier to test changes to the system, since we can keep personal authorization tokens in our sandboxes and do fake releases against our forks. Otherwise, we'd have to swap in personal tokens for the bot tokens to test.

**Comment by thomaslevesque** [comment]
Sounds good to me!

**Comment by thomaslevesque** [comment]
I unchecked the "Include administrators" setting for the master branch.

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque. I've updated the procedure in #1240 to reflect the exception we have that allows us to merge release PRs.

**Comment by thomaslevesque** [comment]
> I've updated the procedure in #1240 to reflect the exception we have that allows us to merge release PRs.

Good thinking, thanks! I *always* forget this kind of thing ;)

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.2.0).
