### ISSUE TITLE
Augment prepare_release to deal with hotfixes

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1245]
The current `prepare_release` script is only capable of helping with mainline releases, not hotfixes. We could augment it (or provide a companion script) to

1. create the milestone, GitHub release, and release issue for the hotfix (a large deviation, since the current script assumes that vNext artifacts exist and need to be renamed)
1. create the hotfix/a.b.c branch from a tag
1. create PRs to both develop and master from the hotfix/a.b.c branch

We might also want to tweak the prepare_release script (or the new one) to support pre-release versions of hotfixes, although I'd also consider that for a later step.

**Comment by blairconrad** [comment]
I wonder if this is worthwhile. We release hotfixes less frequently than we retool. We could just prepare our rare hotfixes manually.

**Comment by thomaslevesque** [comment]
> I wonder if this is worthwhile. We release hotfixes less frequently than we retool. We could just prepare our rare hotfixes manually.

Agreed. Let's close this.
