### ISSUE TITLE
Unclutter the root directory

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1249]
The root of the repo is currently a bit of a mess. There are 23 files in the root directory, and every new script we add makes it worse (especially for .csx scripts which need a .cmd bootstrapper). We should probably try to move some of these files to a subdirectory.

Files and directories that could be moved to a subdirectory:
- `build.csx`: the .cmd bootstrapper probably needs to stay at the root, but we can move the actual script
- `prepare_release.csx`: same reasoning
- `.githubtoken`*: should probably be next to `prepare_release.csx`
- `deploy.ps1`: only called by AppVeyor, we don't need it at the root
- `packages.config` and `packages/`*: it's only used by csx scripts (all projects now use the package cache and `PackageReference`)
- `.nuget/`*: the projects no longer need it, it's only used by scripts
- `FakeItEasy.Dictionary.xml`, `FakeItEasy.ruleset`, `FakeItEasy.snk`: referenced from `Directory.Build.props`, which can specify a subdirectory
- `mkdocs.yml`: according [to the documentation](http://read-the-docs.readthedocs.io/en/latest/builds.html#mkdocs), we could move it to the `docs` folder

Files that should stay at the root:
- `.editorconfig`, `.gitignore`, `.gitattributes`: apply to the whole repo
- `.mailmap`: Git looks for it at the root of the repo
- `appveyor.yml`: AppVeyor looks for it at the root of the repo
- `build.cmd`: should be easily accessible
- `CONTRIBUTING.md`: it's the standard location on GitHub
- `Directory.Build.props`: applies to projects in all subdirectories
- `FakeItEasy.sln`: should be easily accessible, and the root is the only directory that contains all projects
- `GitVersion.yml`: it has to be in the working directory, which is the root during build. Putting it somewhere else would be awkward
- `global.json`: applies to projects in all subdirectories
- `Licence.txt`: it's the standard location on GitHub
- `README.md`: standard location on GitHub

Unsure:
- `how_to_build.md`: could probably be in a subdirectory, but it needs to be easy to find. If we move it, we could add a link in the README.
- `prepare_release.cmd`: it's more convenient to have it at the root, but on the other hand, it's only used by the maintainers, and we don't need it very often.

(files and folders with a `*` are excluded from source control, so they wouldn't appear in the GitHub repo anyway)

**Comment by blairconrad** [comment]
Great analysis, @thomaslevesque. All the "sure" stuff sounds good to me. As far as `prepare_release.cmd` goes, I don't mind it moving to be slightly less convenient.

I'm torn on `how_to_build.md`. We already link to it from `CONTRIBUTING.md`, but I do like it being easy to find. I've checked out other repos and looked for a file with a similar name. Perhaps we should leave it.

**Comment by thomaslevesque** [comment]
Let's leave how_to_build.md where it is then, at least for now. We can revisit later.

**Comment by blairconrad** [comment]
I updated the path to `prepare_release.cmd` in #1240.

**Comment by thomaslevesque** [comment]
> I updated the path to prepare_release.cmd in #1240.

👍

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.2.0).
