### ISSUE TITLE
Fix path to nuget.exe in deploy.ps1

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1262]
We failed to push the packages to NuGet.org [when releasing 4.2.0](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/537#L420).

**Comment by thomaslevesque** [comment]
Oops. When I moved the scripts, I tested them, but to test this one I commented out the calls that would actually upload something...

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.3.0).
