### ISSUE TITLE
Updating to 4.2.0 removes the analyzer from the project file

### ISSUE THREAD

**Issue by xt0rted** [FakeItEasy/FakeItEasy#1263]
I had 4.0.0 installed of FakeItEasy and FakeItEasy.Analyzer.CSharp. I just tried to update them to 4.2.0 and noticed that the analyzer was removed from the project file. I then tried to reinstall it but that didn't add it back.

I then removed the analyzer entirely and tried installing 4.0.0, then removed it and tried 4.1.0, etc. and the only versions that add the analyzer to the project file are 4.0.0 and 4.1.0.

I've tried restarting VS2017, using the package manager console, and VS2017 Preview but the analyzer still isn't installed from 4.1.1 on.

**Comment by thomaslevesque** [comment]
Hi @xt0rted,

That's odd... I'm unable to reproduce the issue so far.
Could you provide a few more details?

- Which framework are you targeting? .NET Core 1/2, .NET Framework... ?
- What kind of project is it? "classic" csproj or "SDK-style" project (.NET Core SDK)?
- If it's a classic csproj, are you managing packages with packages.config or `<PackageReference />`?

**Comment by xt0rted** [comment]
I'm seeing this in two different projects.

- .NET 4.6.2 and .NET 4.7
- Classic csproj
- packages.config
- VS2017 15.4.2

I just created a new empty project and had the same results, didn't matter what version of .net I targeted.

VS 15.5.0 Preview 3 just installed so I need to reboot before I can test in that again.

**Comment by thomaslevesque** [comment]
Ah, I see. I can reproduce it now. Something has changed in the package structure.

4.1.1:
![image](https://user-images.githubusercontent.com/1864281/32543775-d0b3abc4-c476-11e7-9690-d58de230462d.png)

4.2.0:
![image](https://user-images.githubusercontent.com/1864281/32543798-e903c2a4-c476-11e7-9cd2-df7916c9f368.png)

Not sure why it changed, though... we'll need to investigate.

**Comment by thomaslevesque** [comment]
It might be related to #1248.

**Comment by xt0rted** [comment]
The package structure of `4.0.0` and `4.1.0` match that of `4.1.1`, but `4.1.1` doesn't install the analyzer either.

**Comment by thomaslevesque** [comment]
> It might be related to #1248.

Confirmed. Downgrading to .NET Core SDK 1.0.4 generates the package correctly.

> The package structure of 4.0.0 and 4.1.0 match that of 4.1.1, but 4.1.1 doesn't install the analyzer either.

That's not what I observed; 4.1.1 is correctly installed for me.

**Comment by xt0rted** [comment]
This is so strange. In my test project if I install 4.0.0 then update to 4.1.0 the analyzer is removed even though the package is updated. Then if I update to 4.1.1 the analyzer is added back in. I can keep changing the versions to any of the 3 before 4.2.0 and every other install will remove the analyzer. The only package that won't install it at all is 4.2.0.

**Comment by thomaslevesque** [comment]
> This is so strange. In my test project if I install 4.0.0 then update to 4.1.0 the analyzer is removed even though the package is updated.

That looks like a bug in NuGet... I tested by removing/reinstalling every time, so I didn't encounter this problem. 

> The only package that won't install it at all is 4.2.0.

Exactly. I'm pretty sure this is because of the change in package structure.

**Comment by thomaslevesque** [comment]
We used [this](https://github.com/FakeItEasy/FakeItEasy/blob/8f649f313f8afaa35871475ca00ae94a55db91ec/src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.CSharp.csproj#L14) to prevent `dotnet pack` from including the TFM in the output path, but it looks like it's no longer honored with the 2.0.2 SDK...

**Comment by thomaslevesque** [comment]
Opened https://github.com/dotnet/sdk/issues/1717

**Comment by blairconrad** [comment]
Shall we de-list the recent analyzer packages in the meantime?

**Comment by thomaslevesque** [comment]
> Shall we de-list the recent analyzer packages in the meantime?

👍

**Comment by blairconrad** [comment]
Done. Back to 4.1.1.

**Comment by thomaslevesque** [comment]
Apparently the behavior to include the TFM in the path is [hard-coded](https://github.com/NuGet/NuGet.Client/blob/eb6fe311289908d5e1fe6f644030c704be2bc15c/src/NuGet.Core/NuGet.Commands/MSBuildProjectFactory.cs#L142), so there's no way to work around the issue by tweaking the project... The only way I can see is to revert to using nuspec + nuget.exe instead of `dotnet pack`. Or revert to SDK 1.x...

**Comment by thomaslevesque** [comment]
> Or revert to SDK 1.x...

1.0.x in fact... The new behavior was already there in 1.1.0.

**Comment by blairconrad** [comment]
Just to make sure I understand, the new SDKs  do not provide a way to pack .NET Standard-based Analyzers?
I'm surprised nobody was up in arms about this before now.

If we have to revert to nuspec + nuget.exe, I guess we can. It's a shame, though.

**Comment by thomaslevesque** [comment]
> Just to make sure I understand, the new SDKs do not provide a way to pack .NET Standard-based Analyzers?

Well, you can pack them, but the assemblies end-up in a netstandard1.1 subfolder. It works when you install into a SDK-style project, but not in classic csproj.

> I'm surprised nobody was up in arms about this before now.

Yeah, me too... I looked at a few popular analyzer packages, they all seem to use nuspec files.

> If we have to revert to nuspec + nuget.exe, I guess we can. It's a shame, though.

I'd rather avoid it if possible... let's wait for feedback in dotnet/sdk#1717

**Comment by blairconrad** [comment]
> Well, you can pack them,

Sorry, I meant "pack them so they work"

> but the assemblies end-up in a netstandard1.1 subfolder. It works when you install into a SDK-style project, but not in classic csproj.

Ah. I didn't realise it was working for SDK-style projects.

**Comment by xt0rted** [comment]
The analyzer reference being removed is a bug with NuGet. The issue for that is https://github.com/NuGet/Home/issues/6035

**Comment by blairconrad** [comment]
dotnet/sdk#1717 has been moved to NuGet/Home#6184

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.3.0).

Thanks for your this, @xt0rted and @rohit21agrawal. Look for your name in the release notes! :trophy:
