### ISSUE TITLE
Docs do not render properly

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1267]
| |4.1.1|4.2.0|
|-|-----|-----|
|Table of Contents|![image](https://user-images.githubusercontent.com/3275797/32698771-cf828072-c778-11e7-8878-907273a8164e.png)|![image](https://user-images.githubusercontent.com/3275797/32698743-72371ce8-c778-11e7-8d1f-e3421e64ad54.png)|
|Code styling|![image](https://user-images.githubusercontent.com/3275797/32698786-0a72a82e-c779-11e7-8288-c2e978c0142b.png)|![image](https://user-images.githubusercontent.com/3275797/32698788-11bde418-c779-11e7-8811-e4de59320c2b.png)|

I'm sure this is due to the move of `mkdocs.yml` to the `docs` directory as part of the fix for #1249.

**Comment by blairconrad** [comment]
I've been experimenting locally with mkdocs directly, as well as having readthedocs build a branch that I set up on my fork, and will be submitting an issue to them later, as well as a workaround for us.

**Comment by thomaslevesque** [comment]
Looks like the mkdocs.yml file is being ignored...

The easy workaround would be to move it back to the root, but according to [this](http://read-the-docs.readthedocs.io/en/latest/builds.html#mkdocs), the `docs` or `doc` directory should be the first place where ReadTheDocs looks for it...

**Comment by blairconrad** [comment]
Yup, all true. I would have submitted a PR already, but I've not been sitting at a computer. It'll come.

**Comment by blairconrad** [comment]
Until we release a new version, having "latest" be the default build that people see when they go to readthedocs. Then we can restore to "stable".

On that note, I'd consider releasing, but we've no package-level changes to publish. (A disadvantage of hosting tying the docs to the project version.)

**Comment by thomaslevesque** [comment]
> Until we release a new version, having "latest" be the default build that people see when they go to readthedocs. Then we can restore to "stable".

👍 

> On that note, I'd consider releasing, but we've no package-level changes to publish. (A disadvantage of hosting tying the docs to the project version.)

Well, we could have a branch just for the docs, I guess... it would probably be a bit of a pain to maintain, though.

**Comment by blairconrad** [comment]
> Well, we could have a branch just for the docs, I guess... it would probably be a bit of a pain to maintain, though.

I think better not to. So far, the situation where we have very important docs updates and nothing to release has been rare. Let's see how it goes?

**Comment by thomaslevesque** [comment]
> I think better not to. So far, the situation where we have very important docs updates and nothing to release has been rare. Let's see how it goes?

OK

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.3.0).
