### ISSUE TITLE
Use favicon in the docs

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1269]
[According to mkdocs](http://www.mkdocs.org/?#changing-the-favicon-icon),

> By default, MkDocs uses the MkDocs favicon icon. To use a different icon, create an img subdirectory in your docs_dir and copy your custom favicon.ico file to that directory. MkDocs will automatically detect and use that file as your favicon icon.

Why not do that?

**Comment by blairconrad** [comment]
Ah. This may not work: rtfd/readthedocs.org#1130. In mkdocs at home it looks great, but who knows that readthedocs will do?

**Comment by thomaslevesque** [comment]
> Ah. This may not work: rtfd/readthedocs.org#1130. In mkdocs at home it looks great, but who knows that readthedocs will do?

Well, worst case, it doesn't work... no harm done. Let's try ;)

**Comment by thomaslevesque** [comment]
It seems to work!

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.3.0).
