### ISSUE TITLE
Add WithVoidReturnType method

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1272]
As mentioned a few times in the past, we should have a `WithVoidReturnType` method that mirrors `WithNonVoidReturnType`.

**Comment by thomaslevesque** [comment]
Note that it is technically a breaking change, since it touches the configuration interfaces; the change would affect people who implemented `IAnyCallConfigurationWithNoReturnTypeSpecified` in their code, but I can't think of any good reason to do that.

I don't remember what we did in the past for similar cases. If we consider this breaking, it means we can *never* add a feature at the configuration level without causing a breaking change...

**Comment by blairconrad** [comment]
@thomaslevesque continues:

> If we consider this to be breaking, merging it now means the next version will be 5.0.0. (IMO we shouldn't consider this a breaking change; it's true that it changes an interface, but I'm willing to bet that not a single user will be affected)

We're the same. Technically breaking, but nearly everything is. Practically, this should not interfere with anyone. There's no reason for any clients to implement `IAnyCallConfigurationWithNoReturnTypeSpecified`. The only real use of the type is for clients to consume it from the `CallTo` and `AnyCalls` methods and use the methods defined on it.
I think we can stay at 4.3.0.

**Comment by thomaslevesque** [comment]
Agreed 👍

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.3.0).
