### ISSUE TITLE
Add reference to Microsoft.CSharp in the package

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1284]
This is required in order to use dynamic features, such as `Raise.FreeForm`.

Thanks to @MrVermond for [reporting the issue in the chat](https://gitter.im/FakeItEasy/FakeItEasy?at=5a55fec4ba39a53f1afb18e8).

**Comment by thomaslevesque** [comment]
Adding `<Reference Include="Microsoft.CSharp" />` to the csproj is correctly reflected in the nuspec as a `<frameworkAssembly>` element, but this only works for the full .NET Framework. To support all target frameworks, we need to reference the `Microsoft.CSharp` NuGet package.

**Comment by blairconrad** [comment]
@thomaslevesque, shall we consider this a bug fix, since we were not properly exposing our dependencies?

**Comment by thomaslevesque** [comment]
> shall we consider this a bug fix

I wasn't sure, so I didn't add a tag... I guess we could consider this a bug. To be fair, FakeItEasy itself doesn't use any dynamic feature; the user does, although it's not obvious from the usage.

> since we were not properly exposing our dependencies?

Strictly speaking, it's not really our dependency, but we should probably make things easy for the user and add the reference when the package is installed.

**Comment by thomaslevesque** [comment]
> Adding `<Reference Include="Microsoft.CSharp" />` to the csproj is correctly reflected in the nuspec as a `<frameworkAssembly>` element, but this only works for the full .NET Framework. To support all target frameworks, we need to reference the Microsoft.CSharp NuGet package.

Apparently the package isn't compatible with net40; it requires net45 or higher. So, we need a `PackageReference` for netstandard1.6, and a `Reference` for net40; for net45 it doesn't matter (the package just adds a reference to the framework assembly).

**Comment by blairconrad** [comment]
Pretend I don't understand things. How are we affected if the client is writing in VB?

**Comment by thomaslevesque** [comment]
> Pretend I don't understand things. How are we affected if the client is writing in VB?

Excellent question. My guess is that it should already work in VB, since VB.NET natively supports late binding. Only C# requires a special assembly for using dynamic features.

But a guess is not enough; I'll experiment a bit to be sure.

**Comment by thomaslevesque** [comment]
My guess was wrong. It doesn't work at all in VB (although it compiles fine). Also, the syntax is ugly; I guess VB wasn't really considered when the `Raise` feature was designed.

    AddHandler foo.PropertyChanged, Raise.FreeForm.With(foo, new PropertyChangedEventArgs("Blah"))

For some reason, it doesn't invoke the dynamic conversion (`DynamicRaiser.TryConvert`) that makes the magic work, even with `Option Strict Off`. It just throws `Unable to cast object of type 'FakeItEasy.Core.DynamicRaiser' to type 'System.ComponentModel.PropertyChangedEventHandler`. I thought maybe it just didn't work in the `AddHandler` statement, but this throws the same error:

    Dim h As PropertyChangedEventHandler = Raise.FreeForm.With(foo, new PropertyChangedEventArgs("Blah"))
    AddHandler foo.PropertyChanged, h

**Comment by thomaslevesque** [comment]
Apparently this isn't supported at all in VB; [this example](https://gist.github.com/thomaslevesque/e83bbd84e42148bb8a2d7fa0b7e323ce) throws, when the [equivalent C# code](https://gist.github.com/thomaslevesque/21dd105cb7ab29793ff3d71ed70f562f) works.

I'm afraid this feature just isn't usable from VB.NET...

**Comment by thomaslevesque** [comment]
Unless we can make it work, I think we'll need to un-deprecate `Raise.With<TEventHandler>`, because it's the only way to raise an event other than `EventHandler<TEventArgs>` in VB.NET.

(on the other hand, v4.0.0 has been out for a while now, and nobody complained... I suspect we don't have many VB.NET users)

**Comment by thomaslevesque** [comment]
I found something that works, but it's even more ugly:

    AddHandler foo.PropertyChanged, CTypeDynamic(Raise.FreeForm.With(foo, new PropertyChangedEventArgs("Blah")), GetType(PropertyChangedEventHandler))

As a workaround, maybe we should introduce something like `Raise.FreeForm<TEventHandler>.With(...)`; it would achieve the same thing as `Raise.FreeForm.With(...)`, but without using `dynamic`. VB.NET usage would be as follows:

    AddHandler foo.PropertyChanged, Raise.FreeForm(Of PropertyChangedEventHandler).With(foo, new PropertyChangedEventArgs("Blah"))

Still not great, but a little less ugly...

Anyway, I think the `AddHandler` syntax is a pretty bad confusing way to raise events in VB... I wish we could do something better, but there's no easy way to refer to an event in either C# of VB; subscribing or unsubscribing are the only possible operations.

**Comment by blairconrad** [comment]
Thanks for all the research, @thomaslevesque. You're probably right about the low number of VB.NET users. I'm confused about something, though. You suggested introducing 

```vb.net
AddHandler foo.PropertyChanged, Raise.FreeForm(Of PropertyChangedEventHandler).With(foo, new PropertyChangedEventArgs("Blah"))
```

which would work like `Raise.Freeform.With`, but without using `dynamic`.  I am not sure how this differs (aside from syntax) from the now-obsolete

```vb.net
AddHandler foo.PropertyChanged, Raise.With(Of PropertyChangedEventHandler)(foo, new PropertyChangedEventArgs("Blah"))
```

**Comment by thomaslevesque** [comment]
> I am not sure how this differs (aside from syntax) from the now-obsolete

It doesn't. But it's less confusing than having two generic overloads of `Raise.With` that are so similar yet different (the generic type argument means something different for `With<TEventArgs>` and `With<TEventHandler>`, which can possibly cause ambiguities)

**Comment by thomaslevesque** [comment]
Anyway... it looks like VB.NET is a whole new issue, not related to the Microsoft.CSharp fix. We should probably open a new issue to track it.

**Comment by blairconrad** [comment]
Agreed about new issue for VB.NET.

Regarding this issue, I feel a little funny adding the dependency when many users won't need it (VB users, anyone who doesn't want to raise an event freeformly), but see no good alternative. The best I can think of is documentation (our site docs as well as API docs on the method), and I'm not sure they'd be enough.

**Comment by thomaslevesque** [comment]
> I feel a little funny adding the dependency when many users won't need it (VB users, anyone who doesn't want to raise an event freeformly)

That's a very good point. It's like adding Microsoft.VisualBasic to a C# project. I don't think there's a way to add a reference only for a specific language (at some point it was possible to run a script when the package was installed, but I think this feature is deprecated). Maybe we should just document the fact that a reference to Microsoft.CSharp is needed to use `Raise.Freeform`, and not add the reference.

**Comment by thomaslevesque** [comment]
I sent an [alternative PR](https://github.com/FakeItEasy/FakeItEasy/pull/1286) to document the reference instead of adding it ourselves

**Comment by blairconrad** [comment]
> it looks like VB.NET is a whole new issue, not related to the Microsoft.CSharp fix. We should probably open a new issue to track it.

Done. #1287.

**Comment by thomaslevesque** [comment]
Thanks!

**Comment by blairconrad** [comment]
Closing, since we decided to document the situation instead. Documentation added in #1286.
