### ISSUE TITLE
Raise.Freeform.With is not available from VB.Net and our only alternative is deprecated

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1287]
spun off from https://github.com/FakeItEasy/FakeItEasy/issues/1284#issuecomment-356742263

@thomaslevesque suggested either un-deprecating
`Raise.With(Of PropertyChangedEventHandler)(foo, new PropertyChangedEventArgs("Blah"))`
or introducing something like
`Raise.FreeForm(Of PropertyChangedEventHandler).With(foo, new PropertyChangedEventArgs("Blah"))`
for VB.Net.

His rational for the latter is 
> …it's less confusing than having two generic overloads of `Raise.With` that are so similar yet different (the generic type argument means something different for `With<TEventArgs>` and `With<TEventHandler>`, which can possibly cause ambiguities)

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.4.0).

Thanks for your help with this, @MrVermond. Look for your name in the release notes! :trophy:

**Comment by MrVermond** [comment]
Thank you for taking care of that!!!
Great Lib, glad I could help.
