### ISSUE TITLE
Encourage static using Repeated to improve test readability

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1288]
As has been pointed out in #808, specifying desired call counts using `Repeated` can cause confusion, as it's possible to interpret

```c#
A.CallTo(()=>f.Boo()).MustHaveHappened(Repeated.Exactly.Once);
```

to mean that `Boo` must have been called once initially and then an additional time, for a total of 2 calls.

We've so far rejected proposals to change `Repeated`, mostly because it's a breaking change and the advantages presented so far don't seem to outweigh the inconvenience to the majority of users who are currently using the syntax with no issues.

One option available to FakeItEasy clients who are using C#6 or more is to use a `static using FakeItEasy.Repeated;`. This would clean up the code in the tests itself, making this syntax possible:

```c#
A.CallTo(()=>f.Boo()).MustHaveHappened(Exactly.Once);
```

We should update our documentation (readthedocs, XML API docs, sample projects) to promote this usage.

**Comment by blairconrad** [comment]
Placing on hold while we consider an alternative mechanism for specifying call counts. See #808 for details.

**Comment by thomaslevesque** [comment]
I think we can close this now.

**Comment by blairconrad** [comment]
Whoops. Thanks!
