### ISSUE TITLE
Rename IRepeatConfiguration to something not containing "repeat" in 5.0.0

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1294]
In https://github.com/FakeItEasy/FakeItEasy/pull/1293#issuecomment-362575624, @thomaslevesque notes that 

> Besides the to-be-deprecated `Repeated`/`IRepeatSpecification`, the only remaining ambiguous API is `IRepeatConfiguration` (used for call behavior specifications, not assertions), and the user doesn't manipulate it explicitly; we should probably rename it in the next major release anyway.

When he's right, he's right.

**Comment by blairconrad** [comment]
The reason for avoiding "repeat" is that the word can connote "one time plus the number of repeat times". Some people will think that `NumberOfTimes(int numberOfTimesToRepeat)` when called with that value `4` means "4 times" and some may think "5 times".

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
