### ISSUE TITLE
Call description is wrong when asserting a call to a property setter

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1298]
Consider this code:

```c#
public interface IFoo {  int Bar { get; set; } }
public void Test()
{
    var foo = A.Fake<IFoo>();
    foo.Bar = 0;
    A.CallToSet(() => foo.Bar).To(42).MustHaveHappened();
}
```
As expected, this throws an `ExpectationException`, but the call description in the exception message is wrong:

> Assertion failed for the following call:
>     Castle.Proxies.ObjectProxy_12.set_Bar(value: 42)
>   Expected to find it once or more but didn't find it among the calls:
>     1: UserQuery+IFoo.Bar = 0

It should say `UserQuery+IFoo` instead of `Castle.Proxies.ObjectProxy_12`. It works as expected for method calls and property getters, the issue seems to exist only for property setters.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.4.0).
