### ISSUE TITLE
Make descriptions of calls to property accessors more consistent

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1299]
When we assert calls on property accessors, the descriptions are inconsistent between the asserted calls and the list of actual calls made to the fake.

Currently we have this for the asserted calls:
- getter: `IFoo.get_Bar()`
- setter: `IFoo.set_Bar(value: 42)` (*)

But in the list of actual calls, we have this: 
- getter: `IFoo.Bar`
- setter: `IFoo.Bar = 42`

Which I think is better. Anyway, we should probably make the descriptions consistent with each other.

(*) That's a lie. In fact we have `Castle.Proxies.ObjectProxy_12` instead of `IFoo`, but it's another issue (#1298)

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.4.0).
