### ISSUE TITLE
Use AppVeyor build caches

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1323]
[AppVeyor build caches](https://www.appveyor.com/docs/build-cache/) allow us to have some files be retained between builds. We might want to adopt this for

- the nuget.exe in the sandbox directory, and 
- imported nuget packages in `%USERPROFILE%\.nuget\packages`

With luck, this would speed up the builds (the restore phase can take about ~~45 seconds or so (my mistake, I was counting from the beginning of build)~~ 30 seconds or so, 12 seconds to fetch the NuGet.exe) and might be nicer to the AppVeyor infrastructure, so they don't have to fetch the packages anew each time (although they may have their own shared cache for well-known packages; I'm not sure).

Of course we'd want to invalidate the caches when the dependencies change.

**Comment by blairconrad** [comment]
@FakeItEasy/owners, is there a reason not to do this? I'd be interested in at least experimenting.

**Comment by blairconrad** [comment]
Ugh. It seems it takes about 70 seconds to verify the checksums on the csprojs and directory.build.propses, and to unpack the zip files for the nuget packages. That part may be a dud. But sticking to just caching the NuGet.exe might still provide (minor) benefit.

**Comment by blairconrad** [comment]
Bah. It seems that even the gap that I thought was due to downloading NuGet.exe may be the delay when csi starts up build.csx.
I'm not sure the benefit is here. Abandoning.

**Comment by thomaslevesque** [comment]
It was worth a shot anyway, thanks for investigating.

Me, I wish we could disable the "publish test results" step (maybe we can, I haven't looked yet). It takes ages to complete after the build script is done, and brings no benefits, as far as I can tell. The list of tests is so long it makes the browser lag (Firefox at least), so it's unusable.

> Bah. It seems that even the gap that I thought was due to downloading NuGet.exe may be the delay when csi starts up build.csx.

Yeah, csi takes a while to start... just `build.cmd -h` is pretty long.

**Comment by blairconrad** [comment]
> I wish we could disable the "publish test results" step 

We can. I played with it last night. It really speeds things up.
It means we won't get results in the "Tests" tab. I have no problems with this. Want me to? Great! Stay tuned!
