### ISSUE TITLE
Stop reporting tests to AppVeyor

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1326]
As [has been reported](https://github.com/FakeItEasy/FakeItEasy/issues/1323#issuecomment-367960538) (and it's not the first time we've griped about it amongst ourselves), AppVeyor takes about as long to gather the test results as it does to run the whole rest of the build. And we see little or no benefit in it doing so. So let's stop reporting the tests to it.

**Comment by thomaslevesque** [comment]
:+1:

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.5.1](https://github.com/FakeItEasy/FakeItEasy/releases/4.5.1).
