### ISSUE TITLE
Stop trying to run coverity builds

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1334]
I noticed that the [coverity badge is broken](https://github.com/FakeItEasy/FakeItEasy/blob/develop/README.md)
![image](https://user-images.githubusercontent.com/3275797/36851969-98fbe032-1d38-11e8-8d56-7b5dedcd1b9c.png)

because the `https://scan.coverity.com/projects/fakeiteasy-fakeiteasy` endpoint is gone, and I am not sure how to rectify.

Then I noticed that we hadn't been running coverity builds since [build 539](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/539).

An exhaustive search revealed that we'd lost the crontab setting for nightly builds after [AppVeyor removed scheduled builds for free accounts](https://www.appveyor.com/blog/2017/11/08/sheduled-builds-for-free-accounts/). We can request they be reinstated for our account, but I don't think we've once had a meaningful finding from the coverity analysis. And even if we turned the build back on, we'd still have a broken badge!

Me, I'd just drop coverity. I don't think it pays its way.

**Comment by blairconrad** [comment]
@adamralph, you were the initial proponent of running the builds, in #434, so I'm especially interested in your thoughts.

**Comment by adamralph** [comment]
At the time, assuming it was cheap to set up, I thought "why not"? If it's providing no value then 👍 to get rid of it.

**Comment by blairconrad** [comment]
Thanks.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.6.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.6.0).
