### ISSUE TITLE
Document limitations of working with ref returns, in parameters

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1337]
As revealed by:

 https://gist.github.com/thomaslevesque/76a8b2677ab37f9f7ff04e87f80b9b74.

The `in` parameter weakness is a result of https://github.com/castleproject/Core/issues/339.

**Comment by thomaslevesque** [comment]
Note that once the bug in Castle.Core is fixed and we upgrade to the fixed version, the `in` parameter limitation will go away.

**Comment by blairconrad** [comment]
Indeed. I'd toyed with the idea of adding a [characterization test](https://en.wikipedia.org/wiki/Characterization_test) to the specs to capture the current behaviour, with a comment to update the docs. Then when we roll forward to a new Castle.Core with the issue fixed, the tests would make sure we 
1. added (updated) a test with the desired behaviour, and
2. fixed the docs

**Comment by thomaslevesque** [comment]
👍

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.6.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.6.0).
