### ISSUE TITLE
Allow Faking of non-generic types with methods that have in parameters

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1338]
As mentioned in #1337, and due to castleproject/Core#339, types containing a method with an `in` parameter cannot be faked by FakeItEasy .NET Standard, and if the type is a generic type, it cannot be faked by either the FakeItEasy .NET Standard or .NET Framework editions. 

Once Castle.Core supports these scenarios, we should do so as well.

**Comment by blairconrad** [comment]
Since Castle.Core 4.3.0 was released, we can support `in` parameters on non-generic types. I will start that work.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.7.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.7.0).

**Comment by zvirja** [comment]
@blairconrad Do you `in` for delegate fakes? Recently I solved that for NSubstitute and extra efforts were required:
https://github.com/nsubstitute/NSubstitute/pull/420
https://github.com/nsubstitute/NSubstitute/pull/421

Sorry if I'm missing something - just wanted to highlight this :wink:

**Comment by thomaslevesque** [comment]
@zvirja I just checked. Faking delegates with `in` parameters works, but the read-only semantics is not honored, e.g. this will print 123:

    delegate void Foo(in int x);
    ...
    var foo = A.Fake<Foo>();
    A.CallTo(() => foo(A<int>.Ignored)).AssignsOutAndRefParameters(123);
    int z = 0;
    foo(z);
    Console.WriteLine(z);

Thanks for bring this to our attention. I'll open a new issue.

**Comment by blairconrad** [comment]
Yes, thanks @zvirja. And @thomaslevesque for verifying. I'd meant to look last night, but we're expecting houseguests, and the vacuuming sucked up (ha!) all my time.
