### ISSUE TITLE
EqualityArgumentConstraint doesn't use argument value formatters

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1343]
As mentioned in #1196, `EqualityArgumentConstraint` (used to represent "constant" argument values in call specifications) should have been updated to use `ArgumentValueFormatter`, but was somehow forgotten during the implementation.

**Comment by thomaslevesque** [comment]
OK, fixing this breaks a few tests. It now prints `[]` for a faked list, instead of `Faked System.Collections.Generic.List`1[System.Int32]`. This is because `ArgumentValueFormatter` doesn't do anything special when the argument value is a fake; it just sees a collection and renders it as such.

I'm not sure if it's a problem or not. I'm assuming it's not.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.6.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.6.0).
