### ISSUE TITLE
Protect against exceptions when resolving constructor arguments for Fake/Dummy creation

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1348]
As mentioned in #1347, if a `ResolveStrategy` throws, it could derail the entire Fake or Dummy creation process. We should protect against this.

On the other hand, catching `ResolveStrategy` errors may just end up concealing the reason for the failure, so taking the simple path of putting a try/catch or two in `TryResolveDummyValueWithAllAvailableStrategies`, may not be the best bet.

For example, if we try to make a Dummy `Lazy`, `ResolveByCreatingLazyStrategy` is really the best bet. If it fails, maybe we'd like the exception to fly.

However, for the more speculative resolvers, such as `ResolveByCreatingFakeStrategy` and `ResolveByInstantiatingClassUsingDummyValuesAsConstructorArgumentsStrategy`, which could each make several attempts to create a Dummy, it might be best to catch exceptions raised within them and carry on with the attempts. For example, as noted in #1345, we cannot make a Dummy `string` under dotnet core 2.1 rc1 because we fail to create a `ReadOnlySpan<T>`, which can be used as a string constructor argument.

If we just accepted that we can't make a `ReadOnlySpan<T>`, we could move on to another constructor and still create a `string`.

**Comment by thomaslevesque** [comment]
> If we just accepted that we can't make a `ReadOnlySpan<T>`, we could move on to another constructor and still create a `string`.

`string` is really a special case, we should probably treat it as such as have a specific dummy factory for it.

**Comment by thomaslevesque** [comment]
> But what if somebody has made a Dummy factory for Char[]? Then all of a sudden we've changed the string Dummies out from under them. 😄

I don't remember the priorities when creating a dummy... Don't we use user-provided dummy factories over built-in resolution strategies?

> We could still do it sometime. But for now, and it seems you agree, due to merge, I figured this was the best course. What if something else uses a ReadOnlySpan?

Maybe we could have a special case for this too, e.g. create an empty `ReadOnlySpan`. We'd have to do it via reflection, though, since we don't want to take a dependency on `System.Memory`

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.6.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.6.0).

Thanks, @ryanwischkaemper. Look for your name in the release notes! :trophy:
