### ISSUE TITLE
Resolve Fakes' constructor arguments lazily

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1350]
From #1347: `TryCreateFakeWithDummyArgumentsForConstructor` eagerly determines which constructors' arguments can be resolved, by resolving the arguments. That is, every possible argument for every possible constructor is attempted, even if the first constructor succeeds.

For example, if we construct a Dummy `string` (under net461), we end up creating 1 `Char *`, 3 `Char[]`s, 12 `Int32`s, and 1 `SByte *`—much more than we need, since the first constructor found (taking a `Char[]` and 2 `Int32`s) would succeed. Contrast `ResolveByInstantiatingClassUsingDummyValuesAsConstructorArgumentsStrategy`, which only resolves constructor arguments as needed.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.6.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.6.0).

**Comment by TimLovellSmith** [comment]
Sweet... so basically if I update to 4.6 I won't have to see this first chance exception any more?

```
Castle.DynamicProxy.Generators.GeneratorException: 'Can not create proxy for type System.SByte* because it is not accessible. Make it public, or internal and mark your assembly with [assembly: InternalsVisibleTo("DynamicProxyGenAssembly2, PublicKey=0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7")] attribute, because assembly mscorlib is strong-named.'
```

**Comment by blairconrad** [comment]
I believe so. But why not upgrade to 5.2.0?

**Comment by TimLovellSmith** [comment]
@blairconrad  Trying that now. Just a few more tests to fix!. :)
