### ISSUE TITLE
Stop attempting to create IsByRefLike types

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1362]
In #1348, we started catching exceptions when attempts to create Dummies for constructor arguments failed. This fixed #1345, but is inelegant.
We should detect when we're trying to create an `IsByRefLike` type and refuse to do so, rather than having an exception thrown.

**Comment by blairconrad** [comment]
@thomaslevesque, I'm happy to take this. It should be pretty easy for TFMs that have first-class `.IsByRefLike` support, but I'll see if I can do for all TFMs.

**Comment by thomaslevesque** [comment]
Go ahead 👍

**Comment by blairconrad** [comment]
In sidechat, we established that you actually _can_ create byref-like objects under net462. Other TFMs fail. It would be relatively straightforward to guard against creation under netstandard2.1+, slightly less convenient for netstandard2.0.

We're considering dropping netstandard2.0 and netstandard2.1 support. If we do decide to do so, we might as well wait to fix this issue afterward, just to avoid adding and removing special-cased code for the disappearing TFMs.

**Comment by thomaslevesque** [comment]
Closed by #2022
