### ISSUE TITLE
Creating a dummy for a type with PRIVATE default constructor

### ISSUE THREAD

**Issue by volak** [FakeItEasy/FakeItEasy#1366]
Currently when FakeItEasy goes to make a type with a private constructor we just get back `null` and no warnings / exceptions.

Here's a test:

```c#

public interface Thing { }

public interface Foo
{
    Task<TThing> Bar<TThing>() where TThing : Thing;
}

public class FakeThing : Thing {
    private FakeThing() { }
}

[Fact]
public async Task Test1()
{
    var foo = A.Fake<Foo>();
    var bar = await foo.Bar<FakeThing>();

    Assert.NotNull(bar);
}    
```

Personally - I'd like to see a real dummy actually be created.  Just because the constructor is private shouldn't prevent a dummy from being created.  In my app I make users define aggregate root's as private constructor so a new developer doesn't go and do `var entity = new InvoiceAggregateRoot()` so there is a real use case for creating these objects even though they're marked private.

But the bug is IMO if this behavior is not supported it should throw a "Could not create dummy" exception - not just return null like everything is fine.

**Comment by volak** [comment]
On a related side note - is it possible to hook up FakeItEasy's dummy generation to AutoFixture?

I'm using both - and have defined AutoFixture to create these private types using my factory which handles creating the type.  

```
Fixture.Customize<FakeEntity>(x => x.FromFactory(() =>
            {
                var factory = EntityFactory.For<FakeEntity>();

                var entity = factory.Create(Defaults.Bucket, Fake<Id>(), new Id[] { });

                return entity;
            })
```

**Comment by blairconrad** [comment]
@volak, regarding AutoFixture, I'm glad you've found a way to work with `DummyFactory`. Note that there is an integration with AutoFixture (or rather AutoFixture integrates with FakeItEasy), and that as of AutoFixture.AutoFakeItEasy 4.4.0, it's possible to configure all Fake's members to return values from AutoFixture.

**Comment by volak** [comment]
@blairconrad Thanks! Yes I am using AutoFixture.AutoFakeItEasy - here is a complete test for almost exactly what I am doing

```

    public interface Thing { }

    public interface Foo
    {
        Task<TThing> Bar<TThing>() where TThing : Thing;
    }

    public class FakeThing : Thing {
        private FakeThing() { }
    }



    public class UnitTest1
    {
        public static Func<FakeThing> FactoryFunc()
        {
            var ctor = typeof(FakeThing).GetConstructor(BindingFlags.NonPublic | BindingFlags.Instance, null, new Type[] { }, null);

            var body = Expression.New(ctor);
            var lambda = Expression.Lambda<Func<FakeThing>>(body);

            return lambda.Compile();
        }

        [Fact]
        public async Task Test1()
        {
            var fixture = new Fixture().Customize(new AutoFakeItEasyCustomization());
            fixture.Customize<FakeThing>(x => x.FromFactory(FactoryFunc()));

            // Throws exception of not being able to construct FakeThing
            // fixture.Freeze<Fake<FakeThing>>();
            var foo = fixture.Create<Foo>();
            var bar = await foo.Bar<FakeThing>();

            Assert.NotNull(bar);
        }
    }
```

I customize AutoFixture to create FakeThing using its private constructor but FakeItEasy doesn't work unless I add

```
class UnitTest1 : DummyFactory<FakeThing> 
{
    protected override FakeThing Create() 
    {
        return Fixture.Create<TakeThing>();
    }
}
```

**Comment by blairconrad** [comment]
@volak, I'll continue with your original problem and then get back to AutoFixture.

> Personally - I'd like to see a real dummy actually be created.  Just because the constructor is private shouldn't prevent a dummy from being created.

If the constructor is private, FakeItEasy has no way to make the Dummy. It doesn't know about `ThingFactory`.

If you call `A.Fake<FakeThing>()` or `A.Dummy<FakeThing>()`, you do get a `FakeCreationException`.

In your case, where the `FakeThing` would be a result of a method call, the behaviour is covered in the documentation, under [Default fake behavior/Overrideable members are faked](http://fakeiteasy.readthedocs.io/en/stable/default-fake-behavior/#overrideable-members-are-faked). I quote:

> * If `T` can be made into a Dummy, then a Dummy `T` will be returned. Note that this may be a Fake or an instance of a concrete, pre-existing type;
> * otherwise, `default(T)` will be returned.

Because we cannot create a Dummy `FakeThing`, `default(FakeThing)` (`null`) is returned. This is intentional, as it's generally considered to be the least disruptive behaviour. As in any situation where the default return value is not preferred, it's possible to configure the member to return a different value (or, as you've discovered, to provide an alternative method of creating a Dummy).

**Comment by blairconrad** [comment]
@novak, the ability to configure all of a Fake's members to return values from AutoFixture can be accessed like this:

```c#
var fixture = new Fixture().Customize(new AutoFakeItEasyCustomization { ConfigureMembers = true });
```

I can't find proper user documentation for it, but you can see [the API Docs on the wonderful fuget](https://fuget.org/packages/AutoFixture.AutoFakeItEasy/4.4.0/lib/netstandard1.6/AutoFixture.AutoFakeItEasy.dll/AutoFixture.AutoFakeItEasy/AutoFakeItEasyCustomization).

**Comment by volak** [comment]
Aha! I was just about to point out https://github.com/FakeItEasy/FakeItEasy/blob/24bdbc164f13548c7df5b25af2089b7da7a82742/src/FakeItEasy/Creation/DummyValueResolver.cs#L244

could be modified to return ALL constructors public and private to solve the issue in FakeItEasy

But so long as this `ConfigureMembers` exists my test is green now - so great!

**Comment by blairconrad** [comment]
I'm glad you're up and running, @volak.
