### ISSUE TITLE
Use custom rule for Strict fakes

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1368]
As discussed in https://github.com/FakeItEasy/FakeItEasy/pull/1364

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque!

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.7.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.7.0).
