### ISSUE TITLE
Consider replacing the csx scripts by full-fledged csprojs

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1413]
As discussed in https://github.com/FakeItEasy/FakeItEasy/pull/1410#discussion_r211909659

@adamralph said:

> You might find it simpler to do away with scripting completely, as I've done with xbehave and @blairconrad has done with SelfInitializingFakes. It allows you to drop nuget.exe, csi.exe, packages.config, etc. All you need is a csproj for package references and a Program.Main for your build "script". You can then invoke simply with dotnet run.

It would make things easier and IDE support would be better. Although it feels kind of strange to run a C# project to build a C# project :wink:

**Comment by blairconrad** [comment]
Thumbs up, @thomaslevesque. I thought it was weird too, but I ended up quite enjoying it!

**Comment by thomaslevesque** [comment]
I think it won't be as simple as in SelfInitializingFakes, though. We use several tool packages:

- GitVersion.CommandLine
- PdbGit
- xunit.runner.console
- vswhere

And there's no easy way to get the executable location for those. 


We might try something like [this](https://github.com/filipw/dotnet-script/issues/337#issuecomment-415552388) (as you can see, I already tried to use dotnet script for our build!), but it's not ideal.

Another option: a MSBuild task that generates a C# file based on `$(NuGetPackageRoot)` and the package ids and versions. That file would be included in the build so that the main program knows the paths to the tools. It wouldn't be a viable option for a real app, of course, but in the context of a build script I think it could work.

**Comment by adamralph** [comment]
- GitVersion.CommandLine - _I would consider switching to the MSBuild target, so all the work will be done during `dotnet build`. However, the project is a bit "up in the air now" and it's uncertain when an RTM will be released which works with `dotnet build`. IIRC the current betas work, but they might only be on myget._
- PdbGit - _I would switch to Microsoft.SourceLink.GitHub, which is just a package reference, so all the work will be done during `dotnet build`._
- xunit.runner.console - _I would switch to `dotnet test`._
- vswhere - _I would drop this in favour of using `dotnet build`._

I'm managing to run all my builds without using any tools packages.

**Comment by thomaslevesque** [comment]
Thanks @adamralph.

> GitVersion.CommandLine - I would consider switching to the MSBuild target, so all the work will be done during dotnet build. However, the project is a bit "up in the air now" and it's uncertain when an RTM will be released which works with dotnet build. IIRC the current betas work, but they might only be on myget.

Interesting; I'll look into it.

> PdbGit - I would switch to Microsoft.SourceLink.GitHub, which is just a package reference, so all the work will be done during dotnet build.

Yeah, we should probably switch to SourceLink anyway, it seems better supported. I think we didn't use it initially because it supported only portable PDBs, which were not supported by ILMerge. But I don't see this limitation mentioned in the docs anymore, so maybe it's gone.

> xunit.runner.console - I would switch to dotnet test.

I think we were using `dotnet xunit` because it let us control some options not exposed by `dotnet test`. Not sure if it still makes sense.

> vswhere - I would drop this in favour of using dotnet build.

We probably should, but when we try to build the solution with `dotnet build`, we get errors that we don't have with MSBuild... not sure what's going on.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.8.1](https://github.com/FakeItEasy/FakeItEasy/releases/4.8.1).
