### ISSUE TITLE
Fix prepare-release

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1429]
When prepare-release was converted to a compiled program, the indentation of the new release body was messed up, so it's created mostly as a code block.

Also, somehow when I first committed the cross-referencing of the milestone and release body issues, I elided the `?` in the named capture group (I swear is was there when I was testing), so no issue numbers are detected in the release body.
Even if it was there, the group would miss multi-issues like `(#1234, #1235)`.

**Comment by thomaslevesque** [comment]
> When prepare-release was converted to a compiled program, the indentation of the new release body was messed up, so it's created mostly as a code block.

Oops! Sorry about that.

**Comment by blairconrad** [comment]
No worries. We both missed it. And as you pointed out, it's annoying to test this. (I usually update the repo vars to point at my repo and muck about with some issues and the release and milestones. It's a pain.)
It's the missing `$` that really gets me. I do not know how that happened.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.9.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.9.0).
