### ISSUE TITLE
Deployment script can't find nuget.exe

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1430]
We recently stopped copying the nuget.exe to the sandbox and now `deploy.ps1` can't find it, causing the automatic deployment [to fail](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/647#L471), resulting in the following error:

> The term 'C:\projects\fakeiteasy\tools\.nuget\nuget.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by thomaslevesque** [comment]
BTW, is there any reason to keep this script in PowerShell ? For consistency, maybe we should make it a csproj like Build and PrepareRelease.

**Comment by blairconrad** [comment]
No reason that I know of. A compiled project would be fine by me.
