### ISSUE TITLE
Investigate ProxyGenerator.CreateDelegateProxy

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1437]
@stakx is adding delegate-generating code to DynamicProxy let's create a spike that uses it to see how well it fits our model.

I'll make notes here so my in-progress investigation (and inevitable backtracking) doesn't pollute the discussion in https://github.com/castleproject/Core/pull/403.

**Comment by blairconrad** [comment]
## Proxied Delegates need to be visible to the generated dynamic proxy assembly

This matches all the other proxies that DynamicProxy creates, but is a regression. As of 4.8.1, FakeItEasy can fake even private delegates.

**Comment by blairconrad** [comment]
## We lose some connections between the proxy and the FakeManager

When we create the proxy, we add it to a `ConditionalWeakTable`. So, if we proxied an `Action`, we have an `Action` as the key.
If there's a failing assertion (and probably other situations), we will attempt to look up, in `DefaultFakeObjectCallFormatter.GetDescription`, the `call.FakedObject`, but the FakedObject is a `Castle.Proxies.ActionProxy`, so we can't find the manager.

**Comment by thomaslevesque** [comment]
Thanks for investigating @blairconrad. So, the only issue with this change is that we will only support public delegates? I think it's acceptable; it was a bit weird that we supported non-public delegates but not non-public interfaces. But it's a breaking change, so it'll have to be done in a major release.

**Comment by thomaslevesque** [comment]
Did you try to profile each approach? Not that performance is a major concern, but I'm curious...

**Comment by blairconrad** [comment]
> it's a breaking change, so it'll have to be done in a major release.

Yeah, but we're due. :wink: Seriously, it'd be nice to get rid of a few "on hold" issues.

> Did you try to profile each approach? Not that performance is a major concern, but I'm curious...

I did not. I was just assessing for correctness. I can do. I have a colleague who had some cool benchmarking lying around a while ago…

**Comment by thomaslevesque** [comment]
> Yeah, but we're due. 😉 Seriously, it'd be nice to get rid of a few "on hold" issues.

My thoughts exactly.

> On the other hand, if performance is not a major concern, would we rather keep whatever performance we have and not introduce a breaking change?

No, I think we should do it. I don't think the breaking change is a major issue, and it will make the behavior more consistent.

If some people really like to be able to fake private delegate, maybe we could still support the old approach as an option? But I doubt it's worth the trouble.

**Comment by blairconrad** [comment]
> maybe we could still support the old approach as an option? But I doubt it's worth the trouble.

Ugh, please no. I'd much rather either keep the old way or move to the new way and (probably not) slightly inconvenience (very few, if any) users.

**Comment by thomaslevesque** [comment]
I guess users who are currently faking non-public delegates can just make them public. The problem is that they also have to make public the types used in the delegate signature, but the same is true about interfaces or classes.

**Comment by blairconrad** [comment]
It's true. They could also opt to make them internal (if not already) and mark the assemblies' innards as visible to the dynamic proxy assembly (if not already).

**Comment by blairconrad** [comment]
@thomaslevesque, quick profiling using BenchmarkDotNet:


## 4.8.1 method

|        Method |     Mean |     Error |    StdDev |       Min |      Max |
|-------------- |---------:|----------:|----------:|----------:|---------:|
| FakeInterface | 103.4 us | 11.970 us | 35.295 us |  55.51 us | 201.5 us |
|     FakeClass | 122.1 us |  9.974 us | 29.253 us |  59.25 us | 186.1 us |
|  FakeDelegate | 265.1 us |  5.020 us |  4.696 us | 254.48 us | 271.0 us |

## New method

|        Method |      Mean |      Error |     StdDev |       Min |       Max |
|-------------- |----------:|-----------:|-----------:|---------:|----------:|
| FakeInterface |  97.16 us | 13.5966 us | 40.0898 us | 48.98 us | 213.20 us |
|     FakeClass | 117.97 us | 10.6092 us | 31.2815 us |  57.85 us | 195.93 us |
|  FakeDelegate |  13.66 us |  0.2486 us |  0.2553 us | 13.32 us |  14.26 us |

The new delegate timing seems really low, but 🤷‍♂️  


```c#
namespace FakeItEasy.Benchmarks
{
    using System;

    using BenchmarkDotNet.Attributes;
    using BenchmarkDotNet.Running;
    using FakeItEasy;

    public static class Program
    {
        public static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<DelegateBenchmark>();
        }
    }

    [MinColumn]
    [MaxColumn]
    public class DelegateBenchmark
    {
        [Benchmark]
        public object FakeInterface()
        {
            return A.Fake<IServiceProvider>();
        }

        [Benchmark]
        public object FakeClass()
        {
            return A.Fake<Type>();
        }

        [Benchmark]
        public object FakeDelegate()
        {
            return A.Fake<Action>();
        }
    }
}
```

**Comment by stakx** [comment]
@blairconrad: Does FakeItEasy cache its fake delegate types? DynamicProxy does, that might be the reason for the low timing. (Except for the first delegate proxy creation, DynamicProxy would basically just take a lock, do a dictionary lookup, an `Activator.CreateInstance`, plus two or three more reflection calls.)

**Comment by stakx** [comment]
@blairconrad: Some caching going on maybe, where previously that wasn't the case?

**Comment by blairconrad** [comment]
@stakx, yeah, I've been peripherally aware that DynamicProxy caches its types (this is true, right?), where FakeItEasy did not. I was just surprised that for the new method, the delegate timing came in so much lower than faking either a class or an interface. I'm sure it's all down to a nice tight "fake the delegate" implementation.

**Comment by thomaslevesque** [comment]
NIce! Thanks for the benchmark

**Comment by jonorossi** [comment]
> I've been peripherally aware that DynamicProxy caches its types (this is true, right?), where FakeItEasy did/does not cache the delegate types. I was just surprised that for the new method, the delegate timing came in so much lower than faking either a class or an interface. I'm sure it's all down to a nice tight "fake the delegate" implementation.

Yes these delegate types are cached too, but you are spot on there is a separate codepath for delegates which only has one method to emit, see the `DelegateTypeGenerator` class which has been in DP for a long time.

**Comment by blairconrad** [comment]
I'm not sure why we fell off this issue before, but I'm back to investigate.
Using the benchmarks above, with FakeItEasy 8.2.0, I see:

| Method        | Mean      | Error     | StdDev    | Min       | Max       |
|-------------- |----------:|----------:|----------:|----------:|----------:|
| FakeInterface |  1.179 us | 0.0115 us | 0.0102 us |  1.166 us |  1.200 us |
| FakeClass     |  1.164 us | 0.0077 us | 0.0069 us |  1.154 us |  1.179 us |
| FakeDelegate  | 55.328 us | 1.0819 us | 1.1576 us | 53.672 us | 57.228 us |

And my current attempts to use the new mechanism (which result in some failing tests due to an inability to _sometimes_ find the `FakeManager`):

| Method        | Mean     | Error     | StdDev    | Min      | Max      |
|-------------- |---------:|----------:|----------:|---------:|---------:|
| FakeInterface | 1.174 us | 0.0190 us | 0.0178 us | 1.153 us | 1.208 us |
| FakeClass     | 1.153 us | 0.0084 us | 0.0078 us | 1.142 us | 1.169 us |
| FakeDelegate  | 1.890 us | 0.0138 us | 0.0129 us | 1.862 us | 1.907 us |

2 observations and a thought:

1. in general, the combination of net8.0, newer Castle.Core, and my newer laptop makes the numbers look a lot better!
2. faking a delegate the new way (if I can get it completely work) is a lot faster than the old way
3. even in 8.2.0, faking a delegate isn't _that_ slow. If we fail to adapt to the new mechanism, it'll be okay

**Comment by thomaslevesque** [comment]
Nice! The improvement is significant. If you can figure out what the problem is, it'd be great. Let me know if I can help.
