### ISSUE TITLE
Allow IArgumentFormatter implementation to fall back on other formatters to render complex arguments

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#144]
Currently, FakeItEasy decides to invoke `IArgumentValueFormatter`s when there's unexpected or missing calls on a fake. This works pretty well.

However, there's no way for FakeItEasy users to explicitly invoke the `FakeItEasy.Core.ArgumentValueFormatter` functionality  - the class is internal. The downside is that if users write their own formatter implementations, they have to specify every facet of how an object is rendered. There's no way to fall back to other formatters, unless the users have written these formatters themselves, or imported them from a library that exports them.

Suppose there exists a class:

```C#
class NamedValue
{
    public string Name;
    public object Value;
}
```

Not particularly inspiring, but someone may find it useful. Now suppose we want to write an argument value formatter for it. A naive implementation would be:

```C#
class NameValueFormatter
    : ArgumentValueFormatter<NamedValue>
{
    protected override string GetStringValue(NamedValue argumentValue)
    {
        return "NamedValue{ Name=" + argumentValue.Name + 
    	     ", Value=" + argumentValue.Value + " }";
    }
}
```
This will give output like

    NamedValue{ Name=temperature, Value=21.3 }

Not bad. But suppose one of those values were `null`? Then we'd have

    NamedValue{ Name=, Value=21.3 }

A little disappointing. Maybe we'd rather see the `Name=<null>` kind of construction that the `ArgumentFormatter` would give if it were in charge or rendering `Name`.

Perhaps worse, there's no way for you to tell that the `Value` that we rendered twice above is a string, not a float. If the `DefaultStringFormatter` had been invoked, we'd have seen 

    NamedValue{ Name=<null>, Value="21.3" }

Of course, existing formatters would have use when rendering more complicated types, such as those that contain collections, as well as the relatively simple kind of class I used above. (In fact, the very first time I tried to implement an `IArgumentValueFormatter`, I implemented a formatter for one custom type and then was dismayed to learn that not only was there no implicit leveraging of my formatter to format an array of the custom type, FakeItEasy provided me with no help. Of course in that case, I had access to the formatter for the custom type and I could use it, but it was a little awkward.)

And if this issue is accepted, I'd be thrilled to work on it.

**Comment by blairconrad** [comment]
Rereading, I think there are two reasonable approaches to fixing this issue. Both involve creating a new interface, say `IObjectFormatter`, and then providing an implementation of this interface to users' argument value formatters. When called, this helper instance would run an object through the existing argument value formatter pipeline (calling `GetArgumentValueAsString` on it)

The trick is to provide the helper instance to the users' argument value formatters. Here's what I've thought of:

1. altering `GetArgumentValueAsString(object argumentValue)` to accept an `IObjectFormatter` as well as an `object`. This would be a **breaking** change, and if we're going to do it, I think we should in 2.0
2. injecting the `IObjectFormatter` in to the argument value formatter either by constructor or property injection. We'd have to use reflection to determine whether the user's argument value formatter provided the relevant constructor or property. This could be implemented in a non-breaking way, but would be less obvious to the users, and slightly harder for them to take advantage of.

@adamralph, @thomaslevesque, do you have any opinion on the issue? I think position 1 is cleaner than 2. **However**, I'm the only person who has even cared about this issue, as far as I can tell, and that was for about 15 minutes, 30 months ago, so I think I'm leaning toward closing it.

**Comment by adamralph** [comment]
I'm finding it difficult to set aside enough time to go back through this and understand it properly. If, in the meantime, it gets closed, I won't complain.

**Comment by blairconrad** [comment]
I'm not sure there's a burning need for this, but if we decided a week after releasing 2.0.0 that we wanted it, and the preferred implementation was breaking, I'd be gutted. 

I'll summarize the situation/problem, but the "too long; didn't read" version is:

**should we alter the argument value formatter extension point to allow an implementation to build upon other argument value formatter extension points?**

----

FakeItEasy uses argument value formatters to render arguments to methods in error messages. Something like

```
Assertion failed for the following call:
  Any call made to the fake object.
Expected to find it never but found it #1 times among the calls:
  1: FakeItEasyQuestions.ArgumentValueFormatterTests+IFoo.Foo2(name: <NULL>, value: "21.3")
```

The `<NULL>` (a string) and `"21.3"` (a string passed to an `object` paramter`) were rendered by FakeItEasy's builtin formatters.

However, FakeItEasy doesn't know how to render all objects. Suppose `Foo2` was replaced by `Foo` that took a single argument of this type:

```c#
class NamedValue
{
    public string Name;
    public object Value;
}
```

Then the output would be 

```
Expected to find it never but found it #1 times among the calls:
  1: FakeItEasyQuestions.ArgumentValueFormatterTests+IFoo.Foo(namedValue: FakeItEasyQuestions.ArgumentValueFormatterTests+NamedValue)
```

Not helpful. 

The user can write an `ArgumentValueFormatter` that renders the `NamedValue`:

```c#
public class NameValueArgumentFormatter: ArgumentValueFormatter<NamedValueWithArgumentFormatter>
{
    protected override string GetStringValue(NamedValueWithArgumentFormatter argumentValue)
    {
        return string.Format("NamedValueWithArgumentFormatter{{ Name: {0}, Value: {1} }}",
                             argumentValue.Name, argumentValue.Value);
    }
}
```

but it would render

```
Expected to find it never but found it #1 times among the calls:
  1: FakeItEasyQuestions.ArgumentValueFormatterTests+IFoo.Foo(namedValue: NamedValueWithArgumentFormatter{ Name: , Value: 21.3 })
```

You can't really tell what `Name` is, nor that `Value` was a string.

When I ran into this early on, I'd hoped there was a way to piggyback on (take advantage of) the built-in FakeItEasy formatters, or even other formatters that I might have written, but couldn't find one.

So, this boils down to: **should we alter the argument value formatter extension point to allow an implementation to build upon other argument value formatter extension points**?

The Fake options builders and Dummy factories don't really have this problem because there are static access points to get new Fakes or new Dummies (a Dummy factory can just call `A.Dummy<T>()` to get a new Dummy that it wants to compose into the Dummy that it's currently making).

I've created [a gist that shows some of the current behaviour and a rough idea of how a fix might look to a user](https://gist.github.com/blairconrad/9b17fa4fba62303cebd9). The fix idea is very rough, because I had to work around FakeItEasy bits that aren't there yet. If we think the fix is worth pursuing, we can wrangle over the implementation.

**Comment by thomaslevesque** [comment]
Another way to solve this without breaking anything would be to expose the internal `ArgumentValueFormatter` class publicly. Of course this raises the issue of how to create an instance of it... perhaps there could be a static `ArgumentValueFormatter.Default` property to fetch it from the `ServiceLocator`. Not very elegant, though.

Otherwise, I like @blairconrad's proposal to add an `IObjectFormatter` parameter to `GetArgumentValueAsString`. It reminds me of the approach taken by JSON.NET for converters. The [`WriteJson`](http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_JsonConverter_WriteJson.htm) method takes a `JsonSerializer` parameter, so implementers don't have to serialize the full object manually

**Comment by thomaslevesque** [comment]
For consistency with `IArgumentConstraintManager<T>`, perhaps we should use `IOutputWriter` for argument formatting, rather than returning a string. This would also add support for indentation. `IOutputWriter` also has a `WriteArgumentValue` method, but it doesn't use `ArgumentValueFormatter`, which is probably an oversight. If we fixed that, we could do something like this:

```csharp
    public interface IArgumentValueFormatter
    {
        Type ForType { get; }
        Priority Priority { get; }
        void FormatArgumentValue(object argumentValue, IOutputWriter writer);
    }
```

And the implementation could like like this:

```csharp
class NamedValueFormatter : ArgumentValueFormatter<NamedValue>
{
    public override void FormatValue(NamedValue argumentValue, IOutputWriter writer)
    {
        writer.Write("NamedValueWithArgumentFormatter{{ Name: ")
              .WriteArgumentValue(argumentValue.Name)
              .Write(", Value: ")
              .WriteArgumentValue(argument.Value)
              .Write( }}");
    }
}
```
Now that I see it written down, I realize that it's not as convenient as `string.Format` or string interpolation... but still, we should probably think about consistency with `A<T>.That.Matches(...)` when it comes to formatting argument values.

**Comment by blairconrad** [comment]
@thomaslevesque, I like the idea of increasing consistency with what `Matches` provides!
And it's true that what you've written isn't quite as convenient as `string.Format` or bling strings, but users would still be free to use the more convenient option if they didn't care about super-fancy formatting.

**Comment by blairconrad** [comment]
I'm not sure exactly how much we'd gain from indentation support, but I'm sure it wouldn't hurt. I'm excited to take a look at the output writer and how `Matches` is formatted. Unfortunately, I am busy tonight.
I'll steal what time I can.

**Comment by thomaslevesque** [comment]
Anyway, I'm curious to know how much real users care about this feature... I suspect that the vast majority never wrote an argument value formatter (I never did). If your test fails and the output isn't clear enough, well, you just put a breakpoint and look at the object yourself...

So perhaps a more useful improvement would be to provide a default formatter that writes the object with its property values, like the C# REPL does.

**Comment by blairconrad** [comment]
Oh, I bet most users don't care at all. Just like I bet most users don't know about Dummy factories and Fake options builders (or Fake configurators in 1.x.x). Or Scopes.
Of course, when I made this issue, I _was_ a real user, thankyouverymuch. (And some days I like to think that I'm _still_ a real user. :wink:) And on that day, whatever I thought I was trying to have rendered (an enumerable of another type that already had an ArgumentValueFormatter defined), I wished for richer formatting support. In that case, I controlled the formatter that I'd wished was hooked up, and so I accessed it directly. And that's probably by far the most common scenario.
And I moved on, and everything was fine and I never thought about such a feature again, except in the context of this issue.

So, it sounds like there's not that much interest (I feared it was only me) or benefit, really. And a REPL-style formatter could always be implemented and inserted without any breaking changes, so I'm okay to close this…

**Comment by adamralph** [comment]
I like the idea of a default formatter. E.g. https://github.com/scriptcs/scriptcs/blob/3a3a4baf933afab7d9f3ca61a7b3289cd743c8fb/src/ScriptCs.Hosting/ObjectSerializer.cs

**Comment by thomaslevesque** [comment]
> I like the idea of a default formatter. E.g. https://github.com/scriptcs/scriptcs/blob/3a3a4baf933afab7d9f3ca61a7b3289cd743c8fb/src/ScriptCs.Hosting/ObjectSerializer.cs

Yes, JSON is probably the best format for this. However it means we have to take a dependency on JSON.NET. Or perhaps we could use the built-in `DataContractJsonSerializer` or `JavascriptSerializer`. They're not great, but for this use case they're probably enough.

**Comment by adamralph** [comment]
The built in ones are probably not good enough. If we decide to use JSON.NET then we can internalise it, as we do with Castle.Core.
