### ISSUE TITLE
Update xunit, drop dotnet xunit in favor of dotnet test

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1444]
As discussed in https://github.com/FakeItEasy/FakeItEasy/pull/1442#issuecomment-420230719

@adamralph said:

> BTW - you may want to think about switching to `dotnet test` soon, since `dotnet xunit` is no longer a thing.

Also, we're using a beta version of xunit 2.3.0, but xunit 2.4.0 RTM has been released and seems to work fine. We should consider upgrading. `dotnet xunit` is no longer supported in 2.4.0, which means we have to drop it anyway if we upgrade. This might fix an issue where the name of the failed test is not clearly visible in the build output.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.9.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.9.0).
