### ISSUE TITLE
Produce a .NET Standard 2.0 assembly

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1449]
Because we can, because it's [recommended by MS folks](https://twitter.com/davidfowl/status/1025434242832945154), and because it has a much smaller dependency graph.

**Comment by thomaslevesque** [comment]
(also, because I just succeeded in making the tests pass for netcoreapp2.1 with a netstandard2.0 version of FakeItEasy)

**Comment by blairconrad** [comment]
Sounds good. @thomaslevesque. I'm suprised/sad that work was needed for the tests to pass. I look forward to your PR.

**Comment by thomaslevesque** [comment]
Still having a few issues. I tried to remove unnecessary depedencies for netstandard2.0, but it caused other issues. Looks like it's solved now, so I'll send a PR later today.

**Comment by thomaslevesque** [comment]
> I'm suprised/sad that work was needed for the tests to pass.

It was the `TypeCatalogTests` where we dynamically generate an assembly. It required a reference to netstandard.dll

**Comment by blairconrad** [comment]
> It was the TypeCatalogTests where we dynamically generate an assembly.

Oh. Yeah. They are the worst.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 4.9.0](https://github.com/FakeItEasy/FakeItEasy/releases/4.9.0).
