### ISSUE TITLE
Tests hang sometimes

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1451]
As reported by @thomaslevesque in https://github.com/FakeItEasy/FakeItEasy/issues/1443#issuecomment-421333339.

Not every run, but usually within about 30 test runs. I noticed that the hang occurred in the 461 framework version of the specs, but I wasn't taking notes about that the whole time.  Here's how I was testing:

```PowerShell
$iteration = 0
while ( $True ) {
    ++$iteration
    echo "$(Get-Date -Format g): Iteration $iteration"
    .\build.cmd -s spec
}
```

A hang looks like this:

```
2018-09-15 5:47 AM: Iteration 3
Bullseye: Starting... (spec) (skip dependencies)
Bullseye/spec: Starting...
Bullseye/spec/tests/FakeItEasy.Specs: Starting...
Working directory: tests/FakeItEasy.Specs
dotnet test --configuration Release --no-build -- RunConfiguration.NoAutoReporters=true
Test run for D:\Sandbox\FakeItEasy\tests\FakeItEasy.Specs\bin\Release\net461\FakeItEasy.Specs.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
```
Sometimes (sometimes it's silent) when the hung build is interrupted, it spews errors like

```
Attempting to cancel the build...
^CTerminate batch job (Y/N)? C:\Program Files\dotnet\sdk\2.1.402\Microsoft.TestPlatform.targets(33,5): error MSB4018: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task failed unexpectedly. [D:\Sandbox\FakeItEasy\tests\FakeItEasy.Specs\FakeItEasy.Specs.csproj]
C:\Program Files\dotnet\sdk\2.1.402\Microsoft.TestPlatform.targets(33,5): error MSB4018: System.ComponentModel.Win32Exception (5): Access is denied [D:\Sandbox\FakeItEasy\tests\FakeItEasy.Specs\FakeItEasy.Specs.csproj]
C:\Program Files\dotnet\sdk\2.1.402\Microsoft.TestPlatform.targets(33,5): error MSB4018:    at System.Diagnostics.Process.Kill() [D:\Sandbox\FakeItEasy\tests\FakeItEasy.Specs\FakeItEasy.Specs.csproj]
C:\Program Files\dotnet\sdk\2.1.402\Microsoft.TestPlatform.targets(33,5): error MSB4018:    at Microsoft.TestPlatform.Build.Tasks.VSTestForwardingApp.Cancel() [D:\Sandbox\FakeItEasy\tests\FakeItEasy.Specs\FakeItEasy.Specs.csproj]
C:\Program Files\dotnet\sdk\2.1.402\Microsoft.TestPlatform.targets(33,5): error MSB4018:    at Microsoft.TestPlatform.Build.Tasks.VSTestTask.Cancel() [D:\Sandbox\FakeItEasy\tests\FakeItEasy.Specs\FakeItEasy.Specs.csproj]
C:\Program Files\dotnet\sdk\2.1.402\Microsoft.TestPlatform.targets(33,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Cancel() [D:\Sandbox\FakeItEasy\tests\FakeItEasy.Specs\FakeItEasy.Specs.csproj]
```

The initial thought was that it was bad locking in `CreationSpecs.CacheSuccessfulConstructor` and  `DummyCreationSpecs.ClassWhoseLongerConstructorThrowsCreation`. We've certainly had enough problems with them. Then I investigated.

| machine | .NET SDK | other state|results|
|-----------|-----------|-------------|--------|
| Blair's work| 2.1.401| develop      | hang |
|Blair's home|2.1.301|develop        | no hang|
|Blair's home|2.402|develop           | hang|
|Blair's home|2.402|develop and commented out the suspect tests| hang|
|Blair's home|2.402|develop without d178354| no hang after 200 iterations|

Of course, it's hard to be definitive when saying no hang, but the trials show that it's not the tests that we initially thought. Adding `--debug` to the `dotnet test` command did not provide any additional information.

**Comment by thomaslevesque** [comment]
> Adding `--debug` to the `dotnet test` command did not provide any additional information.

Maybe adding `--verbosity detailed` would show which test hangs?

**Comment by thomaslevesque** [comment]
For me it hung at the 42th iteration.

**Comment by thomaslevesque** [comment]
(also on net461, so now I'm only running the specs on this framework to save time)

**Comment by thomaslevesque** [comment]
> Unfortunately, it's the very last test case for this scenario, so I don't know what it tries to do next...

In fact, it's also the last test in the whole assembly. There's nothing after it. But I only see tests that complete, so it doesn't mean anything. I think the problem is another test, that started but never completed.

I saved traces of a successful run and a hung run, sorted them by the test name, and diffed, and here's what I got:
https://gist.github.com/thomaslevesque/721c7ab9419d5be17433f27bee6617d6

You can ignore the first set of changes (the only change is the number in the name of the proxy class), but the next set is more interesting. It's all in `GenericDummyCreationSpecs`. If you look at `ClassWhoseOnlyConstructorThrowsCreation`, you can see that the first step passed in both the successful and hung run, but the next steps were not run in the hung test. So I think `ClassWhoseOnlyConstructorThrowsCreation` is the culprit, and it's stuck in the second step.

**Comment by thomaslevesque** [comment]
Unfortunately I can't think of any reason for this test to hang...

**Comment by blairconrad** [comment]
Hey, same spot. Same diff! On the 31st iteration, FWIW.

**Comment by blairconrad** [comment]
Hmm! Something different. I ran in debug instead of release, because I thought to attach to the process, then forgot and just ended up getting the output.

https://gist.github.com/blairconrad/38b6b297751609e3512cab17346b90d2
We're missing tests in `FakeItEasy.Specs.WrappingFakeSpecs`. Last executed was `Passed   FakeItEasy.Specs.WrappingFakeSpecs.NonVoidException() [02] And a fake wrapping this object`. So in this case we would've passed when creating the fake, but hung when executing a call on the wrapper (`FakeItEasy.Specs.WrappingFakeSpecs.NonVoidException() [03] When a non-void method is called on the wrapper`). 
I'm still not convinced it's us. Continuing.

**Comment by blairconrad** [comment]
Okay. When I create a deadlock (by commenting out `CreatingFirstInstance.Set();` in `FakeItEasy.IntegrationTests.DummyTests.ConcurrentCreationDummy` to force a hang, `FakeItEasy.IntegrationTestsDummyTests` does not appear anywhere in the test output. Not for that test, nor for the others.

I see this cascade of processes:
![image](https://user-images.githubusercontent.com/3275797/45595668-5e5cf100-b97d-11e8-893f-f6b9370a346a.png)

If I attach to testhost, I can pause the execution and see a thread stuck on `ConcurrentCreationDummy.CreatingFirstInstance.Wait()` in  `Same_dummy_type_can_be_created_concurrently_on_different_threads` and another on `ConcurrentCreationDummy.ConcurrentCreationDummy`. And one on the `Task.WaitAll` in that test. Here are the threads:

```
Not Flagged		20664	1	Main Thread	Main Thread	testhost.x86.exe!Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke
Not Flagged		10180	0	Worker Thread	<No Name>	
Not Flagged		13996	3	Worker Thread	<No Name>	Microsoft.TestPlatform.PlatformAbstractions.dll!Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run
Not Flagged		13720	0	Worker Thread	<No Name>	
Not Flagged		6876	5	Worker Thread	<No Name>	
Not Flagged	>	19024	7	Worker Thread	Worker Thread	FakeItEasy.IntegrationTests.dll!FakeItEasy.IntegrationTests.DummyTests.ConcurrentCreationDummy.ConcurrentCreationDummy
Not Flagged		11764	8	Worker Thread	Worker Thread	System.dll!System.Net.Sockets.Socket.Poll
Not Flagged		10408	9	Worker Thread	<No Name>	Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.ProcessRequests
Not Flagged		22256	10	Worker Thread	Worker Thread	FakeItEasy.IntegrationTests.dll!FakeItEasy.IntegrationTests.DummyTests.Same_dummy_type_can_be_created_concurrently_on_different_threads.AnonymousMethod__2_1
Not Flagged		12572	0	Worker Thread	<No Name>	
Not Flagged		6972	12	Worker Thread	<No Name>	xunit.runner.visualstudio.testadapter.dll!Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly
Not Flagged		21928	0	Worker Thread	<No Name>	
Not Flagged		10960	15	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MessageBus.ReporterWorker
Not Flagged		17064	16	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		17332	17	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		2900	18	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		22492	19	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		18540	20	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		12136	21	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		18836	22	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		1480	23	Worker Thread	<No Name>	FakeItEasy.IntegrationTests.dll!FakeItEasy.IntegrationTests.DummyTests.Same_dummy_type_can_be_created_concurrently_on_different_threads.AnonymousMethod__2
Not Flagged		11000	14	Worker Thread	<No Name>	
Not Flagged		5552	24	Worker Thread	<No Name>	
Not Flagged		5432	25	Worker Thread	<No Name>	
Not Flagged		22448	26	Worker Thread	<No Name>	
Not Flagged		15348	27	Worker Thread	<No Name>	
Not Flagged		17160	0	Worker Thread	<No Name>	
Not Flagged		776	28	Worker Thread	<No Name>	
```

However, if I let the hang occur "naturally", there are no threads with call stacks. I think the test runner has finished with our tests:

```
Not Flagged	>	20920	14	Worker Thread	<No Name>	
Not Flagged		12940	1	Main Thread	Main Thread	testhost.x86.exe!Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke
Not Flagged		9996	0	Worker Thread	<No Name>	
Not Flagged		11972	3	Worker Thread	<No Name>	Microsoft.TestPlatform.PlatformAbstractions.dll!Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run
Not Flagged		14780	0	Worker Thread	<No Name>	
Not Flagged		19028	5	Worker Thread	<No Name>	
Not Flagged		384	7	Worker Thread	<No Name>	
Not Flagged		19288	8	Worker Thread	Worker Thread	System.dll!System.Net.Sockets.Socket.Poll
Not Flagged		17572	9	Worker Thread	<No Name>	Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.ProcessRequests
Not Flagged		7572	10	Worker Thread	<No Name>	
Not Flagged		1332	0	Worker Thread	<No Name>	
Not Flagged		18680	12	Worker Thread	<No Name>	xunit.runner.visualstudio.testadapter.dll!Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly
Not Flagged		17144	0	Worker Thread	<No Name>	
Not Flagged		9276	15	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MessageBus.ReporterWorker
Not Flagged		9980	17	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		22016	18	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		22280	19	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		21300	20	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		21916	21	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		17624	22	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
Not Flagged		12692	23	Worker Thread	<No Name>	xunit.execution.desktop.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc
```

Ugh. I feel like the next step is to try to reproduce with a simpler set of tests. Or learn how to debug into the testhost.

**Comment by thomaslevesque** [comment]
I'm out of ideas on how to solve this...
On the bright side, it doesn't happen very often, and I've never seen it happen on AppVeyor.

**Comment by blairconrad** [comment]
I'll eventually try to get a hang dump and see if the dotnet people will take a peek. But not right away. I've disassembled a small appliance in the place where I usually computer, so doing any significant work is quite inconvenient. Fortunately, it's not an _urgent_ issue.

**Comment by MihaMarkic** [comment]
I stumbled upon similar problem with NUnit. I found out that doing a clean before build/test solves the problem. No idea why, though.

**Comment by blairconrad** [comment]
Interesting. Thanks for commenting, Miha. I was relooking at this issue just last night and was on the verge of closing it, as I'd not encountered the problem in a very long time, and I've been building a lot lately.

Just to be clear, was your problem tied to FakeItEasy, or did you have an unrelated problem in a project that used NUnit? If with FIE, what version and framework?

**Comment by MihaMarkic** [comment]
@blairconrad No, not tied to FIE at all -only NUnit and _dotnet test._ I'm seeing the same symptoms though.

**Comment by blairconrad** [comment]
Thanks for clarifying, @MihaMarkic.

**Comment by blairconrad** [comment]
I've not seen a hang since my last comment. Shall we close?

**Comment by thomaslevesque** [comment]
Sure! We can always reopen if it manifests itself again.
