### ISSUE TITLE
Cache FakeOptions constructor to improve performance

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1466]
For a lark, I profiled creating 100,000 instances of a small interface (after warming up FakeItEasy by faking a different interface). Using dotTrace, I found that `DefaultFakeAndDummyManager.BuildProxyOptions` was a hotspot. So I started caching the constructor by type of Fake and found this difference:

![image](https://user-images.githubusercontent.com/3275797/46406033-30471300-c6d8-11e8-9031-bf43b7ba0a86.png)

`BuildProxyOptions`  drops from 19.10% of the total time to 9.95%. Or if you prefer the diff view:

![image](https://user-images.githubusercontent.com/3275797/46406279-02160300-c6d9-11e8-85d4-9a0273b4f514.png)

Of course we're trading away some storage space. If we end up faking many different types once, this is a bad tradeoff, but if types are faked more than once, it may be a benefit.

Also, in many cases we don't even _need_ a `FakeOptions` object. I can explore dropping the construction step as well.

**Comment by blairconrad** [comment]
Actually, I may have come up with a nice way to not construct the `FakeOptions` object. Will explore later.

**Comment by thomaslevesque** [comment]
Well done, @blairconrad! Looks like a good improvement.

**Comment by thomaslevesque** [comment]
> Actually, I may have come up with a nice way to not construct the `FakeOptions` object. Will explore later.

Yes, it would be even better, I guess.

**Comment by blairconrad** [comment]
Rerunning with `FakeOptions` creator cached as a delegate (and in release mode this time; other numbers were in debug):

![image](https://user-images.githubusercontent.com/3275797/46444375-b185c080-c73f-11e8-8a87-037dfcc15c25.png)

27.04% to 2.93%. Not bad. Thanks for the push, @thomaslevesque. I'll work on avoiding construction next.

**Comment by blairconrad** [comment]
I was originally thinking we could avoid creating the object when users don't use creation method that specifies an option builder action, but we also have to make sure there's no `IFakeOptionsBuilder`, and that's more involved. It might still eventually be worthwhile, but if the new 2.93% number is to be believed, maybe it's not our next stop.

**Comment by blairconrad** [comment]
Using BenchmarkMockNet to test constructors. With FakeItEasy 4.8.1

|      Method |          Mean |        Error |       StdDev |   Scaled | ScaledSD |
|------------ |--------------:|-------------:|-------------:|---------:|---------:|
|        Stub |      8.375 ns |     6.764 ns |     1.757 ns |     1.00 |     0.00 |
|  FakeItEasy | 11,059.153 ns | 2,079.941 ns |   540.257 ns | **1,364.10** |   **243.18** |
|         Moq |  5,059.672 ns | 1,041.998 ns |   270.655 ns |   624.09 |   111.94 |
| NSubstitute |  8,111.013 ns | 5,264.036 ns | 1,367.314 ns | 1,000.46 |   230.82 |
|       Rocks |  4,221.011 ns | 4,767.949 ns | 1,238.457 ns |   520.65 |   165.25 |


Using BenchmarkMockNet to test constructors. With a build including this issue:

|      Method |         Mean |        Error |        StdDev |   Scaled | ScaledSD |
|------------ |-------------:|-------------:|--------------:|---------:|---------:|
|        Stub |     7.039 ns |     2.711 ns |     0.7042 ns |     1.00 |     0.00 |
|  FakeItEasy | 8,046.398 ns |   470.824 ns |   122.2949 ns | **1,151.62** |    **96.61** |
|         Moq | 6,175.403 ns | 4,300.547 ns | 1,117.0510 ns |   883.84 |   161.06 |
| NSubstitute | 5,959.644 ns |   129.430 ns |    33.6191 ns |   852.96 |    70.74 |
|       Rocks | 3,990.786 ns | 3,982.395 ns | 1,034.4122 ns |   571.17 |   141.03 |

Take with grain of salt. The computer was doing other things. But still, I'm pleased with the change.

**Comment by thomaslevesque** [comment]
It certainly looks much better! I think I'll do some profiling tonight, to see if there's more to be gained.

**Comment by blairconrad** [comment]
I'm sure there's some fat to trim.

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
