### ISSUE TITLE
Document advanced usage methods

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1474]
@asgerhallas's [comment on a recent StackOverflow answer](https://stackoverflow.com/questions/52721273/checking-calls-on-multiple-returned-wrapped-fakes-with-fakeiteasy/52722562#comment92433564_52746348) made me realize that we nowhere document some of the advanced usages of FakeItEasy. We should. Unless we review the methods and decide to remove them.

In paricultar, I'm thinking of

- [ ] `Fake.ClearConfiguration`
- [ ] `Fake.ClearRecordedCalls`
- [ ] `Fake.GetCalls`
- [ ] `Fake.GetFakeManager`
- not `Fake.InitializeFixture`, since we'd like to remove it in 5.0.0 (the method itself should probably have already been marked obsolete; not a disaster, since the attributes that are required to use it are so marked, but maybe we should spin off an issue now)
- [ ] `FakeManager.Object`
- [ ] `FakeManager.FakedObjectType`
- [ ] `FakeManager.Rules`
- [ ] `FakeManager.AddInterceptionListener` ~~(this is one method I'd consider removing)~~
- [ ] `FakeManager.AddRuleFirst`
- [ ] `FakeManager.AddRuleLast`
- [ ] `FakeManager.RemoveRule`

There may be more.

There's no need to document everything in one big change. We could spin off separate issues or just PRs for subsets of the work.

**Comment by thomaslevesque** [comment]
Good point.

> `FakeManager.AddInterceptionListener` (this is one method I'd consider removing)

Why? I don't see any major issue with it, and it can be a useful extension point.

**Comment by blairconrad** [comment]
I've never seen it used. And I'd've said it's covered by the `AddRule`s, but I see how it has extra power. Okay. Considered and rejected!

**Comment by thomaslevesque** [comment]
>     * not `Fake.InitializeFixture`, since we'd like to remove it in 5.0.0 (the method itself should probably have already been marked obsolete; not a disaster, since the attributes that are required to use it are so marked, but maybe we should spin off an issue now)

It *is* marked obsolete 😉 
https://github.com/FakeItEasy/FakeItEasy/blob/2c912963b733a38ded71fc06b5347f2c1f4199c9/src/FakeItEasy/Fake.cs#L66-L70

**Comment by thomaslevesque** [comment]
> * [Invoking Custom Code](https://fakeiteasy.readthedocs.io/en/stable/invoking-custom-code/) (in lieu of a general node for configuring fakes)

I don't really see how it's related... where would you add that link?

> * [Assertion](https://fakeiteasy.readthedocs.io/en/stable/assertion/)

👍 

> * the table of contents

Oh, I always forget this!

**Comment by thomaslevesque** [comment]
I pushed the changes for assertions and table of contents

**Comment by blairconrad** [comment]
> > * [Invoking Custom Code](https://fakeiteasy.readthedocs.io/en/stable/invoking-custom-code/) (in lieu of a general node for configuring fakes)

> I don't really see how it's related... where would you add that link?

Yeah, maybe not. Had there been an overall page for configuring Fakes, I'd link from there. This one felt closest to me, as for sure anything you need the advanced functions for would be considered "custom code".

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
