### ISSUE TITLE
Simplify/replace/remove ServiceLocator

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1478]
As @thomaslevesque and I noted in private chat, the `ServiceLocator` we're using provides little (if any) benefit, complicates debugging and _may_ decrease performance (it's hard to tell, mostly because the ServiceLocator injects itself into so many stack traces in weird places that it's hard to tell). Let's simplify it a bit.

**Comment by blairconrad** [comment]
@thomaslevesque, I'm happy with the changes we've made to the `ServiceLocator` so far, and could switch to other tasks.

Do you want us to continue simplifying and/or removing, or shall we leave it as is for now?

**Comment by blairconrad** [comment]
Closed by #1479 and #1481.

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
