### ISSUE TITLE
Drop GitFlow

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1487]
@thomaslevesque said it best in https://github.com/FakeItEasy/FakeItEasy/pull/1484#issuecomment-435693538:

> Well, I'm not married to GitFlow, so why not.

We don't make use of its power, and it comes with some overhead. Also, if we want to use a simpler versioner (specifically [MinVer](https://github.com/adamralph/min-ver)), it's standing in the way a bit.

I'm thinking that this work is best done immediately following a release. Off the top of my head, we may need to 

- [x] update FakeItEasy.PrepareRelease
- [x] update [CONTRIBUTING.md](https://github.com/FakeItEasy/FakeItEasy/blob/develop/CONTRIBUTING.md)
- [x] update [README.md](https://github.com/FakeItEasy/FakeItEasy/blob/develop/README.md)
- [x] update protected branch configuration
- [x] [merge develop into master one last time](https://github.com/FakeItEasy/FakeItEasy/pull/1532)
- set the default branch to master in 
    - [x] [project settings](https://github.com/FakeItEasy/FakeItEasy/settings/branches)
    - [x] [Appveyor settings](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/settings)
    - [x] [Read The Docs advanced configuration](https://readthedocs.org/dashboard/fakeiteasy/advanced/)
- [x] update [managing pull requests](https://github.com/FakeItEasy/FakeItEasy/wiki/Managing-pull-requests)
- ~~update FakeItEasy.Deploy~~
- [x] fix up the [next release checklist issue](https://github.com/FakeItEasy/FakeItEasy/issues/1462)
- [x] delete the `develop` branch
- ~~release an alpha version~~
- [ ] remove MinVerMajorMinor from `src/Directory.Build.props`
- [x] delete the `develop` branch

**Comment by blairconrad** [comment]
> I'm thinking that this work is best done immediately following a release

I'm rethinking it. Why not do mid-release? We could just fast-forward master to develop and then do all the things in the checklist, no?

**Comment by blairconrad** [comment]
I was holding off while we had a flurry of competing commits, but I'm keen to work on this now. Any objection? Testing will probably mean releasing an alpha.

**Comment by blairconrad** [comment]
Actually, we wouldn't need to release. We could stop the process after the GitHub bookkeeping is done.

**Comment by thomaslevesque** [comment]
No objection from me.
We still have one issue to address in the [milestone](https://github.com/FakeItEasy/FakeItEasy/milestone/58) for this release (assuming I didn't miss any, which we should probably check), I'll try to do it today.

**Comment by blairconrad** [comment]
Oh, I figured there was no need to have the last issue in the milestone done before we alpha. Regardless, no rush.

**Comment by blairconrad** [comment]
@thomaslevesque, thanks for the merge. I think we're ready to fast-forward master at any time. I won't do until I hear from you, though. (Or feel free to do so if you get to this while I'm sleeping or something.) Then we should be able to whip through the checklist upstairs.

**Comment by thomaslevesque** [comment]
Please merge my PR first ;)

**Comment by blairconrad** [comment]
Oh. I didn't see that you'd rebased!

**Comment by thomaslevesque** [comment]
I merged your PR and did most of the tasks in the checklist. We already established that we don't need to release an alpha, so I struck that.

**Comment by thomaslevesque** [comment]
> We already established that we don't need to release an alpha, so I struck that.

But if we don't, we need to keep the `MinVerMajorMinor` until we actually release a 5.x version.

**Comment by thomaslevesque** [comment]
> > We can delete `develop`.
> 
> Ah, yes. Added it to the list.

And done.

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
