### ISSUE TITLE
Improve performance of Fake creation

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1489]
It could be faster! We should probably focus on optimizing faking interfaces, since I hope that's the most common use case, but it's worth looking at faking classes and delegates as well.

**Comment by blairconrad** [comment]
While there are always performance improvements to be made, we're probably done for this release.
Closed in #1490, #1491, #1497, and #1504.

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
