### ISSUE TITLE
Improve performance of faked method invocation

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1493]
It could be faster!

**Comment by blairconrad** [comment]
While more performance improvements are always possible, we're probably done for this release anyhow.
Closed in #1498 and #1501.

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
