### ISSUE TITLE
Drop fake serialization support in 5.0.0

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1500]
#1499 revealed that we cannot serialize fakes once they've been configured.
Also, if any call has been made to them and we serialize and deserialize the fake, the previously-made calls are lost. (Also note that some calls, such as a property set or get, implicitly configure the fake, so even that last statement is optimistic.)

I don't think there's any value in making the fakes binary serializable and can't imagine that anyone's using the ability in any meaningful way.

**Comment by thomaslevesque** [comment]
👍

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
