### ISSUE TITLE
Allow IFakeObjectCallRule to work preserve work done in IsApplicableTo so it can be used in Apply

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1503]
As @thomaslevesque [noted](https://github.com/FakeItEasy/FakeItEasy/pull/1501#discussion_r235148380), sometimes a call rule does significant work to find out that it applies to a call and then has to throw away that work just to redo the work during the `Apply`  phase.

Shall we supply a way to allow rules to reuse the results of the initial calculation?

Note that this is likely breaking, unless we supply the new mechanism alongside the old one (for example, we could introduce a new interface and new `AddRuleFirst` and `AddRuleLast` overloads) and shouldn't be done until after #1494.
Also, any efficiencies gained are only going to apply in the case where a rule applies to a call, and most rules don't apply to any given call.

**Comment by blairconrad** [comment]
Of the builtin rules, the only ones I see that would benefit are

* `CancellationRule`
* `EventRule`
* `ObjectMemberRule` (handles `ToString`, `Equals`, `GetHashCode`)

I quickly checked SelfInitializingFakes and AutoFixture/AutoFakeItEasy, and their rules would not benefit from the change. Autofac.Extras.AutoFakeItEasy does not implement any fake object rules.

**Comment by thomaslevesque** [comment]
So, is this worth it? Neither or these rules are used very frequently, as far as I can tell.

**Comment by blairconrad** [comment]
On the face of it, I'm guessing it's not worth it, for the reason you say.

However, I don't mind running numbers later. One option would be to do this only for our internal rules, thus avoiding published interface change.

**Comment by blairconrad** [comment]
CancelationRule:

| Method |                     Job |     Mean |     Error |    StdDev | Ratio | RatioSD |
|------- |------------------------ |---------:|----------:|----------:|------:|--------:|
| Cancel |         4.10.0-alpha091 | 69.89 us | 11.310 us | 10.580 us |  1.00 |    0.00 |
| Cancel | 4.9.0-different-rule001 | 66.44 us |  6.577 us |  6.152 us |  0.96 |    0.05 |

![image](https://user-images.githubusercontent.com/3275797/48866185-f1f8d680-ed9f-11e8-8e73-9513558b8e88.png)

Wow. The cancellation rule handling is SLOW.

**Comment by thomaslevesque** [comment]
> Wow. The cancellation rule handling is SLOW. Of course most of that is throwing the exception.

Interesting. Is it faster with an async method? (since in this case we don't throw but returned a canceled task)

**Comment by blairconrad** [comment]
Yes, quite a bit faster.

![image](https://user-images.githubusercontent.com/3275797/48903586-f1a51d80-ee29-11e8-976e-e8cf2fdae543.png)

![image](https://user-images.githubusercontent.com/3275797/48903611-084b7480-ee2a-11e8-937a-c394349feae9.png)

**Comment by blairconrad** [comment]
I think we should leave `IFakeObjectCallRule` as is. The only known client implementations would not benefit from the change, so it doesn't seem worthwhile disrupting clients by changing the interface.

If absolutely necessary, and some client were interested, we could add some overloads at a later date. Or clients could effect the same behaviour by creating a  tiny cache of computed results, keyed by the `IFakeObjectCall`.

We could still entertain the idea of making this change for our pre- and post-user rules once #1494 is closed. At least then there'd be no disruption to the clients.

**Comment by thomaslevesque** [comment]
OK, so let's close this issue. We can always open a new one if we want to optimize the pre- and post-user rules.
