### ISSUE TITLE
Remove IInterceptedFakeObjectCall.AsReadOnly from the public API in 5.0.0

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1505]
As discussed in https://github.com/FakeItEasy/FakeItEasy/issues/651#issuecomment-209093520.
There's no need for clients to call it.

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
