### ISSUE TITLE
Stop faking delegates that are not visible to DynamicProxy in 5.0.0

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1508]
Connects to #1437, in that if DynamicProxy gives us a way to fake delegates, we would likely have to drop this support anyhow. And it would make our capabilities more consistent, since we cannot fake classes or interfaces that aren't visible to DynamicProxy.

**Comment by thomaslevesque** [comment]
I'm having trouble getting the proper error message ("Can not create proxy for type..."). We don't generate this message ourselves, it's returned by DynamicProxy as the exception message when we call `CreateClassProxy`. But we don't do that for delegates, so we can't get the message. Of course, it wouldn't be hard to fake it, but it's annoying...

**Comment by blairconrad** [comment]
Hmm. Annoying. Even building an interface to act like the delegate and proxying it wouldn't work, because we wouldn't be giving the delegate itself to DynamicProxy.
Faking it (perhaps by accessing `Castle.DynamicProxy.ExceptionMessageBuilder.CreateMessageForInaccessibleType` via reflection?) might be the only option.

I guess we now have motivation to hurry along the Castle.Core "proxy a delegate" issue!

**Comment by thomaslevesque** [comment]
I have an idea, but it's slightly ugly... PR incoming.

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
