### ISSUE TITLE
pre_release should update the tag when renaming a GitHub release

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1540]
The first box:

![image](https://user-images.githubusercontent.com/3275797/49741057-92397100-fc63-11e8-9c50-6bb1f6af0db2.png)

After I prepared 5.0.0-alpha.1 this morning, that box was left as "vNext". It should've been moved to 5.0.0-alpha.1. I think. I'm really not sure how well that works when the tag is created later, but I think it's worth trying.

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
