### ISSUE TITLE
Upgrade to ILMerge 3.0.21

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1567]
I don't think it fixes any problem we currently have (still loses SourceLink information), but:
- it no longer requires .NET 3.5
- it provides a MSBuild property with the tool path
- I'm unable to build with 2.14.1208 on my new machine, but it works with the newer version

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 5.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/5.1.0).
