### ISSUE TITLE
Open Generic Fakes

### ISSUE THREAD

**Issue by endeffects** [FakeItEasy/FakeItEasy#1592]
I'd like to register an open generic fake to the IServiceCollection as replacement for my generic repositories. Is it possible? I'm looking for hours now and found no solution. It would be helpfull to run some scoped integration tests.

**Comment by thomaslevesque** [comment]
Hi @endeffects,

Do you mean something like this?

```csharp
services.AddSingleton(typeof(IMyService<>), _ => A.Fake...);
```

I'm afraid it's not possible. The limitation isn't in FakeItEasy, but in Microsoft.Extensions.DependencyInjection. There's no way to access the type parameter in the delegate that creates the service. See https://github.com/aspnet/DependencyInjection/issues/474 for details.

**Comment by endeffects** [comment]
Yes, exactly. Too bad it's not possible. :(
