### ISSUE TITLE
New version breaks existing code (nested argument constraint)

### ISSUE THREAD

**Issue by chrischu** [FakeItEasy/FakeItEasy#1598]
After upgrading to the newest FakeItEasy version I get the exception "An argument constraint, such as That, Ignored or _, cannot be nested in an argument" when running the following code (simplified for brevity's sake):
```
public void AssertSomething(IService service, string name = null, int? value = null) 
{
   A.CallTo(() => service.Method(name ?? A<string>._, value ?? A<int>._)).MustHaveHappened();
}
```

The problem is: I want to use this assertion method several times, sometimes I care about the `name`/`value` parameters, sometimes I don't. Is there any way to still achieve this behavior with the newest version of FakeItEasy?

I tried just moving the `??` operator before the `A.CallTo()` but that doesn't work since FakeItEasy does not allow creating `A<Type>._` outside of `A.CallTo()` apparently.

Thanks in advance!

**Comment by thomaslevesque** [comment]
Hi @chrischu,

What you're trying to do actually never worked as expected, it's just that now we detect it and throw an error. More details in https://github.com/FakeItEasy/FakeItEasy/issues/1177.

Another way of doing what you want is this:

```csharp
public void AssertSomething(IService service, string name = null, int? value = null) 
{
    A.CallTo(
        () => service.Method(
            A<string>.That.Matches(s => name == null || s == name),
            A<int>.That.Matches(i => value == null || i == value.Value)))
       .MustHaveHappened();
}
```

A bit more verbose, but it should do what you want. Note that the exception message when the assertion fails is a bit ugly, so you might want to customize it. Something like this, maybe:

```csharp
public void AssertSomething(IService service, string name = null, int? value = null)
{
    A.CallTo(
        () => service.Method(
            A<string>.That.Matches(s => name == null || s == name, x => x.WriteOptionalConstraint(name)),
            A<int>.That.Matches(i => value == null || i == value.Value, x => x.WriteOptionalConstraint(value))))
       .MustHaveHappened();

}

...

static class OutputWriterExtensions
{
    public static void WriteOptionalConstraint(this IOutputWriter writer, object constraintValue)
    {
        if (constraintValue != null) writer.WriteArgumentValue(constraintValue);
        else writer.Write("Ignored");
    }
}
```

**Comment by thomaslevesque** [comment]
@chrischu did that solve your problem?

**Comment by chrischu** [comment]
@thomaslevesque Yeah, thanks that worked! :)
