### ISSUE TITLE
Move NUGET_API_KEY out of appveyor.yml and into environment variables

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1609]
Currently we have it in `appveyor.yml` and in a NuGet deployment setting, which is unused.
The `appveyor.yml` value is expired, so we end up having to manually push packages to nuget when releasing.
We should put it in https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/settings/environment, so it's easier to change every year.

**Comment by thomaslevesque** [comment]
We can also remove GITHUB_TOKEN and NUGET_SERVER_URL, I think.
And the BUILD environment variable, which isn't used anywhere AFAICT.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 5.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/5.2.0).

Sadly, it seems to have broken communication with GitHub.

https://ci.appveyor.com/project/FakeItEasy/fakeiteasy#L385
