### ISSUE TITLE
GitHub API calls fail during deployment

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1618]
Seen when [trying to deploy 5.2.0](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy#L385).

I suspect this was caused by #1609.

**Comment by thomaslevesque** [comment]
It says "bad credentials" for GitHub. I used the token that was declared in the ["Github Releases" environment in AppVeyor](https://ci.appveyor.com/account/FakeItEasy/environment/17406/settings), maybe it was expired.

**Comment by thomaslevesque** [comment]
I can confirm the GitHub token was not valid (tried from a local script), and that the script can read AppVeyor environment variables (#1619).

I generated a new GitHub token and set it in AppVeyor environment variables.

**Comment by blairconrad** [comment]
Oh, nice. Thanks!

**Comment by blairconrad** [comment]
Fixed, as shown by release of 5.3.0-beta.1

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 5.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/5.3.0).
