### ISSUE TITLE
Embed FakeItEasy icon in package

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1627]
`PackageIconUrl` is deprecated in .NET Core 3 SDK, and is replaced with `PackageIcon`, which refers to an embedded image.
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packageiconurl

We should embed the icon in the package when we switch to .NET Core 3 SDK.

Note: I'm not seeing the NU5048 warning on FIE when using the latest SDK (3.0 RC1), not sure why. I tried on another project and the warning does appear.

**Comment by thomaslevesque** [comment]
> Note: I'm not seeing the NU5048 warning on FIE when using the latest SDK (3.0 RC1), not sure why. I tried on another project and the warning does appear.

Ah, that was because of this:
https://github.com/FakeItEasy/FakeItEasy/blob/1177af6b53709a492e977777fe17508d36881878/src/Directory.Build.props#L12

If we re-enable package analysis, there are some warnings that we should probably fix:

In FakeItEasy.Analyzer.CSharp:
> warning NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
> warning NU5128: - Add lib or ref assemblies for the netstandard1.1 target framework

In FakeItEasy.Analyzer.VisualBasic:
> warning NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
> warning NU5128: - Add lib or ref assemblies for the netstandard1.1 target framework

**Comment by blairconrad** [comment]
I'm for re-enabling the analysis if it's tractable.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 5.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/5.3.0).
