### ISSUE TITLE
Stop wrapping exceptions thrown by "action" callbacks in UserCallbackException

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1640]
Since #1364, we wrap most exceptions thrown by user callbacks (`WhenArgumentsMatch`, `ReturnsLazily`, etc) in a `UserCallbackException`. This makes it easier to understand where the exception was thrown, especially for call specification callbacks (`A<T>.That.Matches(<callback>)`, `Where(<callback>`, `WhenArgumentsMatch(<callback>)`, etc).

We rolled back that behavior for `Invokes` to fix #1543 and now let the exception bubble up without wrapping it, because throwing from the `Invokes` callback is a legitimate scenario.

Now, #1635 makes it apparent that throwing from the `ReturnsLazily` callback is also a legitimate scenario, so we should also stop wrapping the exception in this case.

In fact, we should probably stop wrapping the exceptions thrown by all "action" callbacks:

- `Invokes` (already done)
- `ReturnsLazily`
- `AssignsOutAndRefParametersLazily`
- `Throws`

In the case of `Throws`, the callback is supposed to *return* an exception, not throw it; but it doesn't really matter if it throws, since we just throw the returned exception anyway, so the effect is the same in the end.

**Comment by blairconrad** [comment]
Proposing we call this a "bug" fix, as we treated #1543 as a bug.

**Comment by thomaslevesque** [comment]
Agreed

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 5.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/5.3.0).
