### ISSUE TITLE
Exception thrown from argument constraint factory prevents detection of misused A<T>._, A<T>.Ignored, or A<T>.That

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1644]
If an exception is thrown from an argument constraint factory, it leaves the system in an unstable state, where `A<T>._`, `A<T>.Ignored`, or `A<T>.That` when used outside a call configuration will not be detected as an error.

**Comment by thomaslevesque** [comment]
Can you elaborate? Is this because of the lack of `finally` block which I mentioned in your PR?

**Comment by thomaslevesque** [comment]
Ah, I just saw your new PR. Ignore me.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 5.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/5.3.0).
