### ISSUE TITLE
Automatically add "this change has been released" note to issues

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1652]
Every time we create a non-pre-release release, we add a note to issues (or pull requests) like this:

```
This change has been released as part of FakeItEasy 5.1.2.
```
with a link to the release notes.

It's time-consuming. We could have the release process do this for us. Humans would still need to hand-write notes to the changes that were contributed by the community, though.

**Comment by blairconrad** [comment]
I was considering working on this, and started wondering: is there a reason not to add the note to pre-release releases? I am not sure why we made the distinction.
It's fine as it is, but we could make the switch to add the note on any release. After all, the fix would then be available, and I think most people would understand that something fixed in 5.3.0-beta.1 is also available in 5.3.0 (assuming we don't decide to rollback for some reason).

Here are two easy(ish) options for implementation:
1. just add the notes when it's a "production release" - not a pre-release, as we do now. We can use the issues in the milestone as our target
2. add the notes on any release, using the issues listed in the release notes. Actually, since we roll up the release notes after pre-releases, this means anything fixed in a pre-release would get two notes: one for the first pre-release in which it was fixed, and then one for the production release
3. just add notes for the first release an issue was fixed in, whether it's a pre-release or a production release. This would require more sophisticated logic, possibly including parsing existing notes on the issues

I'm lazy, and nervous about complicated parsing, so prefer to avoid option 3, but could go for either of the other two. Thoughts, @thomaslevesque?

**Comment by thomaslevesque** [comment]
I agree that it would make sense to add the note for pre-releases. If we can avoid adding it twice for the same issue, it's even better, but I understand why you're reluctant about option 3, so let's forget about it for now.

So I guess we should go for option 2

**Comment by blairconrad** [comment]
If this is ever fixed, we'll need to update the release checklist.
Also, if we fix it in 5.3, we'll have to manually add the note to the issues in 5.3.0-beta.1.

**Comment by thomaslevesque** [comment]
This change has been released as part of [FakeItEasy 5.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/5.3.0).
