### ISSUE TITLE
Brainstorm lightweight dummying of POCOS [or objects with no virtual methods?]

### ISSUE THREAD

**Issue by TimLovellSmith** [FakeItEasy/FakeItEasy#1657]
File this under ideas for a rainy day but - 
While wondering whether my tests really got faster from having less fake tuple objects, I started wondering more thoughts...
Why don't we need to fake tuples? Because they have no fakeable behavior. What else has no fakeable behavior? POCOs!
Also seems like the only reason to return a fake class is to let people override virtual methods, so if a class has no virtual methods don't return a fake for it right? Oh... but GetHashCode, and ToString, and Equals are *always* virtual so objects are *always* fakeable, sigh...
So POCOs are fakeable too...
But you can unfakeable them by using 'sealed'... or 'struct'... Too bad that those choices can involve other side effects!

I feel a little suspicion over whether faking Equals and GetHashCode are ever good ideas, but i do also feel it would suck if someone did want to, and then found they couldn't...

Well, by such trains of thought, I arrived at my non-conclusion, which is more of me wondering if i should try an experiment... what will happen if FakeItEasy only ever dummies types as fakes if they have any non-trivial virtual methods and not just those that happened to inherit 'ToString', 'Equals', and 'GetHashCode'?
In fact for those 3 methods, maybe the rule could be that either you are doing A.Fake<> explicitly to get faking, or for dummies you only get a fake if you have a non-sealed override of any of those methods, or a non-sealed virtual/abstract method not inherited from object. Or it was abstract/interface.

This probably sounds far too complicated to explain to people, just to avoid some proliferation of fake dummies... 
Although the same underlying constructors and non-virtual methods should be being called either way...

This brings up another question of whether it is still legit to do A.Fake on these types.... I'd say it is, though controversially [because of bad error messages?], it might not need to actually return a fake at all...

**Comment by thomaslevesque** [comment]
Interesting thoughts, @TimLovellSmith!

An important question to ask is this: is there any real drawback to having dummies that are actually fakes? In other words, should we make it a goal to avoid creating a fake when a dummy is created? To be honest, I'm not sure there's much to gain here.

But assuming we do want to do this, let's think about a possible approach.

The current strategy for creating a dummy of a reference type (not including `Task`, `Lazy`, `Tuple` etc) is this:
- try to create a fake
- if it fails, just try to create an instance by passing dummies to the constructor

A reasonable alternative could be this:
- if it's a concrete type with a public constructor, just create an instance by passing dummies to the constructor
- otherwise, try to create a fake

Technically, it would be a breaking change, but if people rely on dummies being fakes, it's their own mistake... So I guess we could do this. It probably wouldn't be very hard.

@blairconrad what do you think?

> This probably sounds far too complicated to explain to people, just to avoid some proliferation of fake dummies...

Yes, it probably is :wink:

**Comment by blairconrad** [comment]
While I do think it's a mistake for a user to invoke `A.Dummy<T>()` and then expect to configure the result as a Fake (or really expect anything other than that the Dummy is non-null and maybe has the [minimal behaviour we document](https://fakeiteasy.readthedocs.io/en/stable/dummies/#how-are-the-dummies-made)), I don't think we shold make the switch to preferring to invoke a public constructor rather than create a Fake. 

> Technically, it would be a breaking change, but if people rely on dummies being fakes, it's their own mistake... So I guess we could do this. It probably wouldn't be very hard.

I can't find it in the docs right now, but in the past at least we actually encourage people to consider that fakeable Dummies may be Fakes. Specifically, when wants to configure something like

```c#
A.CallTo(() => fake.Property.Method()).Returns(7);
```

on an otherwise unconfigured Fake.  I'm sure people do enjoy this behaviour.

And as @thomaslevesque says, I'm not sure there's much to gain here, and I'd hope we'd have something bigger than perhaps quicker Dummy creation.

**Comment by thomaslevesque** [comment]
> I can't find it in the docs right now, but in the past at least we actually encourage people to consider that fakeable Dummies may be Fakes. Specifically, when wants to configure something like
> 
> ```cs
> A.CallTo(() => fake.Property.Method()).Returns(7);
> ```
> 
> on an otherwise unconfigured Fake. I'm sure people do enjoy this behaviour.

That's a *very* good point. And that alone is a good reason to keep the current behavior.

It's mentioned in the docs [here](https://fakeiteasy.readthedocs.io/en/stable/default-fake-behavior/#overrideable-members-are-faked).

As for @TimLovellSmith's original idea of special-casing POCOs, I don't think it's practical, because there isn't a universal definition of what a POCO is.

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque.

@TimLovellSmith, we appreciate the enthusiastic ideas for improving Dummy creation, I don't think this one is strong enough to make it into the product.
But if you think there are still significant downsides, you could consider implementing a custom `IDummyFactory` that analyzes the requested type, and if it finds that it's better to instantiate than to make a Fake, it could do so.
If that proves sufficiently beneficial, that factory could be released in a separate package, thereby allowing users to opt in

**Comment by TimLovellSmith** [comment]
OK, I'm just going to say one more thing I thought about afterwards... the distinction between Fake and Dummy is getting more and more blurred in my mind - since a lot of dummies are really Fakes anyway. This makes me wonder if you could even just drop the distinction. And maybe even try to stop your users worrying about which objects are fake or dummies..? Because it may not even matter. What? Yes, consider this made up-example:

```
A.CallTo(() => myComputer.UserManager.createNewUser(userargs)).Returns()...
```

Does it matter if myComputer is really a fake or dummies? You might be thinking 'Yes', but I'm going to just say 'No... the only thing that matters is whether UserManager.createNewUser is virtual, and therefore fakeable'. And how did we get there? 

Practically, it really doesn't matter how this worked:
```
myComputer = A.Fake<Computer>();
```
It could have returned a 'fakeComputer' object. Or it could have returned a real computer object with dummied constructors... or an autoimplemented virtual 'UserManager' property which returns dummy objects. But the exciting thing to me today is that ANY of those work!

Why is that exciting? Because what I'm thinking, is that *if Computer had no virtual methods/properties*, there was never a real reason to try to make a Fake for it in the first place. We could have just made real Computer and given it dummy constructor arguments, and it would work the same whether its fake or not. And if those dummied objects had no virtual methods either, then there was no need to 'fake' them... and so on, and so on!

And so what I suspect is that the transitive closure of that effect could lead to significant savings in the number of fake types being generated.

Which brings you back to the question of can you still give good error messages? My possible epiphany here is that you probably can. Because when you think about it, the question doesn't depend on answer to 'are the objects along the way fake?' It just depends on 'is the call at the end a virtual call on a fake object?' And that doesn't change.

**Comment by thomaslevesque** [comment]
> OK, I'm just going to say one more thing I thought about afterwards... the distinction between Fake and Dummy is getting more and more blurred in my mind - since a lot of dummies are really Fakes anyway. This makes me wonder if you could even just drop the distinction.

I don't think so. We really need the concept of dummies anyway, because we need default values for properties, arguments for constructors, etc. We couldn't really hide that concept from the API, because it has visible consequences.

> And maybe even try to stop your users worrying about which objects are fake or dummies.

I don't think they do, in general. I rarely even think about them when writing tests. You can use FakeItEasy for a long time without even knowing what a dummy is. Usually you start learning about them when something isn't working as expected, and then knowing the distinction between fakes and dummies become useful.

> Which brings you back to the question of can you still give good error messages?

Sorry, you lost me here... What's the relation with error messages?

**Comment by blairconrad** [comment]
> > try to stop your users worrying about which objects are fake or dummies.

> I don't think they do, in general. I rarely even think about them when writing tests. You can use FakeItEasy for a long time without even knowing what a dummy is. Usually you start learning about them when something isn't working as expected, and then knowing the distinction between fakes and dummies become useful.

I agree. However, @thomaslevesque and I are on the inside and so have a unique perspective.  (Although even when I started using FakeItEasy, I wasn't confused about the difference between Fakes and Dummies. Then again there was almost no documentation to confuse me!) If you're unsure about Fakes and Dummies, @TimLovellSmith, maybe that reflects a failure in the documentation.  Do you find the [Dummy documentation](https://fakeiteasy.readthedocs.io/en/stable/dummies/) is confusing? We start off

> A Dummy is an object that FakeItEasy can provide when an object of a certain type is required, but the actual behavior of the object is not important.

which I thought set expectations, but it seems there's still some confusion. In general, if you care how a Dummy acts, you probably shouldn't be using a Dummy.

> We really need the concept of dummies anyway, because we need default values for properties, arguments for constructors, etc. We couldn't really hide that concept from the API, because it has visible consequences.

True, but , maybe FakeItEasy never should have exposed a way to create Dummies at will. It's a bit of a secondary behaviour. FIE needs to make Dummies to pass to constructors of Fakes (or other Dummies) and to return from unconfigured methods, but `A.Dummy<T>()` and friends isn't really necessary. I think it was just provided as a convenience—a sort of intention-revealing "I don't care about this value, but the function I'm calling needs me to supply _something_" value. I've used it as such, but not very often.

**Comment by thomaslevesque** [comment]
> True, but , maybe FakeItEasy never should have exposed a way to create Dummies at will. It's a bit of a secondary behaviour. FIE needs to make Dummies to pass to constructors of Fakes (or other Dummies) and to return from unconfigured methods, but `A.Dummy<T>()` and friends isn't really necessary.

I never thought about it this way, but yes, I guess `A.Dummy<T>()` just adds confusion and maybe shouldn't have been exposed in the first place... Anyway, it's there now, so we're kinda stuck with it.

> a sort of intention-revealing "I don't care about this value, but the function I'm calling needs me to supply _something_" value. I've used it as such, but not very often.

I wonder if many people use it like this. I rarely do.

**Comment by TimLovellSmith** [comment]
>>a sort of intention-revealing "I don't care about this value, but the function I'm calling needs me to supply something" value. I've used it as such, but not very often.

>I wonder if many people use it like this. I rarely do.

FWIW I do...

**Comment by blairconrad** [comment]
I'm inclined to close this issue. If there's a need to improve the docs around Dummies, let's pursue in another issue. But without word from @TimLovellSmith suggesting that there's a lack, I'm inclined to just carry on as we are.

**Comment by TimLovellSmith** [comment]
You can close, up to you. I had put off a proper reply to this til i had a bit more time as i guessed i have a long and involved answer coming up here!

Let me try to explain my proposal another [fun?] way, by imagining the docs of FakeItEasy in a parallel universe where someone got hit by a bolt of lightning many years ago. They decided to do some things different too! [may avoid confusion with real docs]

"FakeYtMaybe

The new greater-than-sliced-bread library you have all been waiting for! Essentially comes with two API entry points. These are 'An.Ynteresting<T>' and 'A.Boring<T>'.

Let us explain 'A.Boring<T>' first. This call returns an object or struct that derives from T, which may be a default value, with the exception that it is never `null`. The object in question is not really supposed to do anything! Except, maybe, return similarly boring objects which are never null. You can call methods on the object, and if they are virtual, they will do nothing much at all, and return another boring object.

Now that the boring part is over with lets explain the fun part: 'A.Ynteresting<T>'. This call also returns an object or struct that is either a real T, or a value derived from T, and definitely never 'null'. The object in question comes with a range of default behaviors (similar to 'A.Boring<T>'), BUT it is also intended to be used for configuring custom behaviors on. *However*... the only behaviors you can *actually* modify are the behaviors of interface members [properties, methods, etc], or virtual/abstract members on the object. 

And you can only do that if there is a way to construct a T and pass in lots of **possibly interesting** objects, such that we can figure out a way to hook the call you are trying to configure [you can provide hints on how to do this using optional parameters to An.Ynteresting<T>()]. Since this all sounds hopelessly vague, here is an example to make it clearer than mud:

A.CallTo(anyObject => anyObject.SomeProperty.SomeMethod().SomeOtherMethod()).Returns("what I want");

And, this will almost always work.... With a few quid-pro-quos, provisos, limitations etc. The only real ones being...
1] SomeOtherMethod must be virtual/abstract/interface. Otherwise, sorry, impossible!
2] SomeOtherMethod() must have returned an 'interesting' object. There are many ways this could happen, but here are a few useful possibilities:
a] anyObject could have been created by calling An.Ynteresting<T>()... AND T has a *virtual* property 'SomeProperty' which has a new default behavior, of returning an interesting object, and that object had its own default implementation of virtual method SomeMethod() which returned an interesting object.
b] any Object could have been a regular old object but someone assigned an interesting object to its 'SomeProperty' property using the setter. And that interesting object again defaults to returning interesting objects from its virtual methods, in this case SomeMethod()!
c] or you could have passed interesting objects into the constructor of the real type T... so that it will eventually return an interesting object from SomeMethod()...
d] or you could have relied on the default constructor invocation behavior for `An.Ynteresting<T>` which is to pass in lots of interesting objects...

Note: `An.Ynteresting<T>` sometimes just returns you a T, because that was about as interesting as we could possibly get, because T is...
-Sealed
-An object we couldn't otherwise figure out how to construct from a derived type
or T cannot be *made very interesting* because...
-it has no virtual methods (aside from those it inherited from object - these are boring unless there's an override!),
-important special cases of no interesting virtual methods... it could be a Lazy<T>, Tuple<T>, ValueTuple<T>, or KeyValuePair<TKey,TValue> which overrides ToString in a quite boring way.
" [end doc]


Epilpog: OK that was not really as super convincing as I hoped it was going to be...
But where I am going is - the current docs for Fake behavior attempt to be quite prescriptive of implementation and types. I started to get a sense that is good, because it helps people build mental models which let them understand why they can/can't fake stuff, and how, but comes with the drawback that from a problem-solving standpoint it may be overly restrictive on what the implementation does to get you from A [creating] to B [configuring some call].

**Comment by TimLovellSmith** [comment]
You can close, up to you. I had put off a proper reply to this til i had a bit more time as i guessed i have a long and involved answer coming up here!

Let me try to explain my proposal another [fun?] way, by imagining the docs of FakeItEasy in a parallel universe where someone got hit by a bolt of lightning many years ago. They decided to do some things different too! [may avoid confusion with real docs]

"FakeYtMaybe

The new greater-than-sliced-bread library you have all been waiting for! Essentially comes with two API entry points. These are 'An.Ynteresting' and 'A.Boring'.

Let us explain `A.Boring<T>` first. This call returns an object or struct that derives from T, which may be a default value, with the exception that it is never null. The object in question is not really supposed to do anything! Except, maybe, return similarly boring objects which are never null. You can call methods on the object, and if they are virtual, they will do nothing much at all, and return another boring object.

Now that the boring part is over with lets explain the fun part: `An.Ynteresting<T>`.

This call usually requires no arguments, to instantiate an object of T or derived type that is as *interesting and configurable as possible*. Specifically, we don't say **what** type will be returned, but we promise that
-it never returns null
-it returns `default(T)` for some types where there is nothing really much interesting it could do.
-it returns a T, if T was sealed, but it can figure out how to construct T
-the constructor arguments it gave to T are also made as *interesting and configurable as possible*
-the virtual methods and properties of T will by default return the most interesting and configurable objects possible, i.e. if the returned value is type T2, it should be something like you would get from `An.Ynteresting<T2>`
-it may return a real T, even though T was not sealed, if that seems to be about as-interesting-as-it-gets, because T doesn't have any other way to add interesting behavior [e.g. it had no virtual methods, or all its virtual properties and methods return types which cannot be made interesting]

We still haven't explained what interesting and configurable is all about... well, it is all about being able to do this.

A.CallTo(anyObject => anyObject.SomeProperty.SomeMethod().SomeOtherMethod()).Returns("what I want");

This can work as long as
1] SomeOtherMethod must be virtual/abstract/interface.
2] SomeOtherMethod() must be one of those 'interesting and configurable' objects. There are many ways this could happen, but the most common typical one is that
a anyObject was an object or interesting object,
AND anyObject.SomeProperty returned an interesting object, either because we set the property value, or because anyObject was created using `An.Ynteresting<T>`,
AND SomeMethod() also returned an interesting object, which could be because SomeMethod was virtual [but there are many alternative ways SomeMethod could be made to return an interestin object, e.g. something could have been given interesting constructor parameters, earlier configurations on interesting objects, earlier property assignments, etc.]

Note, remember, when `An.Ynteresting` just returns you a T, its probably because T is...
-Sealed,
-OR An object we couldn't otherwise figure out how to construct from a derived type
-OR T cannot be made very interesting because... it has no virtual methods (aside from those it inherited from object - these are boring unless there's an override!),
-OR some special cases [with no very interesting virtual methods...] it could be a Lazy, Tuple, ValueTuple, or KeyValuePair<TKey,TValue> which overrides ToString in a quite boring way.
" [end doc]

Epilpog: OK that was not really as super convincing as I hoped it was going to be...
But where I am going is - the current docs for Fake behavior attempt to be quite prescriptive of implementation and types. I started to get a sense that is good, because it helps people build mental models which let them understand why they can/can't fake stuff, and how, but comes with the drawback that from a problem-solving standpoint it may be overly restrictive on what the implementation does to get you from A [creating] to B [configuring some call].

**Comment by blairconrad** [comment]
Thanks, @TimLovellSmith. I must admit that I'm a bit confused and overwhelmed by your response. It's possible that it might make things clearer to some readers, but it did not for me. I'm not saying it's without value, but I'm not sure how to translate it into actionable improvements to the documentation.

We're more than happy to talk about concrete (hopefully small, but whatever needs to be done) ways of improving the documentation or even just chatting to resolve your confusion, but I think this issue is not the venue. Do feel free to pursue the problem in another issue, if you think it'll help.

**Comment by TimLovellSmith** [comment]
@blairconrad 
Sorry! It was a pretty unpolished idea still. I do appreciate the attention you gave it, I think I've learned something from the process so far and I'll try to come up with some more concrete ideas.

**Comment by blairconrad** [comment]
@TimLovellSmith, please do not be sorry. You've done nothing wrong. Even if we reject an idea, that doesn't mean it or the conversation around it doesn't have value. Heck, I've probably rejected an idea twice and eventually implemented. Sometimes the time isn't right or our understanding isn't there. We are thrilled to have a passionate community and value your input.
