### ISSUE TITLE
Support building only part of the target frameworks

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1662]
With the multiplication of target frameworks for the library and tests, the build times have been getting longer and longer. Although all these TFMs are there for a good reason, it can significantly slow down the feedback loop when working on the project.

As discussed in chat with @blairconrad, we should consider a way to build only some TFMs.

A possible way to do this would be to define "target framework sets" that define the target frameworks for each project. The default set would be the "full" set, including all currently supported target frameworks. We could then introduce other sets with only some of the target frameworks for faster development cycle.

**Comment by blairconrad** [comment]
> OR we can extract a "test utilities" project that targets the lowest possible TFM, and this way we can avoid changing the analyzer tests. 

I've no problem with this.

> But I think these tests should run on netcoreapp anyway, if only to support non-Windows build.

Also a good idea!

> The approval tests will fail if a target is missing. Maybe we could just skip the test if the assembly can't be found.

I think that's fine. If the assembly is missing for an unexpected reason, we'll probably notice! On the other hand, if I'm running the tests and interested in them running fast, I'm probably doing something like `build spec integ unit` anyhow, so this change could be deferred, if you haven't the appetite for it now. Your choice.

**Comment by thomaslevesque** [comment]
> if you haven't the appetite for it

Oh, it's not like it's a big change ;)

**Comment by thomaslevesque** [comment]
This change has been released as part of [FakeItEasy 5.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/5.4.0).
