### ISSUE TITLE
How to call wrapped method after Invokes() interception?

### ISSUE THREAD

**Issue by asgerhallas** [FakeItEasy/FakeItEasy#1693]
I'm trying to make something like this work: 
        
```
    public interface IInterface
    {
        object MyMethod();
    }

    class MyImpl : IInterface
    {
        public object MyMethod() => 1;
    }

    var fake = A.Fake<IInterface>(x => x.Wrapping(new MyImpl()));

    A.CallTo(fake).Invokes(x => { });
  
    fake.MyMethod().ShouldBe(1);
```

I have tried `A.CallTo(fake).Invokes(x => { }).CallsBaseMethod()` too, but that results in a proxy error: "This is a DynamicProxy2 error: The interceptor attempted to 'Proceed' for method 'System.Object MyMethod()' which has no target. When calling method without target there is no implementation to 'proceed' to and it is the responsibility of the interceptor to mimic the implementation".

Is this possible? And if so how? ...And if not, should it be?

Thanks for making a great library!

**Comment by blairconrad** [comment]
Hi, @asgerhallas. Based on your code, I'd just not configure the fake. It'll call the wrapped method out of the box.

But if you're just omitting some other action you want in there, I'd try

```c#
MyImpl wrappedInstance = new MyImpl();
var fake = A.Fake<IInterface>(x => x.Wrapping(wrappedInstance));

A.CallTo(fake)
    .WithReturnType<object>()
    .Invokes(() => { /* something fancy */ })
    .ReturnsLazily(call => call.Method.Invoke(wrappedInstance, call.Arguments.ToArray()));

Assert.Equal(1, fake.MyMethod());
```

**Comment by asgerhallas** [comment]
Sorry, I should have given more context! :)

I will indeed invoke something fancy... and worse: I'd like to implement this as an extension-method for the CallTo() builder interface, so I dont have access to the wrapped instance. 

So I hoped that I could somehow set it up to call the intercepted method after invoking my delegate.

**Comment by asgerhallas** [comment]
Is there a way to get access to the wrapped instance from an IFakeObjectCall?

**Comment by blairconrad** [comment]
Hi, @asgerhallas, no way that I know of to access the wrapped instance. Of course, you could always pass it to your extension method! (I know, that's ugly.)

Without knowing exactly what you're doing, I'm leery of suggesting a path forward given the current FakeItEasy capabilities, other than to say that you might be able to accomplish what you want by creating your own Rule, not unlike what [SelfInitializing Fakes does](https://github.com/blairconrad/SelfInitializingFakes/blob/6b358aa4b4f684b39f149b0be01adfc2281b6228/src/SelfInitializingFakes/SelfInitializingFake.of.T.cs#L39) or maybe even by adding an interception listener.
Take a peek at _Manipulating a fake's call rules_ and _Intercepting calls_ under [The FakeManager object](https://fakeiteasy.readthedocs.io/en/stable/advanced-usage/#the-fakemanager-object). Then come back and we can talk about what looks like it might work or not work for you, if you're so inclined.

**Comment by asgerhallas** [comment]
Thank you! This is really helpful. Even the fun fact, I think :) 

I'll dive in and return wiser - hopefully.

**Comment by asgerhallas** [comment]
Got it working! :) 

1. Added a rule
2. Did "something fancy" in `IsApplicableTo`. Doing it in `Apply` would stop processing of other rules.
3. `IsApplicableTo` is run multiple times, so added a uniqueness check for calls.
4. If doing this as extensions to the fake (I know this is not the FakeItEasy-way), so remember to filter out those extension method calls.

Thanks again for pointing me in the right direction. 

And thanks again for the library. Just checked, I've been using it since 2011. It's a keeper! :)

**Comment by blairconrad** [comment]
Hey, @asgerhallas, I'm slightly worried about the maintainability of a side effect in `IsApplicableTo`, but if you're happy, I'm happy.

2011? Old-timer! 2 years longer than me. It's nice to hear from a satisfied customer.

**Comment by asgerhallas** [comment]
@blairconrad I agree with you on the maintainability aspect of that solution... but I couldn't find any other way to do side-effects and still continue on to the next rule in the chain. Though I guess a collaboration between an interceptor (to do the side-effect) and a rule (to stop processing or override return value) might do the trick.
