### ISSUE TITLE
Override CallsBaseMethods() with argument matching

### ISSUE THREAD

**Issue by jinwangxx** [FakeItEasy/FakeItEasy#1710]
Hi I am trying to partially mock a class with argument matching

```c#
public class Lookup
{
    public virtual string GetResult(string key)
    {
        return "value";
    }
}

Lookup lookup = A.Fake<Lookup>(x => x.CallsBaseMethods());
A.CallTo(() => lookup.GetResult("invalid_key")).Returns("default_value");`
```
but ` lookup.GetResult("invalid_key")` still returns `"value"`

Would you verify such override is correct? Or is there alternative solution?

Thanks

**Comment by thomaslevesque** [comment]
Are you sure? I just tried it (using your exact code), and it returned `"default_value"` as expected (using the latest version, 5.4.1).
Which version are you using? Is this your actual code or a simplified version?

**Comment by jinwangxx** [comment]
Thanks for the confirmation. Yes it worked after fixing user error. I'll close this issue. Thanks!
