### ISSUE TITLE
Using Wrapping and Implements together

### ISSUE THREAD

**Issue by asgerhallas** [FakeItEasy/FakeItEasy#1716]
Sorry to bother you again!

I am playing around with Wrapping and Implements and wonder and thought the following would work:

```c#
[Fact]
public void FunFact()
{
    var fake = A.Fake<Wrappee>(x => x.Wrapping(new Wrappee()).Implements<IWrappee>());

    var theObject = new object();

    fake.Add(theObject);

    ((IWrappee)fake).GetAll().Single().ShouldBe(theObject);
}

public interface IWrappee 
{
    IEnumerable<object> GetAll();
}

public class Wrappee : IWrappee
{
    readonly List<object> objects = new List<object>();

    public void Add(object obj) => objects.Add(obj);

    public IEnumerable<object> GetAll() => objects;
}
```

But it doesn't, because the `((IWrappee)fake).GetAll()` call is not to the same target instance as the `fake.Add(theObject);` call.

Am I doing something wrong, or is this a bug?

**Comment by blairconrad** [comment]
Hi, @asgerhallas. Some notes!

1. cool test method name
2. `Wrapping` doesn't even need to be involved to reproduce your behaviour. This does the same:
    ```c#
   [Fact]
   public void TestNoWrapping()
   {
       var fake = A.Fake<Wrappee>(x => x.Implements<IWrappee>());

       var theObject = new object();

       fake.Add(theObject);

       Assert.Same(theObject, ((IWrappee)fake).GetAll().Single());
   }
    ```

And on to your main question:

> Am I doing something wrong, or is this a bug?

Not really. `Wrappee.Add` and `IWrappee.Add` are in some sense different methods, so when you configure one, it doesn't affect the other. It can be sometimes confusing, but is the mechanism (I believe) that allows FakeItEasy to deal with explicitly-implemented interfaces.

I don't know that I have any other advice than "avoid doing that". :-(

**Comment by asgerhallas** [comment]
Hi @blairconrad,

> Is there a reason you chose to add the bonus `Implements`?

Totally due to me misunderstanding the details of how the proxy works. I thought that for classes, it would only intercept virtual methods, not interface methods that the class implements. Reading up on https://github.com/castleproject/Core/blob/master/docs/dynamicproxy-kinds-of-proxy-objects.md now, and am still not totally sure which proxy type FakeItEasy uses when `T` is a class? Interface with target?

But things seem to work just the same without it, so thanks for pointing that out! :)

> I don't know that I have any other advice than "avoid doing that".

I will do that then! :D

>

**Comment by thomaslevesque** [comment]
> still not totally sure which proxy type FakeItEasy uses when `T` is a class? Interface with target?

It's always a class proxy.

https://github.com/FakeItEasy/FakeItEasy/blob/master/src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs#L41
https://github.com/FakeItEasy/FakeItEasy/blob/master/src/FakeItEasy/Creation/CastleDynamicProxy/CastleDynamicProxyGenerator.cs#L97

You shouldn't need to worry about it, though...

**Comment by asgerhallas** [comment]
> You shouldn't need to worry about it, though...

I just really like to know how things work...

How does it intercept non-virtual implementations of interface methods then? If you don't mind me asking? :)

**Comment by thomaslevesque** [comment]
I don't mind at all! But I'm not sure I understand the question... do you mean this?

```csharp
var fake = A.Fake<IWrappee>(x => x.Wrapping(new Wrappee());
```

Non-virtual methods can't be intercepted. In this scenario, by default the fake's `GetAll()` method will call the wrapped object's `GetAll()` method, but you can configure it explicitly to do something else.

**Comment by asgerhallas** [comment]
Thanks! 

The above answers (and my own faulty testing) got me believing that the code below would work, because Wrappee implements the interface:

```
    var fake = A.Fake<Wrappee>();

    A.CallTo(() => ((IWrappee)fake).GetAll()).Returns(new object[] {1});

    ((IWrappee)fake).GetAll().Single().ShouldBe(1);
```

But it only works, if I explicitly use Implements:

`var fake = A.Fake<Wrappee>(x => x.Implements<IWrappee>());`

I am aware that I use this kind of backwards. My goal was to let the fake be of the same type as the wrapped type, and still give allow faking the interface methods, when explicitly cast. 

I admit, I might end up confusing my coworkers more than I help them though, so now it's just curiosity :)

I guess my question can be restated as, why does a fake not automatically implement all the interfaces implemented by the faked class? (I guess there's good reason for this, and I can of course just do manually, or by reflection, if I wanted to).

**Comment by blairconrad** [comment]
> why does a fake not automatically implement all the interfaces implemented by the faked class

We tried it once. It broke the world!

See #876.

**Comment by thomaslevesque** [comment]
> why does a fake not automatically implement all the interfaces implemented by the faked class?

Well, the concrete class already implements the interface. But the implementation is non-virtual, so you can't configure it. Adding `Implements<T>` causes the fake to explicitly implement the interface, which effectively "unlinks" the concrete class's method from the interface (i.e. the method is still there, but it's no longer registered as the implementation for the interface). Instead, the interface implementation is done by the fake, so you can configure it.

Anyway, I'd be very careful with this approach if I were you. It will probably be very confusing to your coworkers, as you mentioned, and probably also to you when you look at it a few months from now. In this scenario, I'd just make the method virtual in the concrete class.

> My goal was to let the fake be of the same type as the wrapped type

If this is necessary, it looks like a code smell...

**Comment by asgerhallas** [comment]
> If this is necessary, it looks like a code smell...

Not exactly necessary, just somewhat convenient in this _very particular_ case :)

Thanks both of you for your explanations!
