### ISSUE TITLE
AutoFixture.AutoFakeItEasy broken with FakeItEasy 5.4.1, 5.50

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1736]
I was preparing to test AutoFixture.AutoFakeItEasy with an early FakeItEasy 6.0.0 candidate, and found that many of the unit tests broke with output like

```
X AutoFixture.AutoFakeItEasy.UnitTest.FixtureIntegrationTest.WithConfigureMembers_GetOnlyPropertiesReturnValueFromFixture [6ms]
  Error Message:
   System.MissingMethodException : Method SetReturnValue cannot be found on FakeItEasy.Creation.CastleDynamicProxy.CastleInvocationCallAdapter
  Stack Trace:
     at AutoFixture.AutoFakeItEasy.FakeObjectCall.InvokeWrappedMethod(String methodName, Object[] parameters) in D:\Sandbox\AutoFixture\src\AutoFakeItEasy\FakeObjectCall.cs:line 60
   at AutoFixture.AutoFakeItEasy.MethodCallResult.ApplyToCall(FakeObjectCall fakeObjectCall) in D:\Sandbox\AutoFixture\src\AutoFakeItEasy\MethodCallResult.cs:line 18
   at FakeItEasy.Core.FakeManager.ApplyBestRule(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 268
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(InterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 167
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy_19.get_GetOnlyProperty()
   at AutoFixture.AutoFakeItEasy.UnitTest.FixtureIntegrationTest.WithConfigureMembers_GetOnlyPropertiesReturnValueFromFixture() in D:\Sandbox\AutoFixture\src\AutoFakeItEasyUnitTest\FixtureIntegrationTest.cs:line 266
```

We'd removed the `SetReturnValue` member in 5.4.1 as part of #1697, leaving only the explicitly-implemented interface member.

Not technically a bug _in_ FakeItEasy, but I'm going to mark it like so anyhow, because I am not sure what other category to apply.

**Comment by blairconrad** [comment]
I can think of two solutions, both of which I've implemented and could have PRs out in a trice.

1. restore the member in FakeItEasy. It's not harmful, and will have no effect on the average FIE user. If we do this, then all recent AutoFixture.AutoFakeItEasys will work with all FakeItEasys but 5.4.1 and 5.5.0 (and I'd propose releasing 5.5.1 immediately), or
2. work around the problem in `FakedObjectCall`. This would mean that recent AutoFixture.AutoFakeItEasys will work with all FakeItEasys <= 5.4.0 and the next AutoFakeItEasy released would work with all FakeItEasys. Obviously we have no control over the timing of an AutoFixture.AutoFakeItEasy release.

To me, option 1 makes the most sense. The only downside is an unattractive internal member we have to keep around for a while. But if you really prefer 2, we can pursue it from that direction.

**Comment by blairconrad** [comment]
There's a PR in case we want to handle in-house. I'd still probably create an issue for AutoFixture.AutoFakeItEasy just so they have a record…

**Comment by thomaslevesque** [comment]
> Not technically a bug _in_ FakeItEasy

Definitely not a bug in FakeItEasy... the class is internal, and it still implements the same interfaces. Whether the implementation is explicit or implicit has no effect on the public API. The way I see it, it's a bug in AutoFakeItEasy. They shouldn't depend on anything that's not public.

> * restore the member in FakeItEasy. It's not harmful, and will have no effect on the average FIE user. If we do this, then all recent AutoFixture.AutoFakeItEasys will work with all FakeItEasys but 5.4.1 and 5.5.0 (and I'd propose releasing 5.5.1 immediately), or

Honestly, I'm very uneasy about going down that road. Sure, it'll help AutoFakeItEasy in the short run, but if we start avoiding making changes to internal APIs to avoid breaking someone else, where does it stop? Soon we won't be able to change anything at all in case someone relies on some undocumented internal implementation detail. The whole point (well, a big part of it anyway) of having something internal is so that we can freely change it without breaking users.

> * work around the problem in `FakedObjectCall`. This would mean that recent AutoFixture.AutoFakeItEasys will work with all FakeItEasys <= 5.4.0 and the next AutoFakeItEasy released would work with all FakeItEasys. Obviously we have no control over the timing of an AutoFixture.AutoFakeItEasy release.

I think this is the right solution. In fact, I don't see any good reason why they don't call the methods though the interface in the first place. And everywhere they create a `FakeObjectCall`, they actually pass a `IInterceptedFakeObjectCall`, so they can definitely access the methods they need.

**Comment by thomaslevesque** [comment]
Another reason why I'm opposed to it (well, rather another aspect of the reasons I already mentioned) is that we'll have to keep in mind to not remove this method, even though we don't actually need it. Sure, you put a comment about this in your PR. But every time I'll see this comment, I'll think, "oh no, we let someone depends on internal details, and now we're stuck with it", and I'll feel frustrated.

**Comment by blairconrad** [comment]
Thanks for the response, @thomaslevesque. The history is fairly complicated, in that they started out referring to public members that we moved away. We had a desire to keep their packages working, but you're right; there has to be a limit. If people want to use modern FakeItEasys with AutoFakeItEasy, then having to upgrade is not unreasonable. I'll pursue on the AutofFakeItEasy side.
