### ISSUE TITLE
Faked method taking IDictionary<,> as argument should accept Dictionary<,>

### ISSUE THREAD

**Issue by vegar** [FakeItEasy/FakeItEasy#1758]
I'm mocking a interface that uses interfaces in it's argument list

```
  interface IBus {
    Task Send(object commandMessage, IDictionary<string, string> optionalHeaders = null);  
  }
}

```
At runtime this method is called with an actual dictionary. This results in the following exception being thrown:

```
System.AggregateException: One or more errors occurred. 
   (The faked method has the signature (System.Object, System.Collections.Generic.IDictionary`2[System.String,System.String]), 
   but invokes was used with (System.Object, System.Collections.Generic.Dictionary`2[System.String,System.String]).)
   ---> FakeItEasy.Configuration.FakeConfigurationException: 
    The faked method has the signature (System.Object, System.Collections.Generic.IDictionary`2[System.String,System.String]), 
    but invokes was used with (System.Object, System.Collections.Generic.Dictionary`2[System.String,System.String]).
   at FakeItEasy.ValueProducerSignatureHelper.AssertThatValueProducerSignatureSatisfiesCallSignature(MethodInfo callMethod, MethodInfo valueProducerMethod, String nameOfFeature) in C:\projects\fakeiteasy\src\FakeItEasy\ValueProducerSignatureHelper.cs:line 22
```

How can I make a fake accept this kind of calls?

**Comment by thomaslevesque** [comment]
Hi @vegar,

This code works fine for me:

```csharp
    var bus = A.Fake<IBus>();
    await bus.Send(new object(), new Dictionary<string, string>());
```
So the method does accept a `Dictionary<string, string>`, as expected.

Could you please show how you configured the method? I suspect you did something like this:

```csharp
A.CallTo(() => bus.Send(A<object>._, A<IDictionary<string, string>>._))
  .Invokes((object commandMessage, Dictionary<string, string> optionalHeaders) =>
  {
      ...
  });
```

What you actually pass at runtime doesn't matter (as long as it's a compatible type), but the delegate passed to `Invokes` has to match the method signature exactly, so the second parameter should be `IDictionary`, not `Dictionary`.

**Comment by vegar** [comment]
To be honest, I haven't configured the call at all. I've only asked for a fake `IBus` and rely totally on the default proxy.

**Comment by thomaslevesque** [comment]
Can you show your code then? How does it differ from the working snippet I showed above?
The error message clearly indicates that `Invokes` was used, so the call must have been configured somewhere.

**Comment by vegar** [comment]
Sorry. I'm wasting your time here. 
Of cause you are right. There was a call-setup with an invoke hidden in the test setup, and of cause it was using `Dictionary` instead of `IDictionary`.

**Comment by thomaslevesque** [comment]
Always glad to help!
