### ISSUE TITLE
ClearConfiguration on a strict Fake removes its strictness

### ISSUE THREAD

**Issue by PiotrKlecha** [FakeItEasy/FakeItEasy#1764]
Clearing configuration of a strict Fake removes its "strictness", i.e. it will no longer throw exceptions on unconfigured methods. This seems to be a bug, since Strict is a part of a Fake creation options. It cannot be added to an existing Fake, so it also shouldn't be deleted even if other configured rules are cleared.

The following test fails:
```c#
public interface IInterface
{
	void Method();
}

[Test]
public void ClearStrict()
{
	var i = A.Fake<IInterface>(o => o.Strict());

	Fake.ClearConfiguration(i);

	Assert.That(() => i.Method(), Throws.Exception);
}
```

**Comment by blairconrad** [comment]
Hi, @PiotrKlecha. Thanks for your interest. I like your nice short reproduction!

I'd say that this is not something we'd considered when `Strict` and `ClearConfiguration` were implemented. And we're not entirely sure how we think it should be handled it. While we mull it over, let me suggest a workaround (which to me is the preferred way of working) that might be applicable to your situation, in case you find yourself stuck by this behaviour:

Don't use `ClearConfiguration`. If it's at all possible, just throw away the Fake and make a new one.

If this isn't feasible, would you mind explaining why? I rarely use `Strict` and have never in my life used `ClearConfiguration`, so I'm genuinely curious to see how it's used in the wild.

**Comment by PiotrKlecha** [comment]
Hi, @blairconrad, thank you for your reply.

My case is a rather non-standard one, so it probably won't be the best example, but I have a structure that represents a tree of nodes and use Fakes to simulate this structure in tests. I wanted to reset Fakes when nodes are added or removed to make sure some previously configured paths between nodes are also reset. Creating an new Fake instead of a reset is not possible right now, because other nodes still reference the old instance, although this is might be due to a flaw in the current design. I'm not really stuck however, since overwriting exisiting configuration works fine so far, it just seemed more natural and reliable to clear the whole configuration.

Another case that comes to my mind would be clearing a collection of Fakes, which creation options are different or unknown at the point of reset, so it would be much easier to use ClearConfiguration than to create new Fakes. However, this is just theory, I never needed to do something like this.

**Comment by blairconrad** [comment]
> My case is a rather non-standard one, so it probably won't be the best example

Au contraire! We need the non-standard cases. If it were only for the standard ones, we wouldn't even have the feature to be talking about it.

It's hard to assess without more context, I guess. From your description of a tree whose nodes had been removed, I was surprised that other nodes still have references to those nodes. Without the bigger picture, I think it's going to be hard to comment on your particular situation. I'm beginning to get a "maybe Fakes aren't the best tool for these tests" vibe, but I could easily be wrong. I'd be more than happy to take a deeper look, if you like, in public or out of public, as pleases you.

In the second scenario you mention, with a collection of Fakes that have different (potentially unknown) creation options, I worry about a test working on faked collaborators that it doesn't understand. There may be a use, but I'm made uneasy.

@thomaslevesque and I discussed this issue a little in the background, and it would certainly be possible to retain the strict-making configuration when clearing the configuration on a Fake, but there are a number of complications to consider

1. it's technically a breaking change. Maybe people are relying on the fact that strictness is stripped by `ClearConfiguration`
2. how should other creation options be treated? For example options to
    * configure all of a Fake's methods to use their original implementation
    * have a Fake wrap another object
    * name the Fake (actually this is currently preserved in the face of `ClearConfiguration`)

    Of these, only the first two can be applied after creation, and then by doing some work by hand (incidentally, it would be comparable to hand-configuring a Fake to be "strict", which is possible, just tedious)
3. [implicit creation options](https://fakeiteasy.readthedocs.io/en/stable/implicit-creation-options/) can be applied using the `options.ConfigureFake`. Should those also be preserved?

Personally, I think that implementing special handling to preserve any subset of these configuration options risks introducing more confusion than having a blanket "it will be as if you created a fresh new Fake". But I'm open to discussion.

**Comment by PiotrKlecha** [comment]
> > My case is a rather non-standard one, so it probably won't be the best example
> 
> Au contraire! We need the non-standard cases. If it were only for the standard ones, we wouldn't even have the feature to be talking about it.
> 
> It's hard to assess without more context, I guess. From your description of a tree whose nodes had been removed, I was surprised that other nodes still have references to those nodes. Without the bigger picture, I think it's going to be hard to comment on your particular situation. I'm beginning to get a "maybe Fakes aren't the best tool for these tests" vibe, but I could easily be wrong. I'd be more than happy to take a deeper look, if you like, in public or out of public, as pleases you.

I know that my description was very general, but the actual implementation is unfortunately quite complicated and I'm afraid that sharing these particular details wouldn't be very helpful regarding the desired behaviour of `ClearConfiguration`. My intention, however, was to restore an existing Fake to the state it was in right after creation, so an approach in fact similar to the suggested workaround. Perhaps with some design changes it could work this way.

> In the second scenario you mention, with a collection of Fakes that have different (potentially unknown) creation options, I worry about a test working on faked collaborators that it doesn't understand. There may be a use, but I'm made uneasy.
> 
> @thomaslevesque and I discussed this issue a little in the background, and it would certainly be possible to retain the strict-making configuration when clearing the configuration on a Fake, but there are a number of complications to consider
> 
> 1. it's technically a breaking change. Maybe people are relying on the fact that strictness is stripped by `ClearConfiguration`
> 2. how should other creation options be treated? For example options to
>    
>    * configure all of a Fake's methods to use their original implementation
>    * have a Fake wrap another object
>    * name the Fake (actually this is currently preserved in the face of `ClearConfiguration`)
>    
>    Of these, only the first two can be applied after creation, and then by doing some work by hand (incidentally, it would be comparable to hand-configuring a Fake to be "strict", which is possible, just tedious)
> 3. [implicit creation options](https://fakeiteasy.readthedocs.io/en/stable/implicit-creation-options/) can be applied using the `options.ConfigureFake`. Should those also be preserved?
> 
> Personally, I think that implementing special handling to preserve any subset of these configuration options risks introducing more confusion than having a blanket "it will be as if you created a fresh new Fake". But I'm open to discussion.

I'd say that options that can only be specified during Fake creation (like Strict, Named) should persist after `ClearConfiguration`, but I agree that doing the same for other mentioned options could be unexpected and confusing and would probably make it a very troublesome breaking change.

Perhaps the solution would be to introduce a new method (`RestoreConfiguration` ?) that would remove all rules defined after the Fake was created while leaving those applied during creation intact?

**Comment by PiotrKlecha** [comment]
This discussion encouraged me to take another look at my implementation and it indeed turned out to be flawed. I managed to modify it in a way that requires Fakes to be configured only once after creation, so resetting their configuration is no longer necessary at all.

Although I don't need changes in the way clearing configuration works right now, I think it could still be useful to add a consistent way to restore a Fake's state (like the one I described in previous comment).

**Comment by thomaslevesque** [comment]
Thanks for the feedback @PiotrKlecha! I'm glad you were able to resolve your problem.

We need to think a bit more about `ClearConfiguration`. We might remove it in a future version, or replace it with something that has a more clearly defined behavior.

**Comment by blairconrad** [comment]
@thomaslevesque  and I chatted and are leaning toward removing `ClearConfiguration` rather than trying to adjust it to work with the several kinds of configuration options we have (which may be applied at different times).
