### ISSUE TITLE
Explicitly allowing default property behaviour on a strict Fake

### ISSUE THREAD

**Issue by PiotrKlecha** [FakeItEasy/FakeItEasy#1766]
The default read/write behaviour of a faked property is very useful, however, it seems that there is no way to allow it on a strict Fake by explicitly calling any available configuration method.

A solution could be adding a generalization of the `DoesNothing` method (`UsesDefaultBehaviour` ?), so allowed calls could be configured like this:
```c#
var i = A.Fake<IInterface>(o => o.Strict());

A.CallTo(() => i.Property)
	.UsesDefaultBehaviour();
A.CallToSet(() => i.Property)
	.UsesDefaultBehaviour();
```

It would be even more convenient if a dedicated method wrapping both getter and setter was also added:
```c#
var i = A.Fake<IInterface>(o => o.Strict());

A.CallToProperty(() => i.Property)
	.UsesDefaultBehaviour();
```

**Comment by thomaslevesque** [comment]
Hi @PiotrKlecha,

That's an interesting idea. I suspect it wouldn't be trivial to implement in the current architecture, though...

As a workaround, you can easily mimick the default property behavior with a method like this:

```
static void ConfigureDefaultPropertyBehavior<TProperty>(Expression<Func<TProperty>> propertySelector)
{
    TProperty currentValue = default;
    A.CallTo(propertySelector).ReturnsLazily(() => currentValue);
    A.CallToSet(propertySelector).Invokes((TProperty value) => currentValue = value);
}

...

ConfigureDefaultPropertyBehavior(() => myFake.MyProperty);
```

**Comment by blairconrad** [comment]
@thomaslevesque, your solution is not quite the default behaviour, as you return `default` by, um... default. To more closely emulate the default, you'd want to return a Dummy. Otherwise it's quite clever.

**Comment by PiotrKlecha** [comment]
Hi @thomaslevesque,

Thank you for your reply, I used a similar workaround, but this generic version is even better. I'm fine with this solution for now, although I'd still prefer to use a consistent syntax (A.CallTo...). Perhaps it will be possible to implement it in the future.

@blairconrad Thank you for pointing out the detail about the default.

**Comment by thomaslevesque** [comment]
> @thomaslevesque, your solution is not quite the default behaviour, as you return `default` by, um... default. To more closely emulate the default, you'd want to return a Dummy.

Good point! `A.Dummy<TProperty>()` instead of `default`, then.
(the real default behavior is that the dummy is created lazily, but it probably doesn't matter too much)

> I am not at a compiler, but maybe

That would return a different dummy every time, unless the setter is called

**Comment by blairconrad** [comment]
> That would return a different dummy every time, unless the setter is called

True. :blush: It also doesn't handle the case where no Dummy can be made (when we'd normally return `default`).

**Comment by blairconrad** [comment]
I appreciate the occasional usefulness of a method for configuring properties in this way, I'm not sure it's a common enough use case to pollute `A`. One could argue, I suppose, that it be hidden within the strict creation options, and I think this is possible, but I'm still not sold. I guess the operation could also be useful when creating a Fake that CallsBaseMethods or Wraps another object. On the other hand, in those cases, calling this method to make the property do "the expected thing" is probably superfluous, as the base/wrapped object likely already just stores and returns the value.

I know everyone works differently, and I keep saying this, but I can't shake the feeling that if there's a Fake that's strict, except for this method and that property and so on that it's just better represented by a non-strict Fake combined with asserts at the end of the test, to ensure that the forbidden member(s) weren't called. In most cases (I have no evidence for this), I bet the forbidden members are fewer than the allowed ones.

**Comment by thomaslevesque** [comment]
> I'm not sure it's a common enough use case to pollute `A`.

👍

**Comment by PiotrKlecha** [comment]
I admit that this is a rare case and probably doesn't justify extending `A`, but I think that it would still be useful to add a uniform way of configuring an expression to use its default behaviour. Consider the following example:
```c#
public interface IDependency
{
	void Method();
}

[Test]
public void TestDependency()
{
	var dependency = A.Fake<IDependency>();

	var testedObject = new TestClass(dependency);

	A.CallTo(() => dependency.Method())
		.Throws<Exception>();

	// Assert behaviour when dependency throws

	A.CallTo(() => dependency.Method())
		.DoesNothing();

	// Assert behaviour when dependency no longer throws
}
```

This is fine as long as the method has a void return type, because `DoesNothing` is the same as a faked method default behaviour. If the method had a non-void return type, restoring its default behaviour would require to configure it as returning a `Dummy`, which would probably also be fine. However, it would not be possible to restore a property getter or setter, because doing nothing or returning a fixed value is not what they do by default. Adding a new method (`UsesDefaultBehaviour` ?) would allow to restore any expression in the same way and also configure properties of strict Fakes.

**Comment by blairconrad** [comment]
@PiotrKlecha, the example looks a little odd to me, as I don't usually see assertions between exercising the `testedObject`, but it seems to me what you're trying to accomplish could be done by

```c#
            A.CallTo(() => dependency.Method())
                .Throws<Exception>().Once();
```

(Or if you don't want strictly `Once`, there are a number of other mechanisms for [changing behaviour between calls](https://fakeiteasy.readthedocs.io/en/stable/changing-behavior-between-calls/).)

In this way, it's possible to have a Fake revert to earlier-defined (even "default") behaviour.

**Comment by thomaslevesque** [comment]
I was going to suggest the same thing

**Comment by PiotrKlecha** [comment]
@blairconrad, it's possible to revert to default behaviour using limited call specifications in most cases, however it's not always obvious when a methods' behaviour actually changes and the way I suggested allows to specify that point precisely.

**Comment by blairconrad** [comment]
@PiotrKlecha, I don't really understand how you wouldn't know when to change a method's behaviour, since you would know if you are making a call to change the behaviour between test phases. 

It's a bit of an abuse, but worst case, you could check a flag inside a `WhenArgumentsMatch` matcher (https://fakeiteasy.readthedocs.io/en/stable/argument-constraints/#overriding-argument-matchers)

```c#
A.CallTo(() => fake.Bar)
    .WhenArgumentsMatch(args => shouldStillDoNonStandardBehaviour)
    .Throws<Exception>();
```

And then flip the flag when you want the behaviour to revert.

Regardless, I think this still seems like a very very edge case, and making use of the existing tools is a better solution than adding such a niche operation to the main library.

**Comment by PiotrKlecha** [comment]
@blairconrad, I meant that a test using a limited call specifier like `Once` is more likely to fail in an unexpected way if the production code changes and calls the configured method a different number of times. Or it may not detect that additional calls are not properly caught, because they will not throw exceptions at all.

The suggested 'abuse' actually seems to be quite reasonable. Too bad it won't help with strict Fake property configuration :disappointed:
