### ISSUE TITLE
Versioning seems to be wrong

### ISSUE THREAD

**Issue by laurentkempe** [FakeItEasy/FakeItEasy#1779]
I am trying to use FakeItEasy 6.0.1.0 and 6.1.0.0 with Autofac and its integration Autofac.Extras.FakeItEasy.

I am using .NET Framework 4.7.2 and after adding assembly binding I keep getting issues.
After digging the problem, it seems to be related to FakeItEasy and it's version which are not aligned as you can see on this picture:
![image](https://user-images.githubusercontent.com/272612/84146687-5e0f5e00-aa5c-11ea-89f9-7a84a591ce91.png)
I would expect all versions to show 6.1.0.0.

What we tried with @martinskuta is to use FakeItEasy 6.0.0.0 and then with that one the integration with Autofac and Autofac.Extras.FakeItEasy.works with binding redirect. This is why we think that the way the version is done in FakeItEasy is creating the problem.

**Comment by thomaslevesque** [comment]
Hi @laurentkempe,

Yes, the assembly version doesn't match the file and product version. This is done on purpose to avoid assembly binding issues. Basically, for FakeItEasy 6.x, the assembly version will always be 6.0.0.0.

Many packages do it this way now, including packages from Microsoft. See https://github.com/FakeItEasy/FakeItEasy/issues/1209 for details.

**Comment by thomaslevesque** [comment]
This isn't new, by the way. This change was introduced in [FakeItEasy 4.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.1.0)

**Comment by blairconrad** [comment]
@laurentkempe, I may be a little slow today, but can you explain more deeply what problem you encountered? What were you trying to do? How? How did it not work as you expected?

**Comment by laurentkempe** [comment]
Merci @thomaslevesque for the explanation! I will read more in details to get a better understanding of this way of doing, which is new to me.

@blairconrad we just recently successfully migrated from RhinoMock to FakeItEasy. Now, we are looking to migrate our IoC framework which is StructureMap to something else. I tried with Lamar which should be a straight replacement but it was not. So, I am trying now with Autofac and also Autofac.Extras.FakeItEasy. Currently, we are using a custom built thing called AutoMocker, which is the equivalent of Autofac.Extras.FakeItEasy. The basic idea is that when you test a class, you can use concrete or fake for some dependencies, and the one you are not, are automatically created as fakes.
So, I just tried to delegate our AutoMocker to Autofac.Extras.FakeItEasy which was quite easy till I tried to run it and got runtime exceptions which I could solve for one of our testing assembly with an app.config and assembly binding redirect.

    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FakeItEasy" publicKeyToken="eff28e2146d5fd2c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.1.0" newVersion="6.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>

Then I started with the next test assembly, which reference another test assembly with our AutoMocker and started to see one of the weirdest thing I ever seen on the .NET platform

	System.IO.FileLoadException : Could not load file or assembly 'FakeItEasy, Version=6.0.1.0, Culture=neutral, PublicKeyToken=eff28e2146d5fd2c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	----> System.IO.FileLoadException : Could not load file or assembly 'FakeItEasy, Version=6.0.0.0, Culture=neutral, PublicKeyToken=eff28e2146d5fd2c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

After 🤯 I paired with @martinskuta and we realized that when we use FakeItEasy 6.0.0.0 it works, but when we want to update it to 6.0.1.0 or 6.1.0.0 all starts to break. So digging deeper we have seen the version difference using dotPeek and we think that's the main issue. Then we tried to reference version 6.0.0.0 but still provide as assembly the file from 6.0.1.0 or 6.1.0.0 and it works!

**Comment by laurentkempe** [comment]
It seems that Autofac is not following the way of versioning that you use with FakeItEasy!
While looking at https://github.com/autofac/Autofac.Extras.FakeItEasy/releases/tag/v6.0.0 to me it is weird that they reference such an old version of FakeItEasy 3.4.1. The issue might come from this no?

**Comment by thomaslevesque** [comment]
Ah, I see. Yes, they reference an old version, because they don't want to force their users to upgrade to the latest version of FakeItEasy.

What happens if you add a binding redirect like this?

```xml
<bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
```

**Comment by laurentkempe** [comment]
> Ah, I see. Yes, they reference an old version, because they don't want to force their users to upgrade to the latest version of FakeItEasy.

Yeah I thought exactly the same.

With this binding redirect it works 🎉 

But you have to explain me why it doesn't work with 

```xml
<bindingRedirect oldVersion="0.0.0.0-6.1.0.0" newVersion="6.1.0.0" />
```

**Comment by thomaslevesque** [comment]
> With this binding redirect it works 🎉

Glad it solved the problem!



> But you have to explain me why it doesn't work with
> 
> ```
> <bindingRedirect oldVersion="0.0.0.0-6.1.0.0" newVersion="6.1.0.0" />
> ```

Because there isn't a 6.1.0.0 version of the FakeItEasy assembly. The version is always 6.0.0.0.

**Comment by laurentkempe** [comment]
OMG 🤯 I finally ticked on this!

Thanks @thomaslevesque for your great help!
