### ISSUE TITLE
Using FakeItEasy in a Azure DevOps Pipeline 

### ISSUE THREAD

**Issue by timberzen** [FakeItEasy/FakeItEasy#1780]
Hi 
Can I run Fake It Easy mocks in an Azure Pipeline.
I currently have a mix of MSTest and TypeMock unit tests.
Its possible to run a modified version on Typemock unit test on Azure using the MSTest runner.
But the additional cost of a TypeMock Lic for azure is quite high compared to running FakeItEasy on Azure. 
So can you use thethe MSTest runner to run FakeItEasy tests in azure?
If so, what is the YAML to add or is there something in the Azure market place to add or can I just leave it in the MSUnit test code base and run it unaltered?
Thanks in Advance
Doug

**Comment by blairconrad** [comment]
HI, @timberzen. I don't see why not. It's just a library, with no particular restrictions on usage. I've heard some rumours about things not going well if you're running in a low-trust environment, but that likely doesn't apply. I run builds that use FakeItEasy in the tests [on an Azure Pipeline](https://dev.azure.com/blairconrad/SendComics/_build/results?buildId=40&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5), and don't have any problems. Give it a go!

**Comment by thomaslevesque** [comment]
@blairconrad said it all. There's nothing special about Azure DevOps as far as FakeItEasy is concerned. FakeItEasy is completely agnostic to the environment it's running in, as long as it runs .NET...

**Comment by blairconrad** [comment]
I believe this question has been abandoned. Closing.

**Comment by timberzen** [comment]
thanks
