### ISSUE TITLE
DoesNothing(); not available

### ISSUE THREAD

**Issue by ejwoerlee** [FakeItEasy/FakeItEasy#1781]
When I try to use the DoesNothing on a fake, this functionality is not available. 
Using FakeItEasy v6.1.0/Autofac.Extra.FakeitEasy v6.0.0

A.CallTo(() => aFake.SomeMethodThatShouldDoNothing()) **.DoesNothing();**

** DoesNothing() ** doesn't show up in intellisense

A.CallTo(() => aFake.SomeMethodThatShouldDoNothing()) **.Throws<Exception>();** works fine

**Comment by thomaslevesque** [comment]
Hi @ejwoerlee,

What's the return type of `SomeMethodThatShouldDoNothing`?

`DoesNothing` only applies to `void` methods. It doesn't really make sense for non-void methods, because you need to configure a return value. So you can do something like this instead:

```csharp
A.CallTo(() => aFake.SomeMethodThatShouldDoNothing()).Returns(default)
```

**Comment by ejwoerlee** [comment]
This is the function I want to return nothing in a fake:

`public async Task ConnectAsync(string host, int port)
 {
     await TcpClient.ConnectAsync(host, port); 
 }`
and
`public NetworkStream GetStream()
        {
            if (tcpClient == null)
            {
                throw new ArgumentNullException(nameof(tcpClient));
            }

            return TcpClient.GetStream();
        }`

**Comment by blairconrad** [comment]
Thanks, @ejwoerlee. As @thomaslevesque  noted, `DoesNothing` is only available when configuring `void` methods. Neither of these methods are `void`. In this case, you need to supply a return value via `.Returns` (or an action like throws).

Just to make sure we're not getting ahead of ourselves though, why do you feel a need to specify `DoesNothing`? Have you previously configured these methods to do something and you don't want them to anymore? Or is the Fake strict?

If neither applies, the default behaviour for a faked method will be to return a default value and not perform any other side effect.

**However**, I am compelled to note that in your definitions above, these methods are not marked either `virtual` or `abstract`, so FakeItEasy [will not be able to intercept them at all](https://fakeiteasy.readthedocs.io/en/stable/what-can-be-faked/#what-members-can-be-overridden). The class's production behaviour will always apply.

**Comment by thomaslevesque** [comment]
I think the API might be missing something. `Task` is the async equivalent of `void`, so it's a bit strange that we have `DoesNothing` for methods that return `void`, but not for methods that return `Task`. Maybe we should add one...

**Comment by blairconrad** [comment]
Ugh. I see your point. Technically it's not a `void`-returning method, but logically it is one.
Internally this would be a huge pain to change.

**Comment by ejwoerlee** [comment]
@thomaslevesque @blairconrad Thanks for the reaction(s). 
The two methods interface methods of an interface that is being faked. 
I wanted to override the functionality as not to connect to a Tcp client. 
In case of the method that returns a NetworkStream I think even the default
return value is not usable. I think I have to refactor that part to use an Adapater.

**Comment by thomaslevesque** [comment]
> I wanted to override the functionality as not to connect to a Tcp client.

If the methods are on an interface, and you fake that interface, it will definitely not connect to a TCP Client.

For `GetStream`, you could change it to return `Stream` instead of `NetworkStream`. By default, it will return a fake stream, which probably won't be usable, but you can configure it to return `Stream.Null` (an empty stream where everything you write is ignored), or a `MemoryStream` that you control.

**Comment by ejwoerlee** [comment]
Maybe I'm missing something misunderstand, 
I have this Interface:
`public interface ITcpClientAdapterBO
    {
        bool Connected { get; }
        
        Task ConnectAsync(string host, int port);

        void Close();

        NetworkStream GetStream();
    }` 
and a class implementing the interface:

`public class TcpClientAdapterBO : ITcpClientAdapterBO
    {
        private TcpClient tcpClient = null;

        private TcpClient TcpClient { get => tcpClient ?? (tcpClient = new TcpClient());
                                      set => tcpClient = value; }

        public TcpClientAdapterBO()
        {            
        }

        public bool Connected => TcpClient.Connected;

        public void Close()
        {
            TcpClient.Close(); // Close() => disposes tcpClient object
            TcpClient = null;  // Disposed 
        }

        public async Task ConnectAsync(string host, int port)
        {
            await TcpClient.ConnectAsync(host, port);
        }

        public NetworkStream GetStream()
        {
            if (tcpClient == null)
            {
                throw new ArgumentNullException(nameof(tcpClient));
            }

            return TcpClient.GetStream();
        }
    }
`
and configured this unit test:

`[Test]
        public async Task StartPrintAsync_Success()
        {
            using (var fake = new AutoFake())
            {
                // Arrange - configure the fake                  
                string ipAddress = "127.0.0.1";
                string zpl = "zpl";
                **ITcpClientAdapterBO fakeTcpClientAdapterBO = A.Fake<ITcpClientAdapterBO>();**

                Socket socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
                socket.Connect(ipAddress, 80);
                                
                A.CallTo(() => fakeTcpClientAdapterBO.Connected).Returns(true);
                **A.CallTo(() => fakeTcpClientAdapterBO.GetStream()).Returns(new NetworkStream(socket));**               

                IBarCodePrintStrategyBO sut = fake.Resolve<BarCodeZebraPrintBO>(
                   new Autofac.NamedParameter("tcpClientAdapter", fakeTcpClientAdapterBO));
                 
                // Act                              
                bool result = await sut.StartPrint(ipAddress, zpl);
                socket.Shutdown(SocketShutdown.Both);
                socket.Close();

                // Assert - assert on the fake
                Assert.IsTrue(result);
            }
        }`
I should be able to replace A.CallTo(() => fakeTcpClientAdapterBO.GetStream()).Returns(new NetworkStream(socket));
by A.CallTo(() => fakeTcpClientAdapterBO.GetStream()).Returns(**Stream.Null)**);  ?

Because if I try this, I get : error CS1929: 'IReturnValueArgumentValidationConfiguration<NetworkStream>' does not contain a definition for 'Returns' and the best extension method overload 'ReturnValueConfigurationExtensions.Returns<Stream>(IReturnValueConfiguration<Task<Stream>>, Stream)' requires a receiver of type 'IReturnValueConfiguration<Task<Stream>>'

**Comment by thomaslevesque** [comment]
> I should be able to replace A.CallTo(() => fakeTcpClientAdapterBO.GetStream()).Returns(new NetworkStream(socket));
> by A.CallTo(() => fakeTcpClientAdapterBO.GetStream()).Returns(**Stream.Null)**); ?

Yes, *if* you change the signature of `GetStream` to return a `Stream` instead of a `NetworkStream`. Unless you actually need it to be a `NetworkStream`, but in my experience, it's pretty rare.

If you don't explicitly configure it, `GetStream` will do nothing and just return a fake `Stream`.

**Comment by ejwoerlee** [comment]
@thomaslevesque: thanks for the suggestion!
I **could** change the signature, and by using Stream.Null the unit tests now pass.

**Comment by blairconrad** [comment]
We're glad you're up and running @ejwoerlee. It sounds like this issue has been resolved, so I'll close it. 
If I'm wrong, we can always reopen.
Happy FakeItEasying!
