### ISSUE TITLE
Improve parameter matching and assignment for ref parameters

### ISSUE THREAD

**Issue by ipashchuk** [FakeItEasy/FakeItEasy#18]
In Rhino Mocks, there is a way to specify a dummy ref parameter like so:

``` csharp
ref Arg<string>.Ref(Rhino.Mocks.Constraints.Is.Equal(string.Empty), "New value").Dummy
```

While I generally dislike ref parameters (especially for unit test purposes), there is no way around legacy APIs or third-party code.

What do you think about this syntax:

``` csharp
ref A<string>.That.IsEqualTo(string.Empty).ChangesTo("New value").Dummy

// extension method signature
public static Dummy<T> ChangesTo<T>(this T value, T newValue);

// class
public class Dummy<T>
{
    public T Dummy;
}
```

This obviously is a draft and will require a bit of polishing...

**Comment by thomaslevesque** [comment]
Is there still interest in this issue?

The proposed API looks good enough, but I have a few other ideas:

- change `A<T>.That.Matches(...)` to return something like this:

    ```
    class ArgContraint<T>
    {
        // has to be a field to allow "ref A<string>.That.Matches(...).Value"
        public T Value;
        public static implicit operator T(ArgConstraint<T> constraint) => constraint.Value;
    }
    ```
    Usage:
    ```
    // Non-ref: syntax unchanged due to the implicit conversion
    A.CallTo(() => foo.Bar(A<string>.That.Matches(str => str == string.Empty)))...
    // Ref
    A.CallTo(() => foo.Bar(ref A<string>.That.Matches(str => str == string.Empty).Value))...
    ```
    The benefit is that the syntax for `ref` is almost the same (you just need to add `.Value`), but it would be a significant refactoring (and a breaking change).
- take advantage of the "ref return" feature in C# 7:
    ```
    A.CallTo(() => foo.Bar(ref A<string>.Ref.That.Matches(str => str == string.Empty)))...
    ```
    Note that we don't need the `.Value` here: `A<T>.Ref.That.Matches(...)` would return a `ref T`, not a `T`.
    IMO this would be the cleanest approach, however I'm not sure how that would work for client code that doesn't use C# 7.

All that being said, I'm not really convinced of the value of this feature. I can't think of a single time where I needed something like this.

**Comment by blairconrad** [comment]
> Is there still interest in this issue?

Not from me. Now I'm going to read the rest of your comment.

Your ideas have merit! But I'd still be as happy (happier) seeing this issue closed.

**Comment by thomaslevesque** [comment]
> however I'm not sure how that would work for client code that doesn't use C# 7.

I just tried, and it doesn't work: https://gist.github.com/thomaslevesque/03fc1985e720ebc8d435a85e76aa8719

I even got a compilation error that isn't documented anywhere (`error CS7085: By-reference return type 'ref int' is not supported.`)

**Comment by thomaslevesque** [comment]
(admittedly, this is not a big issue... it just mean this syntax could only be used by C# 7 code)

**Comment by StarWars999123** [comment]
So based on the current specflow release. What is the way to go for a check of ref values? 

I got a function `command(string a, ref int b,byte[] c)` and want to check, that a call with something like `A.CallTo(()=>object.command("MyString",35,A<byte[]>.That.Matches(a=>a.SequenceEquals(expectedValue)))).MustHaveHappened(Repeated.Exactly.Once);`

What can I do to check, that this function is called with a ref value of e.g. 35?

**Comment by blairconrad** [comment]
@StarWars999123, you need to supply a variable to pass into the expression. The value in the variable is used as the constraint. I would use

```c#
int b = 35;
A.CallTo(()=>object.command("MyString", ref b, A<byte[]>.That.IsSameSequenceAs(expectedValue))))
    .MustHaveHappened(Repeated.Exactly.Once);
```

**Comment by blairconrad** [comment]
@StarWars999123, I'm not sure what you meant by "the current **specflow** release". There's no connection between FakeItEasy and SpecFlow.
But the code in my previous comment should be good for any FakeItEasy 3.* release. And maybe earlier, although if you're on an old version, I encourage an upgrade.

**Comment by StarWars999123** [comment]
Sorry. I meant FakeItEasy.

**Comment by blairconrad** [comment]
Oh, well that makes sense, then.
And gives me even more hope that the sample works. :four_leaf_clover:

**Comment by StarWars999123** [comment]
Ok. Now I can handle it partially. But the value returned to the ref parameter by AssignsOutAndRefParameters() is the one, that is used for matching.

```
using NUnit.Framework;
using System;
using FakeItEasy;

namespace FakeItEasyRefParam
{
    public class Class1
    {
        [Test]
        public void myTest()
        {
    
            var b = 40;
            var cmdP = new CommandProcessor();
            var obj = A.Fake<MyClass>();
            cmdP.UseTarget(obj);
            A.CallTo(() => obj.command("", ref b, A<byte[]>._))
                     .WithAnyArguments()
                     .Returns(new byte[3]).AssignsOutAndRefParameters(25);
    
            cmdP.CallMyCommand();
    
            var expectedBForCall = 40; //cause its called with 40 in CallMyCommand()
            A.CallTo(() => obj.command("MyString", ref expectedBForCall, A<byte[]>._))
                    .MustHaveHappened(Repeated.Exactly.Once);//never found
        }
    }



    public class CommandProcessor
    {
        private MyClass target;
        public void UseTarget(MyClass pTarget)
        {
            target = pTarget;
        }

        public void CallMyCommand()
        {
            int b = 40;//gets calculated...

            //-> b is 40 !
            target.command("MyString", ref b, new byte[10]);

            //-> b is 25 !
            Console.WriteLine(b); //save the value
        }
    }

    public class MyClass
    {
        public virtual byte[] command(string s, ref int b, byte[] array)
        {
            return new byte[4];
        }
    }

}
```

This results in an ExpectationException. The last match can not be found. The call, that are logged, were only logged with the new value of 25. However, the call to the was made with 40!

**Comment by blairconrad** [comment]
@StarWars999123, I believe you've found a bug. `ApplyOutAndRefParametersValueProducer` is mutating our incoming call object before we build "recorded call" out of it.

I have to run out, but will create an issue sometime within the next day if nobody else has.

In the meantime, if you need to verify that the call happened, rather than trusting that it did based on other effects, you may be able to get some relief by applying a workaround similar to that in [MustHaveHappened fails when called twice on the same object](https://stackoverflow.com/questions/12846484/musthavehappened-fails-when-called-twice-on-the-same-object): use an `Invokes` to capture the argument and interrogate it later. Or to set a flag or similar.

**Comment by thomaslevesque** [comment]
Based on previous messages, I think we can close this issue. We can still re-open later if there's enough interest, and if we can come up with a good API.
