### ISSUE TITLE
Shortcut for "ignore all arguments" when using A.CallTo. Again after 5 years.

### ISSUE THREAD

**Issue by Jarek300** [FakeItEasy/FakeItEasy#1815]
[Edit by @blaiconrad: Previous issue (#287 - "Shortcut for "ignore all arguments" when using A.CallTo") from 2016 is not current available due to some GitHub server error)]

Maybe technology from 2021 allows to implement this? It would be great to replace 

```c#
A.CallTo(() => varDefDataReader.ReadVarDefItems(
                         A<string>.Ignored, A<VisibleVariables>.Ignored, A<List<VarDefTreeItem>>.Ignored, 
                         A<string>.Ignored, A<CancellationToken>.Ignored))
                .Returns(varDefItemsPage);

```
with

```c#
A.CallTo(() => varDefDataReader.ReadVarDefItems(A.AllIgnored).Returns(varDefItemsPage);
```

**Comment by blairconrad** [comment]
Hi, @Jarek300. Thanks for your interest. Can you tell me what shortcut you're talking about that's no longer available?

My Initial thought is that you're unlikely to ever be able to write the second call in your example, as the C# compiler will require that the arguments in the call match the method signature.

Note that for some small amount of character savings `.Ignored` can be spelled `._`. Another option is to use [WithAnyArguments](https://fakeiteasy.readthedocs.io/en/stable/argument-constraints/#overriding-argument-matchers):

```c#
A.CallTo(() => varDefDataReader.ReadVarDefItems(null, null, null, null, null).WithAnyArguments().Returns(varDefItemsPage);
```
Of course, you still have to provide the correct number of arguments, and with type-compatible values.

**Comment by Jarek300** [comment]
This issue:

![image](https://user-images.githubusercontent.com/10242002/105031983-6863f280-5a56-11eb-8089-ed6f24e8ffaa.png)

If you click it, there is github error 'Looks like something went wrong!'.

**Comment by Jarek300** [comment]
I'm using nullable reference types and can't use null as a parameter. The best solution seems to be add #nullable disable/enable section:

```
#nullable disable
A.CallTo(() => varDefDataReader.ReadVarDefItems(null, null, null, null, null).WithAnyArguments()
    .Returns(varDefItemsPage);
// other fakes
#nullable enable

```

And what do you think about this design?

`A.CallTo(varDefDataReader, "ReadVarDefItems").WithAnyArguments().Returns(varDefItemsPage);`

**Comment by blairconrad** [comment]
> And what do you think about this design?
>
> `A.CallTo(varDefDataReader, "ReadVarDefItems").WithAnyArguments().Returns(varDefItemsPage);`

Passing the fake as well as the name of the method? My first reaction is that I am wary of it. There are a few problems with it from a FakeItEasy API design perspective:
1. the string to specify the method name. It's too easy to not even get the name right, or to accidentally refer to a different method
2. related to "refer to a different method", if there are overloads of the method, the proposed solution would apply to all of them (I assume). This may not always be desired
3. FakeItEasy would not get signature/return type hints from the innards of the `A.CallTo`. It would just know (hope) that they referred to some method. It wouldn't know what the method's return type is (or even if it has one) so the API would not be able to provide a type-safe `.Returns`.

**Comment by blairconrad** [comment]
Sorry, @Jarek300. I've a mind like a sieve. I forgot to mention an alternative to your last suggestion:

```c#
A.CallTo(varDefDataReader)
    .Where(call => call.Method.Name == "ReadVarDefItems")
    .WithReturnType<VarDefItemsPage>()
    .Returns(varDefItemsPage))
```

already exists, approaches the syntax you suggested, and allows for a type-safe (with the provided hint) return value specification.

Given that this option exists, any replacement would have to be superior in at least one dimension before we added it to FakeItEasy.

Note that this overload of `A.CallTo` returns a `IAnyCallConfigurationWithNoReturnTypeSpecified`, so if you really wanted to shave some characters off, you could probably create your own extension method and end up with

`A.CallTo(varDefDataReader).ReadVarDefItems().Returns(varDefItemsPage))`

Or whatever variant you preferred.

**Comment by Jarek300** [comment]
Thanks for your answer! The last idea looks promising.

**Comment by blairconrad** [comment]
A pleasure, @Jarek300. I'm inclined to close this issue as wontfix, just like  #287 (which is back now, as I type), but if you prefer, we can keep it open for a bit in case you'd like to continue the conversation a little.

**Comment by thomaslevesque** [comment]
> Of course, you still have to provide the correct number of arguments, and with type-compatible values.

That's why I like to use `default` instead of `null`, because it works for any type.

> I'm using nullable reference types and can't use null as a parameter. The best solution seems to be add #nullable disable/enable section:

You can use `null!` or `default!`. That's usually not a good idea because it's literally saying "null is not null", but in this case I think it's OK, as it's just a placeholder.

**Comment by blairconrad** [comment]
Great `default`/`null!`/`default!` points, @thomaslevesque. I'm still not modern enough. I use these constructs in exactly one project...

**Comment by Jarek300** [comment]
Great idea,

```
A.CallTo(() => varDefDataReader.ReadVarDefItems(default!, default, default!, default!, default))
    .WithAnyArguments()
    .Returns(varDefItemsPage);
```

is much more readable for me than 

```
A.CallTo(() => varDefDataReader.ReadVarDefItems(
                         A<string>.Ignored, A<VisibleVariables>.Ignored, A<List<VarDefTreeItem>>.Ignored, 
                         A<string>.Ignored, A<CancellationToken>.Ignored))
                .Returns(varDefItemsPage);
```

**Comment by vdurante** [comment]
I have implemented the following:

```cs
public static partial class IWhereConfigurationExtensions
{
    public static TReturn WithMethod<TReturn>(this IWhereConfiguration<TReturn> configuration, string methodName)
    {
        return configuration.Where(call => call.Method.Name == methodName);
    }
}
```

And I use as follows:

```cs
A.CallTo(_permissionService)
    .WithMethod(nameof(_permissionService.ValidateAsync))
    .WithReturnType<Task<bool>>()
    .Returns(true);
```

It doens't have full intellisense, but it works

**Comment by blairconrad** [comment]
Nice, @vdurante. Seems like a reasonable approach for a project's collection of convenience utilities.

**Comment by Jarek300** [comment]
Thanks, I'll give it a try.
