### ISSUE TITLE
Is it possible to fake an object only once in the lifetime of a test (Singleton)?

### ISSUE THREAD

**Issue by LennardF1989** [FakeItEasy/FakeItEasy#1847]
Title might be a little vague, but what I'm trying to figure out is if it's possible to have two A.Fake<Foo>() calls to return the same faked object. 

I reckon I could use https://fakeiteasy.readthedocs.io/en/stable/implicit-creation-options/ - but that's going to be a one-of thing if I use a static (and not per-test).

My problem right now is that I have a service (CMS system) that uses dependency injection to resolve objects. The sane way would obviously be to wrap the service-calls into a separate object/interface, so you can mock it away. But simply put, it puts too much of a burden on the developers in that it's way to invasive on the codebase to do this for something that is supposed to be used as part of a CMS. Alas, sometimes I have to mock 3-4 dependencies of dependencies to get control over 1 single dependency. This is not un-doable, it just makes testing annoying. If it's possible to control the creating of fakes, that would be a life saver.

So either way: If FakeItEasy can't do this, it's a feature-request. Otherwise, I would like to know how to do it :P

In case this is a feature-request, I'd say you get something similar to the DummyFactory, only now with the possibility to inline (without needed to create a discoverable class), and with some calling information context passed in (eg. constructor of Type A wants a fake of Type B, how to proceed?).

**Comment by blairconrad** [comment]
Hi, @LennardF1989. There's currently no such facility, and I'm not sure it's a great fit.

I'm not sure how something being a CMS really affect things, so I'm going to ignore that. If it's super relevant, please expand.

If I understand your usage, I think your desire could be achieved by creating a factory in the test assembly. The factory will always give back the same Fake", and then ensure that each test is given an instance of the factory.

If I've missed the point, please explain how. Code helps.

**Comment by LennardF1989** [comment]
Your synopsis is correct, that is what I'm after. A factory that always gives the same Fake. I'll try to provide some examples. In this case the system I'm using is the Umbraco CMS.

Consider the following class, which is pretty much the ServiceLocator of the CMS: https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web/Composing/Current.cs

This is used in situations where you cannot use the native dependency injection. To control Current, you can inject a IFactory, which is then used by all the properties. This is all fine and great.

The problem, however, start occuring when you try to use something that needs the UmbracoContext: https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web/Composing/Current.cs#L86

This is a concrete implementation (wrapped by an Accessor interface) and needs a lot of dependencies, which are usually resolved by the native IoC. https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web/UmbracoContext.cs#L33

In this case, one of these is a IPublishedSnapshotService which I need to control, to be able to control a Lazy that is being instantiated. https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web/UmbracoContext.cs#L67

Right now, if I fake the accessor interface for the UmbracoContext, FakeItEasy will take over and fill in the blanks, including an instantiation of the UmbracoContext and its dependencies, which is great! But in order to get control over the Lazy I mentioned earlier, I need a reference to the injected Fake IPublishedSnapshotService. The only way to do that right now is go down the rabbit hole (for as far as we aren't already) and construct the UmbracoContext myself.

In the end, I have to do a lot of groundwork, to get control over 1 simple thing. One could argue two things:
- You could just wrap the use of certain Umbraco-calls in a service, which can be mocked away by the test early on, without having to know anything about the in-depth workings of Umbraco. Which I agree with, but also puts a burden on the developer to basically put an abstraction on something that is intended to be used (Umbraco is not going anywhere and if it is to be replace, then all the CMS specific logic will have to be rebuild anyway).
- The above explanation of getting the intended result is boilerplate, do it once, put it in a BaseTest-class and be done with it. Which I also agree with, and which is what we did now.

However, this whole situation got me thinking why there is nothing in place to take a little control of whatever FakeItEasy is doing when its creating Fakes on-demand. In this situation having something like a FakeFactory which I can use to keep track of all Fakes that are being created (no matter where it happens in the application) and determine when I want to use which instance, gives a lot of control over the testing process.

As an example mockup, something like the following would then be possible.

public MyTestFakeFactory : IFakeFactory
{
    public IPublishedSnapshotService MyFake = A.Fake<IPublishedSnapshotService>();

    bool Supports(FakeContext context) 
    {
        return context.TypeName == "UmbracoContext" && context.Method == "Constructor";
    }

    Fake CreateFake(FakeContext context)
    {
        if(context.FakeType == "IPublishedSnapshotService") {
            return MyFake;
        }

        return context.DefaultBehavior();
    }
}

//...

var myTestFactory = new MyTestFactory();
FakeItEasy.RegisterFactory(new MyTestFactory(myTestFactory));

//...

A.CallsTo(myTestFactory.Fake).DoSomething();

**Comment by blairconrad** [comment]
I didn't follow half of that, but I think I had a revelation toward the end.

> why there is nothing in place to take a little control of whatever FakeItEasy is doing when its creating Fakes on-demand

Fakes are made during a test run in one of two ways

1. explicitly, usually right in the test code, via something like `A.Fake<ICollaborator>()` or whatever
2. implicitly, either as a return value for a member, or to be used in constructor arguments

In the first case, you have as much control as you want. Create a factory, give it a Fake to return all the time, and use it instead of calling `A.Fake<>` directly.

At first, it seems that the second case is not directly in your control. However, we should consider that FakeItEasy doesn't try to create Fakes on its own. It makes [Dummies](https://fakeiteasy.readthedocs.io/en/stable/dummies/), though. Sometimes these Dummies happen to be Fakes.

If you want FakeItEasy to use a particular Fake instance for a given type, create a [DummyFactory](https://fakeiteasy.readthedocs.io/en/stable/custom-dummy-creation/) to do so. It can call your Fake factory, and thereby return the same value all the time if you want.

**Comment by blairconrad** [comment]
@LennardF1989, have you had inclination and time to consider the DummyFactory option?
If there's more you want to talk about, I'm happy to do so.

**Comment by blairconrad** [comment]
Closing due to lack of interest.
