### ISSUE TITLE
Is it possible to have a mix of loose and strict modes?

### ISSUE THREAD

**Issue by voroninp** [FakeItEasy/FakeItEasy#1858]
I'd like mock to behave in a way described in [Mark's article](https://blog.ploeh.dk/2013/10/23/mocks-for-commands-stubs-for-queries/)

I'd consider as a command any method returning `void`/`Task`/`ValueTask`, query - for anything else.
So, whenever commands are called, I can verify the call, and when query is performed, the exception is thrown unless the result is explicitly defined.

**Comment by blairconrad** [comment]
Hi, @voroninp. There's nothing like that built into FakeItEasy itself, and I'm not sure if there's widespread demand, but it wouldn't be too hard to configure Fakes in this way. One could make the Fake strict and then override the strictness for the methods one cared about. Here's a very rough attempt, whose tests pass:

```c#

namespace FakeItEasyQuestions
{
    using FakeItEasy;
    using FluentAssertions;
    using Xunit;

    public class Test
    {
        public interface IInterface
        {
            int AQuery();
            void ACommand();
        }

        private T AHalfStrictFake<T>() where T: class
        {
            var fake = A.Fake<T>(o => o.Strict());
            A.CallTo(fake).WithVoidReturnType().DoesNothing();
            A.CallTo(fake).WithReturnType<System.Threading.Tasks.Task>().DoesNothing();
            return fake;
        }

        [Fact]
        public void QueryIsStrict()
        {
            var fake = AHalfStrictFake<IInterface>();
            var exception = Record.Exception(() => fake.AQuery());
            exception.Should().NotBeNull();
        }


        [Fact]
        public void CommandIsLoose()
        {
            var fake = AHalfStrictFake<IInterface>();
            fake.ACommand();
            A.CallTo(() => fake.ACommand()).MustHaveHappened();         
        }
    }
}
```

Of course there are many ways to optimize this. For example, one could apply the configuration via an [implicit creation option](https://fakeiteasy.readthedocs.io/en/stable/implicit-creation-options/). Or possibly by  adding an `IFakeOptions` extension. This is how [CallsBaseMethods` is implemented](https://github.com/FakeItEasy/FakeItEasy/blob/c2852f58e5495ca4f9fdb2d5048d454071149116/src/FakeItEasy/FakeOptionsExtensions.cs#L95), in fact.

**Comment by thomaslevesque** [comment]
Well, mocking EF Core is notoriously difficult... Your best bet is usually to use the in-memory provider, but there are Linq queries that fail to translate when using this provider. I've had some success with [MockQueryable](https://github.com/romantitov/MockQueryable), but it's not perfect (e.g. it doesn't handle things like `Include`).
