### ISSUE TITLE
[Feature Request] Add a `WithFactoryMethod` option to IFakeOptions

### ISSUE THREAD

**Issue by pdevito3** [FakeItEasy/FakeItEasy#1881]
Currently, I have classes with a factory creation method instead of a public constructor and I can't fake them. 

What would you guys think of a new method to handle the creation with the factory method vs a constructor?

For example, say I have a class like this.
```c#
public class Recipe : BaseEntity
{
    public string Title { get; private set; }
    public string Directions { get; private set; }
    public int? Rating { get; private set; }
    public Author Author { get; private set; }
    public ICollection<Ingredient> Ingredients { get; private set; }

    public static Recipe Create(RecipeForCreationDto recipeForCreationDto)
    {
        new RecipeForCreationDtoValidator().ValidateAndThrow(recipeForCreationDto);
        var mapper = new Mapper(new MapperConfiguration(cfg => {
            cfg.AddProfile<RecipeProfile>();
        }));
        var newRecipe = mapper.Map<Recipe>(recipeForCreationDto);
        newRecipe.QueueDomainEvent(new RecipeCreated(){ Recipe = newRecipe });
        
        return newRecipe;
    }
        
    public void Update(RecipeForUpdateDto recipeForUpdateDto)
    {
        new RecipeForUpdateDtoValidator().ValidateAndThrow(recipeForUpdateDto);
        var mapper = new Mapper(new MapperConfiguration(cfg => {
            cfg.AddProfile<RecipeProfile>();
        }));
        mapper.Map(recipeForUpdateDto, this);
        QueueDomainEvent(new RecipeUpdated(){ Recipe = this });
    }
    
    private Recipe() { } // For EF
}
```

I could then create a fake for it it like this:
```c#
RecipeForCreationDto fakeDto = new FakeRecipeForCreationDto();
var fakeTracking = A.Fake<Reccipe>(x => 
            x.WithFactoryMethod(x => x.Create(fakeDto)));
```

Totally open to other APIs, but this is a gap in the current API that is making things hard for this use case.

Happy to make a contribution if you guys aren't up for it, but I haven't looked at your codebase at all yet, so any guidance would be appreciated!

**Comment by blairconrad** [comment]
Hi, @pdevito3. An interesting idea, but I'm struggling to see how this could be implemented.
A Fake of a class type works by having Castle DynamicProxy construct a derived type, which is then instantiated. This means that the class needs to have a protected (or public) constructor that can be accessed. 

The `WithFactoryMethod` option would (I assume) call the factory method? Which would then produce an instance of the original (non-Fake) type, and I'm not sure where we'd go from there.

Maybe I'm missing something in the equation. If you can clear up my confusion, I'm keen to learn.

**Comment by thomaslevesque** [comment]
> Which would then produce an instance of the original (non-Fake) type, and I'm not sure where we'd go from there.

Maybe by using a wrapping fake? But then, it's already possible today:

```csharp
A.Fake<Recipe>(o => o.Wrapping(Recipe.Create(...)));
```

**Comment by blairconrad** [comment]
But `Recipe` isn't fakeable...

**Comment by thomaslevesque** [comment]
> But `Recipe` isn't fakeable...

Indeed. At the very least, the constructor would need to be made protected instead of private. And at least some members should be virtual, otherwise there's no point in faking it.

**Comment by pdevito3** [comment]
Yeah, that was just an initial thought on what stuck out as a potential option, but the implementation here does seem challenging. I'm also not really familiar with the underpinings or Castle, other than Nick Chapsas' video this past week :-) 

I was hoping something like this wasn't out of the realm of faking in some way, but maybe that's the case and I need to rework things a bit. 

Open to other ideas, but yeah not really sure offhand otherwise myself.

**Comment by pdevito3** [comment]
fwiw, the `Wrapping` option does seem to work @thomaslevesque if I make the ctor protected and the props virtual.

i have my classes set up like this to facilitate a more closed class that can enforce ddd like flows, but might have to add this to help on the testing side.

seems like i'd have to open up the props and ctor even with something like the proposed method though so maybe i'm out of luck

**Comment by blairconrad** [comment]
Yeah, as FakeItEasy exists, we're far from being able to fake the class as originally presented. The standard (often unsatisfying, from a user's perspective) in these cases is 

1. alter the class that you want to fake to make it more fakeable, or
2. switch to a commercial mocking library that can fake _anything_, or
3. take a whole 'nother tack

Since you seem to be able to alter the classes a little bit, you could experiment with extracting an interface and just faking that, or maybe making the constructor `internal` and exposing it to dynamic proxy so it can still fake the class. Whether that fits your preferred level of protection, I'm not sure.

**Comment by pdevito3** [comment]
Thanks @blairconrad, that makes sense. will see what I can put together. 

For snicks, when you say `switch to a commercial mocking library that can fake anything, or` what vendors might offer something like this? I know of `Moq` and `NSubstiute` as the main other options in the space and I don't think they can do this either.

**Comment by blairconrad** [comment]
No, Moq and NSubstitute would have about the same powers as FakeItEasy. We all build on the same base.

I was thinking of something like [Isolator](https://www.typemock.com/isolator-product-page/), which I used a very long time ago, and I think there's another. Oh! [JustMock](https://www.telerik.com/products/mocking.aspx). I've never used that one.
There may be others…

**Comment by pdevito3** [comment]
Awesome. Thanks for the help!
