### ISSUE TITLE
Inexplicable Guid values

### ISSUE THREAD

**Issue by jeancallisti** [FakeItEasy/FakeItEasy#1882]
So I have this fake object definition (), that has a fake method in it : 

```
IFooRepositoryClass fooRepo = A.Fake<IFooRepositoryClass>();

A.CallTo(() => fooRepo.FooFunctionAsync(A<Guid>.Ignored).ReturnsLazily(
    (Guid fooId) => {
        fooInternalObject.DoSomething(fooId);
    }
);
```

As you can see, thing out of the ordinary.

Later, in my XUnit tests, I call the fake function : 

```
Guid testGuid = new Guid("aaaaaaaa-9a88-4746-914b-aaaaaaaaaaaa"); //I changed to "aaaaa" to make it easily recognizable
await fooRepo.FooFunctionAsync(testGuid).configureAwait(false);
```

I put a breakpoint on that instruction : 
`await fooRepo.FooFunctionAsync(testGuid).configureAwait(false);
`
...I see that testGuid is indeed _aaaaaaaa-9a88-4746-914b-aaaaaaaaaaaa_

But then I put a breakpoint inside, on this instruction : 
`fooInternalObject.DoSomething(fooId);`

To my great surprise, **_fooId_ has a weird value with lots of zeros, different at each run!**
_f933b838-007b-0000-0000-000000000000
785bb288-001a-0000-0000-000000000000
4d4bb8d8-0012-0000-0000-000000000000_
etc.

What the hell is going on?

**Even weirder :**  I shared my branch to a colleague. He has the _exact same code as me._
...But **for him, fooId has the expected value, i.e. the value of _testGuid_!** He shared his screen, I shared mine. Everything condition seems identical. Only the Guid differs : Expected value for him, bogus values for me. I cleaned the solution, rebuilt, even restarted VS. to no avail!

What the hell is going on? x2

I'm not expecting anyone to fix my unit tests, but maybe this is a well-known behaviour under certain conditions. Ever seen that? Especially those weird 000000 Guid values?

----

[cross-posted to StackOverflow](https://stackoverflow.com/q/72826607/1199)

**Comment by thomaslevesque** [comment]
Hi @jeancallisti,

I was unable to reproduce the problem. Could you please provide a short but complete repro? I tried to guess the actual signatures of your classes and methods, but the code you posted has compilation errors, so I probably didn't match your scenario exactly.

FakeItEasy does nothing special with GUIDs, so I can't think of anything that would produce the weird values you're seeing.

**Comment by jeancallisti** [comment]
No. It disappeared as it appeared. Extremely mysterious.
The main culprit might be Linqpad, which I had open in the background by mistake and have uninstalled since then. I'm wondering if it intercepted Linq queries, a bit like Postman intercepts packages to a given server. but that is just a theory, not tested at all.

**Comment by thomaslevesque** [comment]
Hi @jeancallisti,
Thanks for the update. Linqpad doesn't intercept queries, so I don't think it could be related.
I guess it will remain a mystery!

**Comment by jeancallisti** [comment]
I just had an idea. If I fake an object and then fake a method that has many parameters and then mess upt he arguments one way or another (wrong order, or one parameter missing in the list -- causing all subsequent arguments to shift one position) (especially with optional arguments) maybe there was a bad cast happening? I'm thinking... What if a DateTime becomes a Guid by mistake??? I don't know. Maybe the heading or trailing zeros were the 00:00:00 at the end of the Date (if it's a date without a time or something)

**Comment by thomaslevesque** [comment]
I don't think that's possible. I guess it would be possible in a language like C, but C# has strong typing enforced by the runtime. A `DateTime` can't accidentally be interpreted as a GUID...

**Comment by jeancallisti** [comment]
The mystery remains. I guess we'll never know!
