### ISSUE TITLE
FakeConfigurationException when ReturnsLazily parameter implements parameter type

### ISSUE THREAD

**Issue by C-574** [FakeItEasy/FakeItEasy#1883]
Hello. I recently started to use FakeItEasy for my projects and I love it ❤. However, there is small thing that annoyed me when I tried to mock my MediatR commands and queries. I always have to specify the base type of the command (`IRequest<T>`), instead of the actual implementation when specifying a return value using `ReturnsLazily`. If I use `IRequest<T>`, as defined by the interface, then I must cast the request object to the actual implementation in the value producer, otherwise I get a `FakeConfigurationException`.

I do not know if this behavior is intentional or if changing it could break something, but it would make mocking MediatR requests easier to read.

I tried to resolve this by changing the type check of `IsCallSignatureSatisfiedByValueProducerSignature` to use `IsAssignableFrom` when comparing the call and value producer types and it seemed to work.

Here is the test case:
```cs
namespace FakeItEasy.Tests;
using System.Threading.Tasks;
using Xunit;

public interface IRequest<T> {}

public class MyCommand : IRequest<int>
{
    public int Value { get; set; }

    public MyCommand(int value)
    {
        this.Value = value;
    }
}

public interface ISender
{
    Task<TResponse> Send<TResponse>(IRequest<TResponse> request);
}

public class ReturnsLazilyTests
{
    [Fact]
    public async Task ReturnsLazily_accepts_implementation_of_call_method_parameter_type()
    {
        // Arrange
        var senderMock = A.Fake<ISender>();
        var command = new MyCommand(42);

        A.CallTo(() => senderMock.Send(A<MyCommand>._))
            // This works as expected.
            //.ReturnsLazily((IRequest<int> c) => ((MyCommand)c).Value + 1);
            // This will throw a FakeConfigurationException.
            .ReturnsLazily((MyCommand c) => c.Value + 1);

        // Act
        await senderMock.Send(command).ConfigureAwait(false);

        // Assert
        A.CallTo(() => senderMock.Send(A<MyCommand>._))
            .MustHaveHappened();
    }
}
```

**Comment by blairconrad** [comment]
Sorry you're having problems, @C-574. Thanks for the detailed reproduction steps.

For those reading, I've taken the code above. The error returned is

```
[xUnit.net 00:00:12.91]     FakeItEasyQuestions.ReturnsLazilyTests.ReturnsLazily_accepts_implementation_of_call_method_parameter_type [FAIL]
  Failed FakeItEasyQuestions.ReturnsLazilyTests.ReturnsLazily_accepts_implementation_of_call_method_parameter_type [428 ms]
  Error Message:
   FakeItEasy.Configuration.FakeConfigurationException : The faked method has the signature (FakeItEasyQuestions.IRequest`1[System.Int32]), but returns lazily was used with (FakeItEasyQuestions.MyCommand).
  Stack Trace:
     at FakeItEasy.ValueProducerSignatureHelper.AssertThatValueProducerSignatureSatisfiesCallSignature(MethodInfo callMethod, MethodInfo valueProducerMethod, String nameOfFeature) in C:\projects\fakeiteasy\src\FakeItEasy\ValueProducerSignatureHelper.cs:line 22
   at FakeItEasy.ReturnValueConfigurationExtensions.<>c__DisplayClass10_0`2.<ReturnsLazily>b__0(IFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\ReturnValueConfigurationExtensions.StronglyTyped.cs:line 65
   at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.<>c__DisplayClass28_0.<ReturnsLazily>b__0(IInterceptedFakeObjectCall call) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\RuleBuilder.cs:line 225
   at FakeItEasy.Configuration.BuildableCallRule.Apply(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Configuration\BuildableCallRule.cs:line 102
   at FakeItEasy.Core.FakeManager.ApplyBestRule(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 257
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(InterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 178
   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in C:\projects\fakeiteasy\src\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 186
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy_1.Send[TResponse](IRequest`1 request)
   at FakeItEasyQuestions.ReturnsLazilyTests.ReturnsLazily_accepts_implementation_of_call_method_parameter_type() in D:\Sandbox\FakeItEasyQuestions\Test.cs:line 42
--- End of stack trace from previous location ---
```

**Comment by blairconrad** [comment]
I'm struggling with this a little bit. On the one hand, I think that `ISender.Send` is supposed to act on an `IRequest<int>` and return an `int`, but the method supplied to `ReturnsLazily` transforms incoming `MyCommand` arguments into `int`s, and it's unable to deal with non-`MyCommnand` `IRequest<int>`s passed in during the Act phase. It feels a little impure.

If that were the end of the story, I think I'd say "you should probably just declare your method to produce `IRequest<int>`s".

However, the `A<MyCommand>._` in the `CallTo` gives me pause. As humans, we can read that and say "well, this method has only been overridden when the incoming object is a `MyCommand`". From that point of view, I think your preferred test makes sense. (But it's probably quite difficult to teach the two parts of the configuration machinery about each other: how to make the `ReturnsLazily` know _at that level_ what constraints were supplied to the `CallTo`.)

I'm going to need to think about this for a bit. Pile on with any rebuttals or comments.

**Comment by thomaslevesque** [comment]
Hi @C-574,

This is the expected behavior. The delegate passed to `ReturnsLazily` has to match the signature of the mocked method, which is not the case here. The reason is that you could pass any `IRequest<T>` to the `Send` method; if you could specify the return value using a delegate that only accepts a `MyCommand`, it would fail at runtime if you passed anything else...

**Comment by blairconrad** [comment]
As usual, better-put than what I had, @thomaslevesque. Thanks. The risk of a non-`MyCommand` being passed to the overridden method is always there. And a runtime (worse, during the Act phase) failure can be more difficult to detect and interpret than a failure during the Arrange phase.

compare:

```
System.InvalidCastException :
  Unable to cast object of type 'NonMyCommandIRequestOfInt' to type 'FakeItEasyQuestions.MyCommand'
```
with
```
FakeItEasy.Configuration.FakeConfigurationException :
  The faked method has the signature (FakeItEasyQuestions.IRequest`1[System.Int32]),
  but returns lazily was used with (FakeItEasyQuestions.MyCommand).
```

That's even assuming that the InvalidCastException weren't caught and transformed or suppressed by the production code…

**Comment by C-574** [comment]
Yeah, I already expected that it wouldn't be that easy 😄.

So, casting the `IRequest` object is the only/correct way of mocking such a test case if I understand that correctly. It now makes sense to me why it works like that.

Thank you both for answering.
