### ISSUE TITLE
Consider adding an overload of WithArgumentsForConstructor that accepts a variable number of arguments

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#1906]
i.e. `WithArgumentsForConstructor(params object[] arguments)`

**Comment by blairconrad** [comment]
We already have overloads that take a sample constructor, which can be used where we know in advance which arguments to supply, and one that takes an `IEnumerable`, for when we don't, I guess.

I think you're suggesting something like

```c#
.WithArgumentsForConstructor(arg1, arg2, …)
```

is it not as easy for the client to write

```c#
.WithArgumentsForConstructor(() => new ConcreteType(arg1, arg2, …)
```

?

**Comment by thomaslevesque** [comment]
You're right, the expression syntax is certainly better. I was just thinking in terms of terseness (having to write `new object[] {...}` is annoying).
Adding this isn't a big effort, but now I see at least one good reason not to do it: it could cause ambiguities and non-obvious behavior. For instance, assuming the faked class has a constructor that accepts an `IEnumerable<object>`:
```csharp
IEnumerable<object> arg = ...
var fake = A.Fake<Foo>(o => o.WithArgumentsForConstructor(arg));
```
This would call the `IEnumerable<object>` overload, even though the user probably meant to call the `params object[]` overload.

**Comment by thomaslevesque** [comment]
Closing this. We can always reconsider if someone expresses interest.
