### ISSUE TITLE
Replace API approval tests with baseline package validation

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1912]
The [Baseline Package Validator](https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/baseline-version-validator?WT.mc_id=DT-MVP-5003978) claims

> Package Validation can help you validate your library project against a previously released, stable version of your package. To enable package validation, add the PackageValidationBaselineVersion or PackageValidationBaselinePath property to your project file.
>
> Package validation detects any breaking changes on any of the shipped target frameworks. It also detects if any target framework support has been dropped.

Might be worth trying out. Reduce some of our own code. And if it only detects _breaking_ changes, less noise for us.

Two scenarios to consider. There may be more:

1. intentionally releasing a new major version with a breaking change. How do you do this? Disable validation, release, and then re-enable?
2. what if we augment the API surface by adding a new member, say in 8.1.0, where we're validating against 8.0.0. There's no problem. Nobody thinks to update the version to validate against. Then we release 8.2.0 and accidentally drop the new method. The validation doesn't complain, but we've broken the API relative 8.1.0.

**Comment by blairconrad** [comment]
This idea was originally raised by @thomaslevesque. I was re-reminded of it by

Gérald Barré's [Detecting breaking changes between two versions of a NuGet package at packaging time](https://www.meziantou.net/detecting-breaking-changes-between-two-versions-of-a-nuget-package-at-packaging.htm), via Oleg Karasik's [.NET R&D Digest (January, 2023)](https://olegkarasik.wordpress.com/2023/01/31/net-rd-digest-january-2023/).

**Comment by ViktorHofer** [comment]
@blairconrad I'm the owner of APICompat / Package Validation in the .NET Sdk. If you have any questions or need help enabling it, just let me know.

**Comment by blairconrad** [comment]
> intentionally releasing a new major version with a breaking change. How do you do this? Disable validation, release, and then re-enable?

Actually, you

1. suppress the warning, committing the suppression file
2. release
3. remove the suppression and update the PackageValidationBaselineVersion

> what if we augment the API surface by adding a new member, say in 8.1.0, where we're validating against 8.0.0. There's no problem. Nobody thinks to update the version to validate against. Then we release 8.2.0 and accidentally drop the new method. The validation doesn't complain, but we've broken the API relative 8.1.0.

I'm still not sure what to do about this. I think the answer is "update the PackageValidationBaselineVersion every time you release", which sounds like more (or at least as much) overhead as we incur from the current scheme.

**Comment by ViktorHofer** [comment]
> I'm still not sure what to do about this. I think the answer is "update the PackageValidationBaselineVersion every time you release", which sounds like more (or at least as much) overhead as we incur from the current scheme.

This has been a popular ask since we initially released Package Validation / APICompat in 2021 and is tracked via https://github.com/dotnet/sdk/issues/25268. Unfortunately, this isn't yet committed and needs work across multiple teams: NuGet client and the SDK. For now the best thing would be to define a process that automatically bumps the baseline version.

Some repositories like the Azure SDK added automation for this via a GH action that automatically updates the baseline version property when a new version got released: https://github.com/Azure/azure-sdk-for-net/commit/d35b0608162163b0ecf82606efc7a5c19c0015b1

**Comment by blairconrad** [comment]
Thanks for confirming, @ViktorHofer. And for the pointers. My knee-jerk reaction is that if we have to write a custom step to bump the version number, we might as well keep our custom step to compare the API. @thomaslevesque, if you agree, I propose to close. We can always reopen if the current mechanism becomes burdensome and/or progress is made in https://github.com/dotnet/sdk/issues/25268 that would make this issue more worthwhile.

**Comment by thomaslevesque** [comment]
Yeah, let's drop this for now. The current API approval tests are pretty low maintenance anyway.
