### ISSUE TITLE
ArgumentCollection.ArgumentNames has type IEnumerable<string> but may contain nulls

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1922]
In F# (at least), it is possible to declare a method with anonymous parameters.
In this case, `ArgumentCollection.ArgumentNames` will contain `null`s, but we do not indicate that the elements are nullable strings.

**Comment by blairconrad** [comment]
Two solutions come to mind:

1. return a placeholder for anonymous parameter names, such as empty string. This changes current behaviour (probably not many people rely on it, but some might), but keeps the property signature the same
2. return null for an anonymous parameter name, just as `Parameter.Name` would. Update the signature to `IEnumerable<string?>`


Either option may be regarded as a "breaking change". The value change would be breaking at runtime, not compile-time, and the signature change would be breaking at compile time, not runtime.

I prefer changing the signature. We get to keep existing behaviour, and align with what we'd see if reflecting over the method.

**Comment by thomaslevesque** [comment]
I agree that it's probably the best option.
And while it's technically a breaking change, the existing signature was actually a bug, so I don't think we need to bump the major version for this.

**Comment by blairconrad** [comment]
Agreed on all accounts. I will remove the label. Thanks, @thomaslevesque. I'll send a PR out probably by Monday.
