### ISSUE TITLE
Publish target framework Support Policy

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#1935]
Following #1925, we've been discussing which TFMs we want to support, and what policy we should have ongoing.

We've decided on

* when a new LTS .NET version is released, add a TFM for it
* when a LTS .NET version arrives at end of life, drop it
* don't add a TFM for non-LTS .NET versions

In addition, we will

* keep .NET Framework 4.6.2, at least as long as it's not causing any problems
* keep netstandard 2.0 and netstandard 2.1, as they've not been deprecated

We should add a support policy page to the documentation.

**Comment by blairconrad** [comment]
We haven't talked about what we'll do when/if Castle.Core release a new version, whether they keep their supported target frameworks the same or not…

**Comment by thomaslevesque** [comment]
Good point. In the past, we used the lowest possible version. Not sure if this is still a viable strategy...

**Comment by blairconrad** [comment]
(We recently got some community pressure to upgrade!)

**Comment by blairconrad** [comment]
Me, I'd prefer to use the lowest possible version as you note we've done. Clients are free to move to newer ones for whatever reason they might have (for example, production code that relies on a newer version). All this assumes no changes in supported platforms.

It's always possible that bugs or security vulnerabilities will be found in older versions, but those could be addressed on a case-by-case basis, I think.
