### ISSUE TITLE
Same GetType result for different fakes

### ISSUE THREAD

**Issue by manu-m** [FakeItEasy/FakeItEasy#1947]
My assumption to following code was that the assertion is `true`, but it isn't in real:

```c#
var idle = A.Fake<IState>();
var starting = A.Fake<IState>();

var idleType = idle.GetType();
var startingType = starting.GetType();

Assert.AreNotEqual(idleType, startingType);
```

Is the behavior intended that the `GetType` result of different fakes are the same?

**Comment by blairconrad** [comment]
I think we've answered your question, @manu-m, so I'm closing this. If I'm wrong, please reopen and clarify.
