### ISSUE TITLE
Feature request: Then().Returns...()

### ISSUE THREAD

**Issue by drauch** [FakeItEasy/FakeItEasy#1965]
We have sometimes quite complex test arrangement infrastructure where the first call to a faked dependency is set up someplace and at another place I need to set up the second call to the same faked dependency.

Calling `ReturnsLazily` twice overwrites the first one - as expected, I don't want to change that. But it would be nice to have the option to say ThenReturnsLazily() and thereby put it at the back of the set up calls. Like an implicit call to my suggested `ReturnsNextFromSequenceLazily` (#1964 1964) just split in two parts.

Best regards,
D.R.

**Comment by blairconrad** [comment]
Hi, @drauch. I may be missing a subtlety. Can you show some code? Ideally what you have to do now to workaround the lack, and an envisioned improvement? Because as I read your description upstairs, I'm not sure how what you're asking for is different than [Specifying different behaviors for successive calls](https://fakeiteasy.github.io/docs/7.4.0/changing-behavior-between-calls/#specifying-different-behaviors-for-successive-calls):

```
A.CallTo(() => fakeService.DoSomething())
    .ReturnsLazily(…).Once)()
    .Then
    .ReturnsLazily(…);
```


(which I've not tried, but assume works!)

**Comment by drauch** [comment]
I need it in two different locations:
```
void Arrange1 ()
{
    A.CallTo(() => fake.Foo()).Returns(1).Once();
}

void Arrange2 ()
{
    A.CallTo(() => fake.Foo()).Then.Returns(2).Once();
}
```

Best regards,
D.R.

**Comment by blairconrad** [comment]
This seems kind of niche, to be honest. It looks like you have access to `fake` from some shared location (perhaps it's an instance variable). Have you considered retaining the result of `A.CallTo(() => fake.Foo()).Returns(1).Once()`? 

```csharp
private IDoSomething? fake;
private IThenConfiguration<IReturnValueConfiguration<int>>? ongoingFakeConfiguration;

public interface IDoSomething
{
    int Foo();
}
void Arrange1()
{
    ongoingFakeConfiguration = A.CallTo(() => fake!.Foo()).Returns(1).Once();
}

void Arrange2()
{
    ongoingFakeConfiguration = ongoingFakeConfiguration!.Then.Returns(2).Once();
}


[Fact]
public void Test1()
{
    fake = A.Fake<IDoSomething>();

    Arrange1();
    Arrange2();

    var result1 = fake.Foo();
    var result2 = fake.Foo();

    result1.Should().Be(1);
    result2.Should().Be(2);
}
```

It doesn't seem any worse to me than the existing temporal coupling.

**Comment by blairconrad** [comment]
This may be a disappointment, but we've decided not to implement this change. While it may be useful for some, there are abundant alternate flows.

**Comment by blairconrad** [comment]
Closing.

**Comment by blairconrad** [comment]
This may be a disappointment, but we've decided not to implement this change. While it may be useful for some, there are abundant alternate flows.
