### ISSUE TITLE
How to fake a type that have `dynamic` (ExpandoObject) properties?

### ISSUE THREAD

**Issue by FixRM** [FakeItEasy/FakeItEasy#1974]
Hello, and thank you for this great tool! I'm facing a problem with creating a fake of Microsoft's SignalR [IHubCallerConnectionContext\<T\>](https://github.com/SignalR/SignalR/blob/main/src/Microsoft.AspNet.SignalR.Core/Hubs/IHubCallerConnectionContext.cs) that have `dynamic ` property CallerState. The following code
```C#
var fake = A.Fake<IHubCallerConnectionContext<IHubClient>>();
fake.CallerState.MyProp = 42;
```
will compile but throw
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: "Castle.Proxies.ObjectProxy_1" does not contain property "MyProp".
```
 in runtime.
```C#
var fake = A.Fake<IHubCallerConnectionContext<IHubClient>>();
dynamic state = new ExpandoObject();
state.MyProp = 42;
A.CallTo(() => fake.CallerState).Returns(state);
```
will not compile
```C#
var fake = A.Fake<IHubCallerConnectionContext<IHubClient>>();
dynamic state = new ExpandoObject();
state.MyProp = 42;
A.CallTo(fake.CallerState).Returns(state);
```
will end up with
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: "object" does not contain a definition for "Returns".
```
I finally found that
```C#
var fake = A.Fake<IHubCallerConnectionContext<IHubClient>>();
dynamic state = new ExpandoObject();
state.MyProp = 42;
A.CallTo(() => fake.CallerState).ReturnsLazily(() => state);
```
will work but it seems weird. Is it expected behavior, or issue or am I doing something wrong?

**Comment by blairconrad** [comment]
Hi, @FixRM. Sorry you're having a hard time. 

I have never used `dynamic`s so am not coming in with much experience, but it does seem that the `dynamic` type of the value supplied to `Returns` is causing the problem (not the type of `CallerState`; I was surprised). I think `dynamic` values infect things they touch. I was trying to write a test to reproduce your problem and FluentAssertions was also messed up: `fake.CallerState.MyProp.Should().Be(42)` fails. 

A little digging tells me that a well-known effect of using `dynamic` is that you can no longer use extension methods on objects.

Anyhow, even before I dug, I found that

```c#
var fake = A.Fake<IHubCallerConnectionContext>();
dynamic state = new ExpandoObject();
state.MyProp = 42;
A.CallTo(() => fake.CallerState).Returns((object)state);

// I can even set and test the values later:
bool same1 = 42 == fake.CallerState.MyProp;
same1.Should().Be(true);

fake.CallerState.AnotherProp = 3;
bool same2 = 3 == fake.CallerState.AnotherProp;
same2.Should().Be(true);
```

works. It's not the most elegant, but I think is preferable to using `ReturnsLazily` (you may not feel the same :wink:). 

I can try to look more later, but given the weirdness of `dynamic`, I'm not sure we're going to get to a better "solution". If nothing else, there's probably an opportunity to improve the docs, though.

**Comment by thomaslevesque** [comment]
@blairconrad's explanation is correct. Basically, `dynamic` messes up with extension methods. Just casting the value to `object` is probably the easiest fix.
