### ISSUE TITLE
Provide a non-exception throwing API for verifying that a method has been called

### ISSUE THREAD

**Issue by Alxandr** [FakeItEasy/FakeItEasy#200]
Currently, when I want to check that a method has been called I use `MustHaveHappend`. However, I need an API that allows to simply return true/false if the call has not happened. Now, I get that I can simply wrap this in a try-catch, and return true if it doesn't fail, and false if it does, but this is a completely wasted exception. Having a `DidHappen` or `HasHappened` that takes the same `Repeated` object would be really nice. This would probably be really easy to implement too, as one would simply refactor the current `MustHaveHappened` to return false/true instead of throwing, and then creating a new `MustHaveHappened` that simply calls the old method and throws an exception if it returns false. If more information is needed (like an exception message) this could be provided by out parameters, or by having the verification method return null on success and the actual exception on error (instead of throwing it).

**Comment by Alxandr** [comment]
Hmm. Well, not right now. I ran into an issue with how C# handles resolution of generic types (or rather inferring of them), which made this whole thing moot. My awesome idea for a testing library turned out to be impossible due to some weird technical limitations of the language :-/. Though, I'm considering retrying it in F# just for fun. Being able to do something akin to

```fsharp
A.CallTo methLambda |> should haveHappened exactly 3 times
```

should actually be doable there.

**Comment by adamralph** [comment]
OK, thanks for the feedback. In that case I'm going to close this issue but, of course, feel free to raise any other issues that come out of your work.

The F# approach sounds interesting. I'm interested to hear how you get on!
