### ISSUE TITLE
A.CallTo Ignored parameters don't seem to match for null

### ISSUE THREAD

**Issue by jons-bakerhill** [FakeItEasy/FakeItEasy#2053]
I have a method with this signature 

```csharp
Task<ResultClass> MethodName(
    Guid? param1,
    string param2,
    Guid? param3 = null,
    CustomClass param4 = null,
    IEnumerable<CustomClass2> param5 = null
);
```

Why does this call configuration not match
```csharp
A.CallTo(() => mockInstance.MethodName(
         A<Guid?>.Ignored,
         A<string>.Ignored,
         A<Guid?>.Ignored,
         A<CustomClass>.Ignored,
         A<CustomClass2[]>.Ignored))
    .Returns(new ResultClass());
```

but this one does?
```csharp
A.CallTo(() => mockInstance.MethodName(
        null, null, null, A<CustomClass>.Ignored, new CustomClass2[0] ))
    .Returns(new ResultClass());
```

I don't see anything here about ignored parameters not matching nulls https://fakeiteasy.github.io/docs/7.4.0/argument-constraints/

**Comment by blairconrad** [comment]
Hi, @jons-bakerhill. Sorry to hear about your woes.

Scanning the code, nothing jumps out at me.

To help us diagnose, could you tell us what values are actually being provided to the faked object when the call doesn't match your first setup and does match your setup?

If it's at all possible, providing a running test method or two would really make this easier.

**Comment by blairconrad** [comment]
I took a stab at the values you might be using and wrote this. Both branches pass with FakeItEasy 7.4.0 and 8.3.0. Maybe you can show me how I deviated from your situation?

```csharp
namespace fiequestions;

using FakeItEasy;
using FluentAssertions;

public class T
{
    public class ResultClass {}
    public class CustomClass {}
    public class CustomClass2 {}

    public interface I
    {
        Task<ResultClass> MethodName(
            Guid? param1,
            string param2,
            Guid? param3 = null,
            CustomClass param4 = null,
            IEnumerable<CustomClass2> param5 = null
        );
    }

    [Fact]
    public void TestIgnored()
    {
        var mockInstance = A .Fake<I>();

        var r = new ResultClass();
        A.CallTo(() => mockInstance.MethodName(
                A<Guid?>._, A<string>._, A<Guid?>._, A<CustomClass >._, A<CustomClass2[]>._))
            .Returns(r);

        mockInstance.MethodName(null, null, null, null, null).Result.Should().BeSameAs(r);
    }

    [Fact]
    public void TestNulls()
    {
        var mockInstance = A .Fake<I>();

        var custom2Array = new CustomClass2[0];
        var r = new ResultClass();
        A.CallTo(() => mockInstance.MethodName(
                null, null, null, A<CustomClass>._, custom2Array))
            .Returns(r);

        mockInstance.MethodName(null, null, null, null, custom2Array).Result.Should().BeSameAs(r);
    }
}
```

**Comment by thomaslevesque** [comment]
I would understand if it was `A<Guid>.Ignored` instead of `A<Guid?>.Ignored`, because `Guid` is a value type, so `null` doesn't match `A<Guid>.Ignored`. There's actually an [analyzer diagnostic (FakeItEasy0004)](https://fakeiteasy.github.io/docs/analyzers/6.1.1/) for this.
But I also can't reproduce the problem as described here.

**Comment by jons-bakerhill** [comment]
I'm still trying to create a minimal reproduction myself but I did just see that the actual call is 
`            ResultClass application = await mockInstance.MethodName(null, applicationIdentifier, objectParam1: objectParam1, objectParam2: prefillValues);` which leaves a parameter out and passes the last 2 by name.

**Comment by jons-bakerhill** [comment]
Took a little bit but I was able to create a standalone test project that fails with Ignored and works with null. It is attached.
[UnitTestProject1.zip](https://github.com/user-attachments/files/18132539/UnitTestProject1.zip)

**Comment by thomaslevesque** [comment]
Hey @jons-bakerhill, this project isn't buildable as is, at least on my machine. It's using the legacy project system and old dependencies that I don't have (classic ASP.NET). Would you be able to make a repro that doesn't require so many dependencies?

**Comment by thomaslevesque** [comment]
Anyway, I think I found the issue. You specify `A<Parameter2Class[]>.Ignored` for `arrayParam`, but the code actually calls the method with a `List<Parameter2Class>`. A `List<T>` isn't an array, so it doesn't match. You should use `A<IEnumerable<Parameter2Class>>.Ignored` to match the actual parameter type.

**Comment by jons-bakerhill** [comment]
That appears to have been it! Thanks. It always seems to be the "little" things like that that make development "fun".

**Comment by jons-bakerhill** [comment]
Breaking the test on purpose and looking at the error message it looks like it lists the configured calls not the call that failed to match. Can that be clarified in the error message or can it be changed to show what was actually passed?

```
Service.SomeMethod(
    Guid1: NULL,
    string1: NULL,
    guid2: NULL,
    object1: object1value,
    object2: []).
```

**Comment by thomaslevesque** [comment]
@jons-bakerhill sorry, I'm not sure what you mean. Is this an assertion failure message? Can you should the actual error message you're seeing?

**Comment by jons-bakerhill** [comment]
Yes, that is the assertion failure message (I edited the full message from my reproduction project into my prior comment). I likely won't have time to update the test project to .Net Core unfortunately, my employer's main project is still .NET 4.8. 

If the assertion message is supposed to be the actual call values the it's misleading as it shows `[]` rather than List<>.

**Comment by thomaslevesque** [comment]
> Breaking the test on purpose and looking at the error message it looks like it lists the configured calls not the call that failed to match

No, it's the call that was actually received, not the configured call. It didn't match a configured call, and the fake was strict, so it threw.

**Comment by thomaslevesque** [comment]
> If the assertion message is supposed to be the actual call values the it's misleading as it shows [] rather than List<>.

`[]` just means an empty collection, not necessarily an array.
It's consistent with the new "collection expressions" feature (which is coincidental, since this format predates the introduction of that feature to C#)

**Comment by jons-bakerhill** [comment]
> We could consider printing the type of each expected and received argument. At the cost of longer error messages.

I thought about suggesting that (or similar) but I've been blow away by the help so far and didn't want to be greedy.
