### ISSUE TITLE
Drop support for .NET 3.5

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#217]
I'm not sure whether this time has come yet but I thought I'd start the discussion and give the community an opportunity to comment.

.NET 4.0 has been around for almost 4 years now.

Removing the .NET 3.5 project will lessen our maintenance burden, reduce build times, package size, repo size, etc.

**Comment by thomaslevesque** [comment]
I'll try to recap some of the reasons to drop .NET 3.5:

- Missing recent BCL collection classes.

    We have to use [compatibility shims](https://github.com/FakeItEasy/FakeItEasy/tree/master/src/FakeItEasy.Net35/Compatibility) for `ConcurrentDictionary<K,V>`, `ConcurrentQueue<T>` and `ConditionalWeakTable<K,V>`, which were introduced in .NET 4.0. These shims are less efficient and less reliable than the real BCL implementations, and could be a source of bugs.

- Limited support for Linq Expressions

    In .NET 3.5 the Linq Expressions API only lets us create expressions, not statements. It severely limits our ability to generate code dynamically. For instance in #677 the only way to implement a fix that would work for .NET 3.5 is to manually generate IL with Reflection.Emit, which is very complex and error-prone.

- Awkward management of project source files

    Currently, source files are included directly in the FakeItEasy project, and included as links in the FakeItEasy.Net35 project. This is very impractical, because every time we add a file to FakeItEasy, we must remember to also add it as a link to FakeItEasy.Net35. It also tends to make refactoring harder, because moves and renames are not handled properly for linked files. (A shared project would probably make things easier)

This list is not exhaustive, I'm probably missing a few things.

**Comment by kellyelton** [comment]
Not to mention, everyone is dropping support for XP and vista. 3.5 doesn't
come with 7(its 4.0) and 4.0 is basically EOL from what I read a month ago.

**Comment by blairconrad** [comment]
I don't see how the status of .NET 4.0 has any impact on whether or not to drop support for 3.5.

3.5 may not ship with Windows 7, but that doesn't mean people don't have it.
I do. Moreover, I have projects that target 3.5 and use against FakeItEasy.
Whether those will ever need to upgrade to 2.0+ (hmm, at least one us using 2.0.0-beta004), I don't know, but some clients might want to.

As @thomaslevesque points out, we probably have a way to help with the awkward management of source files, and one that we may want to adopt anyhow if we want to provide a .NET4.5 build (at least #361 would benefit from this).

**Comment by adamralph** [comment]
IMHO the burden of supporting .NET 3.5 in 2.x is not worth the benefit. At this stage I'm happy to say that anyone who needs .NET 3.5 is welcome to stay on 1.x.

**Comment by blairconrad** [comment]
Okay. :scissors:

**Comment by kellyelton** [comment]
The only point I was making is that now's a great time to cut the cord to older frameworks.

**Comment by thomaslevesque** [comment]
Since we all agree, I'll start working on it now.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
