### ISSUE TITLE
Nested argument constraints

### ISSUE THREAD

**Issue by alexjamesbrown** [FakeItEasy/FakeItEasy#219]
Is there a way of doing something like this:

```csharp
A.CallTo(() => _fakeFindContent.Find(
   A<IEnumerable<ContentQuery>>.That.Contains(
       A<ContentQuery>.That.Matches(
           item => item.Keys.SequenceEqual(new[] { "a", "b", "c"}))));
```

Currently, when I run that, it's always asserting as true (incorrectly)

If I alter that to:

```csharp
A.CallTo(() => _fakeFindContent.Find(
    A<IEnumerable<ContentQuery>>.That.Matches(
        x => x.Any(item => item.Key.SequenceEqual(new[] { "a", "b", "c" })))))
    .MustHaveHappened();
```

Then it fails (correctly)

**Comment by blairconrad** [comment]
Is there still interest here? I'm (surprise!) inclined to not pursue the feature, and would recommend the issue for closing. To me, it seems like an edge case, probably tricky to implement and understand, and nobody's had a thing to say about it for over two years.

**Comment by alexjamesbrown** [comment]
Hmm, I'd close it for now, I guess someone can always stumble across this via google and re-open it (or implement it!)

**Comment by blairconrad** [comment]
Oh, thanks for the speedy feedback, @alexjamesbrown. As you say, nothing's permanent, so we can always reopen.
