### ISSUE TITLE
Align behaviour of default values across the API

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#224]
We've talked a lot recently about default return values for unconfigured methods and properties across a number of issues.

Perhaps we need to draw up a table of all the affected areas of the API with current and proposed behaviours. This would help visualise the situation so we can form opinions on how we should proceed.

The best of course of action may be to break all the API points at once for a 2.0 release (as we've hinted at elsewhere).

This issue may serve purely as a central place where we can analyse all the issues together. Implementation my well be spread across several issues.

**Comment by adamralph** [comment]
As we are reaching late stages of preparation for our 2.0 release, it's worth considering any other breaking changes which we may or may not want to include.

Is anyone aware of any existing 2.0 beta behaviours which may fall under this umbrella? Do we want to undertake a full analysis before 2.0? Or shall we leave this for 3.0?

**Comment by blairconrad** [comment]
I don't think any of the changes introduced in the 2.0 betas have added to or exacerbated the "default values" problem described in here.
If you can hold off, let me rethink about #156 before committing to a "now or later" decision. If you can't hold off, I seem to be the main complainer, so I think waiting would be okay.

**Comment by blairconrad** [comment]
Given the lack of agreement on #156, I've not much taste for pursuing this issue now. I think we should leave it out of 2.0. Then if interest strikes, we could perform the analysis later and draw up a plan, which may involve another major version number release.

Alternatively, I've not seen any complaints or confusion _from users_ over possibly unaligned return values. Maybe this exercise is not worth our time. We could consider closing.

**Comment by adamralph** [comment]
Agreed. Let's leave this out of 2.0.

**Comment by blairconrad** [comment]
"breaking" + "out of 2.0" suggests to me that this is a P3 at best. Objections to demoting?

**Comment by adamralph** [comment]
Agreed. Demoted.

**Comment by blairconrad** [comment]
I'm just taking a rerunthrough of all the issues before we hit 2.0, and am thinking that _nobody_ is going to want to do this. It sounds like a cubic boatload of work, for quite possibly no gain at all. How do we feel about closing it?

**Comment by adamralph** [comment]
I'm :+1: to close.
