### ISSUE TITLE
Move contribution guidelines into wiki

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#225]
Looking for opinions on this.

CONTRIBUTING.md would remain since it is a special file which GitHub knows about and prompts contributors to read when raising PRs. If we moved the content to the wiki then this file would probably just link to it.

Spun off from #172

**Comment by adamralph** [comment]
I'm no longer convinced this is worth it. Maintaining CONTRIBUTING.md hasn't been difficult, and it does have the advantage that the guidelines live right next to the code, in your clone.

**Comment by thomaslevesque** [comment]
I don't really see any advantage in having it in the wiki anyway...
