### ISSUE TITLE
Generalised mocking SDK

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#229]
See

* https://github.com/FakeItEasy/FakeItEasy/issues/200#issuecomment-31729263
* https://github.com/FakeItEasy/FakeItEasy/commit/386c8c840764a0915d11ee272e516714bc1f5046#commitcomment-2621343

**Comment by blairconrad** [comment]
Two years with no movement. Does anyone care, or should we close?

**Comment by adamralph** [comment]
I'm :+1: to close.

**Comment by hmemcpy** [comment]
Pretty much who was involved in this discussion had moved to greener pastures :)
That's not going to happen... :+1: to close as well.
