### ISSUE TITLE
Support VS test runner

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#231]
I'm not sure what others are using for running tests in VS. Historically I've always used TestDriven.NET which works just fine. Recently, on my new ultrabook, I've decided to give the VS test runner another spin.

There are several issues currently:

* `FakeItEasy.IntegrationTests.RaisingEventWithMultipleSubscribers` fails when running all tests, but passes when run in isolation
* The `IsValid_should_return_false_for_invalid_values` test which `FakeItEasy.Tests.ExpressionsConstraints.EqualityArgumentConstraintTests` inherits from `FakeItEasy.Tests.ArgumentConstraintTestBase` is not run with the message `Source: no source available`
* The Windows Store 8 test introduced in #214 is not run with the message `Unit tests in source C:\code\FakeItEasy\Source\FakeItEasy.Win8.Tests\bin\Debug\FakeItEasy.Win8.Tests.dll cannot be run. Please create a Windows Store or Windows Phone Unit Test project.`

Even though I'm happy to continue using TestDriven.NET, I think we should encourage contribution by supporting the VS test runner completely.

**Comment by adamralph** [comment]
We should hold off on this one until #545 is closed.

**Comment by blairconrad** [comment]
Is this still valid? The VSIX extension isn't supported anymore. Do we need to use [xunit.runner.visualstudio](https://www.nuget.org/packages/xunit.runner.visualstudio) to run the tests via the VS test runner? If so, unless we want to add that package to FIE, is there much point?

In related news,

![image](https://cloud.githubusercontent.com/assets/3275797/16162318/99336534-34a0-11e6-9824-64b7d5753bb8.png)

And all but `ApproveApi` pass in isolation.

**Comment by blairconrad** [comment]
I should've said. I was running the branch that has no NUnit, just xUnit tests.

**Comment by adamralph** [comment]
Yes, in order to support the VS runner after our migration to xunit, we'd have to install https://www.nuget.org/packages/xunit.runner.visualstudio in all our projects. I guess it depends on how much benefit this would convey to our contributors.

**Comment by adamralph** [comment]
> suggesting xunit.extensibility.execution

I don't understand this. The solution for running xunit with the VS runner has been to install https://www.nuget.org/packages/xunit.runner.visualstudio from time now, as detailed in the recently updated https://xunit.github.io/docs/getting-started-desktop.html#run-tests-visualstudio

When I raised the issue, I was trying to run the current NUnit tests using VS runner. We may indeed find that, after migrating to xunit, and installing xunit.runner.visualstudio the everything just works.

xunit.extensibility.execution is for building extensions for xunit, such as xbehave.

**Comment by blairconrad** [comment]
> I don't understand this

I don't understand anything.

Thanks for the link to the getting started. You may have just provided the solution to
https://github.com/xunit/xunit/issues/887.

**Comment by blairconrad** [comment]
> When I raised the issue, I was trying to run the current NUnit tests using the VS runner. We may indeed find that after migrating to xunit and installing xunit.runner.visualstudio, everything just works.

Perhaps. Especially now that we'll be disabling parallelization in what I think are the relevant assemblies.
