### ISSUE TITLE
improvise smoke test for FakeItEasy-SL.Tests, to be run during build

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#243]
From Pull request #241:

FakeItEasy-SL.Tests does not actually contain tests from a testing framework, and can not reference NUnit because the latter was not built against the Silverlight runtime.

We should add some kind of test that is run at build time, to ensure that basic SL integration is not broken in the future.

**Comment by blairconrad** [comment]
Since we're going to get rid of Silverlight in #507, there's no point in pursuing this.

**Comment by adamralph** [comment]
:+1:
