### ISSUE TITLE
Move examples to separate repo

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#281]
And probably rename to 'samples'.

This allows the samples to be a smoke test of the published NuGet packages and it also allows the core repo and samples repo to evolve at their own pace. The core repo history should look cleaner as a result, i.e. most things on master between each release tag are part of features which make up that release rather than possibly unrelated sample additions.

**Comment by blairconrad** [comment]
As time goes on, I continue to be not in favour of the issue. I'm more and more satisfied with the docs being in the repo, and I don't feel that samples should be any different.
(In fact, a lot of the time we're putting (non-compiling) samples in the docs.)
Is there still interest?

**Comment by adamralph** [comment]
No, let's close.
