### ISSUE TITLE
Raise Non-EventArgs events

### ISSUE THREAD

**Issue by galaktor** [FakeItEasy/FakeItEasy#30]
The `Raise<>.With` syntax is typed to events with the `EventArgs` convention.

There are many cases where I use events with custom delegate types, like such

``` csharp
public delegate void MyDelegate(MyCargo c);
// ...
public event MyDelegate Foo;
```

Unfortunately I cannot raise such an event on a Fake with the given `Raise<>` API.

A way to raise any type of delegate/cargo would be very useful; meaning if `Raise<>` took a custom/generic delegate signature and didn't force the `(sender,EventArgs)` pattern.

The use case I imagine (or, really, expected at first) was this (continuing the above delegate example):

``` csharp
var f = A.Fake<IFireEvents>();

f.Foo += Raise.With<MyDelegate>(new Cargo()).Now;
```

or  maybe

``` csharp
f.Foo += Raise.With<MyCargo>(new Cargo()).Now;
```

where, in the latter case, Raise would expose an `Action<TCargo>` or similar.

Not sure how much of this is really possible, but depending on how desperate I get I might try to hack it up myself in a fork.
However, I'm sure you guys know what to do in this case much better than I do :-)

Thanks for the great tool!

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
