### ISSUE TITLE
No way to assert a call to a setter wasnt made.

### ISSUE THREAD

**Issue by Groostav** [FakeItEasy/FakeItEasy#32]
Big fan of framework, found a small annoyance:

I'd like to assert that a property setter was not called. I'm looking at your documentation, and I cant find a way to do this.

``` C#
        private class IntBox
        {
            public int IntProperty { get; set; }
        }

        [Test]
        public void when_using_A_callTo_on_a_property_set_call()
        {
            var fake = A.Fake<IntBox>();
            fake.IntProperty = 4;

            A.CallTo(() => fake.IntProperty).WithAnyArguments().MustNotHaveHappened();
            //ahhh so set calls are excluded...

//            A.CallTo(() => fake.IntProperty = -1).WithAnyArguments().MustHaveHappened();
            //and of course an expression cannot contain an assignment operator...
        }
```

I would argue that the expected behavior is that

``` C#
A.CallTo(() => fake.IntProperty).MustNotHaveHappened()
```

would check for both `get` and `set` calls, but this would be a breaking change in your framework and might anger a good number of people, so perhaps the simple static methods `Get` and `Set` on `IReturnValueArgumentValidationConfiguration<T>` would suffice, so that my assertion could be:

``` C#
A.CallTo.Get(() => fake.IntProperty).MustNotHaveHappened()
A.CallTo.Set(() => fake.IntProperty).MustNotHaveHappened()
```

Cheers!

-Geoff

**Comment by Jameskmonger** [comment]
I can confirm that @patrik-hagne 's solution above works correctly.

The "set" value is passed as the first argument, so you can do this to match the arguments (for example, to check that "IntProperty" is set to 4:

    A.CallTo(fake)
        .Where(x => x.Method.Name.Equals("set_IntProperty"))
        .WhenArgumentsMatch(x => x.Get<int>(0).Equals(4))
        .MustHaveHappened();
