### ISSUE TITLE
Add default support to DummyValueCreationSession for type Lazy<T>

### ISSUE THREAD

**Issue by cmerat** [FakeItEasy/FakeItEasy#358]
Title pretty much says it all. The class already supports Task&lt;T> results and fakes them appropriately. Currently, the default implementation will use the default Lazy&lt;T> constructor which looks for an empty constructor on the class T (that may not exist in many cases).

I've already written the change in my repo, just need to fix a few things to make sure I conform with the guidelines for contributing (which included raising this issue).

Thanks for your consideration and great work on FakeItEasy. It's a real dream to use.

**Comment by blairconrad** [comment]
@, thanks very much for your work on this issue. Look for your name in the release notes. :trophy:This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).

**Comment by blairconrad** [comment]
@cmerat, thanks very much for your work on this issue. Look for your name in the release notes. :trophy:

This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
