### ISSUE TITLE
Support pushing symbols to symbolsource.org

### ISSUE THREAD

**Issue by whut** [FakeItEasy/FakeItEasy#362]
Support pushing symbols to symbolsource.org, this way it will be easy to debug problems with FakeItEasy.

Documentation: http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-symbol-package

**Comment by adamralph** [comment]
I think [GitLink](https://github.com/GitTools/GitLink) may be a much better solution. See https://oren.codes/2015/09/23/enabling-source-code-debugging-for-your-nuget-packages-with-gitlink/

**Comment by thomaslevesque** [comment]
> I think GitLink may be a much better solution. See https://oren.codes/2015/09/23/enabling-source-code-debugging-for-your-nuget-packages-with-gitlink/

Looks like a great solution. Just to make sure I understand it correctly: it doesn't require the user to install anything, right? It will "just work" for the end user?

**Comment by adamralph** [comment]
Correct

**Comment by blairconrad** [comment]
I've no direct experience with either, but GitLink sounds great.

**Comment by adamralph** [comment]
We'll do GitLink instead - #735
