### ISSUE TITLE
Bad exception thrown when fake's base's constructor fails

### ISSUE THREAD

**Issue by matkoch** [FakeItEasy/FakeItEasy#367]
Related to #365, FIE throws a `FakeCreationException` when calling a fakable method (with struct return type) in the constructor. However, the current exception message isn't really helpful, because it doesn't outline that possibility.

```
FakeItEasy.Core.FakeCreationException : 
  Failed to create fake of type "ClassLibrary7.DomainType".

  Below is a list of reasons for failure per attempted constructor:
    No constructor arguments failed:
      No usable default constructor was found on the type ClassLibrary7.DomainType.
      An exception was caught during this call. Its message was:
      Exception has been thrown by the target of an invocation.
```

As long as #365 is not solved somehow, FIE should either state this situation in the exception, or, what i prefer, introduce a new exception type for virtual/abstract calls in the constructor. Also, the thrown `FakeCreationException` doesn't expose the inner exception - it is null. I think it could be wrapped.

**Comment by blairconrad** [comment]
@matkoch, thanks very much for your work on this issue. Look for your name in the release notes. :trophy:

This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
