### ISSUE TITLE
Virtual calls should behave the same way during the constructor as after the constructor call

### ISSUE THREAD

**Issue by ulrichb** [FakeItEasy/FakeItEasy#371]
Given a class with the anti-pattern of virtual calls during the constructor.

```c#
public class Foo
{
    public Foo()
    {
        Console.WriteLine(this.VirtualMethod("call in constructor"));
    }

    public virtual string VirtualMethod(string parameter)
    {
        return "implementation value";
    }
}
```

When creating a fake of such a class, FIE does not process the calls *during* the constructor call. 

As a consequence ...
* The [default behavior](https://github.com/FakeItEasy/FakeItEasy/wiki/Default-fake-behavior) of virtual members isn't available during the constructor, i.e. `VirtualMethod()` returns null instead of the empty string in the sample above. Note that this is the cause for #368. (@blairconrad: and the deficiency has since been resolved in that issue)
* Calls during the constructor cannot be asserted, i.e. `A.CallTo (() => foo.VirtualMethod ("call in constructor")).MustHaveHappened();` will fail.
* The fake options Strict(), CallsBaseMethods(), and Wrapping() do not apply to virtual methods during the constructor call.
* Also scope configurations using Fake.CreateScope(IFakeObjectContainer) don't apply to virtual methods during the constructor call.

So at the moment FIE simply doesn't support virtual calls in the constructor(s) of faked classes.

I already prepared a PR for this issue and will propose it today.

**Comment by blairconrad** [comment]
@ulrichb, thanks very much for your work on this issue.
This was a **huge** change, and not one that I think I'd've been able to make.

Look for your name in the release notes. :trophy:

This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
