### ISSUE TITLE
Review code with an eye to reducing type and member visibility (or existence!)

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#374]
While we have nothing to hide, having too many publicly visible types and members can be a drawback for a framework. For example:

1. too many public items can present too many options to clients, confusing them, and 
1. there is always a danger in changing public items, as clients may be relying on types continuing to exist, or on particular member signatures

This came to light during discussions around several changes in #373, where a new public type was added and some public constructors (for public types) were changed. In this case, the changes were discussed and deemed to be (likely) safe, since the affected members were of no use to clients. But if they're of no use to clients, why expose them? If they had been internal to begin with, we could've avoided some angst and confusion.

Thus, we should perhaps examine FakeItEasy's public types and public (and protected? probably not as a big a concern) on those types, with an eye to reducing the library's surface area without negatively affecting clients. And then we could act on the findings.

Suggested actions that could improve the library's API, in approximate descending order of preference:

1. removing items from the public API if they're no longer desirable (#410)
1. changing public types that are of no interest to the outside world from public to internal
1. changing public or protected members that are of no interest to the outside world to internal
1. for types that are used by the outside, considering providing a public interface or more focused type and changing the original to be internal
1. moving types that need to stay public into a specialized namespace (`Sdk`?) so they won't hit clients in the face when their IntelliSense kicks in after they type `FakeItEasy.`

We may want to make breaking changes here, but should not do so carelessly. If it's reasonable to preserver the user experience, we should do so.

_This text appeared when the issue was created, before we decided to make it part of the 2.0.0 milestone_:

> We may consider breaking changes for users, but in that case we should
> 
> 1. increase the major version number of the library
> 1. probably make as many [breaking changes](https://github.com/FakeItEasy/FakeItEasy/issues?q=is%3Aopen+is%3Aissue+label%3Abreaking) as we can in one release so we don't have to shock users more than once

I suggest starting a checklist in this issue to track what we've looked at, but spinning off individual issues for each change (or related set of changes) in order to increase discoverability in case someone is adversely affected by a change.

Okay. I've added [a Google Spreadsheet with all the visible named types exported from FakeItEasy](https://docs.google.com/spreadsheets/d/1fD83ph65YQwnzB0XxzjeNrOcZlfriYCC0syYDJIANvQ/edit?usp=sharing) (excluding those that come from Castle.Core). With notes.

**Comment by blairconrad** [comment]
As the Google Drive spreadsheet shows, every publicly-accessible type in FakeItEasy has been assessed. A number of changes have been carried out, in:
* Removed obsolete Any and Configure types - #408
* Remove obsolete types from public API - #410
* Remove obsolete type members from API - #425
* Internalize types and members that don't need to be exposed - #428
* move types out of FakeItEasy namespace where appropriate - #432

I'd identified two additional "problem" types, `ITaggable` and `IFakeObjectConfigurator`.

Internalizing `ITaggable` proved to be problematic, as it breaks serialization of (non-delegate type) fakes. I see no way around. I think we leave it as is.

Internalizing `IFakeObjectConfigurator` can not be done, as `IFakeObjectContainer` extends it, and this interface is published and used for creating scopes. We could have `IFakeObjectContainer` absorb `IFakeObjectConfigurator`, making a 2-method interface. The downside would be that `FakeManagerProvider.FakeManagerProvider` would then take an `IFakeObjectContainer` when it only cares about the `ConfigureFake` method (currently on `IFakeObjectConfigurator`). I am willing to go either way on this, but think that we should just leave the interfaces as is.

Unless someone has other ideas regarding these two oddballs, I think I'm done with the investigation.
Of course, we can leave it open for a bit in case anyone (@adamralph already has a column in the spreadsheet) wants to perform an independent analysis. Otherwise, I'm happy to close it at any time.

**Comment by adamralph** [comment]
@blairconrad thanks very much for this. I'm happy with the current state of things as described by your analysis. I don't really have the bandwidth to carry out any specific further analysis myself so I've removed my column from the sheet.

Thanks for your great work on this. FakeItEasy 2.0 is going to be a much cleaner product as a result!

**Comment by blairconrad** [comment]
… and with any luck, we won't have hordes of angry powerusers complaining that we've got rid of their favourite bit.

(**Attention angry powerusers**: if we've broken something that we shouldn't've, we'll put it back. And probably with alacrity.)

Thanks for _your_ work on this, @adamralph.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
