### ISSUE TITLE
Allow default call behavior to be defined explicitly with other calls in execution order

### ISSUE THREAD

**Issue by tvanfosson** [FakeItEasy/FakeItEasy#377]
Using stack-like behavior to define the call order is counter-intuitive. While the implementation as a stack seems reasonable, that detail shouldn't be exposed to the user. Rather the definition of calls should follow the same sort of linear path that most developers use when reasoning about code. This would lower the cognitive burden on the developer and make FakeItEasy easier to use.

To enable this, I suggest adding an explicit mechanism to define the behavior.  For example, to simulate a service that might be damaged and going down, one could define a sequence where it first succeeds, then fails twice (new call and retry), then subsequently throws an exception.

```csharp
A.CallTo(() => fakeService.DoSomething()).Returns("SUCCESS").Once();
A.CallTo(() => fakeService.DoSomething()).Returns("FAILURE").Twice();
A.CallTo(() => fakeService.DoSomething()).Throws<Exception>().AsDefault();
```

By adding the `AsDefault()` method you could leave the existing semantics intact and allow a developer who wished it to have the alternative, more intuitive flow to the call set up.  I would expect that calling `AsDefault()` twice on the same expression would cause an exception.  Likewise adding an explicit default for an expression that has an existing implicit default would cause an exception.

**Comment by blairconrad** [comment]
There's been no movement on this in over a year, and I'm still not sure that there's any benefit in providing different orders for effects to be applied.
Are there any objections to closing the issue until/unless someone comes back and expresses interest (preferably with a good interface and plan for implementation, although I wouldn't make those requirements…)?

**Comment by tvanfosson** [comment]
I can live with it as is.

**Comment by blairconrad** [comment]
Thanks for the update, @tvanfosson.

**Comment by adamralph** [comment]
Marked as `won't fix`.
