### ISSUE TITLE
push CI builds on the master branch to myget

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#392]
From https://github.com/FakeItEasy/FakeItEasy/issues/362#issuecomment-57425808.

**Comment by adamralph** [comment]
Do we really want to do this? Is there any value?

**Comment by blairconrad** [comment]
Nah. Let's not.

**Comment by adamralph** [comment]
Agreed. @thomaslevesque any objection to closing?

**Comment by thomaslevesque** [comment]
Nope, no objection
