### ISSUE TITLE
Switch to a build system with local dependencies

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#407]
I attempted to upgrade our build script, first to Albacore 2.x and then to Albacore 1.x. The former had many issues (I'm not convinced of the feasibility of Albacore 2.x generally) and the latter, whilst it worked, failed on the build server due to the nature of gem and it's global dependencies.

**Comment by adamralph** [comment]
switched to P3, since our use of bundler has mitigated the problem

**Comment by adamralph** [comment]
In fact, given that bundler has solved the problem, I think we should close this.

I'd like to switch to a build system which doesn't require extra installations, but I don't think we should morph this issue into that, I've raised #645 for that.

**Comment by thomaslevesque** [comment]
> In fact, given that bundler has solved the problem, I think we should close this as invalid.

Agreed, closing this one
