### ISSUE TITLE
Remove obsolete members from public API

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#410]
Following on from #408, there may be other parts of the API which we feel are redundant. It would be good to remove anything we find in 2.0.

**Comment by blairconrad** [comment]
At this point #421 now contains everything that I think can and should be _removed_.

In the interest of having smaller issues and PRs, I'll start a new issue for `internal`izing some types and members.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
