### ISSUE TITLE
investigate fixing integration with .NET Fiddle

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#414]
I tried making [a very simple .NET Fiddle that used FakeItEasy](https://dotnetfiddle.net/D4y15H), but it failed.

I'd enjoy seeing FakeItEasy work with .NET Fiddle, so I sent the owners an e-mail seeing what we could do to get things working, as the error seems similar to Moq's, and the hints in the [package compatibility list](http://dotnetfiddle.uservoice.com/knowledgebase/articles/298018) did not prove fruitful.

**Comment by jimmyheaddon** [comment]
Is this not a case of adding the ```[SecurityCritical]``` attribute on the ```CastleDynamicProxyGenerator.GenerateProxy()``` method?  ```ProxyGenerationOptions``` is ```ISerializable``` and internally calling ```GetObjectData()``` when adding attributes will likely cause this exception to be thrown.

MSDN reference can be found [here](https://msdn.microsoft.com/en-us/library/dd233102.aspx), scroll down to the 'Inheritance' anchor

**Comment by blairconrad** [comment]
@jimmyheaddon, that looks like it. Nicely done.
I must confess, I've never worried about any of this sort of thing before, so I have two questions/problems.

1. there must be a way to test this out without releasing a NuGet package of unknown quality. Perhaps the people behind 'dotnetfiddle at entechsolutions.com' ([via](NuGet Packages Compatibility)) would have a more convenient alternative, and
2. if we made this change, would other people be bitten by the seemingly tighter security on `CastleDynamicProxyGenerator.GenerateProxy`?

**Comment by blairconrad** [comment]
Unfortunately, I wrote the dotnetfiddle people in December and got no response. I can try again.

**Comment by blairconrad** [comment]
I've done so.

**Comment by jimmyheaddon** [comment]
I'm not particularly familiar with dotnetfiddle, hopefully they can suggest a mechanism which doesn't require release packages!

**Comment by blairconrad** [comment]
I'm not overly familiar either. It looked cool when I first heard of it and then didn't work with FakeItEasy and then… other events intruded.

**Comment by blairconrad** [comment]
(Or maybe I should've said FakeItEasy didn't work with it!)

**Comment by jimmyheaddon** [comment]
@blairconrad did you hear anything back on this?

**Comment by blairconrad** [comment]
Ah. Good of you to ask, @jimmyheaddon. Radio silence.
I gotta say, I'm losing enthusiasm for the whole endeavour…

**Comment by blairconrad** [comment]
It's official. My enthusiasm is lost.

**Comment by thomaslevesque** [comment]
I agree that supporting .NET Fiddle in particular isn't very important; however, doesn't the same problem occur anytime the code runs in a medium or low trust context? If it's the case, we should probably consider fixing it (if it's possible)

Related: http://stackoverflow.com/questions/11714762/castle-windsor-does-not-work-under-medium-trust

**Comment by blairconrad** [comment]
I'm not against working in a low trust environment. I'm not very savvy with the trust levels, and am not sure when we'd need to run FakeItEasy in such an environment (outside tools/sites) such as .NET Fiddle. We can reopen, if you'd like, or start a new "run in lower trust environment" issue.

**Comment by thomaslevesque** [comment]
I agree that it's unlikely that someone would actually need to run their unit tests in low trust. I also don't know much about trust levels, so I'm not sure how to investigate the issue...

**Comment by adamralph** [comment]
I can't see any reason to run a regular test lib in low trust. .NET Fiddle would be nice though, since we could point users directly to running examples from GitHub issues, SO answers etc.

**Comment by benArrayx** [comment]
Just FYI, I arrived here because I'm having trouble running tests in a Medium-Trust environment. I need to do this because where my code will be deployed is running on Medium-Trust and I have no control over that, so I need my tests to also run in Medium-Trust in order to avoid problems.

**Comment by blairconrad** [comment]
> where my code will be deployed is running on Medium-Trust 

Where your _test code_ will be deployed?

**Comment by benArrayx** [comment]
My test code is running on my local development machine.

**Comment by blairconrad** [comment]
@benArrayx, presumably in a full trust environment?

In that case, I am not sure how FakeItEasy's reliance on a high trust environment is a problem. Could you expand a little more?

**Comment by benArrayx** [comment]
I'm using this to simulate / generate a partial trust environment: https://github.com/xunit/samples.xunit/tree/master/PartialTrustExample

Any code which is running in partial trust is getting an error "Inheritance security rules violated while overriding member: 'Castle.Core.Logging.LevelFilteredLogger.InitializeLifetimeService()'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.":"Castle.Core.Logging.LevelFilteredLogger.InitializeLifetimeService()"

`   at FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator..ctor(CastleDynamicProxyInterceptionValidator interceptionValidator)
   at FakeItEasy.RootModule.<>c.<RegisterDependencies>b__0_23(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.SingletonResolver`1.UnresolvedState.Resolve(DictionaryContainer container)
   at FakeItEasy.IoC.DictionaryContainer.SingletonResolver`1.Resolve(DictionaryContainer container)
   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass3_0`1.<Register>b__0(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
   at FakeItEasy.ServiceLocator.Resolve[T]()
   at FakeItEasy.RootModule.<>c.<RegisterDependencies>b__0_25(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.SingletonResolver`1.UnresolvedState.Resolve(DictionaryContainer container)
   at FakeItEasy.IoC.DictionaryContainer.SingletonResolver`1.Resolve(DictionaryContainer container)
   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass3_0`1.<Register>b__0(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
   at FakeItEasy.ServiceLocator.Resolve[T]()
   at FakeItEasy.RootModule.<>c.<RegisterDependencies>b__0_22(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.<>c__DisplayClass3_0`1.<Register>b__0(DictionaryContainer c)
   at FakeItEasy.IoC.DictionaryContainer.Resolve(Type componentType)
   at FakeItEasy.ServiceLocator.Resolve[T]()
   at FakeItEasy.A.get_FakeAndDummyManager()
   at FakeItEasy.A.Fake[T](Action`1 optionsBuilder)
   at FakeItEasy.A.Fake[T]()
etc etc
`

**Comment by blairconrad** [comment]
@benArrayx, I think I was unclear. Why are you running your test code in a partial trust environment?

**Comment by benArrayx** [comment]
Because the production environment is a partial trust environment. Code which runs in full trust fails in partial trust, therefore I need to run tests in partial trust to assure that the code will run when deployed.

**Comment by blairconrad** [comment]
Ah, of course, @benArrayx. If there's no tenable alternative to running the tests in the low trust environment (for example, partitioning the tests so that only a portion of them need to be run in a low-trust environment and the remainder could use FakeItEasy), then perhaps an issue is in order. I wouldn't reuse this one, as it was .NET Fiddle-oriented, and there may be other barriers to running on .NET Fiddle. 

Are you interested in creating the issue? You probably have the most information of anyone to contribute to it.

Likewise, once there is an issue, would you be interested in working on it? @jimmyheaddon's [suggested fix](https://github.com/FakeItEasy/FakeItEasy/issues/414#issuecomment-141229900) may work. Not that I understand any of this.
