### ISSUE TITLE
Add badges to readme

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#433]
E.g. https://github.com/scriptcs/scriptcs/blob/dev/README.md

Badges to consider:

Using http://shields.io/:
* Build/TeamCity CodeBetter
* Downloads/NuGet
* Version/NuGet
* Miscellaneous/GitHub Issues
* Miscellaneous/GitHub forks
* Miscellaneous/GitHub stars

Other:
* Issue Stats http://issuestats.com/github/FakeItEasy/FakeItEasy
  - [![Pull requests](http://issuestats.com/github/FakeItEasy/FakeItEasy/badge/pr?style=flat-square)](http://issuestats.com/github/FakeItEasy/FakeItEasy)
  - [![Issues](http://issuestats.com/github/FakeItEasy/FakeItEasy/badge/issue?style=flat-square)](http://issuestats.com/github/FakeItEasy/FakeItEasy)

I've also raised an issue at shields.io to get support for issuestats (https://github.com/badges/shields/issues/351).

**Comment by blairconrad** [comment]
The badges are pretty, and fun, I've always thought that the "build status" badges were a sign of weakness :wink:. Why would we have a broken build!?

**Comment by adamralph** [comment]
Issue Stats now supports `style=flat-square`. I've updated the description accordingly. See https://github.com/hstove/issue_stats/issues/16#issuecomment-86776028

**Comment by jamiehumphries** [comment]
I have added the Issue Stats badges. Are all of the others wanted?

- Build/TeamCity CodeBetter
- Downloads/NuGet
- Version/NuGet
- Miscellaneous/GitHub Issues
- Miscellaneous/GitHub forks
- Miscellaneous/GitHub stars

**Comment by blairconrad** [comment]
Thanks, @jamiehumphries. The PR looks good to me.

Me, I'd prefer to skip all the GitHub ones—the info is right there on the page with the README).
I'm on the fence about the TeamCity badge—why even entertain the possibility of having a failing build? But I guess it _happens_.

How about two lines of buttons:

[Version/NuGet] [Downloads/NuGet]
[PRs Closed in] [ Issues Closed in] [Build/TeamCity CodeBetter]
?

If you're up for it, you could just tack the additional changes onto #563, squashing the commits or not, as pleases you.

**Comment by jamiehumphries** [comment]
@blairconrad, I have added the extra badges that you suggest.

Unfortunately, if just using the standard Markdown for badges something slightly odd is happening with the image alignment if there are two rows of badges:

![image](https://cloud.githubusercontent.com/assets/3533273/11530448/99f34b6a-98ec-11e5-8ef5-9785fd2e0fb4.png)

I think it looks fine in one line, but it's your call:
![image](https://cloud.githubusercontent.com/assets/3533273/11530464/bb33aa2c-98ec-11e5-8408-69c0a105075a.png)

You can see the full readme as it would be on my branch: https://github.com/jamiehumphries/FakeItEasy/tree/433-badges

**Comment by blairconrad** [comment]
@jamiehumphries 
That's odd. I stole your text and put it in [my own branch](https://github.com/blairconrad/FakeItEasy/tree/f96f558afd18224401cba0be603dc47097a386f9) and got this:

![image](https://cloud.githubusercontent.com/assets/3275797/11534430/bac60a72-98dc-11e5-803b-d1aa51b9a5ce.png)

Do you see the same thing I do?

**Comment by blairconrad** [comment]
But I think you're right, @jamiehumphries, all on one line looks good. I worried that it would introduce wrapping problems, but it doesn't.

**Comment by blairconrad** [comment]
Thanks, @jamiehumphries. I'm enjoying the new README!

**Comment by jamiehumphries** [comment]
Thanks @blairconrad. FWIW, it turns out that the image alignment is different for me from browser to browser weirdly. If I look at the branch you linked in Chrome it looks misaligned, but it actually looks fine in Firefox or Edge. Weird!

Either way, not a problem if it's all on one line :smile:

**Comment by blairconrad** [comment]
That's super weird, since I took my screenshot using Chrome.
Regardless, thanks for your work!

**Comment by adamralph** [comment]
:+1: nice work guys!

**Comment by blairconrad** [comment]
Ha. Thanks, @adamralph, but it was all @jamiehumphries. All I did was hit the "looks good" button. Which it did.
