### ISSUE TITLE
Coverity analysis

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#434]
https://scan.coverity.com/

I'm in the process of setting this up for https://github.com/scriptcs/scriptcs. The idea there is to create a build config on CodeBetter CI which is triggered manually, and builds the solution using the coverity build tool and uploads the results to coverity.

We should add a badge to the readme too, e.g. https://github.com/scriptcs/scriptcs/blob/dev/README.md (see also https://github.com/FakeItEasy/FakeItEasy/issues/433).

**Comment by blairconrad** [comment]
Asking for access to Coverity Scan.
Not sure if you guys can see
https://scan.coverity.com/projects/fakeiteasy-fakeiteasy?tab=project_settings yet or not.
Then again, there's not yet much to see.

**Comment by thomaslevesque** [comment]
> Not sure if you guys can see
> https://scan.coverity.com/projects/fakeiteasy-fakeiteasy?tab=project_settings yet or not.

Nope. "You are not authorized to access this page."

And if I try to register the project myself, it says "Name already registered"

**Comment by blairconrad** [comment]
Ah. It's registered to _people_ not organizations. Invited you both.

**Comment by thomaslevesque** [comment]
Ah, I can see it now. But it doesn't show details, it says:

> While we review your project application you cannot view defects.
> It takes about 1-2 business day to review your association with the project and to make sure project meets open source guidelines.

**Comment by blairconrad** [comment]
Yup. Me too. Sounds like the sort of thing that will resolve itself in 1–2 business days.

**Comment by thomaslevesque** [comment]
Looks like we have a few defects: https://scan7.coverity.com/reports.htm#v26293/p14434/fileInstanceId=11154325&defectInstanceId=2690822&mergedDefectId=1417675

All except 2 are in the tests, and the 2 that are in FIE itself are:
- a false positive ("useless call", which is here only to get the method from an expression)
- a possible NRE that can be ignored (because we know that a `RecordingManager.Factory` is registered in the `ServiceLocator`)

**Comment by blairconrad** [comment]
Bah! I wanted to surprise you with the information.
I'm not against at least looking at the defects in the tests, although we could still categorize tests vs. src.

**Comment by thomaslevesque** [comment]
> I'm not against at least looking at the defects in the tests, although we could still categorize tests vs. src.

Oh, I'm not saying we shouldn't look at them. They're just less critical, since they don't affect production code.

**Comment by blairconrad** [comment]
Okay. Shall we can mark the false positive, and set the NRE to ignored?

Also, how do we like to categorize? More sophisticated than src/tests/samples?

**Comment by thomaslevesque** [comment]
> Okay. Shall we can mark the false positive, and set the NRE to ignored?

Sure. I haven't really looked at how it works yet.

> Also, how do we like to categorize? More sophisticated than src/tests/samples?

If we need to categorize, I guess src/tests/samples is fine.

**Comment by blairconrad** [comment]
I'm not sure that we _need_ to. But our "configuration process" is not yet complete:

![image](https://cloud.githubusercontent.com/assets/3275797/23895441/1c27c5fc-087c-11e7-8a31-00fdedfefb87.png)

Don't you want all the points? :wink:

Categorizing would give us the option to ignore some of the code. I don't really see a need for that yet, but I haven't tried looking a the test defects. It could be that they are too annoying to address by hand. For example, I'm sure we're forever passing around `null`s , and that probably annoys Coverity. I'll set it up now and I'm sure we can always change later.

**Comment by blairconrad** [comment]
Categorized.

Marked [defect 1417682 (useless call)](https://scan7.coverity.com/reports.htm#v26241/p14434/fileInstanceId=11154084&defectInstanceId=2690826&mergedDefectId=1417682) as  a false positive.

Marked [defect 1417671 (derefernce null return value)](https://scan7.coverity.com/reports.htm#v26241/p14434/fileInstanceId=11154151&defectInstanceId=2690804&mergedDefectId=1417671) as ignored.

**Comment by blairconrad** [comment]
Marked all "Explicit null dereferenced" defects as intentional (ignored), except for 1417662, which is marked as a false positive.

**Comment by adamralph** [comment]
Anything left to do here?

**Comment by thomaslevesque** [comment]
> Anything left to do here?

Yes, configure a daily Coverity build on AppVeyor

**Comment by adamralph** [comment]
> configure a daily Coverity build on AppVeyor

Is that not what this is doing (from https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/settings)?:

![image](https://cloud.githubusercontent.com/assets/677704/24199565/5e4c2268-0f0a-11e7-9a85-ce14a346d083.png)

**Comment by blairconrad** [comment]
It is. I'd say let's wait for the build tonight, and once it works, close the issue.

**Comment by thomaslevesque** [comment]
@blairconrad isn't it going to run the default build, which doesn't include the `coverity` target?

**Comment by thomaslevesque** [comment]
Ah, sorry, I missed the condition in appveyor.yml

**Comment by blairconrad** [comment]
@thomaslevesque, it should not…

**Comment by blairconrad** [comment]
The build built and the scan was uploaded.

Unless someone still wants a badge, I think we can close. If we want a badge, that's fine too.

**Comment by thomaslevesque** [comment]
OK to close. I don't really care about the badge, but if we want it, we can add it any time.

**Comment by blairconrad** [comment]
This issue was fixed in [Release 3.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.2.0).

Thanks, Team Coverity! :trophy:
