### ISSUE TITLE
Disable Recursive Fakes

### ISSUE THREAD

**Issue by FrankVDL** [FakeItEasy/FakeItEasy#439]
I'm rather new to FakeItEasy and mocking frameworks in general, but I ran into the following

Considering the following 

```C#
public interface IProductLine
{
  int Count { get; set; }
  IProduct Product { get; set;}
}

var fake  = A.Fake<IProductLine>();

Assert.AreEqual(0, fake.Count);
Assert.IsNull(fake.Product);
```

If I understand correctly the second assert will fail because the Product property is automatically faked.

Is there a way to disable this behaviour ?

**Comment by adamralph** [comment]
I assume you're only providing the assert as an example to prove that what you want on the fake isn't happening? Asserting on a fake is a very odd thing to do.

In this case you can configure the fake to return null like so:

```C#
A.CallTo(() => fake.Product).Returns(null);
```

**Comment by FrankVDL** [comment]
@adamralph indead the assert is just to clarify my point.

I would like to do without configuring all my properties (I real, there are a lot of them)
Specially because the default of an object is Null

I like to assume that the properties of an faked object are automatically set to the system defaults.

**Comment by blairconrad** [comment]
@FrankVDL, I don't think we have a way out of the box. However, there's also

```csharp
A.CallTo(fake).WithReturnType<IProduct >().Returns(null);
```

If many of the properties have the same return types, this could save you a little time.

**Comment by blairconrad** [comment]
Oh! Or something even hackier, that **will only work for reference types**

```csharp
A.CallTo(fake).DoesNothing();
```

If the return value is a value type, an error will be thrown. But you could handle those ones with `WithReturnType`.

**Comment by adamralph** [comment]
@FrankVDL from my experience, null return values are the exception rather than the norm, which is why FakeItEasy automatically fakes everything by default and null return values need to be configured explicitly. This is the first time I can remember someone wanting nulls by default for all methods and properties, but that's not to says it's 'wrong' in your case :wink:.

**Comment by FrankVDL** [comment]
Only the properties should default to null, not the methods.

But if I understand correctly, it's unlikely this 'feature' will make it into a next release ? ;-)

**Comment by adamralph** [comment]
My previous comment refers to properties as well as methods (properties are anyway just disguised methods).

How about th suggestion from @blairconrad? Would that work for you?

**Comment by FrankVDL** [comment]
The first suggestion of @blairconrad will result in the same amount of work.
It's unlikely that multiple properties return the same type.

The seconds suggestion is rather unclear to me.
Doesn't make this the fake object useless ?

**Comment by adamralph** [comment]
You can still do

```C#
A.CallTo(fake).DoesNothing();
A.CallTo(() => fake.SomeSpecificMethod(...)).Returns(...);
```

The `DoesNothing` will act as a 'default' configuration with the more specifics configurations giving you  the specific behaviours you want. ( @blairconrad correct if I'm wrong :wink: )

**Comment by FrankVDL** [comment]
Ok,

 that might work for me

**Comment by blairconrad** [comment]
@adamralph, you are not wrong. This is indeed what I had in mind. It's an example of [changing behaviour between calls](https://github.com/FakeItEasy/FakeItEasy/wiki/Limited-Call-Specifications#changing-behavior-between-calls).

**Comment by blairconrad** [comment]
@FrankVDL I just noticed your comment about only having auto-faking disabled for return values on _properties_. As @adamralph mentioned, properties are just methods in disguise, so you may want to amend my suggestion to

```csharp
A.CallTo(fake).Where(call => call.Method.Name.StartsWith("get_")).DoesNothing();
```

And then additional overrides as you need. Unless you name methods starting with "get_", this should only turn off the auto-fake return values for property getters.

**Comment by blairconrad** [comment]
Also, @FrankVDL, I think you signed up for a GitHub account just to make this issue. I'm flattered that you cared enough. Thanks!

Okay. I'll leave everyone alone now.
