### ISSUE TITLE
Rename IDummyDefinition, DummyDefinition

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#441]
As suggested by @patrik-hagne  in https://github.com/FakeItEasy/FakeItEasy/issues/402#issuecomment-70158778 and subsequently refined by @adamralph, `IDummyDefinition` could have a better name. 

Current best suggestion (as I see it): `IDummyFactory`.

Make the change **and** the corresponding one for `DummyDefinition<T>`.

**Comment by blairconrad** [comment]
In addition to renaming the types,
* `CanCreateDummyOfType` (`CreateDummy` before 2.0.0) became `CanCreate` and
* `CreateDummyOfType` became `Create`

**Comment by adamralph** [comment]
Was it `CanCreateDummy` before 2.0?

**Comment by blairconrad** [comment]
No. I completely messed that comment up.  Let's try again.

In addition to renaming the types,
* `CreateDummyOfType` (`CreateDummy` before 2.0.0) became `Create` and
* `CanCreateDummyOfType` (closest pre-2.0.0 analogue: `ForType`) became `CanCreate`

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
