### ISSUE TITLE
1.25.2 Release

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#442]
**Ready** when all other issues forming part of the release are **Done**.

- [x] run code analysis in VS in *Release* mode and address violations (send a regular PR which must be merged before continuing)
- [x] raise PR from hotfix branch to master - https://github.com/FakeItEasy/FakeItEasy/pull/445
- [x] merge hotfix to master - https://github.com/FakeItEasy/FakeItEasy/pull/445
- [x] if necessary, change `VERSION_SUFFIX` on [CI Server](http://teamcity.codebetter.com/admin/editBuildParams.html?id=buildType:bt929)
      to appropriate "-beta123" or "" (for non-betas) value and initiate a build
- [x] check build
-  edit draft release in [GitHub UI](https://github.com/FakeItEasy/FakeItEasy/releases):
    - [x] complete release notes, mentioning non-owner contributors, if any
    - [x] attach nupkg
    - [x] publish the release
- [x] push NuGet package
- [x] copy release notes from GitHub to NuGet
- [x] de-list pre-release or superseded buggy NuGet packages if present (copy any release notes forward to the new version)
- [x] update website with contributors list (if in place)
- [x] tweet, mentioning contributors and post link as comment here for easy retweeting ;-) - https://github.com/FakeItEasy/FakeItEasy/issues/440#issuecomment-71358769
- [x] post tweet in JabbR ([fakeiteasy][1] and [general-chat][2]) and Gitter ([FakeItEasy/FakeItEasy][3])
- [x] post links to the NuGet and GitHub release in each issue in this milestone, with thanks to contributors
- [x] close all issues on this milestone
- [ ] close this milestone

[1]: https://jabbr.net/#/rooms/fakeiteasy
[2]: https://jabbr.net/#/rooms/general-chat
[3]: https://gitter.im/FakeItEasy/FakeItEasy

**Comment by adamralph** [comment]
@blairconrad I've gone as far as I dare without getting your seal of approval to perform the release. I have dash now so if you're happy to release then please go ahead, otherwise I can pick it up again later.

**Comment by blairconrad** [comment]
This issue has been fixed in release 1.25.2.

https://www.nuget.org/packages/FakeItEasy/1.25.2
https://github.com/FakeItEasy/FakeItEasy/releases/tag/1.25.2

**Comment by blairconrad** [comment]
https://twitter.com/fakeiteasyfx/status/559320796418805760

**Comment by blairconrad** [comment]
Okay, @adamralph. I've gone as far as I'd like until we address my question over in #445.
Great work.
