### ISSUE TITLE
List project on Up For Grabs

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#452]
http://up-for-grabs.net/#/

**Comment by adamralph** [comment]
One question before we do this. Should we change our 'easyfix' label to the more idiomatic 'up-for-grabs'?

**Comment by blairconrad** [comment]
In general, these names don't worry me too much. By all means, conform.

**Comment by blairconrad** [comment]
https://github.com/dahlbyk/up-for-grabs.net/pull/156

**Comment by adamralph** [comment]
Awesomeness

**Comment by blairconrad** [comment]
![image](https://cloud.githubusercontent.com/assets/3275797/6029157/a484d7a6-abbc-11e4-8a64-93b12b3b5490.png)

Closed via https://github.com/dahlbyk/up-for-grabs.net/pull/156

**Comment by adamralph** [comment]
woot!
