### ISSUE TITLE
document what's new in 2.0

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#453]
We should make or update

- [x] [Changes in version 2.0](https://github.com/FakeItEasy/FakeItEasy/wiki/Changes-in-version-2.0), cribbed from [xBehave.net's "Changes in version 2.0"](https://github.com/xbehave/xbehave.net/wiki/Changes-in-version-2.0)
- [x] [Creating Fakes](https://github.com/FakeItEasy/FakeItEasy/wiki/Creating-Fakes) to include implicit creation options
- [x] [Raising Events](https://github.com/FakeItEasy/FakeItEasy/wiki/Raising-Events) - no `Now` or `Go`, required typeparam, null sender actually raises with null, and arbitrary event raising
- [x] [Dummies](https://github.com/FakeItEasy/FakeItEasy/wiki/Dummies), specifically "Custom Dummy Creation" and 
    - [x] a note about new `Lazy` Dummies
- [x] New [Ordered Assertions](https://github.com/FakeItEasy/FakeItEasy/wiki/Ordered-assertions)
- [x] [Custom Dummy Creation](https://github.com/FakeItEasy/FakeItEasy/wiki/Custom-Dummy-Creation), [implicit creation options](https://github.com/FakeItEasy/FakeItEasy/wiki/Implicit-Creation-Options), [Formatting Argument Values](https://github.com/FakeItEasy/FakeItEasy/wiki/Formatting-Argument-Values)
- [x] [Lazy or Task dummies](https://github.com/FakeItEasy/FakeItEasy/wiki/Dummies)
- [x] [Default fake behavior](https://github.com/FakeItEasy/FakeItEasy/wiki/Default-fake-behavior) - unconfigured methods return Dummies now

**Comment by blairconrad** [comment]
It could do with a little more polish and organization, but the raw information is now in 
[Changes in version 2.0](https://github.com/FakeItEasy/FakeItEasy/wiki/Changes-in-version-2.0). I'll continue working on it as time allows.

**Comment by blairconrad** [comment]
Aside from this effort, a number of wiki topics will need updating (for example, event raising looks all different now).
From the vague naming of this issue (darn you, @blairconrad), I'm not sure whether we want to make a separate issue or track here.

**Comment by adamralph** [comment]
I think track here. The easiest way is probably to have the v1 and v2 versions of the docs living alongside each other, e.g. each page that needs it can have v1 and v2 sections. Some time (probably much later) we can remove the v1 sections.

**Comment by blairconrad** [comment]
:+1:

**Comment by blairconrad** [comment]
Updated description to include a task list. That should be the highlights.
Is it early to start putting in 2.0 content, marked as such? As far as I know, aside from bookkeeping, #312 is the only outstanding issue.

**Comment by blairconrad** [comment]
I've updated the [Dummies](https://github.com/FakeItEasy/FakeItEasy/wiki/Dummies) page to explain the new Dummy Factories. Thoughts?

It's not the most elegant, but I think it'll do for now.

My inclination would be to at least swap the 1.x and 2.x sections once 2.0 is released (although this would not be urgent) or (my preference) move the 1.x section to its own page, with a pointer near the top of the "custom dummy creation" section like 

> Custom Dummy creation changed significantly in 2.0, becoming more flexible. If you're using FakeItEasy 1.x, upgrade now or [see the 1.x Dummy Definition documentation](this link doesn't go anywhere).

**Comment by adamralph** [comment]
Hmmm.. yes, I see what you mean. I think your suggestion of moving the 1.x docs to their own page is a good idea. How about we use an approach like this:

Top of v2 page:

> Version 2.x | [Version 1.x](points to v1 page)

Top of v1 page:

> [Version 2.x](points to V2 page) | Version 1.x

I'd be fine with duplicating content on each page, given that they are not going to live alongside each other for very long. I also think we should make v2 the default page starting now, as long as it's clear that it is a v2 page and it's easy to navigate to v1.

BTW - that dummies page is quite long. I think the 'custom dummy creation' part should probably be spun off into it's own page.

**Comment by blairconrad** [comment]
> I'd be fine with duplicating content on each page, given that they are not going to live alongside each other for very long.

You're proposing ditching the Version 1.x pages in the nearish future? How long were you thinking about? A few releases in the 2.x stream?
Or do I misunderstand?

**Comment by adamralph** [comment]
Oh, sorry, not very consistent in my thinking there! Actually yes, they probably will stick around for sometime. Perhaps it doesn't need to be so general a solution, more a case by case basis. E.g. in the main dummies page there is only small note for 2.0 but 'custom dummy creation' probably warrants a 2.x page and a 1.x page.

**Comment by blairconrad** [comment]
Oh, absolutely. I'd planned to have the one "main Dummies" page, with twins for the "custom dummy" page.

**Comment by blairconrad** [comment]
Split the pages. Looks like this:

![image](https://cloud.githubusercontent.com/assets/3275797/6318743/47c8feee-ba70-11e4-81a4-4dc8f3fbfc8c.png)

Another options for distinguishing v 1.x and 2.x could be

![image](https://cloud.githubusercontent.com/assets/3275797/6318748/6fe6b97a-ba70-11e4-80b7-42f17dff30cb.png)

**Comment by adamralph** [comment]
Why does the first example have both the version selectors and 2.x after the subtitle?

**Comment by adamralph** [comment]
Could they look something like this?

![image](https://cloud.githubusercontent.com/assets/677704/6318800/9b6a172a-baa4-11e4-8ab0-acce3ef4d7f6.png)

**Comment by adamralph** [comment]
Or perhaps:

![image](https://cloud.githubusercontent.com/assets/677704/6318810/d7fc01d0-baa4-11e4-979d-f0738ef15774.png)

**Comment by adamralph** [comment]
I've been using MSDN as an inspiration, i.e.

![image](https://cloud.githubusercontent.com/assets/677704/6318840/8de6f9dc-baa5-11e4-80d5-796bf75c297b.png)

Obviously we can't get the drop down though....

**Comment by blairconrad** [comment]
The version in the subtitle was a holdover from when I split the page. I'd forgotten to strip. Done.
Of course the actual title for the two pages has to be different. As is, the 1.x version has the "1.x" in the title.

I was thinking about the MSDN example as well, and bemoaning the lack of dropdown.

Updated:

* https://github.com/FakeItEasy/FakeItEasy/wiki/Custom-Dummy-Creation-in-version-1.x
* https://github.com/FakeItEasy/FakeItEasy/wiki/Custom-Dummy-Creation

**Comment by adamralph** [comment]
They look great!

**Comment by adamralph** [comment]
@blairconrad I checked off "New Ordered Assertions" since I saw https://github.com/FakeItEasy/FakeItEasy/wiki/Ordered-assertions (thanks for that!)

I have one question:

From https://github.com/FakeItEasy/FakeItEasy/wiki/Ordered-Assertions-in-1.x

> Note that this feature is not available in the 1.0.x versions, and the API has changed in the 2.x versions.

Does that actually mean that the entire ordered assertions feature wasn't available in 1.0.x versions? I see only one on NuGet, [1.0.0.5](https://www.nuget.org/packages/FakeItEasy/1.0.0.5) - the next version after that is 1.5.3970.199.

**Comment by blairconrad** [comment]
@adamralph asked

> Does that actually mean that the entire ordered assertions feature wasn't available in 1.0.x versions? I see only one on NuGet, 1.0.0.5 - the next version after that is 1.5.3970.199.

That's my understanding. I just preserved the text that @patrik-hagne had written in [his version of the docs](https://github.com/FakeItEasy/FakeItEasy/wiki/Ordered-assertions/64d1e88a0edbc004d4dd58e76d712bc5081aa4a9). That's the second version of the page, but the text you quote was there from the get-go.
I've no reason to doubt its accuracy, but haven't checked. There are several other 1.0.x packages [at the Google Code project](https://code.google.com/archive/p/fakeiteasy/downloads?page=2).

**Comment by adamralph** [comment]
OK, that all makes sense, thanks. The v1/v2 page history threw me off. I thought the 1.x page was a new page, but I get it now.

**Comment by blairconrad** [comment]
I think we're on the cusp of 2.0.0-rc01. There's nothing left to add to "Changes in version 2.0" as far as I know, but I'm loathe to mark it as done (and close this issue) until we release the RC and have decided not to do anything else.

**Comment by adamralph** [comment]
I think we should mark it done and close this issue.

To me an RC means "we are done, this is what we are planning to release, go find holes in it". If, indeed, any issues arise, then updating the docs should form part of closing those issues.

**Comment by thomaslevesque** [comment]
Agreed, let's close it. I don't think there's anything else we want to include in 2.0.x.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
