### ISSUE TITLE
Switch from MSpec to xbehave

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#458]
I've lately been preferring to write comprehensive end-to-end tests (our "specs" or acceptance tests) to unit or integration (component) tests whenever it's feasible.
To this day, every time I do something more complicated than add a single test case, I have to look up the MSpec syntax and/or copy an existing spec.
I also found it difficult and cumbersome to reuse anything other than the test setups.

Perhaps we could adopt another framework? One option would be [xbehave.net](http://xbehave.github.io/). The first time I used it, I found the test pattern easy to understand and apply.
In addition, being based on XUnit, one can leverage the lifecycle and reuse patterns in that framework, and use any testrunners that work for XUnit.

Thoughts? Objections?

**Comment by adamralph** [comment]
Obviously I'm all for [xbehave.net](http://xbehave.github.io/) :wink:

**Comment by adamralph** [comment]
https://github.com/ursenzler/MSpec2xBehaveConverter /via @ursenzler

Just saying' :wink:

**Comment by blairconrad** [comment]
Interesting. I'd rather save this kind of activity for post-2.0 release, but a tool sounds fun, and looks like it would give us a leg up.

**Comment by philippdolder** [comment]
appccelerate is migrating/ed as well :-)

**Comment by ursenzler** [comment]
If you need help with the migrator, let me know. It probably can be tweaked to better match your coding style.

**Comment by adamralph** [comment]
@philippdolder the testing toolkit of champions :wink: 

@ursenzler to help get us started, it would be really great if you could run your migrator against the FakeItEasy source and open a PR, even with just the raw results of the migration.

**Comment by ursenzler** [comment]
I can do that for you.

**Comment by matkoch** [comment]
I authored a new test framework called [TestFx](https://github.com/matkoch/TestFx). I just [ported some tests](https://gist.github.com/matkoch/79a8d5d5c4ea477673e9) from the `CreationSpecs` *and* from the `NullGuardedConstraintTests` (although it is a NUnit test - just for showcasing).

**Comment by ursenzler** [comment]
See pull request https://github.com/FakeItEasy/FakeItEasy/pull/528 for how it would like with my converter.

Let me know, whether I should convert the rest of the specs.
