### ISSUE TITLE
investigate interaction between `Implements` and `CallsBaseMethods`

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#463]
``` c#
public interface IInterface
{
    void DoSomething();
}

public interface IOtherInterface : IInterface
{
}

public abstract class AbstractClass : IInterface
{
    public void DoSomething()
    {
        Console.WriteLine("Got here");
    }
}

[Test]
public void Implements_and_CallsBaseMethods_should_get_along()
{
    var fake = (IOtherInterface)A.Fake<AbstractClass>(builder => builder
        .Implements(typeof(IOtherInterface))
        .CallsBaseMethods());

    fake.DoSomething();
}
```

`fakeDoSomething` does _not_ call `AbstractClass.DoSomething`, no matter in which order the `Implements` and `CallsBaseMethods` are used.

However, 

``` c#
var fake = (IOtherInterface)A.Fake<AbstractClass>(builder => builder
    .Implements(typeof(IOtherInterface)));

A.CallTo(() => fake.DoSomething()).CallsBaseMethod();
fake.DoSomething();
```

does call `AbstractClass.DoSomething`.

Omitting the `(IOtherInterface)` cast also causes `AbstractClass.DoSomething` to be executed:

``` c#
 var fake = A.Fake<AbstractClass>(builder => builder
     .Implements(typeof(IOtherInterface))
     .CallsBaseMethods());

 fake.DoSomething();
```

Found while investigating an answer to [Having an interface fake inherit from abstract while both share same interface inheritance](http://stackoverflow.com/questions/28697918/fakeiteasy-having-an-interface-fake-inherit-from-abstract-while-both-share-sam).

**Comment by adamralph** [comment]
Interesting. This seems like a bug.

**Comment by blairconrad** [comment]
Indeed. Probably something like `CallsBaseMethods` looks at the methods on the type and then only adds the "delegate" instruction if they're not abstract. They're abstract _on the interface_, but not on the type we're faking, so we accidentally miss out. Then the call comes in, using the interface's version of the method, and it sails right on past.

Note: I have not looked. I'm just guessing.

Of course, even if this is true, I wonder if we wouldn't need to investigate method equality on the matchers. Should a call to `IInterface.Method` match `Class.Method`, assuming the latter implements the former? 
I should stop speculating until some actual research has been done.

**Comment by thomaslevesque** [comment]
> Indeed. Probably something like CallsBaseMethods looks at the methods on the type and then only adds the "delegate" instruction if they're not abstract.

[Exactly](https://github.com/FakeItEasy/FakeItEasy/blob/master/src/FakeItEasy/FakeOptionsExtensions.cs#L60-L62)!

```
        public static IFakeOptions<T> CallsBaseMethods<T>(this IFakeOptions<T> options)
        {
            Guard.AgainstNull(options, nameof(options));

            return options.ConfigureFake(fake => A.CallTo(fake)
                                                  .Where(call => !call.Method.IsAbstract)
                                                  .CallsBaseMethod());
        }
```

Not sure how to fix it, though.

**Comment by thomaslevesque** [comment]
Here's a similar scenario that is more worrying:

```
public interface IInterface
{
    void DoSomething();
}

public abstract class AbstractClass
{
    public void DoSomething()
    {
        Console.WriteLine("Got here");
    }
}

public void Test()
{
    var fake = (IInterface)A.Fake<AbstractClass>(builder => builder
        .Implements(typeof(IInterface))
        .CallsBaseMethods());

    A.CallTo(() => fake.DoSomething()).CallsBaseMethod();

    fake.DoSomething();
}
```

This code throws:

> An unhandled exception of type 'System.NotImplementedException' occurred in fakeiteasy.dll
>
> Additional information: This is a DynamicProxy2 error: The interceptor attempted to 'Proceed' for method 'Void DoSomething()' which has no target. When calling method without target there is no implementation to 'proceed' to and it is the responsibility of the interceptor to mimic the implementation (set return value, out arguments etc)

**Comment by thomaslevesque** [comment]
Apparently `IInterface.DoSomething()` isn't properly mapped to `AbstractClass.DoSomething()`. This happens only for additional interfaces (i.e. interfaces not implemented by the faked class), so it *might* be a bug in Castle.Core.

**Comment by blairconrad** [comment]
Am I oversimplifying, or does this whole issue boil down to:

1. `Implements` acts like explicit interface implementation, and
2. explicitly-implemented interface methods are distinct from implicitly-implemented ones

?

**Comment by thomaslevesque** [comment]
I think your analysis is correct, but to be honest, I'm no longer sure of anything about this issue...

**Comment by blairconrad** [comment]
I'm coming to believe that it's not a bug. It's just the way `Implements` works: like explicit interface implementation. And I don't think we'd want to _change_ the behaviour anyhow, mostly because we now have the flexibility of configuring the interface methods or the class methods.
I don't think we should pursue a change. We could potentially document that `Implements` acts like explicit implementation.

**Comment by thomaslevesque** [comment]
Sounds good to me. 👍 for not fixing, since it's not broken.
