### ISSUE TITLE
Assess impact of 2.0 changes on popular packages

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#468]
(From https://github.com/FakeItEasy/FakeItEasy/issues/460#issuecomment-81585682)

> we should take some of the popular integration packages, at a minimum AutoFixture.AutoFakeItEasy, Machine.Fakes.FakeItEasy and Autofac.Extras.FakeItEasy and attempt to upgrade their source to the latest 2.0 beta to assess impact

**edit by @blairconrad. Adding task list**

- [x] AutoFixture.AutoFakeItEasy - @blairconrad - good
- [x] Machine.Fakes.FakeItEasy  - @blairconrad - good
- [x] Autofac.Extras.FakeItEasy - @adamralph - breaks - PR's raised https://github.com/autofac/Autofac.Extras.FakeItEasy/pull/1 and https://github.com/autofac/Autofac.Extras.FakeItEasy/pull/2

**Comment by blairconrad** [comment]
I believe AutoFixture.AutoFakeItEasy is fine, if we close #460 without making a change (specifically if we don't remove `Fake<T>`.) I'll rerun with the latest beta to confirm. 
Heck. I'm going to go edit the description with a task list.

**Comment by blairconrad** [comment]
Okay. I've added the Big Three to the task list. I suggest we go through those first and then reassess. Perhaps if there's no change, we just stop. Or mail the maintainers of selected other packages or something.

**Comment by adamralph** [comment]
The checklist has Autofac in it twice? Which one is supposed to be AutoFixture?

**Comment by blairconrad** [comment]
Bother. Fixed.

**Comment by adamralph** [comment]
Given that I wrote the Autofac one, I'll take a look :wink:

**Comment by blairconrad** [comment]
AutoFixture.AutoFakeItEasy builds and all tests pass with FakeItEasy 2.0.0-beta007.

**Comment by adamralph** [comment]
Autofac.Extras.FakeItEasy breaks with 2.0 since it's using `IFakeOptionsBuilder<T>.OnFakeCreated()`.

I've raised a PR to restrict the package dependency to exclude FIE 2.0 https://github.com/autofac/Autofac.Extras.FakeItEasy/pull/1

**Comment by adamralph** [comment]
Also raised https://github.com/autofac/Autofac.Extras.FakeItEasy/pull/2 for the switch to FIE 2.0.

**Comment by blairconrad** [comment]
2/3 packages were fine. Do we feel a need to chase down anyone else who may be consuming FakeItEasy? After this effort and the tweets about the new release that's coming, I'm inclined stop, but don't mind doing more work.

**Comment by blairconrad** [comment]
Hmm. NuGet allows one to contact owners. I could drop a note in there for the dependent packages.

**Comment by blairconrad** [comment]
I've contacted the owners of every NuGet package that depends on FakeItEasy, save Autofac.Extras.FakeItEasy. The message to them would be more complicated and it seems @adamralph  is on top of it.

**Comment by adamralph** [comment]
wow! nice work! :dizzy_face:

**Comment by blairconrad** [comment]
It was only 18. The power of a lovingly-crafted form letter.

**Comment by blairconrad** [comment]
We've assess the packages we intended to and sent e-mail to the owners of everything else we know about. And tweeted.
I think we're done here.

**Comment by adamralph** [comment]
:+1:

**Comment by adamralph** [comment]
Oh, one thing - we still have 2 outstanding breaking changes on the 2.0 milestone - https://github.com/FakeItEasy/FakeItEasy/issues/467 and https://github.com/FakeItEasy/FakeItEasy/issues/461.

Will we not have to reassess once they go in?

**Comment by blairconrad** [comment]
The one I'm sure won't make a difference, but the other likely will.
On the other hand, owners of dependent packages have been e-mailed (even the owners of the ones we've checked).
Now that they're aware, I'm inclined to let them keep an eye on the releases.

If you'd prefer, we can recheck the 3 that we've already checked (I think you'd check Autofac.Extras.FakeItEasy anyhow), but I think re-e-mailing the other packages' owners is tantamount to harassment.

**Comment by adamralph** [comment]
Yeah, let's not email again, but let's re-check the main three. Shall we re-open?

**Comment by adamralph** [comment]
Actually, I'll just add to the checklist on the release issue.

**Comment by adamralph** [comment]
Checklist items added to #336 for main 3 packages

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
