### ISSUE TITLE
Suggestion : It.IsAny

### ISSUE THREAD

**Issue by linvi** [FakeItEasy/FakeItEasy#469]
As FakeItEasy is trying to be very verbal, I think you should add the **It** class.

Here is the current syntax.
`A.Fake<Animal>.Ignored;` // That we should read as : "An Animal" which is a parameter "That is Ignored"

But with **It** I think the reading experience is much better.
`It.IsAny<Animal>();` // Now the meaning of this is obvious, we have a parameter that can be Any object of type Animal.

Here my very simple implementation:

```C#
public static class It
{
    public static T IsAny<T>()
    {
        return A<T>.Ignored;
    }
}
```

What do you think?

**Comment by blairconrad** [comment]
Thanks for the idea, @linvi. Your way does read nicely.

We've been tending toward a "everything hangs off `A`" approach, to aid discoverability. Also, whenever practical "there's one way to do it", so I'm inclined to leave things as they are.

Of course, if the syntax does bother you, it seems that it would be an easy extension to add to your own projects, just like the suggested repeated syntax changes in #354.

**Comment by linvi** [comment]
Alright, this was just a suggestion :)

Thanks for the good work.
Linvi

**Comment by adamralph** [comment]
Just a nitpick, but the current syntax is actually:
```C#
A<Animal>.Ignored
```
with an optional shorthand of
```C#
A<Animal>._
```
I'm with Blair Conrad. The above provides the idiomatic way of specifying an unrestricted argument value and whether 
```C#
It.IsAny<Animal>()
```
is any better is really in the eye of the beholder.  If someone prefers it, they can just write a trivial extension method, as you demonstrate @linvi.

**Comment by adamralph** [comment]
Or of course, you could publish a NuGet package with your API embellishments :wink:

**Comment by thomaslevesque** [comment]
> Of course, if the syntax does bother you, it seems that it would be an easy extension to add to your own projects

Actually, it wouldn't be that easy. `A.CallTo` takes an expression, and FIE analyzes that expression to recognize `A<T>.Ignored` or `A<T>._`. Just making another method that returns `A<T>.Ignored` won't work, because it won't be recognized by FIE when it analyzes the expression. This is the same reason why this doesn't work:

```
var anyString = A<string>.Ignored;
A.CallTo(() => foo.Get(anyString)).Returns("test");
```

I think it would be a good thing to make `A<T>.Ignored` throw an exception, because it's never supposed to be invoked (it just returns `default(T)` anyway). It should only appear in call specification expressions, which are not invoked, only analyzed.

**Comment by blairconrad** [comment]
>  Just making another method that returns `A<T>.Ignored` won't work, 

YES! Excellent point, @thomaslevesque. How embarrassing.

> I think it would be a good thing to make `A<T>.Ignored` throw an exception

I've not performed an analysis, but it sounds right to me.
The now-private `Now` [works the same way](https://github.com/FakeItEasy/FakeItEasy/blob/bd57a05c0de5ff37609230fd1b8bc4ec45bc9d4d/Source/FakeItEasy/Core/Raise.of.TEventArgs.cs#L72).

**Comment by blairconrad** [comment]
@thomaslevesque has raised #559 to cover exception-throwing from `Ignored`.
