### ISSUE TITLE
Allow calls on expressions where the fake is found by partly evaluating the expression

### ISSUE THREAD

**Issue by TimLovellSmith** [FakeItEasy/FakeItEasy#475]
scenario:

    class P
    {
        public virtual int Foo() { return 0; }
    }

    class T
    {
        public P P { get; set; }
    }

    void Test()
    {
        var t = new T { P = A.Fake<P>(); }
        A.CallTo(() => t.P.Foo()).Returns(2);
    }

observed with FakeItEasy 1.25.1 - this test fails with ArgumentException "The specified call is not made on a fake object."

expected: it passes :)

**Comment by TimLovellSmith** [comment]
Never mind... it looks like I really did something wrong here. Again. :)

**Comment by TimLovellSmith** [comment]
(my test was actually

void Test()
{
    var t = new T {};
    A.CallTo(() => t.P.Foo()).Returns(2);
})

**Comment by blairconrad** [comment]
Doncha hate when that happens?

(Thanks for including the second sample, @TimLovellSmith. I'd've gone nuts wondering.)
