### ISSUE TITLE
Migration of code using Moq's Mock.Of syntax

### ISSUE THREAD

**Issue by vossad01** [FakeItEasy/FakeItEasy#479]
When looking at migration from Moq to FakeItEasy, is there any analog to Moq's `Mock.Of` syntax?  I am not seeing it mentioned in the migration search pattern doc.

If you are not familiar with the the feature:
```
Mock.Of<IDocumentRepository>( x => x.Get( It.IsAny<Guid>() ) == new Document() );
```
The above creates an implementation of `IDocumentRepository` that returns the new document when `Get` is called with any Guid.  The syntax is convenient for tersely creating simple mocks.  Multiple configurations can be specified using `&&`.

**Comment by blairconrad** [comment]
Perhaps I'm missing the point of `Mock.Of`, but 

```c#
var fakeRepo = A.Fake<IDocumentRepository>();
A.CallTo(()=>fakeRepo.Get(A<Guid>.Ignored)).Returns(new Document());
```

?

**Comment by blairconrad** [comment]
Or is it the one-lineness that you're most excited about?

**Comment by vossad01** [comment]
Yep, the strength of `Mock.Of` is that it can be done inline where the mock is needed instead of needing separate declaration and configuration 

``` C#
DoIt( Mock.Of<IDocumentRepository>( x => x.Get( It.IsAny<Guid>() ) == new Document() ) );
```

becomes
``` C#
var fakeRepo = A.Fake<IDocumentRepository>();
A.CallTo(()=>fakeRepo.Get(A<Guid>.Ignored)).Returns(new Document());
DoIt(fakeRepo);
```

which can add a lot to the length of tests

**Comment by blairconrad** [comment]
Oh. Not the sort of thing that really bothers me personally. One could always wrap creation in a helper method.
Or

```c#
DoIt(A.Fake<IDocumentRepository>(
    options => options.ConfigureFake(f =>
                                     A.CallTo(() => f.Get(A<Guid>.Ignored)).Returns(new Document()))));
```

**Comment by vossad01** [comment]
Ah, `ConfigureFake` would seem to be the best analog.

Thanks!

**Comment by blairconrad** [comment]
No problem.
