### ISSUE TITLE
How to fake a call to a generic method that returns the generic type parameter?

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#488]
I have an interface like this:

    public interface IDispatcherService
    {
        void Invoke(Action action);
        T Invoke<T>(Func<T> func);
    }

Each unit test could fake the `Invoke<T>` method by specifying `T` explicitly, but in practice, the behavior of the fake will always be the same: just invoke `func` and return its result. So I'd like to create a `FakeConfigurator` for this interface, but I can't because the method is generic. I looked at [this answer](http://stackoverflow.com/a/22867739/98713) on StackOverflow, but it doesn't apply here, because the return type is `T`.

Is there a way to do it that I'm not aware of?

**Comment by blairconrad** [comment]
Nothing comes to mind. On the other hand,

> in practice, the behavior of the fake will always be the same: just invoke func and return its result

so how do you feel about

```csharp
public abstract class DispatcherService:IDispatcherService
{
    public abstract void Invoke(Action action);

    public virtual T Invoke<T>(Func<T> func)
    {
        return func();
    }
}

…

IDispatcherService fake = A.Fake<DispatcherService>(options => options.CallsBaseMethods());
```

?

**Comment by adamralph** [comment]
:+1:

**Comment by blairconrad** [comment]
Sometimes I like the low-tech approach. In fact, unless there's a compelling need to assert that methods were called and whatnot, given this interface, I'd just make a concrete fake class and not even use FakeItEasy…

**Comment by adamralph** [comment]
Yeah, good point.

**Comment by thomaslevesque** [comment]
Yes, I ended up writing a fake class manually. This approach is fine, I was just wondering if I was missing something.

Thanks

**Comment by blairconrad** [comment]
@thomaslevesque, I don't think so. DynamicProxy (as I understand it) doesn't have support for open generic types (or I assume, methods), and FakeItEasy doesn't provide any extra help. I've never tried providing support for these kinds of things, but I've  feeling there'd be hurdles both in the core of the library and in providing a nice API.
