### ISSUE TITLE
Create a Roslyn analyzer package

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#489]
To provide diagnostics on usage of FakeItEasy in VS2015, as discussed in https://github.com/FakeItEasy/FakeItEasy/issues/56#issuecomment-100865677

**Comment by adamralph** [comment]
Perhaps useful: https://www.microsoftvirtualacademy.com/en-us/training-courses/building-roslynbased-analyzers-and-diagnostics-12596

**Comment by adamralph** [comment]
I'd like to close this in favour of #490. "Create a Roslyn analyzer package" is just an step in delivering our first actual analyzer, which is described by #490.

**Comment by thomaslevesque** [comment]
I agree, this issue doesn't really make sense on its own. Closing now.
