### ISSUE TITLE
Seo the NuGet-page

### ISSUE THREAD

**Issue by patrik-hagne** [FakeItEasy/FakeItEasy#493]
@FakeItEasy/owners I just updated the title of the NuGet-package to get "mocking" and "faking" in there. Hope you don't disagree.

**Comment by blairconrad** [comment]
Looks good to me, @patrik-hagne. Your change just affects the current version, yes? (I'm still a NuGet newbie.)
We'll need also to update the .nuspec?

**Comment by adamralph** [comment]
We already have mocking and faking in the description and the tags but I know that NuGet's search algorithm is rather... 'special'.

Generally I don't like it when the title of the package diverges from the ID, but in this case it is the ID followed by a suffix, and that I can live with.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
