### ISSUE TITLE
IFakeCallProcessor.Process throws enumeratable collection modified (unthreadsafe tests)

### ISSUE THREAD

**Issue by TimLovellSmith** [FakeItEasy/FakeItEasy#502]
I had my tests fail an interesting way today that I initially wondered if it was a thread safety bug in FakeItEasy:

```csharp
var ruleToUse =
    (from rule in this.AllRules
    where rule.Rule.IsApplicableTo(fakeObjectCall) && rule.HasNotBeenCalledSpecifiedNumberOfTimes()
    select rule).First();
```

What happens is somehow the collection AllRules is modified during enumeration... by another test! (Since this test has no background work).

```csharp
private IEnumerable<CallRuleMetadata> AllRules
{
    get { return this.preUserRules.Concat(this.AllUserRules.Concat(this.postUserRules)); }
}
```

```
System.InvalidOperationException: Collection was modified after the enumerator was instantiated.

   System.Collections.Generic.LinkedList`1.Enumerator.MoveNext()
   System.Linq.Enumerable.<ConcatIterator>d__1`1.MoveNext()
   System.Linq.Enumerable.<ConcatIterator>d__1`1.MoveNext()
   System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(IWritableFakeObjectCall fakeObjectCall) in c:\repo\FakeItEasy\Source\FakeItEasy\Core\FakeManager.cs:line 161
   FakeItEasy.Creation.CastleDynamicProxy.CastleDynamicProxyGenerator.ProxyInterceptor.Intercept(IInvocation invocation) in c:\repo\FakeItEasy\Source\FakeItEasy\Creation\CastleDynamicProxy\CastleDynamicProxyGenerator.cs:line 229
   at Castle.DynamicProxy.AbstractInvocation.Proceed() in c:\repo\FakeItEasy\Source\FakeItEasy\Configuration\ConfigurationModule.cs:line 0
   at Castle.Proxies.DeploymentStoreProxy.GetDeployment(ResourceSpec resource)
   at [test code]
```

```csharp
var store = FakeHelper.Create<DeploymentStore>();
var callContext = A.CallTo(() => store.TryGetDeployment(null)).WithAnyArguments();
callContext.Returns(Task.FromResult<Deployment>(null));

await Assert.ThrowsAsync<DeploymentDoesntExistException>(() =>
    store.GetDeployment(
        new ResourceSpec { resourceName = "r1", }));
   callContext.MustHaveHappened();
```

More precisely, AllUserRules must be being modified.
We can see that since this test depends on FakeScope, it is probably modified due to FakeScope conflict and a ChildScope being disposed and calling RemoveRulesConfiguredInScope.

**Comment by TimLovellSmith** [comment]
It might not be a dupe though. I still can't figure out why my workaround for #484 doesn't apply here:
the workaround - lock while using/disposing Fake.CreateScope()

            // lock: works around Fake.CreateScope not being thread-safe
            lock (fakeScopeLock)
            {
                using (Fake.CreateScope(dependencyResolver))
                {
                    Console.WriteLine("FakeHelper.Create<{0}>()", typeof(T));
                    fakeObject = A.Fake<T>();
                }
            }

Maybe I'm quite wrong about the code path that modifies the collection.

**Comment by blairconrad** [comment]
I reformatted the description and comment to use [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

**Comment by blairconrad** [comment]
@TimLovellSmith, thanks for raising this. I didn't have time to take a look on the weekend. My schedule has been quite full, and is likely to stay so for a little while.
Don't interpret slow/missing responses as an indication that we don't care about your problems and appreciate your contributions.

**Comment by blairconrad** [comment]
@TimLovellSmith, you using Scopes here as you were in #484?

**Comment by TimLovellSmith** [comment]
I found out the reason this is really happening is because while running tests multithreaded with xunit we are sharing static objects across threads, and we mocked out the static object with a fake - nothing to do with FakeScopes at all.

We should probably fix our tests not to do that :)

**Comment by adamralph** [comment]
That's good to hear!

By "mocked out the static objects" I guess you mean you assigned a fake
object to a field of a static type?

Does this mean we can close this?

**Comment by TimLovellSmith** [comment]
@adamralph Yup and yup!

>By "mocked out the static objects" I guess you mean you assigned a fake
object to a field of a static type?

>Does this mean we can close this?

**Comment by blairconrad** [comment]
Thanks for following up, @TimLovellSmith.
