### ISSUE TITLE
PureAttribute on A.CallTo()

### ISSUE THREAD

**Issue by matkoch** [FakeItEasy/FakeItEasy#505]
While pairing with @ulrichb today, we realized how annoying it is to forget about the `MustHaveHappened()` call all the time when you're asserting calls. One easy way to inform the developer about such a problem, is to put the JetBrains annotation `PureAttribute` onto the static method. This will underline the expression if it is not succeeded by an extension method.

Note that JetBrains annotations can be made internal, and must not be shipped with FIE or do produce a dependency.

**Comment by blairconrad** [comment]
Thanks for bringing this up, @matkoch.

At the risk of being a downer, several of the owners and other Friends of FakeItEasy had discussed this recently, and I believe the consensus was that `[Pure]` was not the preferred approach.
I'm thinking in particular of the conversation that surrounds https://github.com/FakeItEasy/FakeItEasy/issues/56#issuecomment-96144769.

Note that we do have an issue (#490) for detecting the situation you describe in an analyzer.

**Comment by blairconrad** [comment]
We have #490 planned, and have agreed that an analyzer is the preferred approach, so I'd like to close this. Objections?

**Comment by thomaslevesque** [comment]
> We have #490 planned, and have agreed that an analyzer is the preferred approach, so I'd like to close this. Objections?

Nope. I'll resume work on the analyzer when we officially switch to VS2015.
