### ISSUE TITLE
how to Fake Icons

### ISSUE THREAD

**Issue by winecraft** [FakeItEasy/FakeItEasy#506]
Hi, I am trying to fake some of the **faking fontawesome or scalable vector icons**

**Comment by blairconrad** [comment]
@winecraft, as always, we appreciate your interest.
But we don't understand the question.
I'm not even sure how icons could be faked or why you'd want to in a .Net application.
Can you expand on your question, please?

**Comment by winecraft** [comment]
@adamralph - the icons are pieces of visual data. Similar to a lat/long that they represent some visual value.

For e.g. in a Grid/Table, we use them in a column along with the data values,  where each row is simply represented by some icon. Fortunately, since `fontawesome` is font and treated like text `class="fa fa-user"` or `class="fa fa-bank"` and not png, it would just be another piece of mock data.

**Comment by blairconrad** [comment]
@winecraft, you're talking about [Font Awesome](http://fortawesome.github.io/Font-Awesome/), yes? The icon font and CSS toolkit?
FakeItEasy is an isolation (mocking) framework for .NET. It is not related to HTML, fonts, icons, or CSS in any way.

Unless you know a great deal more than I do about how FakeItEasy could possibly be used to fake an icon, I think you may be asking questions about the wrong framework.
If you still think your question applies, perhaps you could give us a sample unit test (or as much as you could write) showing us how you're attempting to test your production code?

**Comment by blairconrad** [comment]
The question makes no sense me, and @winecraft appears to have lost interest. Closing.
