### ISSUE TITLE
Drop support for Silverlight / Win8 / Win8.1

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#507]
Castle.Core may be dropping support for Silverlight soon (see castleproject/Core#100).
If this happens (and nobody's arguing against it as is), we have no way to support Silverlight.
Win8 and Win8.1 support relies on our SL5 DLL, so that would go too. (And 8.1 may not be functional anyhow.)

Shall we keep an eye on castleproject/Core#100 and, if it's accepted, drop Silverlight support in 2.0?
Or just drop support in 2.0 anyhow?

**Comment by adamralph** [comment]
I vote for just dropping it in 2.0 regardless.

**Comment by blairconrad** [comment]
Thanks.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
