### ISSUE TITLE
'Castle.Proxies.ObjectProxy_5' to type 'System.Web.HttpBrowserCapabilitiesBase'

### ISSUE THREAD

**Issue by Maheshljadhav** [FakeItEasy/FakeItEasy#514]
I have facing issue while Unit Testing Controllers as a whole in MVC 5.

I am testing AuthorizeAttribute for the view. Authorization process gets successfully completed. But when controller is returning view i am facing the issue as stated below.

```
System.InvalidCastException was unhandled by user code
  HResult=-2147467262
  Message=Unable to cast object of type 'Castle.Proxies.ObjectProxy_5' to type 'System.Web.HttpBrowserCapabilitiesBase'.
  Source=System.Web.WebPages
  StackTrace:
       at System.Web.WebPages.BrowserHelpers.GetOverriddenBrowser(HttpContextBase httpContext, Func`2 createBrowser)
       at System.Web.WebPages.BrowserHelpers.GetOverriddenBrowser(HttpContextBase httpContext)
       at System.Web.WebPages.DisplayModeProvider.<.ctor>b__2(HttpContextBase context)
       at System.Web.WebPages.DefaultDisplayMode.CanHandleContext(HttpContextBase httpContext)
       at System.Web.WebPages.DisplayModeProvider.<GetAvailableDisplayModesForContext>d__4.MoveNext()
       at System.Web.Mvc.VirtualPathProviderViewEngine.GetPath(ControllerContext controllerContext, String[] locations, String[] areaLocations, String locationsPropertyName, String name, String controllerName, String cacheKeyPrefix, Boolean useCache, String[]& searchedLocations)
       at System.Web.Mvc.VirtualPathProviderViewEngine.FindView(ControllerContext controllerContext, String viewName, String masterName, Boolean useCache)
       at System.Web.Mvc.ViewEngineCollection.<>c__DisplayClass6.<FindView>b__4(IViewEngine e)
       at System.Web.Mvc.ViewEngineCollection.Find(Func`2 lookup, Boolean trackSearchedPaths)
       at System.Web.Mvc.ViewEngineCollection.Find(Func`2 cacheLocator, Func`2 locator)
       at System.Web.Mvc.ViewEngineCollection.FindView(ControllerContext controllerContext, String viewName, String masterName)
       at System.Web.Mvc.ViewResult.FindView(ControllerContext context)
       at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
       at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
       at ShutDown.UnitTests.LoginTest.Shoud_Allow_Authorised_Users() in d:\ME\Mahesh\Working\Web\Shutdown\ShutDown\ShutDown.UnitTests\LoginTests.cs:line 122
  InnerException: 
```

------------------------------------------------------------------------------------------------------------------------------------------------------
Following code snippet i am using for testing the controller. 

```csharp
[Test]
public void Shoud_Allow_Authorised_Users()
{

    //Arrange
    var repository = A.Fake<ShutDown.Domain.Repository.IUserRepository>();   // OUR SERVICE TYPE

    var controller = new ShutDown.Web.Controllers.HomeController(repository);  //  CONTROLLER TO TEST


    var request = A.Fake<HttpRequestBase>();
    var response = A.Fake<HttpResponseBase>();
    var session = A.Fake<HttpSessionStateBase>();
    var server = A.Fake<HttpServerUtilityBase>();


    var context = A.Fake<HttpContextBase>();
    var user = A.Fake<System.Security.Principal.IPrincipal>();
    var identity = A.Fake<System.Security.Principal.IIdentity>();
    var requestContext = A.Fake<RequestContext>();
    var browser = A.Fake<HttpBrowserCapabilitiesBase>();
    var displayMode = A.Fake<System.Web.WebPages.IDisplayMode>();

    //INSTANTIATE THE REQUEST WITH  HttpContextBase Class IN .NET 3.5 HttpContextBase is used insted HttpContext
    var httpContext = A.Fake<HttpContextBase>();

    ////CREATE SERVER VARIABLES TO INSTANTINEATE
    var serverheaders = new System.Collections.Specialized.NameValueCollection();
    serverheaders.Add("REMOTE_USER", "itsmee");    //DUMMY DATA
    serverheaders.Add("HTTP_REMOTE_USER", "itsmee");  //DUMMY DATA

    A.CallTo(() => httpContext.Server).Returns(server);
    A.CallTo(() => httpContext.Request).Returns(request);
    A.CallTo(() => httpContext.Response).Returns(response);
    A.CallTo(() => httpContext.Session).Returns(session);
    A.CallTo(() => httpContext.User).Returns(user);
    A.CallTo(() => httpContext.Request.IsLocal).Returns(true);
    A.CallTo(() => httpContext.User.Identity.IsAuthenticated).Returns(true);
    A.CallTo(() => request.RequestContext).Returns(requestContext);
    A.CallTo(() => httpContext.Request.Browser).Returns(browser);
    A.CallTo(() => httpContext.Request.ServerVariables).Returns(serverheaders);

    controller.ControllerContext = new ControllerContext
    {
        Controller = controller,
        RequestContext = new RequestContext(httpContext, new RouteData()),  //ASSIGN CONTEXT TO CONTROLLER
        DisplayMode = displayMode,
        
    };

    ////ADD ROUTING VALUES

    controller.ControllerContext.RequestContext.RouteData.Values.Add("Action", "About");
    controller.ControllerContext.RequestContext.RouteData.Values.Add("Controller", "Home");

    //// Act 
    //var result = (ViewResult)controller.;

    var result = controller.ActionInvoker.InvokeAction(controller.ControllerContext, "About");  //ERROR THROWING HERE
    var statusCode = httpContext.Response.StatusCode;


    //// Assert
    Assert.AreEqual(200, statusCode, "Status Code");

}
```

**Comment by blairconrad** [comment]
@Maheshljadhav, thanks for your interest.

I reformattedthe issue description to use [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) for readability.

I know that many people have had trouble faking classes from ASP.NET MVC in the past.
It's big, inscrutable, and has many sealed bits and hidden dependencies.
I don't use the technology myself, so don't have a lot of experience.

It looks like you've managed to create a fake Browser set it up to be returned from `httpContext.Request`, so without a little more knowledge of the innards of `InvokeAction`, I haven't anything to provide, and am at the Day Job, so time it limited.

One thing I'd suggest is looking at other things that have been written about this kind of problem (which may be dated), such as [Jonathan Channon's Mocking HttpContext with Fake It Easy](http://blog.jonathanchannon.com/2013/04/30/mocking-httpcontext-with-fake-it-easy/). There may be hints there.

**Comment by Maheshljadhav** [comment]
thanks for your reply. But what i am trying to do here is that i want to test my Authorization attrubute. My view is decorated with my custom attribute for authentication purpose. 

Following is code snippet for controller and view.

----------------------------------------------------------------------------------------------------------------------------------
 [ShutDown.Web.Authorization.WindowsAuthorize]  //THIS IS AUTHORIZED RESOURCE
        public ActionResult Index()
        {
                     return View();
        }
 ---------------------------------------------------------------------------------------------------------------------------------

So when i tried  Jonathan Channon's Mocking HttpContext with Fake It Easy it doesnt allow me to test the Authorization attrubute.

I want to test it by just checking the Http status code of the response.

**Comment by blairconrad** [comment]
@Maheshljadhav, sorry Mr. Channon's approach didn't work for you. I'm a little confused, though. It appears to me (as someone who doesn't use MVC) that it would—you still have an `HttpContextBase` to interrogate at the end, just as he would've. Why couldn't you check the HTTP status code of the response?

I took a little time yesterday seeing if I could track through some of the MVC code to see why it had gotten hold of an object that was not a  `HttpBrowserCapabilitiesBase`, but came up short. In particular, I couldn't find `System.Web.WebPages.DisplayModeProvider.<.ctor>b__2(HttpContextBase context)`, which I read to be a `DisplaymodeProvider` constructor taking a single argument, a `HttpContextBase`. Can you confirm the exact version of MVC 5 you're using? Better yet, if _you_ have a link to the source…

**Comment by Maheshljadhav** [comment]
I am using MVC 5.2.3.0 for my project.
and following are assemblies in my project.

and following is configuration..


 <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Optimization" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-1.6.5135.21930" newVersion="1.6.5135.21930" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <publisherPolicy apply="no" />
        <assemblyIdentity name="Oracle.ManagedDataAccess" publicKeyToken="89b483f429c47342" culture="neutral" />
      </dependentAssembly>
    </assemblyBinding>

**Comment by blairconrad** [comment]
@Maheshljadhav, I updated your last comment using [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks), since the XML configuration was stripped out without it (and it gives nice syntax highlighting, but that's a bonus). 

I didn't see anything in the section "and following are assemblies in my project.", but the configuration probably gives a hint about that.

I checked the MVC source code at https://aspnetwebstack.codeplex.com/SourceControl/latest, but am still confused, as `DisplayModeProvider` looks the same there as the code I'd seen.

Perhaps you could build locally and debug in, to see what MVC is doing with the things you give it…

**Comment by Maheshljadhav** [comment]
Sorry for the XML notation.

I am putting my XML configuration again here.

&lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
&lt;dependentAssembly&gt;
&lt;assemblyIdentity name=&quot;Newtonsoft.Json&quot; culture=&quot;neutral&quot; publicKeyToken=&quot;30ad4fe6b2a6aeed&quot; /&gt;
&lt;bindingRedirect oldVersion=&quot;0.0.0.0-7.0.0.0&quot; newVersion=&quot;7.0.0.0&quot; /&gt;
&lt;/dependentAssembly&gt;
&lt;dependentAssembly&gt;
&lt;assemblyIdentity name=&quot;System.Web.Optimization&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; /&gt;
&lt;bindingRedirect oldVersion=&quot;1.0.0.0-1.1.0.0&quot; newVersion=&quot;1.1.0.0&quot; /&gt;
&lt;/dependentAssembly&gt;
&lt;dependentAssembly&gt;
&lt;assemblyIdentity name=&quot;WebGrease&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; /&gt;
&lt;bindingRedirect oldVersion=&quot;0.0.0.0-1.6.5135.21930&quot; newVersion=&quot;1.6.5135.21930&quot; /&gt;
&lt;/dependentAssembly&gt;
&lt;dependentAssembly&gt;
&lt;assemblyIdentity name=&quot;System.Web.Helpers&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; /&gt;
&lt;bindingRedirect oldVersion=&quot;1.0.0.0-3.0.0.0&quot; newVersion=&quot;3.0.0.0&quot; /&gt;
&lt;/dependentAssembly&gt;
&lt;dependentAssembly&gt;
&lt;assemblyIdentity name=&quot;System.Web.WebPages&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; /&gt;
&lt;bindingRedirect oldVersion=&quot;1.0.0.0-3.0.0.0&quot; newVersion=&quot;3.0.0.0&quot; /&gt;
&lt;/dependentAssembly&gt;
&lt;dependentAssembly&gt;
&lt;assemblyIdentity name=&quot;System.Web.Mvc&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; /&gt;
&lt;bindingRedirect oldVersion=&quot;1.0.0.0-5.2.3.0&quot; newVersion=&quot;5.2.3.0&quot; /&gt;
&lt;/dependentAssembly&gt;
&lt;dependentAssembly&gt;
&lt;publisherPolicy apply=&quot;no&quot; /&gt;
&lt;assemblyIdentity name=&quot;Oracle.ManagedDataAccess&quot; publicKeyToken=&quot;89b483f429c47342&quot; culture=&quot;neutral&quot; /&gt;
&lt;/dependentAssembly&gt;
&lt;/assemblyBinding&gt;

**Comment by Maheshljadhav** [comment]
I debugged the MVC open source code and and found that is throwing the error at finding the IEnumerable<IDisplayMode> possibleDisplayModes;  and iterating over the result in VirtualPathProviderViewEngine.cs . 

ERROR LINE  NO. 212

 foreach (IDisplayMode displayMode in possibleDisplayModes) <-----Unable to cast object of type 'Castle.Proxies.ObjectProxy_5' to type 'System.Web.HttpBrowserCapabilitiesBase' 

It is throwing the same error which i was facing above. though Fake it easy has faked IDisplayMode.

**Comment by blairconrad** [comment]
@Maheshljadhav, interesting. Were you unable to step down the stack to 
`System.Web.WebPages.BrowserHelpers.GetOverriddenBrowser(HttpContextBase httpContext, Func`2 createBrowser)`?

On [line 54](https://github.com/ASP-NET-MVC/aspnetwebstack/blob/4e40cdef9c8a8226685f95ef03b746bc8322aa92/src/System.Web.WebPages/BrowserHelpers.cs#L54), it's performing the failing cast:

```csharp
HttpBrowserCapabilitiesBase overriddenBrowser =
    (HttpBrowserCapabilitiesBase)httpContext.Items[_browserOverrideKey];
```

Perhaps you can see the returned type (I'm guessing `ObjectProxy_5`) and see what its bases are. If it's the browser object you created, it should have `HttpBrowserCapabilitiesBase` as a base. If not, that may be a clue.
Also, if you keep an eye on `httpContext.Items`, you could find out where the offending item was added to the collection.

**Comment by Maheshljadhav** [comment]
I debugged MVC source code again and found that i was not able to step down the stack to  

System.Web.WebPages.BrowserHelpers.GetOverriddenBrowser(HttpContextBase httpContext, Func2 createBrowser)`

Yes. i have created the the object of the browser.
  var browser = A.Fake<HttpBrowserCapabilitiesBase>();
  A.CallTo(() => httpContext.Request.Browser).Returns(browser);

One more thing to notify you that " HttpContext.Current " is null when i debugged the code. So eventually " HttpContext.Current.Items " is also null here.

**Comment by blairconrad** [comment]
@Maheshljadhav, I threw together a quick test (well, took your test and implemented my own controller, and got entirely different results, probably because I don't know what I'm doing with MVC.
Or don't know what you're doing in the controller.

**Comment by blairconrad** [comment]
Closing due to lack of understanding on my part and participation on the part of the raiser.
