### ISSUE TITLE
have create_milestone rake task create release on the current branch

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#515]
Right now, all releases will be created based on master.
This caused a problem when I created release 1.25.3  (#512).

If the [create_release](https://developer.github.com/v3/repos/releases/#create-a-release) command were told to use the current branch (`git rev-parse --abbrev-ref HEAD`) instead, we'd have a better chance of doing the right thing.

**Comment by adamralph** [comment]
Sounds good.

**Comment by blairconrad** [comment]
This no longer applies after removing the issue/release/milestone-manipulating build targets while fixing #645.
