### ISSUE TITLE
Raise.With does not work properly in release mode

### ISSUE THREAD

**Issue by MrVermond** [FakeItEasy/FakeItEasy#517]
Just try to execute this code in release and in debug mode. Debug works, release fails. Tried with FakeItEasy version 1.25.3

```csharp
public interface ITestA
{
    event EventHandler Closed;
    event EventHandler Loaded;

    void DoStuff ();

    void Wicked ();
}

public interface ITestB
{
    void DoStuff ();

    void Wicked ();

    void Wicked1 (ITestA a);
}

public class TestB
{
    private readonly ITestA _a;
    private readonly ITestB _b;

    public TestB (ITestA a, ITestB b)
    {
        _a = a;
        _b = b;
    }

    public void Attach ()
    {
        WeakEventManager<ITestA, EventArgs>.AddHandler(_a, EventNames.Closed, Closed);
        WeakEventManager<ITestA, EventArgs>.AddHandler(_a, EventNames.Loaded, Loaded);
        _a.Wicked();
        _b.Wicked();
    }

    private void Loaded (object sender, EventArgs e)
    {
        _b.DoStuff();
    }

    private void Closed (object sender, EventArgs e)
    {
        _a.DoStuff();

        // _b.Wicked1(_a.Value);
    }
}

[TestFixture]
public class MyTest
{
    [Test]
    [Repeat (1000)]
    public void Test ()
    {
        var a = A.Fake<ITestA>();
        var b = A.Fake<ITestB>();

        var inst = new TestB(a, b);
        inst.Attach();
        A.CallTo(() => a.Wicked()).MustHaveHappened(Repeated.Exactly.Once);
        A.CallTo(() => b.Wicked()).MustHaveHappened(Repeated.Exactly.Once);

        a.Closed += Raise.With(null, new EventArgs()).Now;

        A.CallTo(() => a.DoStuff()).MustHaveHappened(Repeated.Exactly.Once);

        // A.CallTo(() => b.Wicked1(a)).MustHaveHappened(Repeated.Exactly.Once);
        a.Loaded += Raise.With(null, new EventArgs()).Now;
        A.CallTo(() => b.DoStuff()).MustHaveHappened(Repeated.Exactly.Once);
    }
}
```

**Comment by blairconrad** [comment]
@MrVermond, thanks for noting this.

I reformatted the issue description to use [fenced code blocks](https://help.github.com/articles/github-flavoured-markdown/#fenced-code-blocks) for readability.

i've been able to reproduce the problem with your code (except that I couldn't find `EventNames` and made up appropriate string literals instead). It's interesting. I'm not familiar

Out of curiosity, have you tried with older versions of FakeItEasy? This does not look to me like the sort of thing that would've broken in 1.25.3, but one never knows. Hmm. some event semantics changed in 1.25.0, so I wonder if 1.24.0 is any different. I'm at the Day Job, or would try it out myself right now…

**Comment by MrVermond** [comment]
Oh damn, sorry for the EventNames.
Yes im currently working with the versoin 1.25.1, this is the same behavoir.
I didnt tried 1.25.0 though

**Comment by blairconrad** [comment]
No worries about the names. 1.24.0 would be more interesting than 1.25.0…

I've just rewritten the test to not use `WeakEventManager` for the event-hooking up, and the test passed. I am not familiar with the semantics of the `WeakEventManager`, but fear that it's unhooking events from objects in the background, and wonder if in release mode it's behaving differently and we're having concurrency issues.

Either way, I think the issue may be better reframed as being about raising issues subscribed to by `WeakEventManager` or something. We can work on the exact name as we learn more.
Not that it wouldn't still be worth fixing; it's just that the current title sounds a little dire. :wink:

Also, the test is fairly convoluted with `a` and `b` calling each other. I assume this is because it mirrors what you have in some production code. You've not seen any problems with simpler code?

**Comment by blairconrad** [comment]
@MrVermond, I just realized that _I'm_ using FakeItEasy 1.24.0. I should really update my test/play project. :blush: 

So, at least we didn't introduce the problem in 1.25.0. Which I'm torn about. It's always nice to find a culprit, but I like what that change offers us (ability to omit `Now`).

**Comment by blairconrad** [comment]
@MrVermond, it doesn't appear to be `Raise`. I sloppily rewrote the test so we could raise the events via a public method:

```csharp
public class ITestA
{
    event EventHandler Closed;
    event EventHandler Loaded;

    public virtual void DoStuff() { }

    public virtual void Wicked() { }

    public void RaiseLoaded()
    {
        Loaded(this, EventArgs.Empty);
    }

    public void RaiseClosed()
    {
        Closed(this, EventArgs.Empty);
    }
}

public class ITestB
{
    public virtual void DoStuff() { }

    public virtual void Wicked() { }
}

public class TestB
{
    private readonly ITestA _a;
    private readonly ITestB _b;

    public TestB(ITestA a, ITestB b)
    {
        _a = a;
        _b = b;
    }

    public void Attach()
    {
        WeakEventManager<ITestA, EventArgs>.AddHandler(_a, "Closed", Closed);
        WeakEventManager<ITestA, EventArgs>.AddHandler(_a, "Loaded", Loaded);
        _a.Wicked();
        _b.Wicked();
    }

    private void Loaded(object sender, EventArgs e)
    {
        _b.DoStuff();
    }

    private void Closed(object sender, EventArgs e)
    {
        _a.DoStuff();
    }
}

[TestFixture]
public class MyTest
{
    [Test]
    [Repeat(1000)]
    public void Test()
    {
        var a = A.Fake<ITestA>();
        var b = A.Fake<ITestB>();

        var inst = new TestB(a, b);
        inst.Attach();
        A.CallTo(() => a.Wicked()).MustHaveHappened(Repeated.Exactly.Once);
        A.CallTo(() => b.Wicked()).MustHaveHappened(Repeated.Exactly.Once);

        a.RaiseClosed();
        A.CallTo(() => a.DoStuff()).MustHaveHappened(Repeated.Exactly.Once);

        a.RaiseLoaded();
        A.CallTo(() => b.DoStuff()).MustHaveHappened(Repeated.Exactly.Once);
    }
}
```

and got this failure:

```
Errors and Failures:                                                     
1) Test Error : LessFaking.MyTest.Test                                   
   FakeItEasy.ExpectationException :                                     
                                                                         
  Assertion failed for the following call:                               
    LessFaking.ITestB.DoStuff()                                      
  Expected to find it exactly once but found it #0 times among the calls:
    1: LessFaking.ITestB.Wicked()
```

This lead me to believe that the problem is that the runtime thinks we're done with some objects so we can start unhooking events.

Indeed, adding this line to the bottom either of my new test or your original test causes them to pass:

```csharp
Assert.That(inst, Is.Not.Null);
```

So I think we may just be seeing normal `WeakEventManager` behaviour.

**Comment by MrVermond** [comment]
Hmm sounds interesting. I will try this out in my productive code tomorrow and will write you the result. But it sounds very reasonable.

**Comment by blairconrad** [comment]
Cool. Thanks. That's my goal: sounding very reasonable.

**Comment by MrVermond** [comment]
Hey, your suggestion works fine. So it was really about the too early release of the instance. Thanks a lot for your investigation! I think we can close the issue then.

**Comment by blairconrad** [comment]
@MrVermond, I'm glad to have been of assistance.
