### ISSUE TITLE
Document uses of FakeScope

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#519]
As @RichardLangFromNZ points out in #518, there's no real documentation for `FakeScope`, except for what's mentioned in the [Ordered Assertions documentation](https://github.com/FakeItEasy/FakeItEasy/wiki/Ordered-assertions).

We should probably explain the fake scopes, if anyone understands them.
I've a suspicion that they're not thread-safe at all, so that may be worth mentioning. Or we can procrastinate in case we end up changing the thread-safety…

**Comment by blairconrad** [comment]
As noted in #484, we've confirmed threadsafety issues in `FakeScope`s.

**Comment by adamralph** [comment]
Invalidated by #604
