### ISSUE TITLE
Introduce gaps between numbers in state labels

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#521]
One of the things I'm struggling with personally is to keep track of all the OSS projects I'm working on and the state of various issues within them.

I currently use huboard on almost of all of them, so for an individual project I can easily see anything in progress that I can help close out, but I can't see the this for all projects at once. However, huboard does have the ability to show multiple repos in a single board. All that needs to be done for this to work, is for them to share the same state labels, or at least an intersection of them. Some of my projects have way more state labels than the four we have in FakeItEasy, but so long as Backlog, Ready, Working and Done exist in all of them, *and have the same numbers*, this will work.

To that end, I'd like to change the labels from

`0 - Backlog`, `1 - Ready`, `2 - Working`, `3 - Done`

to

`0 - Backlog`, `100 - Ready`, `200 - Working`, `300 - Done`

This allows other projects to put their extra labels in the 'gaps' this opens between the numbers. I went with hundreds instead of tens, because then that allows the other projects to form wide gaps themselves, for other projects to fill, and so on.

**Comment by adamralph** [comment]
@blairconrad any objection?

**Comment by blairconrad** [comment]
@adamralph, it's not clear to me how you'll pick numbers for the various projects, or how the other projects will pick numbers so they'll all fit in nicely.
However, it won't hurt anyone working within a single project, and if it has a _chance_ of helping someone who likes an overview of multiple projects, why not?

**Comment by adamralph** [comment]
@blairconrad thanks. It doesn't *quite* work as I wanted since it seems that huboard does insist that every repo in the board has exactly the same state labels. However, what I can now do is query GitHub for all the projects I'm involved in where, for example, they have the label `200 - Working`, whereas before this would be `2 - Working` in some projects, `3 - Working` in others, etc.

For the numbering scheme, see https://github.com/xbehave/xbehave.net/labels - it has has 0, 100, 200, 300 aligned with FakeItEasy but many other labels in between.
