### ISSUE TITLE
say what the object is when A.CallTo complains "The specified object is not recognized as a fake object.”

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#530]
Inspired by @AlexAtNet's question 

> [A.CallTo(…).ReturnsLazily(…) throws “The specified object is not recognized as a fake object.”](http://stackoverflow.com/questions/32052187/a-callto-returnslazily-throws-the-specified-object-is-not-recognized)

over at StackOverflow.

Why don't we say what the object is? It might help people out a bit.

taken by @jimmyheaddon

**Comment by jimmyheaddon** [comment]
@blairconrad are you thinking that we update DefaultFakeManagerAccessor.GetFakeManager() to improve the clarity of exception messages from multiple sources, or did you want this explicitly in RuleBuilder.ReturnsLazily()?

**Comment by blairconrad** [comment]
@jimmyheaddon, not just for `ReturnsLazily`. It was a general comment, just inspired by @AlexAtNet's specific example. Thanks for asking!

**Comment by blairconrad** [comment]
@jimmyheaddon, since you've gone quiet on this issue, I'm going to close it and return it back to the generally available pool. Thanks for your work so far. If you decide you'd like to come back to work on this or anything else, we'd welcome it.

**Comment by blairconrad** [comment]
@rocifier has [indicated interest](https://gitter.im/FakeItEasy/FakeItEasy?at=58c09ee97ceae5376a8ea0ab) in this issue.

**Comment by adamralph** [comment]
Thanks @rocifier!

**Comment by blairconrad** [comment]
This issue was fixed in [Release 3.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.2.0).

@rocifier, look for your name in the release notes! :trophy:
