### ISSUE TITLE
An inherited interface member hidden by `new` with the same return type is not configured when the hiding member is configured

### ISSUE THREAD

**Issue by dotnerdify** [FakeItEasy/FakeItEasy#533]
One would expect that a fake where a property with a new modifier would result in the same underlining data.

Better explained through this code.

```c#
using FakeItEasy;
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
        var derived = A.Fake<IDerived>();
        A.CallTo(() => derived.Dependency).Returns(null);

        IBase baseObj = derived;
        Assert.IsNull(baseObj.Dependency); //Fails
    }
}

public interface IDerived : IBase
{
    new IDependency Dependency { get; }
}

public interface IBase
{
    IDependency Dependency { get; }
}

public interface IDependency
{
}
```

Unit test should pass.

**Comment by blairconrad** [comment]
@dotnerdify, thanks for your interest. This is strikingly similar to StackOverflow question [FakeItEasy - problems with new modifier](http://stackoverflow.com/questions/32405776/fakeiteasy-problems-with-new-modifier).

I'm of the opinion that Yacoub Massad's answer is correct: the new `IDerived.Dependency` property is not the same as `IBase.Dependency`, so FakeItEasy is behaving properly.

The interface has two members and the fake has only been told what to do when one of them is called.
Of course, it's easy for me to say. I'm not a rampant `new` user.

**Comment by dotnerdify** [comment]
Yes, I'm the poster :-). 

Well, if technically there's a way of making `IDerived.Dependency` property not the same as `IBase.Dependency` then I agree FakeItEasy should behave like this.

But if you implement IDerived, you can never cast it up to IBase and get access to a different refence, correct? Then why would FakeItEasy behave differently? I may be missing something though.

**Comment by blairconrad** [comment]
@dotnerdify, I see your point. After having read your [pastebin code](http://pastebin.com/qzRwC5NW) linked to from the answer comments, and doing some more thinking, I may be coming around a little.
If there's no way to distinguish from the outside between the two methods, then maybe FakeItEasy would be better to treat them the same.
Maybe there's no downside.

Of course, any solution would need to properly handle the case where `new` is applied to concrete members, where both the original and new methods can be accessed.
I'm not sure what happens with `abstract` class members. Some investigation would be needed.

@FakeItEasy/owners, objections to trying to make FakeItEasy treat the new interface member and original interface member the same?

**Comment by adamralph** [comment]
Yes, FakeItEasy should treat both members the same. The fake is effectively an implementation of the two interfaces and since the two interface properties have the same type, the single implementation should satisfy the two interface members. Only when the return type is different between the two interface implementations should FIE treat them separately, since, effectively, it will have to generate two implementations in the fake, one for each interface member.

**Comment by adamralph** [comment]
@FakeItEasy/owners if in agreement, I think we can label this `100 - Ready` and `up-for-grabs`.

**Comment by blairconrad** [comment]
:+1:

**Comment by adamralph** [comment]
I've added it to the 2.0 milestone, assuming we'd rather roll this breaking change in now.

**Comment by adamralph** [comment]
In fact, this could be considered a bug...

**Comment by blairconrad** [comment]
Agreed for bug.

**Comment by thomaslevesque** [comment]
Actually, I'm not really convinced... `IBase.Dependency` and `IDerived.Dependency` really are two different members; they just occur to have the same name. A class implementing `IDerived` could implement both:

    class Test : IDerived
    {
        public IDependency Dependency { get; }
        IDependency IBase.Dependency { get; }
    }

So I think they should be treated as different members, and configured independently (which is the current behavior). Currently it's possible to configure both calls separately, so the problem has an easy workaround. If we start treating both members as the same, it will become impossible to configure them separately; it will basically disable a scenario that is supported now.

**Comment by thomaslevesque** [comment]
[This comment](http://stackoverflow.com/questions/32405776/fakeiteasy-problems-with-new-modifier#comment52779445_32406325) summarizes the issue pretty well:

> I'm a bit split. On one side I'm thinking, "it should mimic this code". On the other side, perhaps FakeItEasy should keep its flexibility there.

I'm in the "keep the flexibility" camp.

**Comment by thomaslevesque** [comment]
Perhaps we could add a method to make it easier; something like this:

    A.CallTo(() => derived.Dependency).OrHiddenBaseDefinition().Returns(null);

**Comment by adamralph** [comment]
I guess the question is, how does the fake effectively implement the interface. If we claim it is:

```C#
class ProxyGeneratedByCastleWhateverItIsCalled : IDerived
{
    public IDependency Dependency { get; }
    IDependency IBase.Dependency { get; }
}
```

then yes, the current behaviour is correct.

If, however, we claim it is

```C#
class ProxyGeneratedByCastleWhateverItIsCalled : IDerived
{
    public IDependency Dependency { get; }
}
```

then the current behaviour is incorrect.

Currently (correct me if I'm wrong) there is no way to tell FakeItEasy whether or not to implement the base member explicitly or not.

Perhaps, it is the very behaviour which we are discussing which decides this. In which case, we currently use the former approach, and implement the base member explicitly.

**Comment by thomaslevesque** [comment]
> Currently (correct me if I'm wrong) there is no way to tell FakeItEasy whether or not to implement the base member explicitly or not.

Indeed, but we could had a way to tell FIE to implement both members, as I suggested above.

> Perhaps, it is the very behaviour which we are discussing which effectively states which approach we are using. In which case, we currently use the former approach, and we implement the base member explicitly.

Yes, and I think it's fine, because it leaves the user in control. Also, changing it could be a breaking change, if someone actually configures the members differently.

**Comment by adamralph** [comment]
OK, I propose we close this discussion and raise a new (perhaps P3) feature to add a new option to control whether to implement base members implicitly or explicitly. We could consider making implicit the default. It's the simpler option and the one I would expect as a user and indeed explicit by default is the reason this discussion was created. This would make it a breaking change, but I think for the better.

**Comment by thomaslevesque** [comment]
@adamralph, I agree

**Comment by patrik-hagne** [comment]
Implicit interface implementation is a C#-concept, not a .Net concept, so
I'd vote for keeping the current behaviour.
Den 9 jan 2016 16:23 skrev "Thomas Levesque" <notifications@github.com>:

**Comment by adamralph** [comment]
@patrik-hagne that's a fair argument for keeping the current behaviour as default. Would you be opposed to having an option for implicit?

**Comment by patrik-hagne** [comment]
That sounds reasonable!
Den 9 jan 2016 18:44 skrev "Adam Ralph" <notifications@github.com>:

**Comment by blairconrad** [comment]
:+1:

**Comment by adamralph** [comment]
Thanks to @dotnerdify for starting this discussion. It has resulted in the creation of #572.
