### ISSUE TITLE
Add link to gitter chat

### ISSUE THREAD

**Issue by hellboy81** [FakeItEasy/FakeItEasy#535]
Project home readme should contain link to gitter chat room

**Comment by blairconrad** [comment]
Thanks, @hellboy81. It's an interesting idea (although once you get to the readme, the gitter link would be obvious, for people who care).

@FakeItEasy/owners, we should perhaps decide which external "help" services we want to point to, including

* Jabbr
* Gitter
* StackOverflow

**Comment by blairconrad** [comment]
I guess we would also want to re-evaluate the resources we point to on https://fakeiteasy.github.io

**Comment by jimmyheaddon** [comment]
@blairconrad, what communication platform do you guys generally use?  Gitter/Jabbr would've saved some of the to-and-through we had with pull request comments this week :smile:

**Comment by blairconrad** [comment]
@jimmyheaddon, before I showed up, Jabbr was the big winner, and that's probably the primary one, although there's some Gitter chat as well.
The problem with Jabbr (as I see it) is that I never get notified when there's chat there, so invariable show up 2 days later and say something to someone who dropped in.

**Comment by adamralph** [comment]
I'm happy to switch to Gitter as our official chat solution.There's less friction since it uses GitHub for auth and the rooms are naturally aligned with GitHub orgs and repos and the notifications are really good.

**Comment by PureKrome** [comment]
:( re Gitter as offical :(

**Comment by adamralph** [comment]
@PureKrome we'll still look at JabbR :wink:

So the gitter link is on the website now, do we still want to link it in the readme?

**Comment by blairconrad** [comment]
Thanks for the merge, @adamralph.
I chafe at duplicating information, but it may help people a little.
Another option would be in the docs. After I typed that I checked, and we point at Jabbr in the wiki's Home page.
I can change to Gitter (and do we want to add StackOverflow there or on the website) or remove.

**Comment by adamralph** [comment]
Since we have a website, how about we centralise everything there?

* README.md -> logo and basic marketing spiel with 'Find out more' link pointing to website
* Website-> portal for everything, linking to source, docs and chat
* Wiki -> Docs only, with link to 'Get more help' link pointing to website

**Comment by blairconrad** [comment]
Can do. Stay tuned.

**Comment by blairconrad** [comment]
* Submitted #540 to fix README.md.
* Updated wiki: https://github.com/FakeItEasy/FakeItEasy/wiki
* website looked okay, I thought

**Comment by blairconrad** [comment]
New plan. #540 has been abandoned and we'll update the chat link in the README and add the quickstart link to the website.

* web site change: FakeItEasy/fakeiteasy.github.io#21
* README: #541
