### ISSUE TITLE
support build on MSBuild v14-only machines?

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#537]
Per https://github.com/FakeItEasy/FakeItEasy/pull/536#issuecomment-141205040.
As a convenience to contributors, should the rakefile fall back to MSBuild version 14 when there's no version 12?

In theory the newer tools should be able to build the older projects just fine, no?

**Comment by jimmyheaddon** [comment]
:+1:

**Comment by adamralph** [comment]
:+1: I'd probably go 14 first, falling back to 12.

**Comment by blairconrad** [comment]
Sure. I'm easy.

**Comment by blairconrad** [comment]
Should we switch this task to a general "use VS2015 / MSBuild 14" for builds?
I'm interested in exploring some of the alternative ways of structuring the projects, specifically using shared folders to manage our linked source (and as a way to potentially make it easier for us to run all the tests for each framework we target), and think that's a first step.

**Comment by thomaslevesque** [comment]
> In theory the newer tools should be able to build the older projects just fine, no?

Yes, I only use VS2015 and I have no trouble building.

> I'm interested in exploring some of the alternative ways of structuring the projects, specifically using shared folders to manage our linked source (and as a way to potentially make it easier for us to run all the tests for each framework we target), and think that's a first step.

Shared projects would indeed make it easier to share code between projects. But they're only supported as of VS2013 update 1 IIRC; not sure if that's an issue.

**Comment by blairconrad** [comment]
> But they're only supported as of VS2013 update 1 IIRC; not sure if that's an issue.

Not if we make VS2015 the blessed IDE?

**Comment by adamralph** [comment]
With the recent updates to VS2015 (chiefly the return of some sanity to the NuGet UI) it mostly useable so I'd be happy to make MSBuild 14 the required version.

I'm still a little hesitant around shared projects. I know that the xunit guys went down that route initially for v2 but then abandoned it due to the IDE playing very badly with them in practice.

**Comment by blairconrad** [comment]
We can still explore other options. Earlier you'd had reservations about the scheme Castle.Core uses as well (building a single project with many configurations), no?

**Comment by adamralph** [comment]
> Earlier you'd had reservations about the scheme Castle.Core uses as well (building a single project with many configurations), no?

Yep, I find that very awkward too. It requires multiple build passes over the solution/projects to produce the final output.

Here's the approach I use xbehave - https://github.com/xbehave/xbehave.net/blob/7c49a81af810ee7a9902ffea6008ed7a046d1f2a/src/Xbehave.Sdk.Net45/Xbehave.Sdk.Net45.csproj#L71-L75

**Comment by blairconrad** [comment]
Ah, right. The magic includes, used here to includ all the Net40 files into the Net35 project:

```xml
<ItemGroup>
  <Compile Include="..\Xbehave.Sdk.Net40\**\*.cs">
    <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
  </Compile>
</ItemGroup>
```

I remember you showing me this once before.

**Comment by blairconrad** [comment]
But I've caused us to digress. At least we've established that we're happy to go MSBuild v14 only.
I don't _anticipate_ this being a breaking change, so no rush. I was just wondering. Thanks!

**Comment by adamralph** [comment]
> At least we've established that we're happy to go MSBuild v14 only.

Sure, but only if there is a reason to do so. Shared projects would be a reason, but I'm not seeing much value over the recursive include.

@bradwilson - I remember you mentioning that you ran into horrible problems with shared projects. Is that written up anywhere?

**Comment by thomaslevesque** [comment]
> Sure, but only if there is a reason to do so.

Shared projects is not the only reason. Switching to VS 2015 also means we can use C# 6 ;)

**Comment by thomaslevesque** [comment]
> I'm still a little hesitant around shared projects. I know that the xunit guys went down that route initially for v2 but then abandoned it due to the IDE playing very badly with them in practice.

Perhaps the xunit guys were using VS2013 when they tried? They work fine in VS2015 as far as I can tell. I've been using shared projects in a rather large solution (30 or 40 projects), and I haven't encountered any major issue so far. I did have some issues with ReSharper in the beginning, but the latest version of R# fixed all that.

Miguel de Icaza recently published [an interesting blog post](http://tirania.org/blog/archive/2016/Jan-22.html) about Shared Project vs. PCL.

**Comment by bradwilson** [comment]
> Perhaps the xunit guys were using VS2013 when they tried?

Yep, it was a combination of the poor implementation in VS2013 + the lack of any support for the third party tools like CodeRush or Resharper. All of that has been resolved now.

**Comment by adamralph** [comment]
Great, so perhaps shared projects is indeed the way to go now. It would also be nice to use C# 6 - string interpolation, for one thing, is pure bliss.

**Comment by blairconrad** [comment]
A long time ago (https://github.com/FakeItEasy/FakeItEasy/issues/537#issuecomment-141785569), @adamralph said

> :+1: I'd probably go 14 first, falling back to 12.

Do we still feel this way? We didn't switch from a VS2013 sln to a VS2015 sln recently, but that was when the change was embedded in another PR.

I recently got a new machine and didn't bother putting VS2013 on it, so _this issue_ has become interesting to me. I'd take it and add the fallback, but want to make sure I fallback (or fallforward) properly.

MsBuild 12 then 14 is _safest_ for now, but if people really want 14 then 12, I could do it.

**Comment by adamralph** [comment]
MSBuild 12 (and Visual Studio 2013) have been obsolete for 7 months now.

I still think we should target MSBuild 14 with 12 as a fall back.

**Comment by thomaslevesque** [comment]
> I still think we should target MSBuild 14 with 12 as a fall back.

But that means we have to stay compatible with MSBuild 12... so we can't use C# 6 features. Is this really what we want?

**Comment by blairconrad** [comment]
Are you proposing go for v14 only, or sticking with v12 only?

With the either-or MSBuild, at least people don't have to install a different toolset just to compile.

But you're right, it would open the possibility of people adding C# 6 features, building with MSBuild v14 and then submitting a PR which will fail to compile.

On the other hand, I've heard that _some people_ just build in VS2015, not even bothering with the command line at all, so the point may be moot!

**Comment by thomaslevesque** [comment]
> Are you proposing go for v14 only, or sticking with v12 only?

v14 only

Question is, does our CI support it?

**Comment by blairconrad** [comment]
If I read things right, yes?

![image](https://cloud.githubusercontent.com/assets/3275797/13322783/195dae1e-dba4-11e5-8d0e-e533a48bbde5.png)

**Comment by blairconrad** [comment]
although

![image](https://cloud.githubusercontent.com/assets/3275797/13322817/43e6edee-dba4-11e5-9a5d-8df744f32845.png)

confuses me

**Comment by blairconrad** [comment]
agent01 has .NET 4.6, but not 4.5

**Comment by thomaslevesque** [comment]
> agent01 has .NET 4.6, but not 4.5

But we don't target 4.6, so it shouldn't matter

**Comment by blairconrad** [comment]
My point was that there's no machine that has MSBuild v14 and that has DotNet 4.5.
Unless I'm missing _you're_ point…

**Comment by thomaslevesque** [comment]
> My point was that there's no agent that has MSBuild v14 and that has DotNet 4.5.

Ah I see... I misread your previous message. .NET 4.6 is an in-place upgrade of 4.5, so if agent01 has MSBuild v14 and .NET 4.6, it should work fine.

**Comment by blairconrad** [comment]
I sort of thought so. We _could_ just change the restriction on the build.
But if we're doing all this - just supporting v14, then would upgrading the sln to VS2015 be the thing to do as well?

**Comment by thomaslevesque** [comment]
> But if we're doing all this - just supporting v14, then would upgrading the sln to VS2015 be the thing to do as well?

I don't think it's necessary. Since we only have C# code, MSBuild 14 can build a VS2013 solution as well. The problem arises only when you have C++ code that is bound to a specific version of the build tools.

**Comment by blairconrad** [comment]
I'm a little lost. If we changed to just v14, and left the slns as they are, and someone opened the sln in VS2013, then they wouldn't be able to build the fancy new C# with the bling strings [that you were worried about](https://github.com/FakeItEasy/FakeItEasy/issues/537#issuecomment-188789268), no?

**Comment by thomaslevesque** [comment]
> I'm a little lost. If we changed to just v14, and left the sln as it is, and someone opened the sln in VS2013, then they wouldn't be able to build the fancy new C# with the bling strings that you were worried about, no?

What I'm saying is that we don't *need* to change the .sln to make TeamCity use MSBuild v14. But we should probably do it nonetheless if we start using C# 6 features.

**Comment by adamralph** [comment]
This issue isn't about switching to C# 6, it's purely about allowing the build script to run on machines which only have msbuild 14. Let's not conflate the two issues.

For me, the best way to aheive what this issue is about is to switch to using msbuild 14 by default, falling back to the obsolete msbuild 12 if required.

We can make a decision about starting to use C# 6 features (and with it, the corresponding switch to msbuild 14 and VS 2015 as minimum required versions) in a separate issue.

**Comment by blairconrad** [comment]
> we should probably do it nonetheless if we start using C# 6 features

Absolutely. But until we want to use C# 6 features, there's no need.

I think I'm in agreement with @adamralph. Switching to VS2015/C# 6 can be a separate discussion, unless @thomaslevesque has an objection to defaulting to MSBuild v14 _while still keeping the codebase free of C# 6 features_.

**Comment by adamralph** [comment]
Issue resolved. Now let's talk about moving to C# 6 elsewhere :wink:
