### ISSUE TITLE
make spec members static and re-enable rule CA1822

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#544]
From https://github.com/FakeItEasy/FakeItEasy/pull/542#discussion_r40284574.

**Comment by blairconrad** [comment]
Reopening, as this was incompletely fixed by #1026.

**Comment by blairconrad** [comment]
Barred on comments in#1035, this can be closed.
I have no github credentials with me so can't update the labels.

**Comment by blairconrad** [comment]
Or milestone our release notes.

**Comment by thomaslevesque** [comment]
> I have no github credentials with me so can't update the labels.

Which labels did you want to add?

> Or milestone our release notes.

Should this kind of task be in the release notes anyway? Since it affects only the tests, it has no impact for the end user.

**Comment by blairconrad** [comment]
Oh I thought there'd be an in-progress that would need to be removed. But I
guess Adam's waffle does that.

As far as release notes, this past release or so we've been putting
everything in. But I see your point about the tests. And especially since
there's no community involvement, I could get behind not release noting.

  B

**Comment by blairconrad** [comment]
Thanks for closing!

**Comment by adamralph** [comment]
I'm a little confused now. Did we make the spec members static or not?

**Comment by blairconrad** [comment]
We made spec members static. We did not re-enable rule CA1822.

**Comment by adamralph** [comment]
Thanks @blairconrad - I've renamed the issue.
