### ISSUE TITLE
Support UWP?

### ISSUE THREAD

**Issue by RafaelPlantard** [FakeItEasy/FakeItEasy#550]
The fake it easy supports the universal windows platform (UAP) Windows 10?

**Comment by blairconrad** [comment]
I must admit, I am not 100% on top of the latest Windows platform developments, but is this not about the same as asking when FakeItEasy will support .NET Core?
That issue has already been opened as #531.

**Comment by adamralph** [comment]
I honestly have no idea. Just when I think I'm starting to get it by reading things like https://oren.codes/2015/06/16/demystifying-pcls-net-core-dnx-and-uwp-redux/ another curve ball comes along like https://oren.codes/2015/08/29/uwp-nuget-package-dependencies/

I'm lost.

**Comment by adamralph** [comment]
See https://twitter.com/adamralph/status/653581339661348864

This is indeed a duplicate of #351

**Comment by blairconrad** [comment]
@adamralph, I'm going to edit your comment to say "duplicate of #531".

**Comment by blairconrad** [comment]
And thanks for the research!
