### ISSUE TITLE
FakeItEasy failed assertion with randomly <ignored> param (and there is a match in the calls)

### ISSUE THREAD

**Issue by timvanderweijde** [FakeItEasy/FakeItEasy#562]
I'm trying to implement a unit test with a methodcall assertion. (MustHaveHappened)

I'm using the following code:

```c#
[Fact]
public void Should_set_setting_and_map_new_value_for_non_existing_setting()
{
    //Arrange
    var userSetting = new SettingDetailsBuilder().Build();
    var respository = A.Fake<ISettingsRepository>();
    A.CallTo(() => respository.GetUserSetting(0, 0, null)).WithAnyArguments().Returns(userSetting);
    var dataretriever = new SettingsDataRetriever(respository);

    //Act
    var newUserSetting = dataretriever.SetUserSetting("variableName", "SomeOtherValue", 1, 1, "FST");

    //Assert
    A.CallTo(() => respository.GetUserSetting(1, 1, "variableName")).MustHaveHappened();
}
```

But I get randomly a failed test, whereby some arguments are mentioned as "ignored". However, the assertion is with exact parameters.

Error:

    Assertion failed for the following call:
        AlfaProNext.Repositories.Settings.ISettingsRepository.GetUserSetting(1, <Ignored>, <Ignored>)
      Expected to find it at least once but found it #0 times among the calls:
        1: AlfaProNext.Repositories.Settings.ISettingsRepository.Exists(varName: "variableName")
        2: AlfaProNext.Repositories.Settings.ISettingsRepository.GetUserSetting(
              userId: 1,
              profileId: 1,
              variableName: "variableName")

Does anybody knows why this is happening randomly?

ps I added the same issue on Stackoverflow. 
http://stackoverflow.com/questions/33995755/fakeiteasy-failed-assertion-with-randomly-ignored-param-and-there-is-a-match

**Comment by blairconrad** [comment]
@timvanderweijde, can you tell me what version of XUnit and FakeItEasy you're using?

Without seeing more, I fear that you're using XUnit 2.0, which runs tests in parallel, and a FakeItEasy earlier than 2.0.0-beta009.
That release included a fix for #476, a bug where argument matching was not threadsafe.
If my guesses about the versions are right, consider upgrading. Or running the tests in a single thread.

If not, we'll need more information. You've nowhere in the code where an expectation is set on `GetUserSetting`, looking for `1, <Ignored>, <Ignored>`?

**Comment by timvanderweijde** [comment]
hi @blairconrad, 

You are right, we are using XUnit. I will try the latest FakeItEasy beta to resolve this.

Thanks for the fast response!

Regards, Tim

**Comment by blairconrad** [comment]
@timvanderweijde, cool.

I look forward to hearing how it goes. Keep in mind there are some technically breaking changes in 2.0, but we have worked to minimize them.
If in doubt, consult the [list of all changes so far in 2.0](https://github.com/FakeItEasy/FakeItEasy/wiki/Changes-in-version-2.0). And/or ask us!

**Comment by timvanderweijde** [comment]
@blairconrad 

Every looks great now! Thanks again!

**Comment by blairconrad** [comment]
Gee. That was quick. Great. In the meantime, I put essentially the same answer in the StackOverflow question, on faith.

Happy FakeItEasying!

**Comment by timvanderweijde** [comment]
haha I was doing the same thing in StackOverflow. :-) Better then no answer I suppose. ;-)
