### ISSUE TITLE
Remove all write-only properties

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#571]
Per @thomaslevesque's remark: https://github.com/FakeItEasy/FakeItEasy/pull/529#discussion_r49126608.

While we're at it, I think it has some friends that are in a similar state. See the [FakeManager constructor](https://github.com/FakeItEasy/FakeItEasy/blob/bd57a05c0de5ff37609230fd1b8bc4ec45bc9d4d/Source/FakeItEasy/Core/FakeManager.cs#L43).

**Comment by adamralph** [comment]
I think that we should sweep up all instances of this anti-pattern in one go. Shall we change the title to

> Remove all write-only properties

?

**Comment by blairconrad** [comment]
Some may be harder than the family that we've identified, but I'm all for taking a crack at it.

**Comment by blairconrad** [comment]
Good thinking.

**Comment by adamralph** [comment]
If any of them turn out to be public, I think we should remove the `refactoring` label and add the `feature` and `breaking` labels, and probably get it into 2.0.

**Comment by blairconrad** [comment]
Cool. So... how does one _find_ write-only properties? Anything easier than writing code to reflect over all the members of all the types and examine access levels?
Regardless, we should do all the libraries, not just the .Net 4.0 like I did when looking for unused types…

**Comment by blairconrad** [comment]
Adding to 2.0 for now, since we'll need to do the analysis before deciding whether it's in 2.0…

**Comment by thomaslevesque** [comment]
> If any of them turn out to be public, I think we should remove the refactoring label and add the feature and breaking labels, and probably get it into 2.0.

If any of them are public, they should probably be treated in priority. Private usages of this pattern are not a really big issue, they can be fixed at any time

> how does one find write-only properties

if they're auto-properties, it's pretty easy: just search for `private get`

**Comment by adamralph** [comment]
> Adding to 2.0 for now, since we'll need to do the analysis before deciding whether it's in 2.0…

:+1: good call

**Comment by blairconrad** [comment]
Because I love this sort of thing, I've been poking. I used ReSharper to find property bits that could be made private, as a first step. Because why purge the write-only properties and then find out there are more?I found some gets that could be made private while I was at it. Would you rather I left them for a separate issue?
(Also some properties that can just be removed altogether.)

**Comment by thomaslevesque** [comment]
> Would you rather I left them for a separate issue?

I don't think it needs to be done in a separate issue (perhaps just a separate commit)

**Comment by adamralph** [comment]
Write only properties is an anti-pattern we want to get rid of and it needs restructuring of some classes in order to do it.

Reducing the scope of gets and removing properties altogether sounds like it's just redundant code removal. Or would it also involve some structural change?

If we can find a way of wording this issue nicely to contain all the change then we leave as one, but if they are quite different things conceptually then it may be better to split into separate issues to be easily understandable by our community.

Note that the separate issues could still all be closed by a single pull request if that's easiest.

**Comment by blairconrad** [comment]
I ran an analysis on the head of 461-new-fake-options-builder, and everything that ReSharper found whose accessibility could be reduced is private or internal or in a test project, so there's no external changes.
And there's a conflict relative #575 in FakeScope.
I can create a "reduce type member visibility" issue (or even a PR) when the time comes, and then proceed here.

**Comment by blairconrad** [comment]
… and as it turns out, the only types that currently have write-only properties are also internal or private.
Removing from 2.0.

**Comment by adamralph** [comment]
Closing n the basis of #779. If we do find more write only properties which have no getter at all, we can fix them as we find them.
