### ISSUE TITLE
Support collections of fakes in Fake.InitializeFixture

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#578]
I was playing with the `[Fake]` and `[UnderTest]` attributes and the `Fake.InitializeFixture`, and I realized it doesn't support collections of fakes. I was trying to do something like this:

``` c#
public class Foo
{
    public Foo(IBar[] bars) { ... }
}

public class FooTests
{
    [UnderTest]
    public Foo Foo { get; set; }

    [Fake]
    public IBar[] Bars { get; set; }

    public FooTests()
    {
        Fake.InitializeFixture(this);
    }

    ...
}
```

Currently this doesn't work, because `Fake.InitializeFixture` attempts to create a fake array of `IBar`s, rather than an array of fake `IBar`s.

If support for this was added, perhaps it should be done with a separate `[Fakes]` attribute, that would let the user specify the number of elements, e.g.:

``` c#
[Fakes(3)]
public IList<IBar> Bars { get; set; }
```

However this would probably require non trivial changes in `DefaultFixtureInitializer`, because currently it initializes the SUT first, collecting the created fakes along the way, and then assigns the members marked as `[Fake]`.

**Comment by blairconrad** [comment]
Marking on hold now that we've raised the idea of [removing the whole feature](https://github.com/FakeItEasy/FakeItEasy/issues/964#issuecomment-280834895).

**Comment by blairconrad** [comment]
Closing, since we're going to remove the feature in #992, and it's already been deprecated in #1102.
