### ISSUE TITLE
Make That hide object members

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#580]
(Raised by @dealproc in a private chat.)

… probably by extending `IHideObjectMembers`?

Otherwise we see this in the IDE:

![image](https://cloud.githubusercontent.com/assets/3275797/12486933/d6ca622c-c032-11e5-9399-f5e257e86141.png)

Then you accidentally pick `Equals` instead of `IsEqualTo`, and, to quote @dealproc without his permission

> that's not cool the first 20 times you do it.

**Comment by blairconrad** [comment]
There's probably other places that could benefit, but I think that it's `That`'s role in establishing conditions that really causes the confusion.

**Comment by thomaslevesque** [comment]
It shouldn't be hard at all, and could probably be included in 2.0.0.

**Comment by blairconrad** [comment]
I expect it's super easy, which was one of the reasons for adding the **up-for-grabs** label.
Could easily be done in time for 2.0.0, but it's non-breaking, so if it happens not to make it in, there's no harm—it could be go in 2.1.0 or later as well!

**Comment by blairconrad** [comment]
Bumping to **P2** because I feel bad - even though there's no behavioural change, fixing this would remove an annoyance that was reported by a valued community member.

**Comment by dealproc** [comment]
see what i can do, i'm the one that reported it, so see if i can contrib it back.

**Comment by dealproc** [comment]
We can add it in for use within 2013, but won't be recognised in 2015 until https://github.com/dotnet/roslyn/issues/4434 is resolved and RTM.

**Comment by blairconrad** [comment]
Oops. Should've removed **up-for-grabs** when I added **taken**.

**Comment by blairconrad** [comment]
Thanks for your contribution, @dealproc. Look for your name in the release notes!
:trophy:

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
