### ISSUE TITLE
Clean up specs touched by #574

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#582]
Rework all the Specs, according to a comment made by @adamralph: https://github.com/FakeItEasy/FakeItEasy/pull/576#discussion_r49584676

- [x] CreationOptionsSpecs.cs
- [x] CreationSpecs.cs
- [x] FakeOptionsBuilderSpecs.cs
- [x] FakeScopeSpecs.cs

In addition to changes inspired by that comment,  @thomaslevesque and I have had some additional conversation in #574, where I ultimately ended up proposing replacing steps like

```c#
"Given a type that has an implicit options builder defined"
    .x(() => { }); // see RobotActivatedEvent

"And the options builder updates the options to configure the fake"
    .x(() => { }); // see DomainEventFakeOptionsBuilder.BuildOptions
```

With 

```c#
"Given a type that has an implicit options builder defined"
    .See<RobotActivatedEvent>();

"And the options builder updates the options to configure the fake"
    .See<DomainEventFakeOptionsBuilder>();
```

Which would be defined by this extension method

```c#
public static class SpecExtensions
{
    public static IStepBuilder See<T>(this string text)
    {
        return text.x(() => { });
    }
}
```

**Comment by adamralph** [comment]
The proposed extension method is kinda cool :sunglasses:, but it does lose the `BuildOptions` part of `// see DomainEventFakeOptionsBuilder.BuildOptions`

**Comment by adamralph** [comment]
FWIW, I'm not sure this is a P1 :wink:

**Comment by blairconrad** [comment]
@adamralph said

> it does lose the BuildOptions part of `// see DomainEventFakeOptionsBuilder.BuildOptions`

It does. Originally the extension method was intended for the `// see type` comments, and I was working on a tortured version for referring to methods, and nothing came of it. 
Then I thought, "well, there's only one thing of interest in `DomainEventFakeOptionsBuilder`, and it's clear from context, so I floated the idea of just using the type-See.

Regarding **P1**, sure, I agree. I just didn't want anyone to think I took the last step lightly. Mostly you, because you care more about the spec wording that most, probably. Or have more evolved sensibilities. Something.

**Comment by thomaslevesque** [comment]
> and I was working on a tortured version for referring to methods, and nothing came of it.

Actually, the syntax you came up with wasn't that bad, just a little verbose:
```
"And the options builder updates the options to configure the fake"
    .See((DomainEventFakeOptionsBuilder ob) => ob.BuildOptions);
```
It could also be written like this:
```
"And the options builder updates the options to configure the fake"
    .See<DomainEventFakeOptionsBuilder>(ob => ob.BuildOptions);
```
which looks a little nicer IMO (every bit as verbose, though)

**Comment by blairconrad** [comment]
Oh, if we don't hate `.See<DomainEventFakeOptionsBuilder>(ob => ob.BuildOptions);` that much, I'd be happy to go with that.

Regardless, sometime later I'll start a PR so we can assess the "textual" changes to the Specs and then we can optionally wrangle over fancy extension methods.
