### ISSUE TITLE
make IFakeOptions of T hide object members.

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#583]
Very much like #580.
Otherwise we get offered `Equals` and `ToString` and so on, for no good reason.

**Comment by dealproc** [comment]
Mind if I take it?

**Comment by dealproc** [comment]
Odd... in master, it seems to be there:

https://github.com/FakeItEasy/FakeItEasy/blob/master/Source/FakeItEasy/Creation/IFakeOptions.cs#L15

If you're using vs2015, there's a bug with Roslyn that is not respecting the `EditorBrowsable` attribute.

**Comment by thomaslevesque** [comment]
It's already there in `IFakeOptions`, but not in `IFakeOptions<T>`

**Comment by blairconrad** [comment]
My mistake. I've updated the description to exclude `IFakeOptions`. I made the issue at work while I happened to see the problem when showing a colleague something. And I made an assumption about where the lack was.

**Comment by blairconrad** [comment]
@dealproc, You're more than welcome to it!

**Comment by blairconrad** [comment]
Thanks for your contribution, @dealproc. Look for your name in the release notes!
:trophy:

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
