### ISSUE TITLE
Move IHideObjectMembers to top level namespace

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#585]
It's currently in `FakeItEasy.Configuration` because, I can only guess, it was originally only used for types in that namespace. We're already using it for several types not in that namespace, e.g. `IFakeOptions`. It should be in the namespace `FakeItEasy`.

**Comment by blairconrad** [comment]
Good idea. Let's wait until other **in-progress** `IHideObjectMembers` members are merged, though…

**Comment by adamralph** [comment]
:+1:

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
