### ISSUE TITLE
Add a .editorconfig

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#586]
for use with http://editorconfig.org/

Some potential contributors struggle with formatting issues, specifically around whitespace.
In some cases, these are easily worked around, and sometimes not.

The presence of a `.editorconfig` file may help avoid some problems. Not everybody is using an editor (or has the plugin) that will respect these settings, but if even a few do, it's no great hardship to add and maintain the file.

Thoughts?

**Comment by thomaslevesque** [comment]
I like the idea. I never used editorconfig myself, but I'm willing to give it a try.

**Comment by thomaslevesque** [comment]
Just added it as an experiment. Perhaps I was a bit hasty in creating a PR, though ;)

**Comment by blairconrad** [comment]
Ha! PRs are useful for discussion, if nothing else.

**Comment by blairconrad** [comment]
> @thomaslevesque was assigned by @`adamralph 7 minutes ago

Does this indicate approval?

**Comment by adamralph** [comment]
> @thomaslevesque was assigned by @adamralph 7 minutes ago

I think this was Waffle, because @thomaslevesque created the PR and wrote in it

> Fix #586

**Comment by adamralph** [comment]
Anyway, I'm all up for `.editorconfig`. I already use it in several other projects.

**Comment by thomaslevesque** [comment]
> I think this was Waffle

Ah, that explains it! I was quite impressed by your reaction time ;)
