### ISSUE TITLE
switch branch check to just require continuous-integration/codebetter-ci

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#590]
Previously on https://github.com/FakeItEasy/FakeItEasy/settings/branches/master, "default" was required but "continuous-integration/codebetter-ci" was not.

#589 was failing as the "default" check had not completed, but it showed that "continuous-integration/codebetter-ci" was complete, and it looked great!

[Report change status to Github on the CI server settings](http://teamcity.codebetter.com/admin/editBuildFeatures.html?id=buildType:bt929) showed
that the context was continuous-integration/codebetter-ci:
![Report Change Status](http://i.imgur.com/5gDMnxD.png!)

So @thomaslevesque and I chatted and we switched that one to be required.

**Comment by blairconrad** [comment]
@adamralph, do you know if we did the right thing?

**Comment by adamralph** [comment]
Oops! Sorry, yes, this was me fiddling with something which I didn't think would have any bad effect :blush: 

In other projects, we've aligned the codebetter build name to use the naming convention dictated by Travis CI which, whilst opinionated, is better then "default", e.g.

![image](https://cloud.githubusercontent.com/assets/677704/12693440/fe1178de-c744-11e5-9296-00dc0045a6d7.png)

If you're happy with the naming, then yes, making this the only required build is exactly the right thing to do.

**Comment by adamralph** [comment]
(And I also thought "codebetter-ci" would be better than "teamcity".)

**Comment by blairconrad** [comment]
> (And I also thought "codebetter-ci" would be better than "teamcity".)

If nothing else, it will improve my tweets.

In the future, if we're performing these kinds of maintenance operations, it's probably a good idea to char (or better, raise an issue, since we can search on those later) so we can all see what's going on and fix it later, or learn something. For example, I'm going to learn something right now:

What are you doing with both teamcity and travis CI builds?

**Comment by blairconrad** [comment]
And thanks for clearing that up!

**Comment by thomaslevesque** [comment]
> What are you doing with both teamcity and travis CI builds?

My guess is that it's because Travis CI uses Mono.

**Comment by adamralph** [comment]
> In the future, if we're performing these kinds of maintenance operations, it's probably a good idea to char (or better, raise an issue, since we can search on those later) so we can all see what's going on and fix it later, or learn something. For example, I'm going to learn something right now:

Sorry, yes, you're absolutely right. I shouldn't have just gone ahead and done it. *Eats humble pie.* Normally I'd at least ping on gitter, if not raise an issue. I'm not sure why I didn't this time. No excuses.

> What are you doing with both teamcity and travis CI builds?

As @thomaslevesque indicates, it's to perform a CI build on Mono, so that the project can claim to "officially support Mono".

**Comment by blairconrad** [comment]
@adamralph, no worries. I hadn't intended to chasten, just to suggest a guideline for us all in the future.

Oh, Mono. Cool.
