### ISSUE TITLE
Remove custom object containers (currently used by Scopes)

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#603]
From https://github.com/FakeItEasy/FakeItEasy/issues/484#issuecomment-184679735.

When creating a new Fake Scope, it's possible to provide a custom `IFakeObjectContainer` that the scope will use to create new Dummies and to build up Fake Options. With recent improvements in Dummy Factories and Fake Option Builders, this power is no longer necessary. And considering that Fake Scopes aren't safe across threads, now seems to be the time to remove the custom object containers from Scopes (and FakeItEasy).

**Comment by blairconrad** [comment]
I'm happy to work on this, if nobody else wants it. Or wants to argue against doing it.

**Comment by thomaslevesque** [comment]
:+1:

**Comment by adamralph** [comment]
:+1:

**Comment by blairconrad** [comment]
You and your labels, @adamralph! 
Just when I thought I had it figured out.

"'Like ordered assertions, we're not removing a feature, just having provided a different way to perform the same operations' @adamralph will say" thought I.

**Comment by adamralph** [comment]
@blairconrad that quote applies to https://github.com/FakeItEasy/FakeItEasy/issues/602 since there we are not removing a feature, only changing the API.

In this issue, we are actually removing a feature, no?

**Comment by blairconrad** [comment]
Well, you can still supply your own Dummies, and your own things for building fake options.
Really, I'm fine with **removal** on there. I just like to complain. And nest quotes.

**Comment by adamralph** [comment]
:smile:

**Comment by adamralph** [comment]
@blairconrad I've made #604 dependent on this issue, since it can be done before this issue, but perhaps it makes sense to combine them?

**Comment by blairconrad** [comment]
I think separate is good, as we probably want @thomaslevesque to finish #602 before we do #604 anyhow.

**Comment by blairconrad** [comment]
Folks, I'm nearing the end of this. Part of the fallout is that `DynamicContainer` can (I think should) be split into two internal classes, one that applies the appropriate discovered `IFakeOptionsBuilder` (if any) and one that will create a Dummy from the appropriate discovered `IDummyFactory`. These are basically classes that each have a single method:

1. `public void BuildOptions(Type typeOfFake, IFakeOptions fakeOptions)` and
2. `public bool TryCreateDummyObject(Type typeOfDummy, out object fakeObject)`

As a work in progress I borrowed a page from the `DynamicContainer` playbook and called the classes

1. `DynamicOptionsBuilder` and
2. `DynamicDummyFactory`

I don't _love_ the names, but am at a loss for something better. Do you guys have any opinions on the names, or suggestions?

I'd considered `ExtensionBased*`, since these classes will work on the discovered extension points, but am not sure how that will read to everyone else.
Ordinarily, I'd just chop off the prefix, but in this case, I think this just introduces more confusion.

Thanks!

**Comment by thomaslevesque** [comment]
Will these classes be public? `DynamicContainer` is public, but I think it's only so that it can be used in a scope. If you can make `DynamicOptionsBuilder` and `DynamicDummyFactory` internal, it doesn't matter too much what their name is; we can always rename them later if necessary.

**Comment by blairconrad** [comment]
internal

**Comment by blairconrad** [comment]
And it's true we can always rename, but we're touching things now, and I like to get a good name in early, so we don't have confusion later.
Like the old "what's the difference between `IFakeOptionsBuilder` and `IFakeObjectOptionsBuilder`?" question.
I'll carry on for now. I can always address complaints in the PR review.

**Comment by blairconrad** [comment]
As I mentioned, I split `DynamicContainer` in two. After that, the `IFakeObjectOptionsBuilder` and `IFakeObjectContainer` interfaces weren't pulling their weight, so I removed them.
PR incoming!

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
