### ISSUE TITLE
Fake arguments being evaluated as null when not in the lambda expression

### ISSUE THREAD

**Issue by Jameskmonger** [FakeItEasy/FakeItEasy#607]
I have a setup similar to the one below in one of my tests, and the `CallTo` assertion at the bottom is failing when setup like this.

    var fakedTool = A.Fake<ITool>();

    var concreteUnderTest = new Concrete(fakedTool);

    concreteUnderTest.doSomething();

    var fooConstraint = A<Foo>.That.Matches(f => f.Name.Equals('Alice'));
    var barConstraint = A<Bar>.Ignored;

    A.CallTo(() => fakedTool.ObservedFunction(fooConstraint , barConstraint))
        .MustHaveHappened(Repeated.Exactly.Once);

I have placed a breakpoint directly above the `CallTo` line, and the values of `fooConstraint` and `barConstraint` are both `null`.

When I set the assertion up like this, however, it passes:

    A.CallTo(() =>
        fakedTool.ObservedFunction(
            A<Foo>.That.Matches(f => f.Name.Equals('Alice')),
            A<Bar>.Ignored
        )
    ).MustHaveHappened(Repeated.Exactly.Once);

What is causing this behaviour? Is it intended?

**Comment by blairconrad** [comment]
@Jameskmonger, it's just the way it works, unfortunately. `That` and `Ignored` are magic.

See [Always place Ignored and That inside A.CallTo](https://github.com/FakeItEasy/FakeItEasy/wiki/Argument-Constraints#information_source-always-place-ignored-and-that-inside-acallto)

**Comment by thomaslevesque** [comment]
> What is causing this behaviour? Is it intended?

It's not really intended, it's an unfortunate side effect. The lambda you pass to `A.CallTo` is executed in a special context where calls to `That` and `Ignored` are recorded as constraints. When used from outside of `A.CallTo`, they just return null.

There's an open issue (#559) to make it throw explicitly when used outside of `A.CallTo`, rather than making the test fail for no obvious reason.

**Comment by Jameskmonger** [comment]
Thanks for your answers, @blairconrad and @thomaslevesque. I like the solution suggested in #559. It wasn't too difficult to see that there was an issue with the constraints being null, but it would have saved me 10 minutes or so if it had simply thrown an exception.

I'll close this now!

**Comment by blairconrad** [comment]
Oh, I'd forgotten about #559. Good memory, @thomaslevesque.
Thanks for raising the question, @Jameskmonger.
I don't suppose you're interested in working on #559? No pressure if you're not!

**Comment by Jameskmonger** [comment]
I can certainly take a look into it @blairconrad. I'll fork when I get a chance :smiley:

**Comment by thomaslevesque** [comment]
> I don't suppose you're interested in working on #559? No pressure if you're not!

I had started working on it, and then forgot about it... I should probably finish what I started :wink:

**Comment by blairconrad** [comment]
Uh oh!
Now I've started a thing.

Perhaps you two should rock-paper-scissors-lizard-spock it out and then either assign it to @thomaslevesque or mark it as **taken** by @Jameskmonger.

**Comment by Jameskmonger** [comment]
No problem @thomaslevesque, feel free to finish it if you've already started!
