### ISSUE TITLE
Accept that csprojs will start with BOMs and not end with newlines

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#608]
From https://github.com/FakeItEasy/FakeItEasy/pull/606#issuecomment-187477612.

Whenever we modify a project file in Visual Studio, the IDE adds the UTF-8 BOM to the beginning of the file and removes the final newline in the .csproj.

Rather than check the diffs and fight with the IDE on every commit, I think we should

1. update all the .csproj files to add the BOM and remove the final newline, and
1. update the .editorconfig file with
```ini
[*.csproj]
insert_final_newline = false
charset = utf-8-bom
```

Objections?

**Comment by adamralph** [comment]
:+1: from me

**Comment by blairconrad** [comment]
Taking. Because @thomaslevesque will love it.

**Comment by thomaslevesque** [comment]
:+1:
