### ISSUE TITLE
Throw exception on "empty" CallTo statement

### ISSUE THREAD

**Issue by Jameskmonger** [FakeItEasy/FakeItEasy#612]
I've noticed that it is entirely possible to put an empty `CallTo` statement, such as:

    A.CallTo(() => foo.Bar());

When the developer intended to write:

    A.CallTo(() => foo.Bar()).MustHaveHappened();

It would potentially be useful for an exception to be thrown if a `CallTo` statement is called without anything chained onto it.

**Comment by blairconrad** [comment]
Thanks for bringing this up, @Jameskmonger.

**Comment by blairconrad** [comment]
It appears to be a duplicate of #490, so if you've no objection, I think we should close this issue, though.

**Comment by blairconrad** [comment]
There's no way to throw an exception when the result of `CallTo` is unused, since the code can't tell whether the result is used or not. That's why an analyzer will be made.
