### ISSUE TITLE
Switch the solution's minimum version to VS2015

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#615]
From https://github.com/FakeItEasy/FakeItEasy/issues/537#issuecomment-188925534

Would allow us to use fancy C#6 features. Also supports other issues, like #489.

**Comment by adamralph** [comment]
And also switching the rake file to require msbuild 14.

**Comment by blairconrad** [comment]
Yes. Excellent point.

**Comment by blairconrad** [comment]
The rake file will locate MSBuild, since #614 has been closed.

In addition to updating the .sln, we will need to make sure that the TeamCity agent has MSBuild 14. @thomaslevesque investigates.

**Comment by thomaslevesque** [comment]
The `JetBrains-dotnet-agent01` agent seems to be compatible. It has:
- MSBuild 14
- VS2015
- .NET 4.6
- targeting packs for .NET 3.5 and 4

**Comment by adamralph** [comment]
When we do this, we'll have to remove the MSBuild 12 fall back from the rake file.

**Comment by thomaslevesque** [comment]
> When we do this, we'll have to remove the MSBuild 12 fall back from the rake file.

Good point.
