### ISSUE TITLE
Consider changing ordered assertion behaviour for the 2.0 release

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#624]
In #605, we opted to decouple ordered assertions and scopes without changing the ordered assertions' behaviour.

@thomaslevesque has raised the spectre of changing the behaviour because they work only in very limited scenarios.
We believe that any attempt at improving the behaviour would require the `ISequentialCallContext` to collect individual call assertions and perform a final step to actually evaluate the assertions, perhaps via a `Validate` or similar method. This would be a breaking API change.

Should we make this change now while we're breaking APIs or keep the ordered assertion behaviour and API, knowing that if ever we wanted to change, we'd have to break the API at that time?

**Comment by blairconrad** [comment]
I've no strong feeling either way, in that it seems that what we have meets peoples' needs. And, if we decide to change things later, I also don't mind doing a (smaller scale) major number release.
On the other hand, if we have a plan for changing things that doesn't rob current users of what are likely common use cases, I'm in.

**Comment by thomaslevesque** [comment]
The current behavior is somewhat broken, but as we discussed at length in #605, we don't really know what the correct behavior _should_ be. I'm not sure we can come up with a behavior that will satisfy everyone...

As much as I'd like to fix it, perhaps it's better to drop this for now, otherwise release 2.0.0 will never get out.

**Comment by adamralph** [comment]
I vote for leaving this for post 2.0.

No-one has asked for it (including ourselves presumably, as users), so the interest is purely academic. Of course, there is an element of "build it and they will come" but I'm guessing that ordered assertions is a rarely used edge case feature anyway, and the advanced scenarios we are talking about move that squarely into a corner case. How likely is it that anyone will ever want to assert calls A, B, A in order? ([Inappropriate intimacy](http://c2.com/cgi/wiki?InappropriateIntimacy), [Gullivers Travels tests](http://dhickey.ie/2014/03/gullivers-travels-test/), etc.)

That said, I'm more than happy to pull this in at some point if someone is motivated enough to do it, but I'm sure it can wait for a 3.0 release. However, I'd be reluctant to pull it in if it breaks code that relies on immediate execution. Perhaps it would need to be a separate "advanced ordered assertions" API.

**Comment by blairconrad** [comment]
It sounds like we're in agreement:

"Won't fix in 2.0. Would fix later if there was a demonstrable need."

**Comment by adamralph** [comment]
:+1:

**Comment by blairconrad** [comment]
This issue was not fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
