### ISSUE TITLE
add MustUseReturnValue to `A.CallTo` and `NextCall.To`

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#633]
Proposed by @drauch in https://github.com/FakeItEasy/FakeItEasy/issues/490#issuecomment-199825874.

We hadn't cared for the idea of putting `Pure` on the methods back when discussing #505, but `MustUseReturnValue` has exactly the semantics we want.

@thomaslevesque has determined that this would present a duplicate warning to one that the Analyzer discussed in #490 would, but there's no real harm.

**Comment by blairconrad** [comment]
@thomaslevesque, @adamralph, do we want to include this in 2.0? You guys seem to have very specific definitions of RCs that honestly, I don't think sound different from my idea, but when you talk about it, it seems like you do. I can go either way.

**Comment by adamralph** [comment]
I'm :-1: on this. I'll chime in more over on #490

**Comment by blairconrad** [comment]
Closing, for the reason @adamralph said.
