### ISSUE TITLE
Remove NextCall.To()

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#642]
Only known uses are

* "Specifying a call by example" - http://fakeiteasy.readthedocs.org/en/stable/specifying-a-call-to-configure/#specifying-a-call-by-example
* a way to configure property setters, which will be made redundant by #175
* VB.NET syntactic sugar http://fakeiteasy.readthedocs.org/en/stable/assertion/#vbnet - an edge case feature not worth supporting

**Comment by adamralph** [comment]
@FakeItEasy/owners can we confirm that (we can live without/have a replacement for) "Specifying a call by example"?

**Comment by thomaslevesque** [comment]
> @FakeItEasy/owners can we confirm that we (can live without/have a replacement for) "Specifying a call by example"?

We will have a better alternative for property setters; other than than, I don't think specifying a call by example has much value, and it doesn't work properly in many scenarios (e.g. doesn't support `A<T>.Ignored`).

The only good reason to keep, IMO, would be for language constructs that are not supported in expression trees. But apart from assignments, I can't think of any compelling example.

**Comment by blairconrad** [comment]
Just as @thomaslevesque said.

**Comment by adamralph** [comment]
Excellent. So we can go ahead.

**Comment by thomaslevesque** [comment]
I just did a quick search in GitHub for occurrences of `NextCall` in C# and VB code, and found only [one occurrence](https://github.com/agross/FakeItEasySpecs/blob/344786a9e42fe71fdae1b96715e97d6f4d4d1ca4/FakeItEasySpecs/EventSubscriptionSpecs.cs#L38) outside of FakeItEasy itself (and it could easily be replaced with something else). Of course, not all the code in the world is on GitHub, but it still gives an idea of the usage of this feature. I don't think many people will miss it. Let's go ahead and remove it.

**Comment by adamralph** [comment]
We only `taken` when an issue is taken by an external contributor, no?

**Comment by adamralph** [comment]
I.e. it's a workaround for not being able to assign people outside the org to issues.

**Comment by adamralph** [comment]
See https://github.com/FakeItEasy/FakeItEasy/wiki/Issue-labels

(sorry for notification spam :blush:)

**Comment by thomaslevesque** [comment]
> See https://github.com/FakeItEasy/FakeItEasy/wiki/Issue-labels

Ah, thanks! I was about to suggest we create such a page ;)

**Comment by blairconrad** [comment]
So we do. Oops.
I see you've removed the **taken** label. Thanks. Especially since the alternative would've been to remove me!

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
