### ISSUE TITLE
Switch to a build system which doesn't require extra installations

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#645]
I'm getting more and more loathed to install Ruby when I'm building a new dev machine purely for the purpose of running Rake. Rake is a majestic tool, but there are several worthy competitors nowadays which can be bootstrapped locally by a `build.cmd` and/or `build.sh`. E.g. Fake, Cake, Bau.

**Comment by thomaslevesque** [comment]
:+1: for Cake. It's really easy to use, well documented, and it's C#, so we already know the syntax. Most build tools are supported out of the box (NuGet, unit testing, CI...), and we can use NuGet packages. I also like the fact that you don't need to install anything specific to use it (not even scriptcs, and not even Cake itself; the PowerShell bootstrapper takes care of everything).

I looked at Fake, and while I like F# in general, I think Fake makes too much use of custom operators, which makes the syntax not obvious at all. For instance, it's hard to guess the meaning of `==>`, `=?>`, `!!` or `++` without looking the doc.

I haven't tried Bau yet, but I assume it will be @adamralph's first choice ;)

**Comment by blairconrad** [comment]
I've only used one of the suggestions (Bau), and that for the most trivial of projects. I liked what I saw. But I also really liked what I saw in the Cake docs yesterday.
If I knew nothing about either project, and saw the two tools for the first time, I'd try Cake. It seems to have a bigger community, and more tools built in.
However, having a Bau expert in the camp would be useful. @adamralph, I assume you've at least looked at Cake out of professional curiosity. Do you know of a reason, other than the obvious, why we might prefer Bau over Cake? Or Cake over Bau?

**Comment by adamralph** [comment]
I'll try and be completely impartial.

First, C# vs F#.

C# isn't a great scripting language. It's simply too verbose and symbolic (curly braces, primarily). F# is more concise, but I agree with @thomaslevesque that the various operators are quite confusing, and it would mean having to familiarise ourselves (not just the owners, but our community) with another language. On balance I think C# is the better choice.

Now Bau vs Cake.

There hasn't been much movement on Bau since the initial push in 2014. A fledgling community did start to gather initially but it hasn't really gained momentum. This is primarily down to me having other priorities. The main advantage of Bau is that it is focused purely on the task running domain and it leans on the infrastructure of scriptcs for execution and package management. The yields advantages such as compatibility with the scriptcs language support in omnisharp, which means you get intellisense for Bau files in VS Code, Atom etc. Bau is completely modular. It has a tiny core and everything, such as support for MSBuild, xunit, etc. is provided by lego-piece integration packages. Also, there is the advantage of having me as an owner of Bau in that I could push through any changes which we require in FIE fairly quickly.

Cake has a much larger community and is way more feature rich than Bau. It has a lot of momentum and new features are being added all the time. It's a shame that includes it's own underlying infrastructure rather than being built on some ubiquitous platform for execution and package management because this means language services for editors have to be custom made for Cake (I may be wrong on this, perhaps the lowest common denominator of Roslyn does yield some language support in various editors) and it also carries some of it's specialised idioms, e.g. `tools/packages.config` and installation under `tools/` for package management. Lastly, it is monolithic rather then modular. Support for everything under the sun is in the main package regardless of what bits you need (even if you don't need *any* of it).

On balance, Cake is probably the best choice right now. Whilst I much prefer the shape of the technical foundation of Bau, the project has languished and Cake is way more active.

**Comment by thomaslevesque** [comment]
> The main advantage of Bau is that it is focused purely on the task running domain and it leans on the infrastructure of scriptcs for execution and package management. The yields advantages such as compatibility with the scriptcs language support in omnisharp, which means you get intellisense for Bau files in VS Code, Atom etc.

That's an interesting point. As far as I can tell, the syntax is almost the same, so it should be possible to make Intellisense work for Cake as well. But is it really that important? I mean, we don't modify the build script very frequently...

> it also carries some of it's specialised idioms, e.g. tools/packages.config and installation under tools/ for package management.

In fact, you no longer need `packages.config`, you can just use:

    // old syntax, kept for backwards compatibility
    #tool NUnit.ConsoleRunner

    // new syntax, not limited to NuGet, and lets you specify the version
    #tool "nuget://NUnit.ConsoleRunner/?version=3.2.0"

**Comment by adamralph** [comment]
> it should be possible to make Intellisense work for Cake as well

It's nothing to do with the syntax of the library, it's about whatever is providing the intellisense to have enough contextual information to do so. E.g. in scriptcs, we have `Require<T>` which is provided by the host interface which is used to execute the script. If intellisense doesn't know about this, then it can't provide intellisense. In Cake, you have a top level `Task()` method which, again, will be provided by the host interface which Cake constructs to allow Roslyn to run the script. Intellisense would have to have explicit knowledge of Cake in order to provide intellisense for this. Indeed, it seems like work on this is [underway](https://github.com/cake-build/cake/issues/494).

This also troubles me https://github.com/cake-build/cake/issues/395#issuecomment-137814150

> Cake scripts are a superset of C#, that's why we have our own extension.

This again illustrates why Cake will have to re-invent all the various infrastructure pieces itself, since it's built on it's own platform rather than something like scriptcs. Imagine a world where something like Omnisharp has to have specific support written into it for each task runner (or other applications), instead just once, for scriptcs.

**Comment by adamralph** [comment]
As discussed elsewhere, it probably make sense to hold off on this until the dust has settled on the RTM tooling for .NET Core.

**Comment by blairconrad** [comment]
> As discussed elsewhere, it probably make sense to hold off on this until the dust has settled on the RTM tooling for .NET Core.

I think there are enough changes to make that there's benefit in working on it now (translation: I think it would be fun to work on now). May I?

**Comment by thomaslevesque** [comment]
> I think there are enough changes to make that there's benefit in working on it now (translation: I think it would be fun to work on now). May I?

Sure, why not!

**Comment by adamralph** [comment]
May I humbly suggest https://github.com/adamralph/simple-targets-csx

**Comment by blairconrad** [comment]
Of course. But you're too late. If you thought I was doing anything other than trying to create a fiendish chimera of our `rakefile.rb` and the SelfInitializingFakes's `build.csx`, you are very naive indeed. :smiling_imp: 

I'm aiming for a pretty direct port of our rakefile right now, actually. There may be opportunities to restructure later, but I'd like to get it functioning first. I already have build and pack working.

The "next build target" bits that nobody but me use will likely be tricky. Perhaps we could just keep those in ruby (whether it's rake or not makes no difference to me) for the nonce, and then revisit once we GitFlow it up, since we may not want to handle the releases anyhow. And we'll still have removed the ruby dependency for non-owners.

**Comment by blairconrad** [comment]
I added the issue to the milestone and release notes. This may be controversial. Remove if you think it's silly.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.1.0).
