### ISSUE TITLE
Consider removing SequenceNumber from ICompletedFakeObjectCall

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#651]
It's new, so nobody will miss it.
Is there any benefit to exposing it? Detriment?

**Comment by adamralph** [comment]
:+1: to remove it. It's an internal implementation detail.

**Comment by thomaslevesque** [comment]
If you can find an easy way to remove it, sure, it would certainly be better. But I don't think it will be easy... I already thought about how to do it, and couldn't come up with anything satisfying.

**Comment by adamralph** [comment]
Ah, sorry, I thought it was something trivial to do.

So I humbly went and had a look at the code rather than commenting from afar: given that it's in the `FakeItEasy.Core` namespace and that no test writer will ever touch it directly, does it really matter?

**Comment by blairconrad** [comment]
The `Invokes` and `ReturnsLazily` users will see it, is all.

**Comment by blairconrad** [comment]
I see `Method`, `Arguments`, and `FakedObject` being useful to them. `SequenceNumber` less so.
I'm not saying there's that much harm, but once people see it, they may ask questions, and…

**Comment by adamralph** [comment]
Ah yes, I see what you mean

![image](https://cloud.githubusercontent.com/assets/677704/14469459/f3e4d9d0-00e4-11e6-9df0-a427faa59524.png)

**Comment by adamralph** [comment]
I suppose it *could* be useful. E.g. I might use `Invokes()` to record the sequence number of all my fake calls and then do some kind of fancy advanced ordered assertion. As usual, it's a need I'd always try to avoid having, but still...

**Comment by adamralph** [comment]
In fact, this is a nice escape hatch for us for when someone asks how to do anything other than the very basic ordered assertion capability which we've propagated from 1.x to 2.x. It could be worth documenting as such and would be a good reason to keep the property.

**Comment by blairconrad** [comment]
If people want to use Invokes to record sequence numbers, they can make up their own sequence numbers!

**Comment by adamralph** [comment]
Hmmm.. true.

**Comment by blairconrad** [comment]
I'd rather do something really helpful to support better ordering assertion (i.e. implement better ordering assertions) or say "this is what we have" than say "This is what we have. Plus this other thing."

Gimme a few minutes.

**Comment by blairconrad** [comment]
Unsurprisingly, @thomaslevesque is right. It seems tough to get rid of. The old "make it a class trick" would be applicable, but I don't want to go to that well too often.

It could be pushed down to `ICompletedFakeObjectCall` and `IInterceptedFakeObjectCall`, but I'm not sure there's much benefit.

**Comment by thomaslevesque** [comment]
Actually, there might be a way to do it. Rather than having `SequenceNumber` exposed on `IFakeObjectCall`, we could maintain the sequence numbers in an internal class, using a [`ConditionalWeakTable<TKey, TValue>`](https://msdn.microsoft.com/en-us/library/dd287757%28v=vs.110%29.aspx).

**Comment by thomaslevesque** [comment]
I just realized that `ConditionalWeakTable<TKey, TValue>` isn't available in .NET 3.5... we would need an alternative to store the value (otherwise we would leak instances of `IFakeObjectCall`)

**Comment by blairconrad** [comment]
@thomaslevesque, https://github.com/FakeItEasy/FakeItEasy/blob/492fab97d84d243415d6ab6f9daad7a7896fc267/src/FakeItEasy.Net35/Compatibility/ConditionalWeakTable.cs

**Comment by thomaslevesque** [comment]
> @thomaslevesque, https://github.com/FakeItEasy/FakeItEasy/blob/492fab97d84d243415d6ab6f9daad7a7896fc267/src/FakeItEasy.Net35/Compatibility/ConditionalWeakTable.cs

Oh, that's nice :)
I'll have to look into it to see how it works; I thought it relied on a CLR feature introduced in .NET 4.

**Comment by thomaslevesque** [comment]
We could probably use it, but I think it needs to be improved. For instance, its performance is probably not great: a key lookup is `O(n)`.

**Comment by thomaslevesque** [comment]
> I'll have to look into it to see how it works; I thought it relied on a CLR feature introduced in .NET 4.

[Here it is](https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/runtime/compilerservices/ConditionalWeakTable.cs#L29-L30):

>     **    Prior to ConditionalWeakTable, the CLR did not expose
>     **    the functionality needed to implement this guarantee.

**Comment by thomaslevesque** [comment]
Also:

>     **    ConditionalWeakTable is fully thread-safe and requires no
>     **    additional locking to be done by callers.

This is not true of the .NET 3.5 compatibility shim

**Comment by adamralph** [comment]
Gentle reminder that .NET 3.5 has been obsolete for 4 years and we have talked about [dropping support for it](https://github.com/FakeItEasy/FakeItEasy/issues/217) before.

However, I'm not sure we've reached a convincing argument yet here for going ahead with that.

**Comment by thomaslevesque** [comment]
> Gentle reminder that .NET 3.5 has been obsolete for 4 years and we have talked about dropping support for it before.

True. Personally, I wouldn't mind dropping support for 3.5, but even in my company, where we try to stay up to date with new tech, some projects where still targeting .NET 3.5 not so long ago... So I think dropping support could affect a lot of people (it would be interesting to have usage stats about this).

> However, I'm not sure we've reached a convincing argument yet here for going ahead with that.

I'm not sure either. In itself, exposing something that most users won't need isn't a very big issue. What bothers me is that we're exposing an implementation detail. If we want to change the implementation, it will cause a breaking change (or not; we could always keep the `SequenceNumber` even if we don't use it internally)

**Comment by adamralph** [comment]
If https://github.com/FakeItEasy/FakeItEasy/pull/657 gets merged then this becomes

> Consider removing SequenceNumber from *ICompletedFakeObjectCall*

Still a valid consideration, but perhaps a *slightly* less important one.

I'm still not sure where in the public API (to a test author) we expose `ICompletedFakeObjectCall`.

**Comment by blairconrad** [comment]
> I'm still not sure where in the public API (to a test author) we expose `ICompletedFakeObjectCall`

https://github.com/FakeItEasy/FakeItEasy/blob/master/src/FakeItEasy/Fake.of.T.cs#L50

For starters.

**Comment by blairconrad** [comment]
* Also `Matching`.
* Self-initialized fake recorders.

Just make it `internal` and build. Scads of places.

**Comment by thomaslevesque** [comment]
Here as well: https://github.com/FakeItEasy/FakeItEasy/blob/master/src/FakeItEasy/Core/IInterceptedFakeObjectCall.cs#L30

But ideally, `AsReadOnly()` shouldn't be in the public API either

**Comment by blairconrad** [comment]
Hear hear!

**Comment by adamralph** [comment]
What are these `Fake<T>`, `Matching` and "Self-initialized fake recorders" of which you speak? :stuck_out_tongue_closed_eyes: 

Joking aside, many of these "advanced" features are quite a mystery to me...

**Comment by blairconrad** [comment]
Agreed, @adamralph. FakeItEasy is more powerful than we know. And probably than it needs to be.
I've used `Matching`, I think.

**Comment by thomaslevesque** [comment]
> Agreed, @adamralph. FakeItEasy is more powerful than we know. And probably than it needs to be.

Reminds me of an [article](http://www.dylanbeattie.net/2016/04/exuperianism-improving-things-by.html) I read yesterday.
Version 10 will be perfect, because there won't be anything left to take away :wink:

**Comment by thomaslevesque** [comment]
The PR is merged, and it doesn't look like we're going to remove `SequenceNumber` completely. Shall we close this issue?

**Comment by adamralph** [comment]
Are we sure we've exhausted the possibilities? It's true that

> AsReadOnly() shouldn't be in the public API either

but it would be nice to not add new things that don't belong...

**Comment by adamralph** [comment]
@thomaslevesque nice article. I must admit, a PR with more red than green always warms my heart...

**Comment by blairconrad** [comment]
I'd take a crack a peek again, if you don't mind waiting for me.

**Comment by adamralph** [comment]
Sure, there's no rush...

**Comment by adamralph** [comment]
@blairconrad any eureka moments yet? I'm happy to leave this open, but I think #175 should take precedence and I'm not sure we should delay the 2.0.0 release for it. We always have the option to `[Obsolete]` the property during 2.x and schedule it for removal in 3.0.0.

**Comment by blairconrad** [comment]
@adamralph, #175 has been taking precedence. I've taken no time on this issue, and I'm not going to have any before my vacation. Obsoleting and scheduling for later removal is fine by me.

**Comment by thomaslevesque** [comment]
> Actually, there might be a way to do it. Rather than having `SequenceNumber` exposed on `IFakeObjectCall`, we could maintain the sequence numbers in an internal class, using a `ConditionalWeakTable<TKey, TValue>`.

The `ConditionalWeakTable<TKey, TValue>` shim for .NET 3.5 wasn't good enough IMO, but now that we dropped .NET 3.5, this approach becomes viable again. What do you think? I'd like to give it a try.

**Comment by thomaslevesque** [comment]
OK, just finished implementing it, it works just fine.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.0.0).
