### ISSUE TITLE
codify how we're handling the analyzer package

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#666]
All of a sudden, thanks to @thomaslevesque, we have an analyzer package. :tada: 

It's built alongside the main package, and currently takes the same version number as the main package.

How are we going to release this?

1. It'll need its own NuGet package.
2. How shall we maintain its release notes? Separately, or will there be one set of notes for both packages?
3. Ditto the documentation.
4. What do we do when we want to 
    1. release a package that has FakeItEasy changes but no Analyzer changes? 
    2. release a package that has Analyzer changes but no FakeItEasy changes? 

I'm sure there are other questions that I just haven't thought of right now.

**Comment by thomaslevesque** [comment]
> How shall we maintain its release notes? Separately, or will there be one set of notes for both packages?

I'd say one set of release notes for both packages. The analyzer is probably not going to change very often anyway.

> Ditto the documentation.

Does it need documentation? I don't think there's much to say about it, besides how to install it. It can probably be included in the main FakeItEasy documentation.

> What do we do when we want to
> 
>     i. release a package that has FakeItEasy changes but no Analyzer changes?
>     ii. release a package that has Analyzer changes but no FakeItEasy changes?

Increment the version for both. This way, you don't have to think about which analyzer version you need for which FakeItEasy version: just pick the same version of both.
Having different version numbers would be a maintenance nightmare IMO, unless we move the analyzer to its own repo.

**Comment by blairconrad** [comment]
> I'd say one set of release notes for both packages

So the analyzer NuGet package will have all kinds of release notes that talk about how we added a 
new property setting syntax or whatever, even though the analyzer doesn't change at all?
Sounds a little confusing.

> Increment the version for both

Works for me, if nobody minds having FakeItEasy bump up its release number with no change in functionality.

> unless we move the analyzer to its own repo.

That's an interesting question. Is there a reason for it to be in the same repo?
We've wondered whether samples and docs should be tied to the same repo. Of any of these, the analyzer seems like the the one the least tied to the FakeItEasy source repo. Not that I want to move it out.

**Comment by thomaslevesque** [comment]
> That's an interesting question. Is there a reason for it to be in the same repo?

Not really. The analyzer tests (not the analyzer itself) references FakeItEasy, but it can do so via NuGet. The only issue is that if we add a new diagnostic for a new FakeItEasy feature, we might need to reference the latest version of FakeItEasy before its released. It could probably be handled by including FakeItEasy as a submodule.

**Comment by blairconrad** [comment]
Ah. I missed the reference. For this:

```private static readonly MetadataReference FakeItEasyReference = MetadataReference.CreateFromFile(typeof(Fake).Assembly.Location);```

An alternative to including a submodule would be to pick up a pre-release FakeItEasy (not from MyGet) and test, no?

Regardless, I'm not trying to push the analyzer out. Just to understand. I do prefer having the analzyer in the same package.
I just wanted to make sure we had a plan for some of the questions that will arise.

**Comment by blairconrad** [comment]
I do think that separate release notes make more sense. Whether that means we edit a common set and they're post-processed to split into notes for the main DLL or the analyzer, or if it's two separate sources, I'm not fussy.

**Comment by thomaslevesque** [comment]
> An alternative to including a submodule would be to pick up a pre-release FakeItEasy (not from MyGet) and test, no?

Sure, we could just embed an appropriate version of the FakeItEasy assembly in the analyzer repo.

> I do prefer having the analzyer in the same package.

I assume you mean the same repository?

**Comment by thomaslevesque** [comment]
> I do think that separate release notes make more sense. Whether that means we edit a common set and they're post-processed to split into notes for the main DLL or the analyzer, or if it's two separate sources, I'm not fussy.

I think it makes sense to have separate release notes for the NuGet packages, but not for the GitHub release; the analyzer isn't really a separate product.

Anyway, I don't think people really go to NuGet to read release notes; they're much easier to read on GitHub. The NuGet packages could just include a link to the GitHub release.

**Comment by blairconrad** [comment]
That all makes sense to me.

**Comment by adamralph** [comment]
The release notes concerns [could vanish](https://github.com/FakeItEasy/FakeItEasy/issues/665#issuecomment-210287341), as long as it's clear which notes apply to FIE and which to the analyzer.

The idea of releasing one of the packages without any changes, just because there are changes to the other, bothers me a little. But then, for a given release, e.g. 2.1, if that only contains FIE changes and not analyzer changes, I guess we don't *have* to release analyzer 2.1? We could just hold back that package until it actually has some changes. Yes, there would be gaps in the version history for that package, but perhaps that would be better than having people update for no reason?

**Comment by thomaslevesque** [comment]
> The idea of releasing one of the packages without any changes, just because there are changes to the other, bothers me a little. But then, for a given release, e.g. 2.1, if that only contains FIE changes and not analyzer changes, I guess we don't have to release analyzer 2.1? We could just hold back that package until it actually has some changes. Yes, there would be gaps in the version history for that package, but perhaps that would be better than having people update for no reason?

That would work.

Another option is to include the analyzer in the same package as the main assembly. It would make sense because the analyzer is useless unless you have FakeItEasy as well. And for people who don't want the analyzer, we could have another package with only FakeItEasy.

**Comment by adamralph** [comment]
> Another option is to include the analyzer in the same package as the main assembly.

This did cross my mind. What is the usual practice? Or what are the guidelines?

The only thing that puts me off slightly is the PowerShell cruft that the analyzer package currently needs. Feels neater to have that tucked away in a package for people that don't mind it. Also, if people are using R# annotations or other such things would the analyzer get in the way? Sure, we can have another "FakeItEasy only" package but I'd rather not if we can avoid it.

**Comment by thomaslevesque** [comment]
> This did cross my mind. What is the usual practice? Or what are the guidelines?

I'm not sure... Analyzers are new enough that there isn't really a "usual practice", and I haven't found clear guidelines either.

**Comment by blairconrad** [comment]
> Another option is to include the analyzer in the same package as the main assembly.

except for the powershell issue that @adamralph notes, I love this.

**Comment by adamralph** [comment]
Are there any precedents for analyzers bundled in with libraries?

**Comment by thomaslevesque** [comment]
> Are there any precedents for analyzers bundled in with libraries?

I suspect there are, but I don't know of any specific example.

**Comment by adamralph** [comment]
It think it may be worth trying to find some, to see if any obvious pros/cons present themselves.

**Comment by adamralph** [comment]
Removed from the 2.0.0 milestone, as per https://github.com/FakeItEasy/FakeItEasy/issues/490#issuecomment-213720229

**Comment by adamralph** [comment]
Once we resolve this, we can put #490 onto the next milestone, be it 2.0.0 or otherwise.

**Comment by adamralph** [comment]
Started a poll https://twitter.com/adamralph/status/726465900384272385

**Comment by thomaslevesque** [comment]
> Started a poll https://twitter.com/adamralph/status/726465900384272385

You might want to add a third option: one package with just the library, one for just the analyzer, and one for both (it will be empty and only have dependencies on the other two)

**Comment by thomaslevesque** [comment]
So we would have 3 packages:

- FakeItEasy.Analyzer
- FakeItEasy.LibraryOnly
- FakeItEasy
    dependent on FakeItEasy.Analyzer and FakeItEasy.LibraryOnly

(I think it's better to include the analyzer in the "normal" package, for better discoverability)

**Comment by adamralph** [comment]
The 3-package solution could work, but I wonder if it would make the landscape confusing with respect to packages which depend on FakeItEasy...

**Comment by thomaslevesque** [comment]
> The 3-package solution could work, but I wonder if it would make the landscape confusing with respect to packages which depend on FakeItEasy...

Good point. Libraries that use FakeItEasy internally should probably depend on the library-only package (they shouldn't force the analyzer upon their users, who might not even use FakeItEasy directly)

**Comment by adamralph** [comment]
Right now, FakeItEasy and FakeItEasy.Analyzer seems the lowest risk...

**Comment by thomaslevesque** [comment]
> Right now, FakeItEasy and FakeItEasy.Analyzer seems the lowest risk...

True, but users will have to know about the analyzer to install it...

**Comment by adamralph** [comment]
Yep, that's the downside. We could consider a readme in the nupkg, although I'm not sure if they are annoying or not.

**Comment by thomaslevesque** [comment]
On the other hand, people who search for FakeItEasy will probably see FakeItEasy.Analyzer in the search results.
Readme files in NuGet packages are not very annoying, but I doubt anyone reads them...

**Comment by adamralph** [comment]
Good point about the search results.

Are the readme files still opened in VS when installing packages?

**Comment by thomaslevesque** [comment]
> Are the readme files still opened in VS when installing packages?

I'm not sure. I think you have to open them explicitly in the install.ps1

**Comment by adamralph** [comment]
I'm thinking that the search results are enough. Also, in the package manager console, they will see it in Intellisense.

**Comment by thomaslevesque** [comment]
The poll looks pretty clear cut in favor of separate packages. Shall we go ahead with it? Or do you want to wait for the end of the poll?

**Comment by adamralph** [comment]
I guess we can wait until tomorrow. I'll RT again in the morning.

**Comment by adamralph** [comment]
@SimonCropp makes an [interesting point](https://twitter.com/SimonCropp/status/726550379857498117):

> also it is possible for a single roslyn extension to target multiple majors of a single lib. Since thereis no runtime dependency

This made me realise that our current analyzer would have worked for 1.x before we refactored it to use attributes. This demonstrates a significant downside of that approach. I.e. you have to release the main package in order to build new diagnostics in the analyzer, since the main package has to participate in that exercise via the decoration of members with attributes.

What this also highlights is that there is no correlation between the version numbers of the main package and that of the analyzer, since there is no dependency, other than the artificial one that we have introduced by the necessity to decorate the main package with attributes. This means that it would be way more logical to call the analyzer 1.0.0 now. And in fact, depending on what the analyzer exposes, I'm not sure there would ever be a reason to bump the major version to 2, since I can't envisage what a breaking change would be. Moreover, if it is indeed logical to disconnect the version numbers then that also implies it would be better to have the analyzer in its own repo. Otherwise, we'd have to have a separate naming convention for the git tags and GitHub releases for each product.

**Comment by thomaslevesque** [comment]
> This made me realise that our current analyzer would have worked for 1.x before we refactored it to use attributes. This demonstrates a significant downside of that approach.

True, but 1.x will soon be legacy, so I don't worry too much about it. And if we really want to, we *could* release a 1.25.4 with the attributes.



> What this also highlights is that there is no correlation between the version numbers of the main package and that of the analyzer, since there is no dependency, other than the artificial one that we have introduced by the necessity to decorate the main package with attributes. This means that it would be way more logical to call the analyzer 1.0.0 now. And in fact, depending on what the analyzer exposes, I'm not sure there would ever be a reason to bump the major version to 2, since I can't envisage what a breaking change would be. Moreover, if it is indeed logical to disconnect the version numbers then that also implies it would be better to have the analyzer in its own repo. Otherwise, we'd have to have a separate naming convention for the git tags and GitHub releases for each product.

Yes, we discussed the versioning issues earlier, and I don't think we came to a clear decision. I agree that it would make sense for the analyzer to have its own version. As for having it in its own repo, I guess it makes sense, but it will need a separate CI job.

**Comment by adamralph** [comment]
Even leaving 1.x aside, the attribute based approach also has the problem that we need to release the main package in order to release new diagnostics, or to extend the coverage of a given diagnostic. I'm beginning to think we should refactor and keep the information about which diagnostic applies to which method completely self contained in the analyzer. Now  that the code there is nicely factored, I guess it wouldn't be too difficult to introduce a map of full member names to diagnostics, which essentially all that the attributes are achieving anyway.

**Comment by blairconrad** [comment]
Noted shortcomings of tying analyzer  to main package are good points, but
I don't mind using the analyzer as a carrot to entice people to upgrade to
newer FIE. But if y'all think separate is better, I'm okay with that. But
then I think separate repos are a good idea.
Also, @adamralph's map to diagnostic sounds just like R#'s external
annotations...

**Comment by thomaslevesque** [comment]
> Now that the code there is nicely factored, I guess it wouldn't be too difficult to introduce a map of full member names to diagnostics, which is essentially all that the attributes are achieving anyway.

Indeed, it should be pretty easy.

> But then I think separate repos are a good idea. Also, @adamralph's map to diagnostic sounds just like R#'s external annotations...

True, but at least it's in a format we choose, rather than the ugly XML of R#'s annotations.

**Comment by adamralph** [comment]
I'm thinking just a static dictionary in the code...

**Comment by thomaslevesque** [comment]
> I'm thinking just a static dictionary in the code...

Yes, me too. Instead of a "diagnostic name to diagnostic descriptor" dictionary, we'll have a "member name to diagnostic descriptor" dictionary.

**Comment by thomaslevesque** [comment]
I created a new repo [FakeItEasy.Analyzer](https://github.com/FakeItEasy/FakeItEasy.Analyzer), copied it the analyzer source files to it, and made just a few changes so that it compiles:

- include all attributes in AssemblyInfo.cs (some of them were in CommonAssemblyInfo.cs) and set the version to 1.0.0
- reference FakeItEasy as a NuGet package from the unit test project (it was a project reference)

Of course, at this point, the tests don't pass, because FakeItEasy 2.0.0-rc1 on NuGet doesn't have the `[MustUseReturnValue]` attributes.

TODO: 
- [ ] setup CI for the analyzer on TeamCity
- [ ] update the analyzer to use a map rather than the attributes
- [ ] Add a license and a readme
- [ ] Decide how the analyzer should be signed (currently using the same SNK as FakeItEasy itself)

**Comment by thomaslevesque** [comment]
> Of course, at this point, the tests don't pass, because FakeItEasy 2.0.0-rc1 on NuGet doesn't have the `[MustUseReturnValue]` attributes.

I'm afraid this is often going to be an issue. I created a PR (FakeItEasy/FakeItEasy.Analyzer#1) to change the analyzer behavior as discussed, but I still have broken tests because of `CallToSet`, which is not in FakeItEasy 2.0.0-rc1.

Basically, we'll never be able to write analyzer tests for new FakeItEasy features before we have a new version of FakeItEasy on NuGet. Possible solutions:
- include the FakeItEasy binary directly in the analyzer repo
- publish an always-up-to-date package, with incremental version number, via TeamCity (e.g. FakeItEasy-2.0.0-latest42, where 42 is the build number), and add the TeamCity feed as a NuGet source.

**Comment by adamralph** [comment]
> we'll never be able to write analyzer tests for new FakeItEasy features before we have a new version of FakeItEasy on NuGet.

Yep, it does make things a little awkward.

I'd rather not embed a binary in the analyzer repo and I'm not sure the TC feed is stable enough to use for this purpose. MyGet is another possibility...

I must say I'm not feeling particularly comfortable with either option right now...

**Comment by thomaslevesque** [comment]
> Yep, it does make things a little awkward.
> 
> I'd rather not embed a binary in the analyzer repo and I'm not sure the TC feed is stable enough to use for this purpose. MyGet is another possibility...
> 
> I must say I'm not feeling particularly comfortable with either option right now...

Another option is to include FakeItEasy in the analyzer repo as a submodule. My first experience with submodules has been absolutely awful, but it should be OK in this case, since we never need to modify FakeItEasy itself from the analyzer repo.

**Comment by blairconrad** [comment]
If you're still keen on separating the analyzer from the regular package, my thought is: try separate repos (because separate release schedule, mostly) and use a read only submodule. It should work okay without writes, and is probably least work. If we have problems, can revisit more sophisticated approach...

**Comment by adamralph** [comment]
@blairconrad @thomaslevesque what has your experience of submodules been like?

I haven't done much with them. My last experience was about a week ago when I couldn't, for the life of me, get the latest xunit release to build, until I found something in their repo which talked about having to update submodules. I couldn't get things ship-shape, so in the end I deleted my clone and had to re-clone with a special submodules argument at the end, which I've already forgotten. There's also something special about fetching the latest submodule when that repo is updated. Conclusion: the submodule adds considerable friction.

I do remember hearing all kinds of winging and complaints about submodules in the community a while back but not so much recently so perhaps things have been improved, but as I say, my recent experience wasn't pleasant.

**Comment by blairconrad** [comment]
@adamralph, busted. I've had no experience with git submodules. Naively assumed
 worked like subversion externals. And _sounded_ like less work to set up. Will keep big fat mouth shut.

**Comment by adamralph** [comment]
@blairconrad I'm not claiming to know much about them. Indeed, it may be possible to set them up to be less painful than what I've experienced, but right now I'm sceptical.

**Comment by thomaslevesque** [comment]
> @blairconrad @thomaslevesque what has your experience of submodules been like?

In my experience, the thing about submodules is, they're OK if you use them exactly for what they're intended for, but terrible for everything else.

As I said before, I had a really bad experience with them, but mostly because it was not the right tool to use. Basically, I have an app that's made up of many projects, some of them (12 or so) intended to be shared with other apps. The "common" projects each live in its own repo. I started using submodules, which I didn't know, to include the common projects in the app. But since the common projects were still to be implemented, each feature of the app also required changes in the submodules; and each submodule had to be branched separately, committed separately, pushed separately, and merged separately, which obviously made the workflow completely impractical. I dropped submodules in favor of subtrees, which have their own issues, but at least make the workflow more tolerable.

However, our situation is different; we're not going to make changes to FakeItEasy's code from the FakeItEasy.Analyzer repository, so a submodule is probably the best approach. There's nothing really difficult; when you clone, you can specify `--recursive` to checkout the submodules automatically; of if you have already cloned the repo, just run `git submodule update --init`. To pull the latest changes in the submodule, `cd` into the submodule and run `git pull <remote> <branch>`.

**Comment by adamralph** [comment]
@thomaslevesque thanks for the info. I'm giving it some thought...

**Comment by blairconrad** [comment]
I'm going to try a different tack

> Basically, we'll never be able to write analyzer tests for new FakeItEasy features before we have a new version of FakeItEasy on NuGet.

Does this matter that much? If the Analyzer is a separate package, with its own release schedule, is there a big problem with waiting until we have a new version of FakeItEasy before augmenting the Analyzer tests?

I'm inclined to suggest living with the short delay between FakeItEasy feature and Analyzer support.

The enterprising person who's working on a new FakeItEasy feature and Analzyer support for the same who's hobbled by the lack of published FakeItEasy package with the new feature can always temporarily use a local NuGet feed pointing at their own FakeItEasy package. It's a _little_ more work in that case, but not much, and I'm not sure it's going to come up often.

**Comment by thomaslevesque** [comment]
> Does this matter that much? If the Analyzer is a separate package, with its own release schedule, is there a big problem with waiting until we have a new version of FakeItEasy before augmenting the Analyzer tests?

No, it doesn't matter that much. But ideally it would be nice to release an up-to-date analyzer when we release a new FIE feature. It can still be achieved with a submodule, as mentioned above.

**Comment by blairconrad** [comment]
As @thomaslevesque and I were discussing earlier, whatever method we choose for sucking FakeItEasy builds into the Analyzer package is an internal detail and can be changed later if need be, so without a clear winner, perhaps we should just try one.

The GitHub submodule sounds like it will work, but is a little esoteric (I think), and will require us to rebuild FakeItEasy in order to build the Analyzer. And we'd either have to rely on FIE changes being merged to master or temporarily point at a branch in the FakeItEasy org's repo in order to work on an Analyzer test that depends on non-merged FIE commits.

An alternative would be to depend on NuGet packages. @thomaslevesque points out that If we rely on the official feed, then we'd by necessity introduce a delay before it's possible to work on Analyzer features (or the tests for same) for new FIE methods - we'd have to wait for an official release, and it then becomes hard to release the new FIE and new Analyzer in close proximity.

As noted, the CodeBetter TeamCity does publish a NuGet feed, which we could try to use instead. That too would require FIE changes to be merged to master before they become available, but it's no worse than the submodule, and if we wanted to work against unmerged changes, the feed could always be temporarily changed to point to a local NuGet repo (that is, a directory where we've built FIE and put the outputs (although this tactic might mitigate the problems that arise from using the official feed as well)).

I'm up for either approach (or would love to hear an alternative) but think pointing at a NuGet feed (the CodeBetter one?) will introduce less friction, so maybe we could try that?
If the feed proves to be too unstable, we can always revisit.

**Comment by thomaslevesque** [comment]
:+1: to what @blairconrad just said

**Comment by adamralph** [comment]
I chatted with the [Nancy guys](https://nancyfx.slack.com/archives/general/p1463655591006735) about this. They have a much bigger problem. Several packages with a [rich dependency chain](https://github.com/NancyFx/Nancy/tree/master/src).

The way they do it is to build them all out of the same repo with a shared version number.

Sometimes, they patch one package, and only release that one, but of course that bumps the patch version for *all* packages. So, if package X and Y are at 2.0.0, X may be patched and released as 2.0.1, and then Y may be patched and released as 2.0.0. This mean Y has jumped from 2.0.0 straight to 2.0.1.

However, for minor releases, they always release in lockstep, i.e. a 2.1.0 version of all packages will be released all at once, even if only package actually has a new feature.

This is a *much* easier method to manage the source and build than any other method we've talked about so far (although we did talk about this very method before). I'm wondering if the downside of releasing redundant packages, or even allowing ourselves to skip minor version in either package, is worth the hassle of trying to do something more elaborate.

**Comment by blairconrad** [comment]
I don't mind all the source living in one repo, using a common version number.
I'd also be happy to skipping version numbers (even minor ones (even major ones!)) if we don't need to release one of the packages.

If everyone else likes that approach, then we'd just have to decide how to manage the release notes. I think the latest suggestion was to put all the release notes (for both packages) in the GitHub release notes, having the NuGet packages just include links to those. I'm happy to give that a try.

**Comment by adamralph** [comment]
I'm happy with that. I'd even be happy with the packages just having a fixed link to https://github.com/FakeItEasy/FakeItEasy/releases - anyone who is curious enough to view the release notes can find the specific version they're interested in, and it's usually going to be the latest (top) version.

@thomaslevesque ?

**Comment by thomaslevesque** [comment]
Fine by me.

> I think the latest suggestion was to put all the release notes (for both packages) in the GitHub release notes, having the NuGet packages just include links to those

I tried that recently for [a project of mine](https://www.nuget.org/packages/XamlAnimatedGif/). The only issue is that the NuGet website doesn't linkify URLs in the release notes.

> I'd even be happy with the packages just having a fixed link to https://github.com/FakeItEasy/FakeItEasy/releases - anyone who is curious enough to view the release notes can find the specific version they're interested in, and it's usually going to be the latest (top) version.

Agreed, this way we don't even need to update the link in the nuspec for every release ;)

**Comment by blairconrad** [comment]
> the NuGet website doesn't linkify URLs in the release notes.

True, and sad. But FakeItEasy users are savvy enough to cut the URL and paste into a browser. It's actually easy enough that even I can do it!

> this way we don't even need to update the link in the nuspec for every release ;)

Sure, but I'd use build magic to make sure that was automatic for us anyhow, if we wanted version-specific links. I'm not worried either way.

**Comment by thomaslevesque** [comment]
> But FakeItEasy users are savvy enough to cut the URL and paste into a browser.

Sure, it's not a major issue... just a minor annoyance

**Comment by blairconrad** [comment]
Let's note up what we talked about in https://github.com/FakeItEasy/FakeItEasy/wiki/Managing-releases or thereabouts and then this can be closed.

**Comment by blairconrad** [comment]
I've updated https://github.com/FakeItEasy/FakeItEasy/wiki/Managing-releases. If one of you guys wants to take a gander and, if satisfied, close this issue, I'd be obliged.
Once that article is stable, I can submit a PR for #665.

**Comment by thomaslevesque** [comment]
> copy release notes from GitHub release to the release notes for the NuGet package(s) (since we don't create a GitHub release for each pre-production build, the GitHub release notes won't be available to the public)

Didn't we say we would just include a link?

**Comment by adamralph** [comment]
Didn't we say we would just include a link?

That doesn't work for non-RTM releases because the release itself is just a draft and not publicly visible. On the other hand, we could create a full GitHub release for non-RTM releases and then use the same mechanism as an RTM release. (This would involve duplication between the GitHub release notes for a non-RTM and the final RTM.)

**Comment by blairconrad** [comment]
> we could create a full GitHub release for non-RTM releases

Making such a proposal was going to be my next step, but I didn't want to open the door to a big discussion yet.
Toward the end of the betas, and particularly when codifying the pre-production release process for @thomaslevesque, I realized that the procedure saves us nothing, and we'd probably better off with a consistent process. Lemme spin off another issue.

**Comment by blairconrad** [comment]
Or co-opt #665?

**Comment by adamralph** [comment]
I would include it in #665.

As far as this issue is concerned. I think we are done, so I'm :+1: to close.

**Comment by blairconrad** [comment]
Will do. Thanks.
