### ISSUE TITLE
update docs links to point to readthedocs.io

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#683]
per https://blog.readthedocs.com/securing-subdomains/

**Comment by adamralph** [comment]
I got the email this morning :smile:

**Comment by blairconrad** [comment]
I was updating the [Changes in version 2.0](https://github.com/FakeItEasy/FakeItEasy/wiki/Changes-in-version-2.0), so while I was there, I fixed all the links in the wiki.
