### ISSUE TITLE
find a better way to describe a call than making an ExpressionCallMatcher

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#684]
From https://github.com/FakeItEasy/FakeItEasy/pull/673/files#r60991134

**Comment by blairconrad** [comment]
Of course, if #673 doesn't get merged, the point may be moot.

**Comment by thomaslevesque** [comment]
This change has been released as part of [FakeItEasy 4.5.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/4.5.0).
