### ISSUE TITLE
Move the analyzer to its own repository

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#696]
As discussed in https://github.com/FakeItEasy/FakeItEasy/issues/666#issuecomment-216021954

(I created the PR before the issue, oops!)

**Comment by thomaslevesque** [comment]
The new repo for the analyzer is https://github.com/FakeItEasy/FakeItEasy.Analyzer

**Comment by adamralph** [comment]
As discussed, we'll resolve the conversation at #666 first before deciding how to proceed.
