### ISSUE TITLE
Remove redundant [MustUseReturnValue] attributes

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#697]
Related to FakeItEasy/FakeItEasy.Analyzer#2

The analyzer will no longer rely on this attribute, so it becomes redundant and should be removed.

**Comment by adamralph** [comment]
As discussed, we'll resolve the conversation at #666 first before deciding how to proceed, and if we do proceed with a separate repo, this will be a sub-task of the issue in the new repo which will replace #490.
