### ISSUE TITLE
Add an API approval test

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#701]
Using https://github.com/approvals/ApprovalTests.Net and https://www.nuget.org/packages/PublicApiGenerator/

This will allow us to see the effect of any change to the public API.

Initially, at least, I don't think we should include this in the default rake tasks, since the management of this test will be a little different to usual and I think it will add unwanted friction for contributors. We can still eyeball PRs as we do know to spot breaking changes, and if unsure, we can pull the changes down locally and run the approval test (`bundle exec rake approve`). We also have the option of setting up a second build config which runs this test and make it a "not required" check in GitHub for merging a PR. I.e. if a contributor changes the public API in a non-breaking way, we can eyeball the results of the failed build and verify that, merge the PR, and take care of updating the test later.

**Comment by thomaslevesque** [comment]
Interesting, I didn't know about that tool!
