### ISSUE TITLE
Use Predicate<T> instead of Func<T, bool> where appropriate to improve readability

### ISSUE THREAD

**Issue by Mertsch** [FakeItEasy/FakeItEasy#707]
Is there any reason why
`
T Matches<T>(this IArgumentConstraintManager<T> scope, Expression<Func<T, bool>> predicate)
`
should not be
`
T Matches<T>(this IArgumentConstraintManager<T> scope, Expression<Predicate<T> predicate)
`
?
And any other place where `Func` with return `bool` is used

**Comment by adamralph** [comment]
@Mertsch thanks for raising this.

There are a couple of things to consider here.

Firstly, this would be a breaking change. E.g. if someone has declared their predicates in their tests for reuse as typed as `Func<T, bool>` then their tests will no longer compile if we change the signatures in FakeItEasy to `Predicate<T>`.

Secondly, there are various arguments for using `Func<T, bool>` over `Predicate<T>`. See [this SO answer](http://stackoverflow.com/questions/665494/why-funct-bool-instead-of-predicatet) for more on this.

Given that we imminently releasing 2.0.0 which is a major (breaking) release, we have the capacity to introduce breaking changes, so the first point is not a problem. However, the arguments for using `Func<T, bool>` over `Predicate<T>` are compelling, so I'm leaning towards not making this change.

**Comment by Mertsch** [comment]
@adamralph Thanks for looking into it. Given the argumentation I can see why to choose `Func`.

It's a bit sad though that this widely used concept in the .NET framework is basically legacy code.
