### ISSUE TITLE
Add a shorter version of A<T>.That.Matches(...)

### ISSUE THREAD

**Issue by Mertsch** [FakeItEasy/FakeItEasy#708]
`A<int>.That.Matches(i => i == 13)`
is quite long for checking against a single value.
As far as my testing has gone, I rarely test against something that is not specific, so I am suggesting to add another helper to be able to write
`A<int>.That.Is(13)`

`A<T>.That.Is<T>(T value)`

**Comment by adamralph** [comment]
@Mertsch thanks for raising this.

Right now you can write

```C#
A<int>.That.IsEqualTo(13)
```

would that suit your needs?

**Comment by Mertsch** [comment]
@adamralph Thank you for your reply. Yes that is exactly why I was looking for.
For some odd reason this method does not appear in my R# "powered" intellisense.

I will do a test without R#, if it appears, I will close and report a bug there.

![2016-05-10 21_29_45-intelli](https://cloud.githubusercontent.com/assets/9402861/15159746/73e74826-16f6-11e6-91cc-79591b224edd.png)

**Comment by blairconrad** [comment]
Or just ‛13‛.

**Comment by adamralph** [comment]
Lol - of course! :blush: 

@Mertsch you don't need to use `A<int>` at all, so instead of:

```C#
A.CallTo(() => foo.Bar(A<int>.That.IsEqualTo(13)))...
```

just write:

```C#
A.CallTo(() => foo.Bar(13))...
```

**Comment by Mertsch** [comment]
@adamralph @blairconrad Oh, thanks for the hint. It's funny how sometimes the simplest things are the last thing you guess.
Works perfectly!

**Comment by blairconrad** [comment]
@Mertsch, you can learn more about argument constraints at http://fakeiteasy.readthedocs.io/en/stable/argument-constraints/, in case there are other shortcuts you are missing.
Thanks for your interest!

**Comment by Mertsch** [comment]
@blairconrad Cool, very handy stuff. FakeItEasy just became even more awesome for me :)
