### ISSUE TITLE
Nullable Struct invoked with Struct

### ISSUE THREAD

**Issue by linvi** [FakeItEasy/FakeItEasy#718]
This question might have already been answered but I could not find any.

I have a method that I mock which takes a `long?` parameter. When I mock it and invoke it with a `long` the following exception is thrown.

> Exception thrown: 'FakeItEasy.Configuration.FakeConfigurationException' in FakeItEasy.dll

> Additional information: The faked method has the signature (System.Nullable`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]), but returns lazily was used with (System.Int64).

Surely this should be a working scenario.

Thanks for this awesome library.

**Comment by adamralph** [comment]
Hi @linvi thanks for raising this.

Can you please post a code snippet from the test which shows this behaviour?

**Comment by adamralph** [comment]
Never mind, I managed to reproduce it:

```C#
void Main()
{
    var foo = A.Fake<IFoo>();
    A.CallTo(() => foo.Bar(42)).ReturnsLazily((long x) => x);
    foo.Bar(42);
}

public interface IFoo
{
    long? Bar(long? baz);
}
```

**Comment by adamralph** [comment]
However, this works:

```C#
void Main()
{
    var foo = A.Fake<IFoo>();
    A.CallTo(() => foo.Bar(42)).ReturnsLazily((long? x) => x);
    foo.Bar(42);
}

public interface IFoo
{
    long? Bar(long? baz);
}
```

**Comment by linvi** [comment]
Will you be able to continue working with the example that you have?
I will try to change my code slightly to fix it.

**Comment by linvi** [comment]
I cannot really fix this (at least not that I can think of).
The problem is that the method is invoked with a parameter class. This class contains an `ID` which is of type `long` (and not `long?`).

Therefore I cannot set the `Fake` parameter to return lazily a `long?` (as the parameter is actually a `long`).

**Comment by adamralph** [comment]
@linvi would you be able to post an isolated code example which demonstrates the problem?

**Comment by linvi** [comment]
I will try it out but this will have to wait for tomorrow, I cannot continue working on this right now.

I will get back to you.

**Comment by thomaslevesque** [comment]
Based on @adamralph's example, the current behavior seems correct to me. However:
- it would be better (less confusing) to throw on the `ReturnsLazily` call rather than when the method is actually called, if possible
- The error message should probably say "ReturnsLazily", not "returns lazily", since it refers to the method

**Comment by thomaslevesque** [comment]
> it would be better (less confusing) to throw on the `ReturnsLazily` call rather than when the method is actually called, if possible

OK, looks like it's not possible... at this point we have no way to know which method is being configured; there might be several (e.g. `A.CallTo(fake).WithReturnType<long>()`)

**Comment by linvi** [comment]
I thought the following code would reproduce it but it does not. I will try again tomorrow.

``` c#
public interface IToFake
{
    void Test(long? value);
}

public interface IToFakeParam
{
    long Value { get; set; }
}

public class ToTestClass
{
    private readonly IToFake _fake;

    public ToTestClass(IToFake fake)
    {
        _fake = fake;
    }

    public void Test(IToFakeParam param)
    {
        _fake.Test(param.Value);
    }
}

[TestClass]
public class MyReproClass
{
    [TestMethod]
    public void MyReproTest()
    {
        // Arrange
        var fake = A.Fake<IToFake>();
        var fakeParam = A.Fake<IToFakeParam>();
        var toTest = new ToTestClass(fake);

        fakeParam.CallsTo(x => x.Value).Returns(1);

        // Act
        toTest.Test(fakeParam);

        // Assert
        // ...
    }
}
```

@thomaslevesque Quick hello from Ep..42 promo 2011 :)

**Comment by thomaslevesque** [comment]
@linvi this is not a real test, is it? The syntax doesn't look right (there's no `CallsTo` method that would apply to `fakeParam`)

> @thomaslevesque Quick hello from Ep..42 promo 2011 :)

Sorry, I don't understand what you mean... maybe you're confusing me with someone else ;)

**Comment by linvi** [comment]
> @linvi this is not a real test, is it? The syntax doesn't look right (there's no CallsTo method that would apply to fakeParam)

I am just specifying that the `Fake<IToFakeParam>` property `Value` will Return 1. What do you consider wrong about this code?

> Sorry, I don't understand what you mean... maybe you're confusing me with someone else ;)

Apparently I do :p Sorry about that.

**Comment by thomaslevesque** [comment]
> I am just specifying that the Fake<IToFakeParam> property Value will Return 1. What do you consider wrong about this code?

Well, it doesn't compile... there's no `CallsTo` method on `IToFakeParam`, and no `CallsTo` extension method.

**Comment by thomaslevesque** [comment]
> Well, it doesn't compile... there's no CallsTo method on IToFakeParam, and no CallsTo extension method.

Ah, my bad. Actually there *is* such an extension method... it's hidden in `FakeItEasy.ExtensionSyntax.Full.ObjectExtensions`. It's no longer there in 2.0, which is why I missed it...

**Comment by linvi** [comment]
So I have to admit that this was my issue. Sorry for losing your time.

Here is what I was doing in a helper class: 

``` c#
classToTest
                .CallsTo(x => x.IsUserIdValid(A<long>.Ignored))
                .ReturnsLazily((long id) =>
                {
                    return result == null && id != TweetinviSettings.DEFAULT_ID || result != null && result.Value;
                }); c#
```

`.ReturnsLazily((long id) =>` used to work but as soon as I deleted the (long) version of the `IsUserIdValid` method it stopped working.

Sorry for losing your time.

**Comment by adamralph** [comment]
@linvi no problem. We're glad you worked it out.
