### ISSUE TITLE
Rake build error when having both 14 and 15 msbuild

### ISSUE THREAD

**Issue by mvas** [FakeItEasy/FakeItEasy#719]
This is what I'm getting when running `bundle exec rake`
```
D, [2016-05-22T23:07:20.990390 #5656] DEBUG -- : Executing Exec: "F:/Projects/github/_mvas/FakeItEasy/.nuget/NuGet.exe" restore FakeItEasy.sln
MSBuild auto-detection: using msbuild version '15.0' from 'C:\Program Files (x86)\MSBuild\15.0\bin'.
Error parsing solution file at F:\Projects\github\_mvas\FakeItEasy\FakeItEasy.sln: This version of msbuild is not supported: 'Microsoft.Build, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
F, [2016-05-22T23:07:21.503093 #5656] FATAL -- : Exec Failed. See Build Log For Detail
```

I have MSBuild 15 and 14 both installed, seems like nuget should be told to use 14 strictly

**Comment by adamralph** [comment]
@mvas thanks for raising this.

> nuget should be told to use 14 strictly

Is that possible?

**Comment by mvas** [comment]
Yes, it has the option --MSBuildVersion
trying to send a pull request

**Comment by adamralph** [comment]
Thanks very much! Limiting it to MSBuild14 will be fine for now.

When MSBuild 15 (Visual Studio 15) goes RTM and we want to support it, I guess we'll need to upgrade `.nuget\Nuget.exe` to a version which *does* support it.

**Comment by mvas** [comment]
Yes, so far nuget documentation says `Supported values are 4, 12, 14`

**Comment by thomaslevesque** [comment]
Weird, I have VS 15 Preview installed, and I'm not getting this error... it correctly picks MSBuild 14 on my machine.

**Comment by mvas** [comment]
nuget chooses the highest version which it could find, I've managed to find [that issue about autodetection](https://github.com/NuGet/Home/issues/1392)

I don't have MSBuild in my PATH at all, so nuget seems to be looking around in Program Files

could you please check if you have MSBuild14 in PATH ?

**Comment by thomaslevesque** [comment]
> @thomaslevesque, could you please check if you have MSBuild14 in PATH ?

I do. That must be the reason. If I remove it, I get the same error.

**Comment by mvas** [comment]
checked nuget sources, that's exactly how it works
[see nuget guts](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs#L317)

**Comment by adamralph** [comment]
Seems rather dumb. Rather than continue searching for one that it *does* support, it just tries the highest one and explodes.

**Comment by adamralph** [comment]
I think we just need to update NuGet.exe https://github.com/NuGet/NuGet.Client/commit/12c6114edab1209e94b4007094c18b631ff4c850

3.4.3.855 has been released - https://github.com/NuGet/NuGet.Client/releases/tag/v3.4.3.855-VSIX-Dev14

**Comment by adamralph** [comment]
@mvas @thomaslevesque I've raised https://github.com/FakeItEasy/FakeItEasy/pull/721 which updates nuget.exe. Can you please try and build on your machines using that branch?

**Comment by mvas** [comment]
Update should work as well, here is the change which should support msbuild15 
https://github.com/NuGet/NuGet.Client/commit/12c6114edab1209e94b4007094c18b631ff4c850#comments

I'll try

**Comment by thomaslevesque** [comment]
Works for me :+1:

**Comment by mvas** [comment]
Works for me as well!

**Comment by adamralph** [comment]
Awesome, so I guess we can merge #712...

**Comment by thomaslevesque** [comment]
> Awesome, so I guess we can merge #721...

Done
