### ISSUE TITLE
A.CallTo expected parameters not set correctly

### ISSUE THREAD

**Issue by tpluscode** [FakeItEasy/FakeItEasy#730]
Hi. I'm having this very strange issue with faked call in my test. It only happens when I run the whole suite (xUnit). I'm guessing something with parallel execution?

[I simply set up a method call with ignored parameters](https://github.com/wikibus/Argolis/blob/a91ee5cd593cc08073ddb6b6ea69a7e80036566b/src/Lernaean.Hydra.Tests/ApiDocumentation/DefaultPropertyRangeRetrievalPolicyTests.cs#L40):

```
A.CallTo(() => _propertyType.MapType(A<PropertyInfo>._, A<IReadOnlyDictionary<Type, Uri>>._))
    .Returns(mappedPredicate);
```

Sometimes (roughly 30% of runs) the call doesn't return the expected value. I've determined that it's because instead of `<ignored>, <ignored>`, the interceptor rule is set to expect `<NULL>, <ignored>` for parameters. I've simply replaced the call setup with concrete values, which fixes this for now. However, I'm baffled.

I'm not sure I can reproduce this, but you can see for yourself by checking out [this revision](https://github.com/wikibus/Argolis/tree/a91ee5cd593cc08073ddb6b6ea69a7e80036566b).

Any ideas?

**Comment by blairconrad** [comment]
@tpluscode, thanks for raising this. I'm getting your code right now, but I have to ask. What version of FakeItEasy are you currently running against?

**Comment by blairconrad** [comment]
@tpluscode, I did just check out your code and run paket, and it installed FakeItEasy 1.25.3, which is out of date, and known to have bugs when `A<>._` is used in a multithreaded environment.
( #476 was fixed in yesterday's 2.0.0 release)

I have a strong feeling/hope that this is your problem. I continue to investigate. But do you (or anyone listening) know why paket would download 1.25.3 instead of 2.0.0?

**Comment by blairconrad** [comment]
Okay. I ran all the tests and got fairly consistent failure for `Should_map_property_range_to_RDF_type`. Then I updated to FakeItEasy 2.0.0, and can no longer reproduce. I think that's it.

**Comment by tpluscode** [comment]
Yesterday's release! I guess I asked this just about time. Thanks for a quick reply.

As for Paket, it keeps resolutions fixed until they are updated manually. I installed 1.25.3 previously and  it simply stayed that way

**Comment by blairconrad** [comment]
Ah. Thanks for the info, @tpluscode. I didn't realize that paket stored its "installed version numbers"... somewhere else. The .csprojs?

OH! `paket.lock`. I see it now. :blush:

Anyhow, I'm glad things worked out for you.

**Comment by adamralph** [comment]
:tada: great to see 2.0.0 solving problems in the wild!
