### ISSUE TITLE
Source stepping via GitLink

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#735]
*from https://github.com/FakeItEasy/FakeItEasy/issues/362#issuecomment-207228506*

Replaces #362.

**Comment by adamralph** [comment]
When this is released we should add ourselves to https://github.com/GitTools/GitLink#projects-using-gitlink

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.1.0).
