### ISSUE TITLE
Load extension points from assemblies loaded later

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#744]
I just hit a hard-to-debug issue, related to how we load extension points, and I thought we might be able to improve things a little.

I have a test assembly "MyTests", which references a common "TestUtilities" assembly. TestUtilities defines a few fake option builders. Depending on which tests run first, other tests that rely on these fake option builders will pass, or fail. To be exact, if the first fake is created *before* the first usage of TestUtilities, then TestUtilities is not yet loaded when we start scanning for extension points.

I think it might be possible to scan assemblies that are loaded after the initial scan (using the `AppDomain.AssemblyLoad` event). This way, the load order won't matter as much.

(in the meantime, I added a bootstrapper to solve the issue)

**Comment by adamralph** [comment]
It feels like an edge case, and I wonder if adding a bootstrapper isn't in fact the best solution. Otherwise, we'd have to eagerly load all assemblies present on disk which could be quite a performance hit. (I actually thought that's what we are already doing but I guess not.)

**Comment by thomaslevesque** [comment]
> It feels like an edge case

Really? It seems to me that having common fake option builders/dummy factories/value formatters in a separate assembly isn't very unusual. True, a bootstrapper can solve the issue, but it's not very convenient.

> Otherwise, we'd have to eagerly load all assemblies present on disk

Why would we do that? It's not what I'm suggesting. My idea was to do an initial scan for extension points in loaded assemblies (exactly what we're currently doing), and detect subsequent assembly loads to scan them as well.

**Comment by adamralph** [comment]
Ah, OK, sorry I should read more carefully.

To compensate for my sieve-like brain I had to look up the history, and it looks like we changed the behaviour in [1.19](https://github.com/FakeItEasy/FakeItEasy/issues/268). Previously we did indeed scan the disk.

And now, as I'm typing this, an intense case of déjà vu is overwhelming me. I'm sure the idea of listening for the loading of new assemblies was raise once before...

**Comment by blairconrad** [comment]
If it's at all reassuring, no issues but this one contain the string "AssemblyLoad", @adamralph.

In general, I like the idea, but there will probably be quite a lot of rework. Currently we bring load all the assemblies that we're going to, find the types that act as extension points, and put them in catalogues. Then as we need Options Builders, Dummy Factories, or Argument Formatters, we look in the catalogue for a suitable type, cache it, and then use it. We'd certainly have to rework that, adding more types to the catalogues as we find them.

Which brings up a point. What if we find a Dummy Factory (for sake of argument) and then later an assembly is loaded that contains a better-matching Dummy Factory? We'll be using different Dummy Factories for our Dummies.

**Comment by thomaslevesque** [comment]
> Which brings up a point. What if we find a Dummy Factory (for sake of argument) and then later an assembly is loaded that contains a better-matching Dummy Factory? We'll be using different Dummy Factories for our Dummies.

Good point... this would make the behavior seem inconsistent. Now I'm no longer sure it's a good idea.

**Comment by adamralph** [comment]
Dialled back to a discussion because we're now not sure if this is a feature or an anti-feature :wink:

**Comment by thomaslevesque** [comment]
> we're now not sure if this is a feature or an anti-feature

Indeed. The inconsistent behavior it introduces is probably a show-stopper, so unless you object, I'll close the issue.

**Comment by adamralph** [comment]
:+1: to closing. I think the current behaviour is the only reasonable behaviour, with a bootstrapper being the escape hatch for more intricate scenarios.

**Comment by thomaslevesque** [comment]
> with a bootstrapper being the escape hatch for more intricate scenarios.

Actually, I found a more convenient approach (applicable in my case, probably not in general):
- the assembly that contains the extension points declares a `PreLoadAssemblyAttribute`
- I apply this attribute to the test assembly that needs the extension points: `[assembly: TestUtilities.PreLoadAssembly]`
- this causes the assembly to be loaded eagerly

**Comment by adamralph** [comment]
Not a bad idea!

**Comment by thomaslevesque** [comment]
> Not a bad idea!

Except that I just realized that it doesn't actually work... not sure what made me think it did. The attribute is just metadata, and no instance of the attribute class is actually created when the assembly is loaded, so it doesn't cause the assembly that defines the attribute to be loaded.

I just hit a variation of the same issue again, and I'm back to square one... I guess I'll just add a bootstrapper, but it's annoying.

**Comment by blairconrad** [comment]
Would you feel better knowing that I think the problem may go away in .NET Standard, because of the way we chase dependencies to find our extension points?
It's something that I've been pondering with our last 2 or so failing integration tests that we have, blocking me trying to add netstd integration tests…

**Comment by thomaslevesque** [comment]
> Would you feel better knowing that I think the problem may go away in .NET Standard

Not really, since my app targets .NET 4.5... :wink:
