### ISSUE TITLE
support usage of IEquatable<T> as argument matchers

### ISSUE THREAD

**Issue by philippdolder** [FakeItEasy/FakeItEasy#750]
Would be helpful to have `IEquatable<T>` supported out of the box for argument matching.

Instead of 
```c#
A.CallTo(() => this.pickupNotifier.Notify(A<ParcelReadyForPickup>.That.Matches(_ => _.Equals(new ParcelReadyForPickup("Recipient", "Description"))))).MustHaveHappened();
``` 

one could simply write 
```c#
A.CallTo(() => this.pickupNotifier.Notify(new ParcelReadyForPickup("Recipient", "Description"))).MustHaveHappened();
```

where `ParcelReadyForPickup : IEquatable<ParcelReadyForPickup>`

**Comment by thomaslevesque** [comment]
Hi @philippdolder,

Thanks for the suggestion.

It works as expected if you override `Object.Equals(Object)`, which you should always do when you implement `IEquatable<T>`; this is mentioned [in the documentation](https://msdn.microsoft.com/en-us/library/ms131187.aspx):

> If you implement `IEquatable<T>`, you should also override the base class implementations of `Object.Equals(Object)` and `GetHashCode` so that their behavior is consistent with that of the `IEquatable<T>.Equals` method.

So, I guess we *could* support the use of `IEquatable<T>` without the corresponding `Object.Equals(Object)` override, but I'm not convinced we should...

**Comment by blairconrad** [comment]
Hi, @philippdolder! Nice to see you again. Thanks for the idea.
I'm with @thomaslevesque, though; a well-class that properly implements `IEquatable<T>` should already work.

**Comment by philippdolder** [comment]
@thomaslevesque @blairconrad to be honest, I tried this just for a demo sample, so I didn't take care of properly implementing the equals pattern.

So, I'll just close the issue. Thanks for the fast reply

**Comment by blairconrad** [comment]
Thanks for getting back to us. Of course, if you discover some gap, we'd be keen to hear about it.
