### ISSUE TITLE
Add overload with optionsBuilder parameter for CollectionOfFake

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#755]
Unlike `A.Fake`, `A.CollectionOfFake` doesn't have an overload with an `optionsBuilder` parameter. It's probably an oversight, which could easily be remedied.

**Comment by adamralph** [comment]
I noticed this too just now, whilst considering [your previous comment](https://github.com/FakeItEasy/FakeItEasy/issues/482#issuecomment-225460868). :smile:

**Comment by blairconrad** [comment]
Putting in 2.1.0 milestone and removing up-for-grabs, because in theory that means we want it done soonish. @thomaslevesque, @adamralph, do either of you want this? If not, my xUnit conversion (which I hate with the heat of a thousand suns) can wait for a bit.

**Comment by thomaslevesque** [comment]
It's closely related to the issue I just resolved, so I might as well do it, unless one of you want it.

**Comment by blairconrad** [comment]
I was secretly hoping you'd take it.

**Comment by blairconrad** [comment]
This issue has been fixed in [release 2.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.1.0).
