### ISSUE TITLE
Public docs and exception messages refer to the internal IFakeObjectContainer

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#757]
See https://github.com/FakeItEasy/FakeItEasy/pull/756/files#r66874863

**Comment by claudiobernasconi** [comment]
@adamralph I am thinking about starting to contribute to FakeItEasy and just saw this hopefully entry-level issue. Can you clarify on what you expect to be fixed with this issue? Thanks in advance.

**Comment by blairconrad** [comment]
Hi, @claudiobernasconi. Thanks for your interest.

@thomaslevesque had originally noticed that in some of our comments and error messages, [we still reference](https://github.com/FakeItEasy/FakeItEasy/search?utf8=%E2%9C%93&q=IFakeObjectContainer) `IFakeObjectContainer`, a type that was removed in #606.

So the task would be to update the comments and error messages.

We'd appreciate the help. Are you still interested?

**Comment by claudiobernasconi** [comment]
Hi, @blairconrad sure, I am. I am going to scan the code for it and create a pull-request when it is ready to go. Do I need to be assigned to this issue? Can you do that?

**Comment by blairconrad** [comment]
Wow. That was fast!

I was writing up a note about how there were some complexities, but now that you have a PR, maybe we'll just review it. I'll add you as a collaborator so I can assign the issue.

I'm at work now, but can take a look probably tonight (I'm in UTC-5).

**Comment by claudiobernasconi** [comment]
Well, maybe I did misunderstand a thing then. The matches I found seemed reasonable to resolve. I appreciate your review since this is my first contribution to this repository. Nevermind, it does not have to be tonight. I just wait. Btw. 

I'm in UTC+1 and will get back to it tomorrow. I am really willing to help, and maybe need some guidance.

**Comment by adamralph** [comment]
Thanks very much @claudiobernasconi!

**Comment by blairconrad** [comment]
Folks, given that we are referencing `IFakeObjectContainer` in an error message, not just a comment, I think this issue could be considered a (minor) bug. Objections?

**Comment by adamralph** [comment]
No objections.

**Comment by blairconrad** [comment]
You're up early!

**Comment by adamralph** [comment]
Going hiking today :wink:

**Comment by thomaslevesque** [comment]
> Folks, given that we are referencing IFakeObjectContainer in an error message, not just a comment, I think this issue could be considered a (minor) bug. Objections?

Agreed

**Comment by adamralph** [comment]
Reworded as a bug.

**Comment by adamralph** [comment]
Hmmm... I'm not sure which milestone to put this on now. We've already released 3.0.0-rc0001 so this shouldn't really be part of 3.0.0. (Perhaps we (I) should have waited with the merge of #982 until after 3.0.0.)

**Comment by blairconrad** [comment]
Yeah, I though we were going to wait. I'd even warned @claudiobernasconi that we'd sit on his changes for a bit (not the most elegant of solutions, but it does avoid having to muck about with tags and junk).

**Comment by adamralph** [comment]
@blairconrad somehow I skipped over that part of your comment on the PR. Apologies.

However, it is easy to release 3.0.0 from the same commit as 3.0.0-rc001. We just need to create the tag on the same commit and re-run [the AppVeyor build](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/99). Assuming that's how we're going to proceed, any objection to putting this on a 3.1.0 milestone? (We can rename to 3.0.1 later if we decide to release bug fixes only.)

**Comment by blairconrad** [comment]
@adamralph, no worries.

Yeah, @thomaslevesque and I were going over the mechanism for releasing 3.0.0 in the Gitter chat.
I'd probably rerun build 97, but you have the gist. Putting it on a 3.1.0 sounds great. I'm happy to make the Release/Release Issue/PR to update the version later tonight, unless someone wants to do it manually in the meantime.

**Comment by adamralph** [comment]
Yep, re-running any one of builds 97, 98, or 99 will achieve the same thing. They're all pointing to the same commit.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.1.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.1.0).

@claudiobernasconi, look for your name in the release notes! :trophy:
