### ISSUE TITLE
Overloads of A.CollectionOfFake methods accepting an optionsBuilder

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#758]
Assuming it's possible, it seems like an obvious missing slice in our overload matrix for `A`.

**Comment by thomaslevesque** [comment]
It makes sense for fakes, but probably not for dummies.

**Comment by adamralph** [comment]
Ah yes, of course, thanks.

**Comment by blairconrad** [comment]
It's early in Canada. Can someone explain to me how this is different from #755?

**Comment by adamralph** [comment]
@blairconrad it's not. I just have a memory like a sieve :smile:

**Comment by thomaslevesque** [comment]
> I just have a memory like a sieve :smile:

Me too, apparently... I opened #755 2 days ago, and didn't even notice the duplicate ^^
