### ISSUE TITLE
Have the fakeiteasyfx account tweet StackOverflow questions

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#760]
A while ago, I set up an [IFTTT](https://ifttt.com/) action to tweet new FakeItEasy questions on StackOverflow. Here's an example of one in action:

https://twitter.com/Hippopottoman/status/742663916837306368

This is great, but now that [fakeiteasyfx is a Twitter account](https://twitter.com/fakeiteasyfx), maybe we should have it tweet. It'll look more official, and probably get more views.

Yea, or nay?

**Comment by thomaslevesque** [comment]
As discussed in the chat, I'm :+1: for this

**Comment by blairconrad** [comment]
If we go for this, I'm happy to implement.

**Comment by blairconrad** [comment]
nice "r"

**Comment by blairconrad** [comment]
The old tweets mentioned `#FakeItEasy` explicitly, because I'm not it. I wonder if it's necessary. Could remove and expand SO:

```
New #StackOverflow question:
{{EntryTitle}}
{{EntryUrl}}
```

Or leave. Or expand both:

```
New #FakeItEasy #StackOverflow question:
{{EntryTitle}}
{{EntryUrl}}
```

… but then we're eating up a lot of our characters.

**Comment by thomaslevesque** [comment]
I don't think we need to mention StackOverflow. The tweet will contain an extract with the SO logo, which is well known. So I think we can do this:

```
New #FakeItEasy question:
{{EntryTitle}}
{{EntryUrl}}
```

**Comment by blairconrad** [comment]
I'd not considered this, @thomaslevesque.

I usually see in TweetDeck, with no such extract:

![image](https://cloud.githubusercontent.com/assets/3275797/16044148/2f03e882-3211-11e6-994d-be07e68bba8c.png)

To compare with 

![image](https://cloud.githubusercontent.com/assets/3275797/16044172/571aa6d0-3211-11e6-86de-a24991b8d23d.png)

**Comment by adamralph** [comment]
I'm leaning towards :-1: on this. I believe the tweets that come out of our official account should be human crafted/curated. An automatic tweet of *any* SO question that is raised feels like spam and doesn't have the interest level of the linked question as an input parameter.

I also think that the vast majority of followers are not interested in having a feed of new SO questions. It's something likely to be only of interest to us owners plus perhaps a vanishingly small number of very enthusiastic contributors, so I think this will significantly reduce the signal to noise ratio for most followers and may lead to a few un-follows.

People who are really interested in a feed of new SO questions can set that up themselves easily enough. We could wrap this up for them in a separate "fakeiteasyso" account but generally, I don't think this is the best way of receiving this information. Twitter feeds scroll past fairly quickly once you follow a few accounts. I'd rather have these notifications delivered by email and use that as a queue.

**Comment by thomaslevesque** [comment]
@adamralph, point taken. I think you're right, relaying those questions automatically doesn't have much value.

**Comment by blairconrad** [comment]
All fair points, @adamralph.

**Comment by blairconrad** [comment]
Thanks for spending time on this, guys.

**Comment by adamralph** [comment]
Thanks for raising it. Always good to have the discussion, and set a precedent for future similar conversations elsewhere.
