### ISSUE TITLE
Register IFakeAndDummyManager as a singleton

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#769]
In https://github.com/FakeItEasy/FakeItEasy/pull/768#discussion_r67624889, @thomaslevesque observed:

> I just realized that `IFakeCreatorFacade` is not registered as a singleton... and most of its dependencies are not singletons either. This means that everytime we call `A.Something`, we create new instances of all these things. I wonder if this could be improved…

Note that `IFakeCreatorFacade` and `DefaultFakeCreatorFacade` were removed in https://github.com/FakeItEasy/FakeItEasy/pull/776 so this issue now drops down to the single dependency of `DefaultFakeCreatorFacade`, which is `IFakeAndDummyManager`.

**Comment by thomaslevesque** [comment]
I tried to change the registration to make it a singleton, and everything seems to work. But there might be a good reason for it not being a singleton that I'm not aware of...

**Comment by adamralph** [comment]
What I find particularly suspicious is that there are tests in existence which specifically insist that these types are *not* registered as singletons...

**Comment by blairconrad** [comment]
@adamralph, you talking about https://github.com/FakeItEasy/FakeItEasy/blob/ac9c555b871a5e1304c3f47fde2c8282e177333c/tests/FakeItEasy.Tests/ServiceLocatorTests.cs or something else?

If just ServiceLocatorTests, I think these are just testing to make sure ServiceLocator does the right thing when someone is registered as a non-singleton, and that use of these classes in the tests is just luck.

I'm not saying don't analyze, but if an analysis suggests that it's okay to make a singleton, I wouldn't let those tests stop us.

**Comment by adamralph** [comment]
@blairconrad yep, those are the ones. I guess you're right, these are tests for the `ServiceLocator` itself, and the types used in the test are irrelevant.

**Comment by adamralph** [comment]
If this turns out to yield a significant performance improvement, let's re-label as an enhancement, change the title to "Improve performance by..." and stick it on the next milestone.

**Comment by adamralph** [comment]
Note that if #776 make it in then this will have to be re-titled.

**Comment by blairconrad** [comment]
> Note that if #776 makes it in then this will have to be re-titled.

@adamralph, it made it in. Were you suggesting that we should retitle to reference `IFakeAndDummyManager` and its implementation?

**Comment by adamralph** [comment]
@blairconrad correct, thanks for the reminder. I've updated the title and added a note to the description.

**Comment by blairconrad** [comment]
I think we'll at least need a new `DummyValueCreationSession` each time we try to construct a Dummy or Fake. It keeps a record of the types currently being resolved, and if we're accessing the same session from multiple threads, they could interfere.
Which doesn't mean that we can't use a singleton `IFakeAndDummyManager`, but would mean that we'd need to start passing the context around instead of hanging the `DummyValueCreationSession` on the fake and dummy manager.

**Comment by blairconrad** [comment]
Regarding how currently being resolved dummies could interfere with each other, I'm worried about:

* thread 1 starts to create a Dummy `A`, which requires a `B`. We record that we're trying to resolve `A`.
* thread 2 starts to create a Dummy `B`. We record that we're trying to resolve `B`
* thread 1 continues and finds the `A` constructor that needs a `B`. We look up the types we're trying to resolve, find `B`, and assume we have a circular reference, so unfairly drop that constructor from consideration

**Comment by adamralph** [comment]
If each use of the thing isn't atomic but rather relies on mutating it's state, then indeed, we won't be able to make it a singleton.

**Comment by blairconrad** [comment]
Still hope for `DefaultFakeAndDummyManager` and its friends, if we don't mind passing around a `DummyValueCreationSession`. I haven't checked the other classes. I'd just remembered that one from my look at how Dummies really get made, back in the day.

**Comment by blairconrad** [comment]
* `DefaultExceptionThrower`
* `DelegateProxyGenerator`
* `CastleDynamicProxyGenerator`
all appear to be safe and `FakeCallProcessorProvider.Factory` is already registered as a singleton. So `FakeObjectCreator` is probably fine.

`DynamicOptionsBuilder` is registered as a singleton. So that finished up `DefaultFakeAndDummyManager`, I think.

Yeah. I think it'd be okay, except for `IDummyValueCreationSession`.

**Comment by blairconrad** [comment]
Changing title, as the dummy creation session cannot become a singleton. Although, I am going to explore some potential improvements in the area.

**Comment by blairconrad** [comment]
This issue was fixed in [Release 3.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/3.3.0).
