### ISSUE TITLE
Static constructor cause exception

### ISSUE THREAD

**Issue by RomanKernSW** [FakeItEasy/FakeItEasy#794]
>   Below is a list of reasons for failure per attempted constructor:
>     No constructor arguments failed:
>       No usable default constructor was found on the type 

I've tried to mock a class that contains a static and default (instance) constructor.

`static SomeClass()
        {
            ....
        }
        public SomeClass()
        {
            ...
        }`

I dont understand why this exception even triggered. Public constructor exists... NSubstitute can handle such class

**Comment by adamralph** [comment]
@RomanKernSW thanks for raising this. If the class has a default constructor with no parameters, then it should be fakeable, so there must be something else at play. Is the class sealed?

Perhaps you can post a minimal reproduction of the problem?

**Comment by RomanKernSW** [comment]
Hm, OK. I guess I know why this exception happens. Exception Stacktrace is partially showed. The class contains some autoproperties that initalize a Web Service. Unit Test Project do not contains the definition of the endpoint for this service. Guess it would be more helpfull to show full stacktrace.

I have tried with new class that contains static and non static constructor and the mock works.

Current version of FakeItEasy is: 1.25.3.0

**Comment by adamralph** [comment]
@RomanKernSW great, thanks for the update!
