### ISSUE TITLE
Have RuleBuilder.MustHaveHappened build call description lazily 

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#796]
Currently the description is built even before checking to see whether the call happened.
If we delayed the description-building, we could
1. maybe save some time? If people had complicated descriptions that never needed to be written, and
2. support dynamic call descriptions, perhaps that included information about the supplied argument that did not match

See more on this in my recent discussions with @dennisdoomen [in Gitter](https://gitter.im/FakeItEasy/FakeItEasy?at=577bc1b1ef3990705bb60293).

With _very hacky_ experiment [in my repo](https://github.com/blairconrad/FakeItEasy/commit/0493991054351809457599106e2398a9eb7e0510).

**Comment by blairconrad** [comment]
@adamralph, @thomaslevesque, does this sound reasonable? Could we move it to **ready**?

**Comment by thomaslevesque** [comment]
Sounds good to me.

(I updated the first sentence in the description, which no longer made sense after you changed the title)

**Comment by blairconrad** [comment]
I bet it didn't, @thomaslevesque!

**Comment by blairconrad** [comment]
Hey, @dennisdoomen. You seem to have an interest in this feature. You want the issue?

**Comment by dennisdoomen** [comment]
Sorry guys, I don't have time to work on FIE right now. Have my hands full with FluentAssertions, my blog and my day job.

**Comment by blairconrad** [comment]
No worries. I thought I'd ask because it seems more like working on a feature that played into one of your goals. It's easy enough to make it available to the community if they want.

**Comment by blairconrad** [comment]
From the description: 

> support dynamic call descriptions, perhaps that included information about the supplied argument that did not match

this would require a new structure for the messages, as we currently write the description of the matcher once, not once per received call.
It's not a reason _not_ to implement lazy evaluation, we maybe won't get all the benefits we hoped for.

**Comment by thomaslevesque** [comment]
> we maybe won't get all the benefits we hoped for.

Which benefit wouldn't we get?

**Comment by blairconrad** [comment]
Potentially tailoring the "must have happened" message to identify the particular failure, like in #1078.
Or using FluentAssertions (or similar assertion library) to create the constraints and benefit from their rich error messages.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).
