### ISSUE TITLE
Request for accessing some internals

### ISSUE THREAD

**Issue by morgul77** [FakeItEasy/FakeItEasy#805]
Hi

We are doing lots of integration testing using Autofac and Fakeiteasy. However, there's sometimes a hole in what we test, because we A: have to fake it or B: wait for the side effect. 

I really like the Fakeiteasy syntax, and coupled with Autofac's support for dynamic proxy, I have now managed to get a prototype of a concept that lets our tests know if a particular piece of code has been called, and being able to inspect the return value.

Registration in autofac (Dump() is from linqpad):
```c#
var builder = new ContainerBuilder();
	builder.RegisterType<CA>().AsImplementedInterfaces();	
	builder.RegisterType<B>().AsImplementedInterfaces().WhenCompletedCallMatches(builder, x => x.Do(),() => "no return value".Dump())
													  .WhenCompletedCallMatches(builder, x => x.Do(A<string>.That.Matches(y => y.Equals("this"))), s => ("if this is " + s).Dump())
													  .WhenCompletedCallMatches(builder, x => x.Do(A<string>.That.Matches(y => y.Equals("that"))), s => ("if that is " + s).Dump()); ;
	using (var container = builder.Build())
	{
		var ia = container.Resolve<IA>();
		ia.Do();
		ia.Do("this");
		ia.Do("that");
		ia.Do("something else");
	}
```

The actual code, is perhaps misusing Fakeiteasy, but I think it helps, because I can use the ExpressionCallMatcher, the parser, and other useful things. Code as follows:
```c#
public class Interceptor : IInterceptor
{
	public virtual void Intercept(IInvocation invocation)
	{
		invocation.Proceed();
	}
}
// Define other methods and classes here
public static class ContainerBuilderExtensions
{
	public static IRegistrationBuilder<T, ConcreteReflectionActivatorData, SingleRegistrationStyle> WhenCompletedCallMatches<T>(this IRegistrationBuilder<T, ConcreteReflectionActivatorData, SingleRegistrationStyle> registration, ContainerBuilder builder, Expression<Action<T>> callSpecification, Action actionToInvoke)
	{
		var interceptorName = Guid.NewGuid().ToString();
		EnableInterceptionOnce(registration);
		registration.InterceptedBy(interceptorName);
		var fakeItEasyInterception = A.Fake<IInterceptionListener>(d => d.ConfigureFake(
		t =>
		{
			A.CallTo(() => t.OnAfterCallIntercepted(A<ICompletedFakeObjectCall>.Ignored, A<IFakeObjectCallRule>.Ignored)).Invokes(x =>
			   {
				   var completedCall = new CastleInvocationCallAdapter(x.GetArgument<ICompletedFakeObjectCall>(0).GetArgument<IInvocation>(0));
				   var factory = ServiceLocator.Current.Resolve<IExpressionCallMatcherFactory>();
				   var callExpressionParser = ServiceLocator.Current.Resolve<ICallExpressionParser>();
				   var matcher = factory.CreateCallMatcher(callExpressionParser.Parse(callSpecification));
				   if (matcher.Matches(completedCall))
					   actionToInvoke();
			   }
			);
		}));
		var castleInterceptor = A.Fake<Interceptor>(b => b.CallsBaseMethods().Implements<IInterceptor>());
		Fake.GetFakeManager(castleInterceptor).AddInterceptionListener(fakeItEasyInterception);
		builder.Register(a => castleInterceptor).Named<IInterceptor>(interceptorName);
		return registration;

	}

	private static void EnableInterceptionOnce<T>(IRegistrationBuilder<T, ConcreteReflectionActivatorData, SingleRegistrationStyle> registration)
	{
		if (!registration.RegistrationData.ActivatingHandlers.Any(x => x.Method.Name.Contains("EnableInterfaceInterceptors")))
			registration.EnableInterfaceInterceptors();
	}
	public static IRegistrationBuilder<T, ConcreteReflectionActivatorData, SingleRegistrationStyle> WhenCompletedCallMatches<T, TResult>(this IRegistrationBuilder<T, ConcreteReflectionActivatorData, SingleRegistrationStyle> registration, ContainerBuilder builder, Expression<Func<T, TResult>> callSpecification, Action<TResult> actionToInvoke)
	{
		var interceptorName = Guid.NewGuid().ToString();
		EnableInterceptionOnce(registration);
		registration.InterceptedBy(interceptorName);
		var fakeItEasyInterception = A.Fake<IInterceptionListener>(d => d.ConfigureFake(
		t =>
		{
			A.CallTo(() => t.OnAfterCallIntercepted(A<ICompletedFakeObjectCall>.Ignored, A<IFakeObjectCallRule>.Ignored)).Invokes(x =>
			   {
				   var completedCall = new CastleInvocationCallAdapter(x.GetArgument<ICompletedFakeObjectCall>(0).GetArgument<IInvocation>(0));
				   var factory = ServiceLocator.Current.Resolve<IExpressionCallMatcherFactory>();
				   var callExpressionParser = ServiceLocator.Current.Resolve<ICallExpressionParser>();
				   var matcher = factory.CreateCallMatcher(callExpressionParser.Parse(callSpecification));
				   if (matcher.Matches(completedCall))
					   actionToInvoke((TResult)completedCall.ReturnValue);
			   }
			);
		}));
		var castleInterceptor = A.Fake<Interceptor>(b => b.CallsBaseMethods().Implements<IInterceptor>());
		Fake.GetFakeManager(castleInterceptor).AddInterceptionListener(fakeItEasyInterception);
		builder.Register(a => castleInterceptor).Named<IInterceptor>(interceptorName);
		return registration;
	}

}
```

Now; in order to make this happen I had to open up fakeiteasy for linqpad, to get access to the internals. Which of course, is not very nice. But I get all the goodies from both worlds.

So the question is: Is it possible to open up the internals a bit? Or is there a way I can do this without all the hoops?

I have attached a "working" example of this as a linqpad script. I had to dispose of the ilmerge in the compilation as well, because castle.core is also in Autofac.DynamicProxy etc etc, so it only works on the modified fakeiteasy that's also in the zipfile.

[LINQPad Queries.zip](https://github.com/FakeItEasy/FakeItEasy/files/382472/LINQPad.Queries.zip)

**Comment by thomaslevesque** [comment]
To be honest, I don't understand everything you're doing (perhaps because I'm not familiar with Autofac). Also, I can't run your LINQPad query, even with your custom version of FakeItEasy; which version of LINQPad are you using? In mine (5.05.01), the query assembly isn't named LINQPadQuery, but has a random name, which is different for every query...

> Is it possible to open up the internals a bit?

Possible, yes... but that's probably not something we'll want to do, unless there's a very compelling reason. We try to expose as little of the internals as possible, because if we expose internals in the public API and people start to rely on them, then we can't change implementation details without introducing breaking changes.

That being said, we *could* perhaps introduce new APIs for making it easier to match calls, e.g. in interceptors. Would a `Matches` extension method that applies to `IFakeObjectCall` be useful to you? It could take a call specification in the same form as `A.CallTo`.

Or perhaps, an `InvokesAfter` method that can access the completed call? I think it would let you write something like this:

    builder.RegisterInstance(A.Fake<IB>(o => o.Wrapping(new B()).ConfigureFake(b =>
    {
        A.CallTo(() => b.Do()).InvokesAfter(() => "Hello World no return value".Dump());
        A.CallTo(() => b.Do(A<string>.That.Matches(y => y.Equals("this")))).InvokesAfter(s => ("if this is " + s).Dump());
        A.CallTo(() => b.Do(A<string>.That.Matches(y => y.Equals("that")))).InvokesAfter(s => ("if that is " + s).Dump());
    })));

**Comment by thomaslevesque** [comment]
Actually, I realize there's something missing... in my example, the return values are not specified, and there's no easy way to tell FakeItEasy to return the value from the wrapped instance. Maybe we could add a `CallsWrappedMethod()` method, similar to `CallsBaseMethod()`  (of course, it would fail if there's no wrapped instance...)

**Comment by morgul77** [comment]
Well, the wrapping won't work. I went down that path, I need Autofac to do the instantiating of the component.

About linqpad, I forgot to mention that you need to enable "Allow linqpad to access internal types in other assemblies" LINQPadQuery is something linqpad uses behind the scenes. https://linqpad.uservoice.com/forums/18302-linqpad-feature-suggestions/suggestions/513533-add-support-for-internalsvisibleto. I also use Always fresh appdomains, as not to confuse proxy generation.

That beeing said, looking at it again, here's the lines I need to have done:
```
var completedCall = new CastleInvocationCallAdapter(x.GetArgument<ICompletedFakeObjectCall>(0).GetArgument<IInvocation>(0));
                   var factory = ServiceLocator.Current.Resolve<IExpressionCallMatcherFactory>();
                   var callExpressionParser = ServiceLocator.Current.Resolve<ICallExpressionParser>();
                   var matcher = factory.CreateCallMatcher(callExpressionParser.Parse(callSpecification));
                   matcher.Matches(completedCall)
```

which is if an IInvocation matches Expression. 

I understand the need to hide the internal though. Perhaps a method along the lines of CompletedFakeObjectCallExtensions.Matching, 

This code works, but not with a return value:
```
 var completedCall = new CastleInvocationCallAdapter(x.GetArgument<ICompletedFakeObjectCall>(0).GetArgument<IInvocation>(0));				  
				   if (FakeItEasy.CompletedFakeObjectCallExtensions.Matching(new[] { completedCall},callSpecification).Any())
```

which only needs the CastleInvocationCallAdapter to be public, and for the problem with return values, a duplicate method of Matches method like so:
```
public static IEnumerable<ICompletedFakeObjectCall> Matching<TFake, TResult>(this IEnumerable<ICompletedFakeObjectCall> calls, Expression<Func<TFake,TResult>> callSpecification)
        {
            var factory = ServiceLocator.Current.Resolve<IExpressionCallMatcherFactory>();
            var callExpressionParser = ServiceLocator.Current.Resolve<ICallExpressionParser>();
            var matcher = factory.CreateCallMatcher(callExpressionParser.Parse(callSpecification));

            return
                from call in calls
                where matcher.Matches(call)
                select call;
        }
```
would solve that problem as well

**Comment by thomaslevesque** [comment]
> Perhaps a method along the lines of CompletedFakeObjectCallExtensions.Matching,

Ah, yes, I forgot about that one. The form of the API always struck me as odd; we have a way to filter a collection of calls based on a specification, but no direct way to just test if a call matches a specification. It seems a pretty specific use-case, and makes me wonder if this method was publicly exposed by accident... Anyway, we could probably add similar extension methods to match a call against a specification.

**Comment by morgul77** [comment]
Yeah, I thought it might be a mistake too, but hey, accidents sometimes are a blessing.

I'll see if I can come up with a suggestion tonight.

Are you thinking along the lines of a single ICompletedFakeObjectCall, or enumerable?

I don't know the overhead of parsing the callspecification, but I would be happy if the suggested method above is added and the  CastleInvocationCallAdapter was public, and it would be consistent with the existing method.

Alternatively, there could be an overload accepting the IInvocation from Castle, but I guess that would break the feel of the API for all other purposes (not having the code in front of me, but I'm guessing it won't appear anywhere).

**Comment by blairconrad** [comment]
@morgul77, I'm trying to play catchup here and look for what might be a simpler solution.
I think I see what you're doing, but have a couple of questions. Perhaps I'm misunderstanding things.

1. The action you've configured in your registration, using the `Dump` (which I realize would be different in a real test): you don't know which object the method was invoked on, because you never actually create or refer to the objects. Do I understand correctly?
2. If the goal is to figure out whether a method has been called, could that not be achieved by using [Autofac.Extras.FakeItEasy](http://autofac.readthedocs.io/en/latest/integration/fakeiteasy.html#configuring-fakes)?I'm probably missing something, but if so, could you explain to me the gap? I tried this  
    ```c#
    using (var autoFake = new AutoFake())
    {
        var ia = autoFake.Resolve<CA>();
        ia.Do();
        ia.Do("this");
        ia.Do("that");
        ia.Do("something else");
        
        A.CallTo(() => autoFake.Resolve<IB>().Do("that")).MustHaveHappened();
    }
    ```
    with good results.

**Comment by morgul77** [comment]
1. Typically I would perhaps create Task and wait for it, and continue asserting. Or I could pass the return value to some other validation, or check a database id. Autofac takes care of  all the objects, and in the integration test regime we have, we can spawn different services, and have them interact like they where seperate systems. So often we are interested in knowing what part of a real system that was called, the object instance doesn't matter. In short, you understood correctly. I might add some more methods though, to return a Task<TResult>, or Task<ICompletedFakeObjectCall> depending on how this turns out.

2. Autofake is really nice for unittesting, and is the opposite of what I'm trying to achieve. In the scenario I intend to use it, we use the production autofac container, with all the bells,whistles and quirks that are registered.

**Comment by morgul77** [comment]
Ok, I had a stab at this.

While it worked when I did not have Castle.Core in the dll, it doesn't with, because if the internalizing I think.  

So, I went back a few steps, to see of other options are better.

I thought the InvokesAfter actually could work, but a different setup for Autofac is needed something like

```
	builder.Register(ctx=>A.Fake<B>(x => x.Implements<IB>().ConfigureFake(b =>
	{
		A.CallTo(() => b.Do()).InvokesAfter(() => "no return value".Dump()).CallsBaseMethod();
		A.CallTo(() => b.Do(A<string>.That.Matches(y => y.Equals("this")))).InvokesAfter(s => ("if this is " + s).Dump()).CallsBaseMethod();
		A.CallTo(() => b.Do(A<string>.That.Matches(y => y.Equals("that")))).InvokesAfter(s => ("if that is " + s).Dump()).CallsBaseMethod();;
	})));
```

But, after some initial testing, this breaks autofacs resolving, making it prone to errors due to the change in constructor signature I think. I ended up with fake dependencies.

I went back to look at the castle.core problem and found that I could make a CastleInvocationCallAdapterExternal, with dependency on the Castle.Core that autofac.dynamicproxy  happens to provide.

I've created a pull request on the changes

**Comment by blairconrad** [comment]
Sorry for the delay, @morgul77. I was stepping back to think about this and to look for alternative implementations. I think I ran into a problem similar to the one you had with the the internalized Castle.Core or not. Specifically, I'd thought to grab the `CastleInvocationCallAdapter`'s constructor by reflection and to use it. But the two competing `IInvocations` gave me trouble.

I appreciate how using a custom `CastleInvocationCallAdapterExternal` reduces the changes you're asking for in FakeItEasy.

However, I still have misgivings about this. I'm sympathetic to your need, but the whole thing feels a little wrong to me, and way outside the scope of FakeItEasy's intent. The changes being made don't support using a Fake and checking to see if the calls made to it match an expression, but rather checking to see if the calls match Castle.Core's representation of a call. I know there's nothing directly in the PR about Castle.Core, but were it not for the need to do a "double interpretation" of a method call, we wouldn't be considering a change at all.

And the PR exposes methods in what I tend to think of as niche areas (and in which I'd be happier seeing _fewer_ things exposed than more).

I think I need more time with this. I'm happy to hear counter-arguments.

**Comment by blairconrad** [comment]
> Well, the wrapping won't work. I went down that path, I need Autofac to do the instantiating of the component.

I know you've looked into this a lot longer than I have, but could Autofac not still instantiate the component? Then that instance can be wrapped, via a decorator. Something like this:

```c#
builder.RegisterType<B>().Named<IB>(nameof(B));
builder.RegisterDecorator((IB realB) =>
    A.Fake<IB>(options => options
        .Wrapping(realB)
        .ConfigureFake(b =>
        {
            A.CallTo(() => b.Do()).Invokes(() => System.Console.WriteLine("Hello World no return value"));
        })), fromKey: nameof(B));
```

(apologies, I don't use Autofac, so this may be non-idiomatic)

As is, it doesn't allow for a side effect that makes use of the return value, but perhaps that's something to look into, similar to the `InvokesAfter` or `CallsWrappedMethod` discussed earlier?
Alternatively, a listener could be attached to the Fake at this point and then the "simple" version of the completed call matching may be useful. That would only require addition of the Func-style `Matching`, I think.

**Comment by morgul77** [comment]
I agree, a decorator would be better.

```
	builder.RegisterType<B>().Named<IB>("test");
	builder.RegisterDecorator<IB>((c, inner) =>
	{

		var fake = A.Fake<IB>(x => x.Wrapping(inner).CallsBaseMethods().ConfigureFake(b =>
		{
			A.CallTo(() => b.Do("that")).ReturnsLazily(u =>
			{
				var returnValue = u.Method.Invoke(inner, u.Arguments.ToArray());
				dynamic test = Convert.ChangeType(returnValue, u.Method.ReturnType);
				"After return value method".Dump();
				return test;
			});
			A.CallTo(() => b.Do()).Invokes(u =>
			{
				u.Method.Invoke(inner, u.Arguments.ToArray());
				"After void method".Dump();
			});
		}
		));

		return fake;
	}, fromKey: "test").As<IB>();
```

If I could cast to the correct type with a litte more elegance..  (but I think  it would always work, I just need to wrap this up more nicely again).

Feel free to comment if you something that might go wrong!

Nice scenery on my journey through all this though:)

I do not need the matching with this approach.

**Comment by morgul77** [comment]
Ok, if you are interested, see the attached linqpad script. Works with the currently released fakeiteasy and autofac.
[take3.zip](https://github.com/FakeItEasy/FakeItEasy/files/385538/take3.zip)

Thanks for beeing resistant and suggestive,  Its the best solution I can come up with, with the current version of the frameworks, and it's better than using FakeItEasy for something it's not meant for.

This feels like an outside implementation of the aforementioned .CallsBaseMethod().InvokesAfter().

**Comment by blairconrad** [comment]
@morgul77, the new version of the Func type of `MethodCalledCompleted` is quite slick. I agree that the cast is a little awkward, but kudos to you for coming up with it at all.

It may just be my increasing familiarity as I keep thinking about your situation, but I find your newest solution to be the most straightforward. It's definitely my favourite. It's still a bit of hoop-jumping for you, but it is an unusual (from FakeItEasy's viewpoint) thing that you're doing…

I see what you're saying about the outside implementation of `InvokesAfter`. Perhaps it would be better to internalize something like that at some point.

**Comment by blairconrad** [comment]
Oh, no need to thank me for being resistant and suggestive. I'm, by nature, resistant to new features or expanding the API. And I _should be_ suggestive!

**Comment by blairconrad** [comment]
Unless you thanking me for being resistant and @thomaslevesque for being suggestive. That's often how the roles break down! :grinning:

**Comment by blairconrad** [comment]
Oh, and for what it's worth, I think `_inner` could be removed and `fake` moved to an inner scope in `ContainerBuilderExtensions.When`. Of course, maybe you're just presenting a simplified version, but 

```c#
public static IInterceptor<TInterface> When<TConcrete, TInterface>(this ContainerBuilder builder)
{
    var name = Guid.NewGuid().ToString();
    var configurationCalls = new List<Action<TInterface, TInterface>>();
    builder.RegisterType<TConcrete>().Named<TInterface>(name);
    builder.RegisterDecorator<TInterface>((c, inner) =>
    {
        var fake = A.Fake<TInterface>(x => x.Wrapping(inner).CallsBaseMethods());
        foreach (var configurationCall in configurationCalls)
            configurationCall(fake, inner);
        return fake;
    }, fromKey: name).As<TInterface>();

    return new Interceptor<TInterface>(configurationCalls);
}
```

seems to work…

**Comment by blairconrad** [comment]
And while I'm here, I'm surprised at the `CallsBaseMethods`. If we're wrapping `inner`, having the calls propagate to it rather than to the concrete implementations on the Fake seem like a better choice, if only because the Fake may have been created with different constructor arguments. Consider

```c#
var fake = A.Fake<TInterface>(x => x.Wrapping(inner));
```

**Comment by morgul77** [comment]
You are right about the inner and fake. When I typed it out before, it came down a little bit wrong.

Thanks for the suggestions!

I ofcourse had trouble with the first think I tried. Autofac delegated factories with regards to decorators, doesn't do that well (the delegatefactory will try to resolve the decorator instead of the real object). So I'm not home free yet, but thats a question for the autofac guys.

If you are curious, here it is:

```
void Main()
{
	var builder = new ContainerBuilder();

	//builder.RegisterType<B>().AsImplementedInterfaces();
	builder.RegisterType<B>().Named<IB>("test");
	builder.RegisterDecorator<IB>((c, inner) => new BDecorator(inner), fromKey: "test").As<IB>();


	using (var container = builder.Build())
	{	
		var ia = container.Resolve<BFactory>();	
		ia("ctor argument").Do();
	}
}
public interface IB
{
	void Do();

}

public delegate IB BFactory(string test);
public class B : IB
{

	public B(string test)
	{
		test.Dump("Constructor B called");
	}
	public virtual void Do()
	{
		"B".Dump("Called");
	}
	
}

public class BDecorator : IB
{
	IB _inner;
	public BDecorator(IB inner)
	{
		_inner = inner;
	}
	public virtual void Do()
	{
		"Decorated".Dump();
		_inner.Do();
	}
	
}
```

I guess this one can be closed, and I hope it doesn't all go to hell beacuse of those delegates (we use them quite a lot), and I have to go back to interceptors and callmatching again (don't want to) :)

Vacation soon!

**Comment by blairconrad** [comment]
@morgul77, I think the complaint is that Autofac doesn't know how to make a `B` using `public B(string test)`. If I add 

```c#
builder.RegisterInstance("hippo");
```

to your `Main`, everything works fine:

![image](https://cloud.githubusercontent.com/assets/3275797/17179640/eec4c266-53e7-11e6-8736-63976db28c78.png)

Then again, maybe you knew this and I misunderstood and there's still a bug.

**Comment by blairconrad** [comment]
Closing, as (I think is) suggested by https://github.com/FakeItEasy/FakeItEasy/issues/805#issuecomment-235556124.
If I misinterpreted, we can always reopen.
Or if the new approach doesn't pan out, we can always revisit this or another approach.
Thanks for your interest, @morgul77.

**Comment by morgul77** [comment]
Hi again.

I tried some different options, and the only path I have left for this to work with fakeiteasy is using the code in this pull request.

However, I see the need for keeping things internal, it  a lot nicer than a "random competing framework" I have looked at.

Would this path be viable?
1. Include the Matches routine as is
2. InternalsVisibleTo Autofac.Extras.FakeItEasy
3. Include the extension code in Autofac.Extras.FakeItEasy 
4. Have Autofac.Extras.FakeItEasy depend on Autofac.Extras.DynamicProxy2

3 and 4, I would have to ask the autofac team.

Is 2 out of the question?

**Comment by blairconrad** [comment]
Welcome back, @morgul77. At this point I'm still against opening up the internals of FakeItEasy to any other packages. The power of the `internal`s is that we're able to rework the code without worrying about how it will affect anyone else. If even one external package has access, we lose that ability.

I'm sure you've pursued many avenues for resolving your remaining hurdles, but maybe there's still progress to be made if we combine forces.
Way back in https://github.com/FakeItEasy/FakeItEasy/issues/805#issuecomment-235556124 about 3 weeks ago, things were looking pretty good, except for a problem (we thought) with AutoFac where it was trying to resolve a decorator, not the decoratee.

Can you catch us up with where you've gotten and what your best solution is so far? Maybe we can find another way.

**Comment by morgul77** [comment]
Hi

I'm sorry, I got too much stuff going on in my personal life, and no work time allotted for this.

To be brief:
*Wrapping won't work, because it wraps an already existing object with dependencies
*Decorators won't work with delegate factories (since the decorator is now the object to be created)

So that's where I'm at. You can close the issue up, since I won't have to follow it now.
