### ISSUE TITLE
Helper method for ordered assertions

### ISSUE THREAD

**Issue by galaktor** [FakeItEasy/FakeItEasy#82]
I use a helper method to make ordered assertions (https://github.com/FakeItEasy/FakeItEasy/wiki/Ordered-assertions) more readable in my tests. It looks like so:

```csharp
/// <summary>
/// Little helper to hide the FakeItEasy boilerplate for asserting calls in specific order.
/// </summary>
private void InOrder(Action act, Action assert)
{
	using(var scope = Fake.CreateScope())
	{
		act();

		using(scope.OrderedAssertions())
		{
			assert();
		}
	}
}
```

Used in a test, looks like this:

```csharp
[Test]
public void Receive_SomeCondition_FirstReceivesBeforeSecond()
{
	// setup stuff

	InOrder(act: () => target.Receive(stuff),

	assert: () =>
	{
		A.CallTo(() => first.Receive(stuff)).MustHaveHappened();
		A.CallTo(() => second.Receive(stuff)).MustHaveHappened();
	});
}
```
It fits nicer into an arrange/act/assert scenario, and therefor reads much better than the naked boilerplate of creating scope.

I suggest this be added to the FakeItEasy API (or something similar).

**Comment by adamralph** [comment]
@galaktor thanks for raising, but given the lack of enthusiasm to have this in the main lib, we decided to close this as a `wontfix`. You can, of course, continue using your own extension, and even consider publishing your own extension FIE extension package with this and any other personal helpers you find useful.
