### ISSUE TITLE
Switch analyser package to .NET Standard

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#833]
Currently we produce a PCL Profile7 assembly (`net40`, `dotnet` and `win8`) and put it in a `dotnet` folder in the nupkg.

Whilst this works, `dotnet` (ASP.NET Core 1.0) is a deprecated moniker and we should stop using it. I think we should be using a .NET Standard moniker instead.

However, this works for now, and I don't think we should make this change until the .NET Standard tooling comes out of preview.

**Comment by thomaslevesque** [comment]
This was fixed as a side effect of #1090

The analyzers now target `netstandard1.1`

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).
