### ISSUE TITLE
Unnatural fakes don't support property setter specification

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#838]
Unnatural fakes (`Fake<T>`) don't have the new `CallToSet` method used to specify property setters which was added for #175. For consistency, it should probably be added.

**Comment by thomaslevesque** [comment]
The signature would be something like this: 

    public IPropertySetterAnyValueConfiguration<TValue> CallsToSet<TValue>(
        Expression<Func<T, TValue>> propertySpecification)

**Comment by thomaslevesque** [comment]
@FakeItEasy/owners any objection to making this issue `ready`?

**Comment by blairconrad** [comment]
No sir!

**Comment by thomaslevesque** [comment]
This is a bit harder than expected, but I'm making progress. I should have a PR ready soon.

**Comment by blairconrad** [comment]
This issue has been released in FakeItEasy 3.0.0:
https://github.com/FakeItEasy/FakeItEasy/releases/3.0.0
