### ISSUE TITLE
Make analyzer tests fail when target code does not compile

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#843]
Currently, one can write a test and if the code doesn't compile, the test passes. When I modify the code tested inside `UnusedReturnValueAnalyzerTests.Diagnostic_Should_Not_Be_Triggered_When_Call_Is_Configured_With_Returns` like so:

```c#
using FakeItEasy;
namespace TheNamespace
{
    class TheClass
    {
        void Test()
        {
            var foo = A.Fake<IFoo>();
            A.Call To(() => foo.Bar());
        }
    }

    interface IFoo { int Bar(); }
}
```

(I removed the `Returns`, but accidentally added a space in `A.CallTo`. It's a little contrived, but the sort of problem a copy/paste might introduce)
the test passes.

In some cases, this won't materially affect the quality of the test, but in some it will. 

Instead, we could have the test fail. With output like this:

```
Build failed. Diagnostics are:
  Test0.cs(10,22): error CS1528: Expected ; or = (cannot specify constructor arguments in declaration)
  Test0.cs(10,22): error CS1003: Syntax error, '[' expected
  Test0.cs(10,39): error CS1003: Syntax error, ']' expected
  Test0.cs(10,15): error CS0426: The type name 'Call' does not exist in the type 'A'
  Test0.cs(10,20): warning CS0168: The variable 'To' is declared but never used
```

As you might guess. I have a spike, if we're interested.

**Comment by thomaslevesque** [comment]
> As you might guess. I have a spike, if we're interested.

I think we are!

This has bothered me for a while, but I never got around to fixing it.

**Comment by blairconrad** [comment]
Thanks for the merge, @thomaslevesque!
