### ISSUE TITLE
Analyzer gives false positive FakeItEasy0001 when call spec is returned from a method

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#844]
For instance this code causes the issue:

```c#
private IVoidConfiguration Test()
{
    var fake = A.Fake<IDisposable>();
    return A.CallTo(() => fake.Dispose());
}
```

> error FakeItEasy0001: Unused call specification 'A.CallTo(() => fake.Dispose())'; did you forget to configure or assert the call?

**Comment by blairconrad** [comment]
This issue has been released in [FakeItEasy 2.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.3.0).
