### ISSUE TITLE
Optimize away Expression.Compile() for simple FakeItEasy tests?

### ISSUE THREAD

**Issue by TimLovellSmith** [FakeItEasy/FakeItEasy#850]
I did some profiling of a unit test run with FakeItEasy 2.0. I noticed some 10% of CPU samples were in System.Linq.Expressions.Compiler.LambdaCompiler.Compile(). About 60% of those had FakeItEasy.ExpressionExtensions.Evaluate on the stack. Half of those were from AssertThatMemberCanBeIntercepted, the remainder from GetFakeManagerCallsMadeOn.... but that no longer exists in latest FakeItEasy code.

**Comment by TimLovellSmith** [comment]
Actually it seems like this is optimized much better in 2.2. I get 0% of CPU samples in LambdaCompiler.Compile() now!

**Comment by TimLovellSmith** [comment]
It looks like it has been replaced with calls to System.Reflection.Emit.DynamicMethod.CreateDelegate()... that can likely be optimized away now for the common case where there's no real need to create a delegate and invoke it, just to evaluate the subexpression 'fake':

var fake = A.Fake<X>();
A.CallTo(() => fake.DoSomething()).Returns(y);

**Comment by blairconrad** [comment]
Hey, @TimLovellSmith. Lovely to see you. Thanks for this. I was worried when I first started reading the issue, as I thought that some recent work I'd done would've made some of the parsing cost a little lower. Glad you found the same!

Out of curiosity, are your profiling reports anywhere visible? I'd be keen to take a look. (I know, I could make some myself, but examples from the wild could be informative.)

**Comment by TimLovellSmith** [comment]
Since this is from a closed source project for work I don't want to post the whole profile dumps, but here are a couple screenshots to give you an idea of where I saw our CPU cycles were going...

CPU samples, sorted by exclusive samples [samples within the function body] - CreateDelegate sits at 6.66% of CPU usage.

![speedup1](https://cloud.githubusercontent.com/assets/2711795/18439879/c9533fb4-78bb-11e6-932a-322cdcd7f3f1.jpg)

It appears only 2-3%, not 6-7% comes from this code path which I'm optimizing:

![createdelegatecallgraph](https://cloud.githubusercontent.com/assets/2711795/18440018/67088282-78bc-11e6-8426-e840f1343272.jpg)

We could maybe also call FastEvaluate method from InvokeExpression, but I haven't read enough of that code path to come up with an opinion of whether that would likely be a useful speedup (in theory).

I'm trying to get a before/after profile of this change to see what the real impact is.

**Comment by TimLovellSmith** [comment]
So here is what an actual performance comparison shows, note that I did BASELINE in the reverse order to usual for my own convenience (and everybody else's confusion!):

BASELINE FakeItEasy (2.3.0-aaalpha = my build of master plus this change)
=== TEST EXECUTION SUMMARY ===
Total: 828, Errors: 0, Failed: 0, Skipped: 0, Time: 11.293s

FakeItEasy 2.2.0:
=== TEST EXECUTION SUMMARY ===
Total: 828, Errors: 0, Failed: 0, Skipped: 0, Time: 11.368s

And the all important CPU cost deltas (red arrows are good! green arrows are bad!)
![backwardsdelta](https://cloud.githubusercontent.com/assets/2711795/18442427/8cd40852-78c5-11e6-93d9-cc2e59977180.jpg)

**Comment by blairconrad** [comment]
@TimLovellSmith, I wouldn't've expected a full dump. These kinds of summaries are what I was curious about. A 2.5% difference for 585 CPU samples is pretty good, but it sounds better as a 1/3 reduction in the amount of time spent in `System.Linq.Expressions.Compiler.LambdaCompiler.Compile`, no? Or do I misunderstand the numbers?

Thanks for the report. And the rest of the work!

**Comment by TimLovellSmith** [comment]
@blairconrad So I had a look at the other call path, which is via ExpressionArgumentConstraintFactory.InvokeExpression(), and happily, I think it's going to be just as beneficial there!

Now working on measuring the improvement from optimizing both.

**Comment by TimLovellSmith** [comment]
@blairconrad 

And here are the results... [Sample size of 1, so not very statistical, hah.] [Is it just me or are VS performance tools seem to be oscillating back and forth between showing the cost as going to either LambdaCompiler().Compile() or DynamicMethod.CreateDelegate()? I don't know why.]

[BASELINE - no optimizations, FakeItEasy 2.2]
FakeItEasy 2.2.0:
 === TEST EXECUTION SUMMARY ===
 Total: 828, Errors: 0, Failed: 0, Skipped: 0, Time: 11.368s (reusing previous result)

[Both optimizations, + other enhancements from master... maybe will be FakeItEasy 2.3]
=== TEST EXECUTION SUMMARY ===
Total: 828, Errors: 0, Failed: 0, Skipped: 0, Time: 10.653s

And CPU new improved performance delta, in percentages, this time:
![newimproveddelta](https://cloud.githubusercontent.com/assets/2711795/18448697/eb3e9ef0-78e0-11e6-95bf-5de89c3815cf.jpg)

**Comment by TimLovellSmith** [comment]
It does not seem to make FakeItEasy's unit tests run any faster for me though.

**Comment by TimLovellSmith** [comment]
I am adding a couple more optimizations (trivial method calls and boxing expressions) and using the optimized evaluator everywhere. The results seemed to be positive on my own tests, and neutral on FakeItEasy's:

(after)
=== TEST EXECUTION SUMMARY ===
Total: 828, Errors: 0, Failed: 0, Skipped: 0, Time: 10.502s

CPU Sampling Delta with previous batch of optimizations (green is good):

![latestdelta](https://cloud.githubusercontent.com/assets/2711795/18484934/7a021d2e-799f-11e6-88d3-944e74042a1d.jpg)

Interesting that the savings are all in 'ThePreStub' and I don't know why, I can only speculate that now there get to be a lot less calls to some class or other. I think most of the other deltas are noise. I wonder how repeatable the results will be. :D

**Comment by TimLovellSmith** [comment]
Results are not highly repeatable! a rerun saw quite different results, but the second time some of the savings appear to be in the LambdaCompiler.Compile area, as expected... (but the rest are just moved to DynamicMethod.CreateDelegate - CLR you are so confusing!)

![latestdeltarerun](https://cloud.githubusercontent.com/assets/2711795/18485404/7e93d1be-79a1-11e6-8189-1fe7c2385917.jpg)

**Comment by blairconrad** [comment]
This issue has been released in [FakeItEasy 2.3.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/2.3.0).

@thomaslevesque, thanks again, and look for your name in the release notes! :trophy:

**Comment by thomaslevesque** [comment]
> @thomaslevesque, thanks again, and look for your name in the release notes! 🏆

I think you meant @TimLovellSmith ;)

**Comment by blairconrad** [comment]
I DID! Too sleepy!

@TimLovellSmith, a thousand pardons!

**Comment by blairconrad** [comment]
Once more, with feeling:

**@TimLovellSmith, thanks again, and look for your name in the release notes! :trophy:**

**Comment by TimLovellSmith** [comment]
@blairconrad LOL and thank you for the acknowledgement! :)
