### ISSUE TITLE
Breaking changes to call configuration in master

### ISSUE THREAD

**Issue by TimLovellSmith** [FakeItEasy/FakeItEasy#853]
Hi,
I was just now testing private build of latest master assuming that this  will be 2.3.
(Is it actually going be 3.0?)

As I was doing this, I was unpleasantly surprised to see there seem to be some changes to FakeItEasy that caused two tests to fail - seems to me like it might better go with a major version bump, as what we're doing isn't that unusual - is it?

```
[FAIL]
      System.InvalidOperationException : The behavior for this call has already been defined
      Stack Trace:
        C:\repo\FakeItEasy\src\FakeItEasy\Configuration\BuildableCallRule.cs(83,0): at FakeItEasy.Configuration.BuildableCallRule.UseApplicator(Action`1 newApplicator)
        C:\repo\FakeItEasy\src\FakeItEasy\Configuration\RuleBuilder.cs(131,0): at FakeItEasy.Configuration.RuleBuilder.ReturnValueConfiguration`1.ReturnsLazily(Func`2 valueProducer)
        CacheProvisionWorkerTests.cs(90,0): at RefreshTest()

[FAIL]
      System.InvalidOperationException : The behavior for this call has already been defined
      Stack Trace:
        C:\repo\FakeItEasy\src\FakeItEasy\Configuration\BuildableCallRule.cs(83,0): at FakeItEasy.Configuration.BuildableCallRule.UseApplicator(Action`1 newApplicator)
        C:\repo\FakeItEasy\src\FakeItEasy\Configuration\RuleBuilder.cs(52,0): at FakeItEasy.Configuration.RuleBuilder.Throws(Func`2 exceptionFactory)

        CacheDataArchiveTests.
cs(69,0): at <AddImportExportOperation_Failure_Ti
mesoutParent>d__1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Here is an example of what we're doing that breaks:

```c#
var getCS = A.CallTo(() => store.GetTenantStorageAccountConnectionString(deployment, A<CancellationToken>.Ignored));
getCS.Returns(Task.FromResult(cs));
var add = A.CallTo(() => operations.AddImportExportOperation(deployment, A<RequestData>.Ignored));
add.Returns(Task.FromResult(0));
var enqueue = A.CallTo(() => queue.EnqueueMessageToTenantAsync(null, cs));
enqueue.Throws(new Exception());

var ex = await Record.ExceptionAsync(() => cda.AddImportExportOperation(null, deployment, null, null));
Assert.NotNull(ex);

add.Throws(new Exception()); /* blows up */
//... further testing
```

**Comment by thomaslevesque** [comment]
This is indeed a breaking change, but it was introduced in 2.0.

**Comment by thomaslevesque** [comment]
If you want to change the behavior of a call, the currently recommended approach is described [here](http://fakeiteasy.readthedocs.io/en/stable/limited-call-specifications/#changing-behavior-between-calls). A better. A more intuitive approach is being worked on in #804; if we decide to go ahead with it, it will likely be in 3.0.

**Comment by thomaslevesque** [comment]
BTW, if the method returns a `Task`, you don't need to explicitly configure it explicitly; by default, it will return a completed task. If it returns a `Task<T>`, it will return a completed task with a dummy `T` as the result. To configure the result explicitly, you don't actually need `.Returns(Task.FromResult(value))`, you can just write `.Returns(value)`

**Comment by TimLovellSmith** [comment]
@thomaslevesque 
Oh it was during the 2.0 release? Sorry for the alarm! I was on FakeItEasy.2.0.0-beta009 still.
Thanks!
