### ISSUE TITLE
Formalize DoesNothing, Invokes, and AssignsOutAndRefParameters behaviour

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#854]
Inspired by https://github.com/FakeItEasy/FakeItEasy/pull/840#issuecomment-246211238 and https://github.com/FakeItEasy/FakeItEasy/issues/806#issuecomment-239269257

`Invokes`, `DoesNothing`, and `AssignsOutAndRefParameters` (I'm omitting the `Lazily`s throughout, because I'm lazy. The reader may extrapolate.) only partially configure a method.

If a method has a return value, then none of these three will completely describe the configured method's behaviour. That is, where does the return value come from?

Currently, the return value is assigned via an internal undocumented rule behaviour (see #830). Where we return `null` (or a default value for a value-type). #830 would have us change this behaviour to return a Dummy, but the effect would be the same - an implicitly-assigned value.

Is this desirable? Should FakeItEasy
1. support clients by allowing them to partially configured a method and have FakeItEasy fill in the rest of the behaviour, or
2. require the specification of a return value (for methods known to be non-void)? (or exception to throw or redirection to the base method in any case, since I think `Invokes` could be useful in either of these situations as well)

To complicate matters, currently `AssignsOutAndRefParameters` cannot be specified on a method that's known not to be void without first specifying `Returns`. `Invokes` and `DoesNothing` have no such restrictions, so it seems like we're partially down the "force users to fill in all the blanks" road.

I'm torn between the options.
- @thomaslevesque noted that people may still expect a strict fake to throw when one method is configured with `Invokes` (although it doesn't now). From that perspective, forcing a return/throw/callsbasemethod will make things more explicit and reduce the confusion.
- On the other hand, forbidding `Invokes` unless returns/etc. has been specified will likely break users' tests, and may irritate them if they don't actually care what the return value is and they're just relying on the side effect.

At first I was strongly in the "drive clients toward fully specifying the result they want", but the more I think about it, the more I feel like that's counter to the FakeItEasy way, where we give reasonable default behaviours (for some interpretation of "reasonable") and let the clients override. 
Had I to recommend a path right now, I think I'd go for the looser approach, where FakeItEasy supplies a return value that could be overridden.

Thoughts?

**Comment by thomaslevesque** [comment]
Thanks @blairconrad for formalizing our discussion on this topic.

> Had I to recommend a path right now, I think I'd go for the looser approach, where FakeItEasy supplies a return value that could be overridden.

I tend to agree, except perhaps in the case of strict fakes, where returning an implicit default value goes against the idea of strictness.

**Comment by blairconrad** [comment]
It's strict _until you say otherwise_. I think adding an `Invokes` (or anything) is saying otherwise.
If you're creating a fake whose whole goal is to not be called, then defining behaviour on (a method of) the fake surrenders that position, no?

**Comment by thomaslevesque** [comment]
> It's strict until you say otherwise. I think adding an Invokes (or anything) is saying otherwise.
> If you're creating a fake whose whole goal is to not be called, then defining behaviour on (a method of) the fake surrenders that position, no?

Fair point!

**Comment by blairconrad** [comment]
I'm back. I think it's fair to say that we want to provide a reasonable default behaviour for users.
To this end we implemented #830, where all return values are Dummies until configured otherwise, even if there's an intervening `Invokes`, `DoesNothing`, or `AssignsOutAndRefParameters`.
This is nice and consistent and, I believe, give users a good experience. It lightens their load, and provides consistent behaviour.

And `DoesNothing` now cannot be specified on a member that we know not to be void.

The only wrinkle remaining is that when a non-void member is configured via `A.CallTo(Expression<T>)`, we disallow `AssignsOutAndRefParameters` until a `Returns` has been specified. Is this overly restrictive? I expect in many cases users will want to specify the return value, but what if they don't? Perhaps they like using `TryGet` methods and then just seeing if the found object is `null` or not .
Should we relax this restriction in order to make things a little more convenient for these users? Then they could call `AssignsOutAndRefParameters`  on a non-void member and keep the default (Dummy) return value.

If not, then I think there's nothing else to here.

**Comment by thomaslevesque** [comment]
> Should we relax this restriction in order to make things a little more convenient for these users? Then they could call AssignsOutAndRefParameters on a non-void member and keep the default (Dummy) return value.

If we can, let's do it 👍

**Comment by blairconrad** [comment]
With #1134 closed, I think we're done here. Thanks, @thomaslevesque.
