### ISSUE TITLE
Make our AppVeyor nupkg feed the blessed one for the netstd pre-releases

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#857]
It's a better source than @jeremymeng's AppVeyor feed. Not that we don't appreciate him setting that up!

Currently we're pushing both the "regular" and netstd nupkgs to the AppVeyor feed.
We could (optionally) stop pushing the "regular" one, and tell people to go to the AppVeyor feed when they want the netstd packages.

(If we leave the "regular" ones in the feed, then we have some complicated versioning issues to deal with, I think, making sure that people don't pick up the wrong package.)

**Comment by jeremymeng** [comment]
What's the url of your appveyor feed?  I'd be happy to retire mine.

**Comment by blairconrad** [comment]
@jeremymeng it'd be https://ci.appveyor.com/nuget/fakeiteasy.

Do you mind keeping yours around for a bit, though? It's the only one published so far.

**Comment by blairconrad** [comment]
From the description:

> Currently we're pushing both the "regular" and netstd nupkgs to the AppVeyor feed.

This is a complete lie. We're pushing the netstd nupkg (FakeItEasy and Analzyer).

I think we could publicize https://ci.appveyor.com/nuget/fakeiteasy immediately.

**Comment by blairconrad** [comment]
So yeah, I guess this comes down to just deciding that the appveyor feed is our source for .NET Standard goodness. And maybe add a bit of text in the README or something.
Objections?

**Comment by thomaslevesque** [comment]
> Objections?

None from me!

**Comment by blairconrad** [comment]
Closing in favour of #861. Sorry for the confusion.
