### ISSUE TITLE
Make our AppVeyor nupkg feed the blessed one for the netstd pre-releases

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#861]
(Replaces #857, which I'd added a lot of confusion to by being wrong about how AppVeyor's NuGet feeds work.)

----

It's a better source than @jeremymeng's AppVeyor feed. Not that we don't appreciate him setting that up!

The AppVeyor feeds's URL is 

https://ci.appveyor.com/nuget/FakeItEasy

The only snag is that the feed contains some older builds, before we worked out our versioning scheme. These builds look like full versions of FakeItEasy 2.3.0 (which has not been released yet) and obscure the -netstd pre-releases. We should probably not make the switch until we've released a full 2.3.0, at which point the -netstd packages will start having 2.4.0 pre-release versions.

**Comment by blairconrad** [comment]
There seems to be no way to remove old builds from AppVeyor feeds.
I could remove and recreate the project, if nobody minds.
Since most of our settings are in the appveyor.yml, this shouldn't be too hard.

**Comment by thomaslevesque** [comment]
> Since most of our settings are in the appveyor.yml, this shouldn't be too hard.

most? What isn't in it?

**Comment by thomaslevesque** [comment]
> There seems to be no way to remove old builds from AppVeyor feeds.

How about [this](https://ci.appveyor.com/nuget)?

> Delete package command
> ```
> nuget delete <package id> <package version> -ApiKey 6kp3n2a6qm51akkg6v71c468 -Source https://ci.appveyor.com/nuget/FakeItEasy-account/api/v2/package
> ```

**Comment by blairconrad** [comment]
There are some project-level settings that we have to recreate. Such as:

* Project Name
* GitHub repo
* Default branch
* skipping branches without `appveyor.yml` (which is not much of an issue at this point, but was when we first made the project)

I don't see how any of those could be defined in the appveyor.yml. But they're probably easy to get right!

Also

* `VERSION_SUFFIX` environment variable. Again, easy to do.
* maybe the build version image (VS2015). Not sure about this. Again, not hard.

That's probably it.

**Comment by blairconrad** [comment]
Oh, and the web hooks. I think @adamralph did a thing to make the AppVeyor build required.

**Comment by blairconrad** [comment]
> How about [this](https://ci.appveyor.com/nuget)?

That specifies account feed. We could try it on the project feed, I suppose.

**Comment by blairconrad** [comment]
It didn't work.

Althought http://help.appveyor.com/discussions/problems/5154-i-cant-remove-nuget-package-from-project-feed
gives me hope that you may be onto something.

**Comment by blairconrad** [comment]
Okay. I deleted the things from the account!

```powershell
> nuget delete FakeItEasy 2.3.0 -ApiKey XXXX -Source https://ci.appveyor.com/nuget/FakeItEasy-account/api/v2/package
WARNING: Deleting FakeItEasy 2.3.0 from the 'https://ci.appveyor.com/nuget/FakeItEasy-account/api/v2/package'.
  DELETE https://ci.appveyor.com/nuget/FakeItEasy-account/api/v2/package/FakeItEasy/2.3.0
  OK https://ci.appveyor.com/nuget/FakeItEasy-account/api/v2/package/FakeItEasy/2.3.0 980ms
FakeItEasy 2.3.0 was deleted successfully.
> nuget delete FakeItEasy.Analyzer 2.3.0 -ApiKey XXXX -Source
 https://ci.appveyor.com/nuget/FakeItEasy-account/api/v2/package
WARNING: Deleting FakeItEasy.Analyzer 2.3.0 from the 'https://ci.appveyor.com/nuget/FakeItEasy-account/api/v2/package'.
  DELETE https://ci.appveyor.com/nuget/FakeItEasy-account/api/v2/package/FakeItEasy.Analyzer/2.3.0
  OK https://ci.appveyor.com/nuget/FakeItEasy-account/api/v2/package/FakeItEasy.Analyzer/2.3.0 909ms
FakeItEasy.Analyzer 2.3.0 was deleted successfully.
```

However

```powershell
> nuget.exe list FakeItEasy -Prerelease -Source https://ci.appveyor.com/nuget/FakeItEasy -AllVersions
FakeItEasy 2.3.0
FakeItEasy 2.3.0-netstd
FakeItEasy.Analyzer 2.3.0
FakeItEasy.Analyzer 2.3.0-netstd
```

**Comment by thomaslevesque** [comment]
So they're deleted, but still listed?

**Comment by blairconrad** [comment]
Deleted from the account feed, but not from the project feed!
And the project feed is the public one.

**Comment by blairconrad** [comment]
I'd submit a PR, but I don't think that's a thing.

**Comment by thomaslevesque** [comment]
I'm probably missing something... how do you access the account feed?

**Comment by blairconrad** [comment]
You don't! It's a secret!

At least that's what I've been able to puzzle out.
That aborted PR I sent... #860?
The "account" toggle in there adds the account feed _to your AppVeyor build_. Which works because it's inside the authenticationwall, I assume.

But it's not for use from the outside of the account's projects.

Or I'm wrong about all this, as I'm kind of piecing it together from various articles and the things that didn't work and the logs of that stuck build.

**Comment by blairconrad** [comment]
As an experiment, I added a _second_ project, copying the few settings I thought I'd have to.
Now:

```powershell
.\.nuget\nuget.exe list FakeItEasy -Source https://ci.appveyor.com/nuget/fakeiteasy-rlv6e9nq02rw -AllVersions -Prerelease
FakeItEasy 2.3.0-netstd
FakeItEasy.Analyzer 2.3.0-netstd
```

If we like it (I do), we could:

* remove the [old project](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy)
* rename the [new project](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy-au76p)
* set the preferred NuGet project URL, and
* make the check required

And then we'd be ripe to point people at the feed.

**Comment by thomaslevesque** [comment]
> If we like it (I do), we could:
> 
> - remove the old project
> - rename the new project
> - set the preferred NuGet project URL, and
> - make the check required
> 
> And then we'd be ripe to point people at the feed.

:+1:

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque. Commencing.

**Comment by adamralph** [comment]
Is this done?

**Comment by blairconrad** [comment]
@adamralph, between us I think we've done everything.

There's only one project left, we have a good NuGet URL, and the check is required:
![image](https://cloud.githubusercontent.com/assets/3275797/19020122/9c1a7a14-886d-11e6-9d9a-d92093247267.png)

Closing. Thanks for the reminder!
