### ISSUE TITLE
Make IStartConfiguration<T> internal

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#864]
This is the unnatural fake equivalent of `IFakeConfigurationManager` (which is internal). I don't think there's ever been any good reason to make it public.

There are 2 classes that implement it:
- `Fake<T>` (but its members are never called through the interface)
- `StartConfiguration<T>`, which members are called from `Fake<T>`

For consistency with `IFakeConfigurationManager`, it should probably be hidden from the public API.

**Comment by blairconrad** [comment]
Agreed, @thomaslevesque. Nice find.

While looking at this, I notice that there's a convenience method `CustomArgumentConstraints.Fakes` that's used in some `Fake<T>` unit tests. I can't imagine this being useful to anyone writing tests (except possibly tests of FakeItEasy). What do you think of removing/hiding it?

**Comment by blairconrad** [comment]
Truth be told, I'm not entirely sure why `StartConfiguration` is a separate class. It could be folded right into `Fake<T>`, IMO.

**Comment by thomaslevesque** [comment]
> Truth be told, I'm not entirely sure why StartConfiguration is a separate class.

Probably for the same reason `FakeConfigurationManager` is separate from `A`.

> It could be folded right into Fake<T>, IMO.

I guess it could, but it would become inconsistent with `A` (not sure how much it matters)

**Comment by blairconrad** [comment]
Good point about the inconsistency. And even if we wanted to fold it, we could do it later with impunity. Just an idle thought. Thanks!

**Comment by blairconrad** [comment]
This issue has been released in FakeItEasy 3.0.0:
https://github.com/FakeItEasy/FakeItEasy/releases/3.0.0
