### ISSUE TITLE
Have AppVeyor run the approve task

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#868]
From https://github.com/FakeItEasy/FakeItEasy/pull/866#issuecomment-249143589.

We should have an automated test to ensure that we don't accidentally change the API of the .NET Standard version of FakeItEasy.

We could either amend the current project to also run the `approve` task, or add a second project similar to what we'd done for TeamCity.
I think we added a second build configuration to TeamCity so that it could fail and not freak out the users when a mandatory check failed on their PR.
I could go either way.

**Comment by thomaslevesque** [comment]
> add a second project similar to what we'd done for TeamCity.

Sounds like a good plan 👍
