### ISSUE TITLE
Unintended consequences from implicitly implemented interfaces

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#876]
In 2.3.0 we resolved #477, which means that class fakes now implement the interfaces of the base class. It was supposed to be a non-breaking enhancement, but it turned out to be a breaking change:

FakeItEasy 2.2.0:
```c#
List<int> list = A.Fake<List<int>>();
list.Add(1);
list.Count.Dump(); // 1
((ICollection<int>)list).Count.Dump(); // 1
```

FakeItEasy 2.3.0:
```c#
List<int> list = A.Fake<List<int>>();
list.Add(1);
list.Count.Dump(); // 1
((ICollection<int>)list).Count.Dump(); // 0, oops!
```

Basically, what happened is this:
- `List<int>` implicitly implements `ICollection<int>`; we used to inherit that implementation
- the changes made for #477 mean that we now create the fake as if `o => o.Implements<ICollection<int>>()` was passed in the creation options
- by doing this, we introduce a new, separate implementation of `ICollection<int>`, which is not configured and returns default values

So, it's clearly a breaking change; whether it's a good or a bad change is debatable (Moq does the same as FIE 2.3.0, NSub and RhinoMocks do the same as FIE 2.2.0), but anyway, it wasn't our intention when we addressed #477.

We used to be able to chose between 2 behaviors:
- one where the interface members were implemented by the base class. `list.Count` was always the same, whether it was called via `List<int>` or via `ICollection<int>`. It was less flexible (`Count` couldn't be configured), but it was simple to understand. It was the default behavior.
- one where the members of interfaces of the faked class are now independent of the base class implementation. It's more flexible, but also more complex and difficult to understand. This behavior was enabled by doing `o => o.Implements<ICollection<int>>()`, but is now the default behavior (for *all* interfaces of the faked class)

Now we can only have the second behavior.

So, should we revert, or keep the new behavior?

(in case it's not obvious, I'm in favor of reverting)

**Comment by thomaslevesque** [comment]
In other words, the new behavior is equivalent to doing this:

```
class MyFakeList : List<int>, IList<int>, ICollection<int>, IEnumerable<int>
{
    // Explicitly reimplement *all* interface members of the base class
    int ICollection<int>.Count => 42;
    IEnumerator<int>IEnumerable<int>.GetEnumerator() => new MyFakeEnumerator();
    ...
}
```

**Comment by blairconrad** [comment]
Very well explained, @thomaslevesque.
I hate to flip-flop, and I think the original intent of #477 can still provide value, but the unintended change is a bug, and I've come to believe as you do—that it should be reverted.
I think we should release 2.3.1, reverting the change.

As you say, people who do need their fakes to implement all interfaces still have the option of explicitly configuring them to do so, and restoring the old behaviour gives us the time to re-evaluate and see if we can help those users out, perhaps via a convenience operator on `IFakeOptions`, not unlike `CallsBaseMethod`.

@adamralph, what say you?

**Comment by thomaslevesque** [comment]
I guess the new behavior *could* be considered to make sense, if we configured each explicit interface implementation to call the base class implementation by default. So I made a few tests, and noticed something strange. If we do this:

```
A.CallTo(() => ((ICollection<int>)list).Count).CallsBaseMethod();
```

Then `((ICollection<int>)list).Count` returns the same value as `list.Count`, as expected.

**But** if we just create the fake with `o => o.CallsBaseMethods()` and don't configure the property, then it has no effect and `((ICollection<int>)list).Count` returns 0... This might be a bug.

**Comment by blairconrad** [comment]
> **But** if we just create the fake with `o => o.CallsBaseMethods()` and don't configure the property, then it has no effect and `((ICollection<int>)list).Count` returns 0... This might be a bug.

Had I to guess, I'd think it might be #463.

**Comment by adamralph** [comment]
Neither path is particularly attractive but I think the safer option is to revert, release 2.3.1, with the removal of #477 in the release notes, re-open #477 with no milestone and re-assess it.

**Comment by thomaslevesque** [comment]
Thanks @adamralph

Since we all agree, let's revert.
