### ISSUE TITLE
weakness in next_version rake task

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#883]
The `next_version` rake task doesn't work because of the ruby SSL bug.
Previously we'd worked around that by having the rakefile download a PEM file from http://curl.haxx.se/ca/cacert.pem unless the `SSL_CERT_FILE` environment variable was set.
Unfortunately, that URL now redirects to HTTPS, so the approach no longer works.
I've just cached a version of the PEM and permanently set my SSL_CERT_FILE environment variable. Which works fine, but is a manual step that any releaser has to perform.
So, I thought of a few alternatives, roughly sorted in my descending order of preference:

1. change the rakefile to output an error if SSL_CERT_FILE isn't set, telling users what to do. We keep talking about dropping rake. If we do that soon, we can choose another alternative.
2. do nothing for now. This is sort of like point 1, with similar reasoning, but is not quite as friendly to infrequent users of the task
3. use a different approach to creating new PRs and milestones and whatnot. We could rely on one of the other octokit flavours (although I think picking anything other than .NET would be silly), which (hopefully) understand SSL. This may even become part of our new build system.
4. use a different approach to fetch the PEM, like a powershell script or some foolishness
5. drop the task altogether. I am not sure anyone but me is a fan. Although for the year or so where I did every release, I found it to be a godsend, since I think the version-setting, and milestone-, issue- and release-creating are extremely tedious and error-prone.

What would you @FakeItEasy/owners like?

**Comment by blairconrad** [comment]
**or** we could just commit the PEM and reference it if `SSL_CERT_FILE` isn't set.

**Comment by thomaslevesque** [comment]
> or we could just commit the PEM and reference it if SSL_CERT_FILE isn't set.

+1
We might need to update it manually every now and then, though

**Comment by blairconrad** [comment]
It's a danger. But mine's from... 2014?
