### ISSUE TITLE
Package links are neglecting the analyzer

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#886]
In both README.md and on https://fakeiteasy.github.io/ we link to https://www.nuget.org/packages/FakeItEasy which neglects the analyzer package. Perhaps we should create a "FakeItEasy" account on nuget.org, give it ownership of both packages, and then link to it's profile page instead, which would list both packages?

Alternatively, we could link to https://www.nuget.org/packages?q=fakeiteasy which happens to list our two packages at the top and also shows the rest of the community packages. I'd hope that our two packages would *always* come out on top, but I guess it *could* change.

Alternatively, we could link to each package directly, in two links.

Regardless of which solution we choose, the inclusion/addition of a link to https://www.nuget.org/packages?q=fakeiteasy might also be quite a nice way to promote the ecosystem.

**Comment by blairconrad** [comment]
Great observation, @adamralph. I agree; we should do something about this.

However, I don't favour linking to the search page as our "Package(s)" link, for a variety of reasons:

* as you point out, the order may change, pushing our packages lower (unlikely)
* packages may start matching that have nothing to do with FakeItEasy (unlikely)
* the link might be interpreted as claiming credit for others' fine packages
* or it could be interpreted as claiming responsibility for low-quality packages

I don't enjoy creating and maintaining extra accounts, but prefer the control that a dedicated NuGet account would afford.

As for promoting the ecosystem, that sounds like a fine idea as well. I'd be inclined to indicate that we're just mentioning the existence of the packages, without necessarily endorsing.
And I don't think we'd need a button on the web page. Something in text? Maybe in the docs or readme or other section of the landing page?

**Comment by thomaslevesque** [comment]
I also think that a dedicated NuGet account would be the best approach.

**Comment by adamralph** [comment]
@blairconrad all good points. OK, I'm happy to proceed with the NuGet account approach too. We can spin off the promotion of the ecosystem into a separate issue, if we have the appetite.

**Comment by blairconrad** [comment]
Creating an account now.

**Comment by blairconrad** [comment]
AHA!
[image](https://cloud.githubusercontent.com/assets/3275797/19023422/544726a2-88bc-11e6-9845-deea568e03d0.png)

**Comment by blairconrad** [comment]
Thanks, @adamralph.
