### ISSUE TITLE
.Net Standard pre-release package forces downgrade of System.Linq.Expressions

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#894]
As reported by @jchannon in https://twitter.com/jchannon/status/784307755305672704:

![image](https://cloud.githubusercontent.com/assets/3275797/19187399/40146a1e-8c59-11e6-815f-ef566b094122.png)

I see our [project.json](https://github.com/FakeItEasy/FakeItEasy/blob/c8e3b690920ec5003a6e41272d59ca01c2176b91/src/FakeItEasy.netstd/project.json) requires 4.1.0, but the [nuspec](https://github.com/FakeItEasy/FakeItEasy/blob/c8e3b690920ec5003a6e41272d59ca01c2176b91/src/FakeItEasy.netstd/FakeItEasy.nuspec) requires 4.0.11.

I think the .NET dependencies can be removed from the nuspec, but I can't find confirming documentation. Giving it a try.

**Comment by jchannon** [comment]
Im not sure how you guys are packaging your netstd package but you shouldnt need the nuspec file at all. The meta data can be contained in the project.json and dotnet pack can create the nupkg.

See here for example https://github.com/NancyFx/Nancy/blob/master/src/Nancy/project.json#L1-L11

**Comment by blairconrad** [comment]
@jchannon, we've kept the nuspecs. Partly from inertia (I think) and partly because we're still using it to build our vanilla package for .NET 4.0 support.

I'd wondered about setting versions, but if I read your Cake file right, you mutate the project.jsons to get the build versions, yes?

**Comment by jchannon** [comment]
Correct.

We get the version number, modify the json file, build and pack

**Comment by blairconrad** [comment]
as an aside, https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/33-sypfhiso/artifacts has an attempt at a fix.

**Comment by jchannon** [comment]
Same issue on 000032

**Comment by jchannon** [comment]
The weird issue is its downgrading from FIE 0000032 to 0000019 also

**Comment by jchannon** [comment]
Just to be clear that build 33 artifact didn't work.

Calling @jeremymeng to the rescue.... 😄

**Comment by jchannon** [comment]
OK after some testing, 33 does work!

**Comment by blairconrad** [comment]
Sorry, I was occupied. Yay!
Was the issue the downgrade to the old package?

As @thomaslevesque points out, we'll probably want to refine the approach a little bit and trim the dependencies.

**Comment by jchannon** [comment]
Yup my fault, you could possibly revert your project.json change?

I assume the fix was the nuspec change?

**Comment by blairconrad** [comment]
Yeah, reverting the project.json is probably the right move.
I'd feel bad saying that without testing more (felt a little bad getting you to take my completely untested "fix"). But if you're game…

**Comment by jchannon** [comment]
Yup go nuts... 😄

**Comment by blairconrad** [comment]
I reverted the project.json changes and 
https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/33-qxlegkfg/artifacts 
built.
