### ISSUE TITLE
Strict Fake with catchall arguments

### ISSUE THREAD

**Issue by SurajGupta** [FakeItEasy/FakeItEasy#897]
I'm attempting to create a Strict Fake that returns different values for various argument values, but if none of the arguments match I'd like a catchall so that `ExpectationException` is not thrown.  I would like `ExpectationException` thrown for the methods that have no configuration.

for example:

```
public interface ICanExercise
{
    string DoJumpingJacks(int minutes);
    string DoPushUps(int reps);
}

var person = A.Fake<ICanExercise>(_ => _.Strict());
A.CallTo(()=>person.DoJumpingJacks(1)).Returns("no sweat");
A.CallTo(()=>person.DoJumpingJacks(5)).Returns("heart is pumping");
A.CallTo(()=>person.DoJumpingJacks(A<int>._)).Returns("did something good today");
```

here's what I'm expecting based on the order in which I configured the fake:

```
person.DoJumpingJacks(5);  // "heart is pumping"
person.DoJumpingJacks(3);  // "did something good today"
person.DoPushUps(10); // throws ExpectationException
```

here's what actually happens:
```
person.DoJumpingJacks(5);  // "did something good today"
person.DoJumpingJacks(3);  // "did something good today"
person.DoPushUps(10); // throws ExpectationException
```

How do I use the catch-all as a last resort and not the default?

**Comment by thomaslevesque** [comment]
Fake call rules are "stacked", and each call is evaluated against each rule "from the top". The first rule that matches is used. So in your current code, calls are evaluated against the catch-all rule first, which always matches, and the other rules are not even considered.

If you put the catch-all rule first, it should work as you expect.

**Comment by blairconrad** [comment]
@SurajGupta, @thomaslevesque's explanation is absolutely correct, of course. But if you're looking for a little more information about this, check out [Changing behavior between calls](http://fakeiteasy.readthedocs.io/en/stable/limited-call-specifications/#changing-behavior-between-calls) in the docs.

**Comment by SurajGupta** [comment]
@thomaslevesque @blairconrad - thanks for the quick reply and pointer to docs!
