### ISSUE TITLE
Replace IFakeOptionsForWrappers with IFakeOptions in .NET Standard build

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#914]
From https://github.com/FakeItEasy/FakeItEasy/issues/820#issuecomment-261774982:

> I notice that we expose `IFakeOptionsForWrappers` and `IFakeOptionsForWrappers<T>` in the netstd build, and they only expose `RecordedBy`.
> Shall we replace them with `IFakeOptions` (`<T>`) for the netstd build? If we'd remove it once we remove Self-Initializing Fakes, I think it makes sense to make the change now.

Everyone else thought it made sense too!

**Comment by adamralph** [comment]
Do we need a separate issue for this? For me it feels like part of #531

**Comment by adamralph** [comment]
Ah, I guess you want to easily form release notes for the next pre-release. In that case, should we use the 3.0.0-pre milestone? IIRC this exactly the type of case it was designed for.

**Comment by blairconrad** [comment]
Yes, good point. Changing milestone.
