### ISSUE TITLE
Request to add Dummy(Type type) convenience method to A

### ISSUE THREAD

**Issue by SurajGupta** [FakeItEasy/FakeItEasy#942]
Wondering if we could add this method to static class `A` for convenience:
`public static object Dummy(Type type)`

**Comment by thomaslevesque** [comment]
It's already there, but not in `A`:

    object FakeItEasy.Sdk.Create.Dummy(Type typeOfDummy)

**Comment by SurajGupta** [comment]
thanks!  I think it would be more discoverable in `A`, but also realize that you probably don't want to inflate that class too much.

**Comment by blairconrad** [comment]
Sounds like this has been resolved. Closing.
Thanks for your interest in FakeItEasy, @SurajGupta!
