### ISSUE TITLE
Hide object members on fluent API interfaces

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#944]
A number of types don't hide object members. Here are the public non-static types that don't:

* FakeItEasy.ArgumentValueFormatter`1[T]
* FakeItEasy.Configuration.ArgumentCollection
* FakeItEasy.Configuration.FakeConfigurationException
* FakeItEasy.Configuration.IDoNothingConfiguration`1[TInterface]
* FakeItEasy.Configuration.IOutAndRefParametersConfiguration`1[TInterface]
* FakeItEasy.Configuration.IRepeatSpecification
* FakeItEasy.Core.FakeCreationException
* FakeItEasy.Core.FakeManager
* FakeItEasy.Core.ICompletedFakeObjectCall
* FakeItEasy.Core.IFakeObjectCall
* FakeItEasy.Core.IFakeObjectCallRule
* FakeItEasy.Core.IInterceptedFakeObjectCall
* FakeItEasy.Core.IInterceptionListener
* FakeItEasy.Core.Raise`1[TEventArgs]
* FakeItEasy.Creation.ITaggable
* FakeItEasy.DefaultBootstrapper
* FakeItEasy.DummyFactory`1[T]
* FakeItEasy.ExpectationException
* FakeItEasy.FakeAttribute
* FakeItEasy.FakeOptionsBuilder`1[TFake]
* FakeItEasy.IArgumentValueFormatter
* FakeItEasy.IBootstrapper
* FakeItEasy.IDummyFactory
* FakeItEasy.IFakeOptionsBuilder
* FakeItEasy.IHideObjectMembers
* FakeItEasy.IOutputWriter
* FakeItEasy.Priority
* FakeItEasy.Repeated
* FakeItEasy.SelfInitializedFakes.CallData
* FakeItEasy.SelfInitializedFakes.ICallStorage
* FakeItEasy.SelfInitializedFakes.ISelfInitializingFakeRecorder
* FakeItEasy.SelfInitializedFakes.RecordingException
* FakeItEasy.SelfInitializedFakes.RecordingManager
* FakeItEasy.UnderTestAttribute
* FakeItEasy.Configuration.IWhereConfiguration`1[TInterface]

It's arguable that none of these _need_ to expose the `object` members, but it's probably not harmful for most of them. The ones that define in the fluent API should hide object  members.

I'd like to update a number of types before we release 3.0. And I think we should add an automated test to ensure that we don't accidentally forget to hide the object members on new types. I'd probably put this in the Approval test project, but am happy to go along with ideas for another location.

I think a whitelist of types that don't need to implement `IHideObjectMembers` is safest, so I'd put a list of exceptions in the test, and we'd filter candidate types against it.
Assuming everyone's on board, do you have any opinions on whether we apply the test to:

* exported non-static types,
* exported interfaces (because I think any of the types we have to worry about are actually exposed as interfaces), or
* exported interfaces whose name ends in "Configuration" or "Specification" (I think all the fluent API members meet this restriction)

**Comment by thomaslevesque** [comment]
I think most of those types shouldn't hide object members. The only ones I see that should are in the `FakeItEasy.Configuration` namespace.

IMO there's no reliable way to automatically identify types should have `IHideObjectMembers` just based on their names; we should probably list them explicitly.

**Comment by blairconrad** [comment]
Ah, yes. `FakeItEasy.Configuration`. That's probably better than any of my 3 options.

> IMO there's no reliable way to automatically identify types should have IHideObjectMembers just based on their names; we should probably list them explicitly.

As the classes are today, restricting to `(*Specification or *Configuration)` yields the same correct (IMO) results as restricting to the `FakeItEasy.Configuration` namespace:

* FakeItEasy.Configuration.IDoNothingConfiguration`1[TInterface]
* FakeItEasy.Configuration.IOutAndRefParametersConfiguration`1[TInterface]
* FakeItEasy.Configuration.IRepeatSpecification
* FakeItEasy.Configuration.IWhereConfiguration`1[TInterface]

I think checking the namespace would work.
But if I've not convinced you, I don't think there's enough benefit in adding a test; the idea is to prompt us when we'd forget to extend the interface, so if we have to add types to the list explicitly, we're only preventing (very unlikely, IMO) regressions.

**Comment by blairconrad** [comment]
Update! In the previous comment, the filter was only looking at interfaces!

**Comment by thomaslevesque** [comment]
In fact, `FakeItEasy.Configuration` doesn't cover everything. There's also `FakeItEasy.Creation.IFakeOptions` (`<T>`), `FakeItEasy.IArgumentConstraintManager<T>`, `FakeItEasy.IOutputWriter` and maybe a few others.

Maybe we could just manually mark types that are part of the fluent API with a custom attribute, and have a test that checks that those types implement `IHideObjectMembers`. But then, if we can think of adding the attribute, we can also think of adding the interface... In the end, I think the only effective way is to pay attention to those things when we introduce new types to the fluent API.

**Comment by blairconrad** [comment]
Good find for the other interfaces. Fortunately, they've already been covered.
I think that most activity around the API changes will live in `FakeItEasyConfiguration` in the future; it does seem to be the place where we miss the most types. Searching that namespace would provide an additional safety net, as would including all exposed interfaces in the solution (this just means a bigger whitelist).
But that's okay, I'll drop it in favour of "constant vigilance". 

At least you're not against adding `IHideObjectMembers` to the 4 interfaces that lack it. I'll work on that.

**Comment by thomaslevesque** [comment]
> At least you're not against adding IHideObjectMembers to the 4 interfaces that lack it. I'll work on that.

I'm definitely not against it. And `IOutputWriter` too, which doesn't have it.

**Comment by blairconrad** [comment]
> At least you're not against adding IHideObjectMembers to the 4 interfaces that lack it.

On rereading that, I come off like a huge jerk, who's bitter about the "test" discussion.
I am a jerk, but am not bitter about the discussion.
Apologies, @thomaslevesque!

> And `IOutputWriter` too

:+1+: Thanks.

**Comment by thomaslevesque** [comment]
> On rereading that, I come off like a huge jerk, who's bitter about the "test" discussion.

Not at all

**Comment by blairconrad** [comment]
what do you think about `IFakeObjectCall`?

**Comment by blairconrad** [comment]
Hmmm. Perhaps not. We return those from `Fake.GetCalls` and so on.

**Comment by thomaslevesque** [comment]
> what do you think about `IFakeObjectCall`?

It's not a fluent interface, so I don't see any reason to hide object members.

**Comment by blairconrad** [comment]
This issue has been released in FakeItEasy 3.0.0:
https://github.com/FakeItEasy/FakeItEasy/releases/3.0.0
