### ISSUE TITLE
Add an analyzer that supports VB.NET

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#952]
As discussed in https://github.com/FakeItEasy/FakeItEasy/issues/951#issuecomment-267312413

Currently the analyzer only supports C#, we should add one for VB.NET. Hopefully we can share part of the code between the two analyzers.

**Comment by thomaslevesque** [comment]
I started to work on this. For now I just copied the C# analyzer and replaced "CSharp" with "VisualBasic" everywhere, and it's partially working.

It seems to be possible to write an analyzer that work for both C# and VB. Not sure if it's feasible in our case, but if it is, it would probably be the best approach. Otherwise, we'll probably need a Analyzer.Common project for shared code.

**Comment by thomaslevesque** [comment]
> and it's partially working.

OK, there was actually a minor thing to fix, now it works:

![screenshot](http://i.imgur.com/X7bDRtu.png)

(and the fix is actually compatible with the C# version, so good news so far)

**Comment by blairconrad** [comment]
That's tremendous, @thomaslevesque!

**Comment by thomaslevesque** [comment]
So, it's pretty easy to make `UnusedReturnValueAnalyzer` work for both C# and VB, but it's a bit ugly. Some of the code has to be duplicated, because the types to use are different (for instance, `Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax` and `Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax` are completely different types), so I have to use aliases or fully qualified names to disambiguate. The cleanest approach would probably be to have some shared code with `#if`s in the `using` clauses.

**Comment by blairconrad** [comment]
This issue has been released in FakeItEasy 3.0.0:
https://github.com/FakeItEasy/FakeItEasy/releases/3.0.0
