### ISSUE TITLE
Remove IStartConfiguration<T> from Fake<T>'s interfaces

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#959]
Relates to #864

There's absolutely no reason for `Fake<T>` to implement `IStartConfiguration<T>`. This interface is now internal anyway, and the members of `Fake<T>` are never called via the interface.

Technically, it's not a breaking change, but there's a bug the version of `PublicApiGenerator` that we use, which causes `IStartConfiguration<T>` to appear in `Fake<T>`'s implemented interfaces, even though it's internal, so it will change the approved API file. We should probably upgrade to a more recent version of PublicApiGenerator anyway.

**Comment by blairconrad** [comment]
Based on the confusing state of source nuget packages ([quoting](https://gitter.im/FakeItEasy?at=58e344d7b52518ed4dd94f65) @adamralph:

> source packages are in a mess right now
> in the old world of project.json, the contentFiles element works as designed. The source files are not copied into the project. They are transformed from the packages folder into the obj folder at build time, and > compiled into the assembly in bin from there
> in the old old world of VS2015 csproj, the content folder works as designed. The source files are copied into the project and are not restored during package restore, so the idea is that you commit them, as regular > source files
> in the new world of VS2017 csproj, they are basically broken. See NuGet/Home#4803

) and my difficulty using them anyhow (I couldn't compile the PublicApiGenerator source file once included in FIE; probably something dumb I'm (not) doing), I propose keeping our version of PublicApiGenerator for now.

**Comment by thomaslevesque** [comment]
> I propose keeping our version of PublicApiGenerator for now.

Fine by me. We can always upgrade later.

**Comment by blairconrad** [comment]
This issue was fixed in [Release 3.2.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.2.0).
