### ISSUE TITLE
Default behavior of read/write properties should not override explicit getter or setter configuration

### ISSUE THREAD

**Issue by thomaslevesque** [FakeItEasy/FakeItEasy#962]
(Spawned from a [discussion on the chat](https://gitter.im/FakeItEasy?at=586a3b787a3f79ef5dc86a23))

I recently noticed a surprising behavior for faked read/write properties. [As documented](http://fakeiteasy.readthedocs.io/en/stable/read-write-property-behavior/), setting the value of an unconfigured property configures it to return the assigned value. But when you do that, **it also overrides any configuration made on the setter**. The same is true when you read an unconfigured property.

Neither of these code snippets throw an exception:
```csharp
    var foo = A.Fake<IFoo>();
    A.CallToSet(() => foo.Bar).To(() => A<int>.That.Not.IsEqualTo(42)).Throws(new Exception("wrong answer"));
    foo.Bar = 42; // previously configured behavior is overridden here
    foo.Bar.Dump();
    foo.Bar = 123; // should throw here, but doesn't
    foo.Bar.Dump();
```
```csharp
    var foo = A.Fake<IFoo>();
    A.CallToSet(() => foo.Bar).To(() => A<int>.That.Not.IsEqualTo(42)).Throws(new Exception("wrong answer"));
    foo.Bar.Dump(); // previously configured behavior is overridden here
    foo.Bar = 123; // should throw here, but doesn't
    foo.Bar.Dump();
```

We should probably consider changing this behavior, as it is counter-intuitive.

**Comment by thomaslevesque** [comment]
This issue is caused by the current implementation of the default call rules for properties, which is described in [this gist](https://gist.github.com/thomaslevesque/f75fa12b3abc402ae4a24c665eaa6307).

A proposed solution is to change these rules as follows:
1. `PropertyBehaviorRule` no longer applies to property setters, but only to getters
2. `PropertySetterRule` will still add a `PropertyBehaviorRule`, but only if none exists for the setter being processed. If a rule already exists, its value will be updated, and it will be moved to the top

The second point is only to avoid creating more rules than necessary.

PR #961 implements these changes. No tests are broken, and the code snippets in the previous message now work as expected.

**Comment by thomaslevesque** [comment]
I mark the issue as breaking because it's an observable behavior change, but it's unlikely that people rely on the current behavior. In fact, it could be argued that the current behavior is a bug, in which case this change would merely fix it.

**Comment by blairconrad** [comment]
@thomaslevesque, I know we ended our chat today with me being on board, but as I continue to think about it, I'm still concerned about some of the corner cases. Sorry to waffle on this.

I agree that in the two examples you have above, we should throw. The thing I'm worried about is what the behaviour should be in this sort of situation:

```c#
var foo = A.Fake<IFoo>();
A.CallTo(() => foo.Bar).Throws(new Exception("wrong question"));
foo.Bar = 42;
foo.Bar.Dump();
```

Under the proposed solution, this would not throw, and I still think the last line should. Saying that it's an error for the `Bar` getter to be called shouldn't be affected by someone (e.g. production code) subsequently invoking the setter.

I think a case can be made for the behaviour I like (and also for the last line to dump `42`, as I think you think it should).
I have an implementation in mind that supports my preferred behaviour, but let's leave implementations out for now. I think they make the conversation more difficult and remove us from the users' experience.

Here's how I think of the situation. Perhaps users think this way, and perhaps not, but it's a way to model a Fake object.

When created, a Fake has certain built-in behaviours:
* Unconfigured non-void methods will return a Dummy when invoked. (Not controversial now, but it's one fundamental behaviour of a new Fake.)
* Unconfigured property setters will, when called, store the passed-in value to be returned whenever their unconfigured getter is subsequently called.
* Unconfigured property getters whose setter has never been called (assuming they have one) will return the same value whenever invoked (A Dummy.)

If this is our model (and I realize that it may not be the one everyone shares), then invoking a property's setter only has an effect on the getter if the getter is unconfigured. Once the getter is explicitly configured, it retains its configured behaviour, be it returning a value, throwing an exception, calling the base, whatever. Only when the setter and getter are unconfigured does the setter influence the getter.
(If the properties are indexers, then the indexes have to match to have their effects felt, of course.)
This is consistent with the examples at the very top of this issue.

The alternative behaviour is that "invoking a property setter causes the property getter to return the set-in value" always. It is easy to explain, but I think it reduces the flexibility of the Fakes (or at least would require the user to jump through hoops to preserve getter behaviour in the face of production code that invokes the setter). And I think it looks weird for an explicitly-configured getter to be  overridden by a call to the setter.

**Comment by thomaslevesque** [comment]
> (and also for the last line to dump 42, as I think you think it should).

I don't necessarily think it should do that. You make a pretty convincing argument. Especially the fact that the production code can set the property and thus override the configured getter behavior is a real issue.

On the other hand... I just asked two of my colleagues what they would expect your code snippet to do, and both answered "dump 42".

So, should we pick the more intuitive behavior, or the more flexible one? I'm leaning towards flexibility, as you suggest. However it means that the "assign the setter to configure the getter" approach to configuring properties will now work only some of the time...

**Comment by blairconrad** [comment]
> I just asked two of my colleagues what they would expect your code snippet to do

A very good idea! Now I'm more torn than I was before.

Unfortunately, in my head it's still "properties on Fakes will act like field-backed properties (with a default Dummy value) until someone configures them".

This is a real problem if that explanation only exists in _my_ head.

**Comment by thomaslevesque** [comment]
OK, I tried to implement the behavior you suggest. Now we have [one failing test](https://github.com/FakeItEasy/FakeItEasy/blob/fdeb2b1f8a9e0dd363233befa97ff5fa9985722f/tests/FakeItEasy.Tests/Core/FakeManagerTests.cs#L207-L223), which was testing specifically the behavior that has changed.

To match the new behavior, this test could be rewritten like this:

```csharp
        [Fact]
        public void Object_properties_dont_have_property_behavior_when_explicitly_configured()
        {
            var foo = A.Fake<IFoo>();

            A.CallTo(() => foo.SomeProperty).Returns(2);
            foo.SomeProperty.Should().Be(2);

            foo.SomeProperty = 5;
            foo.SomeProperty.Should().Be(2);

            A.CallTo(() => foo.SomeProperty).Returns(20);
            foo.SomeProperty.Should().Be(20);

            foo.SomeProperty = 10;
            foo.SomeProperty.Should().Be(20);
        }
```

It does seems a little strange that setting `SomeProperty` now has no effect. Actually, it *does* have an effect, but this effect is not visible while the explicit `CallTo` configuration applies. So the following test passes:

```
        [Fact]
        public void Object_properties_dont_have_property_behavior_when_explicitly_configured()
        {
            var foo = A.Fake<IFoo>();

            A.CallTo(() => foo.SomeProperty).Returns(2).Twice();
            foo.SomeProperty.Should().Be(2);

            foo.SomeProperty = 5;
            foo.SomeProperty.Should().Be(2);
            foo.SomeProperty.Should().Be(5);

            A.CallTo(() => foo.SomeProperty).Returns(20).Once();
            foo.SomeProperty.Should().Be(20);

            foo.SomeProperty = 10;
            foo.SomeProperty.Should().Be(10);
        }
```

I wonder if it's not even more confusing than before...

**Comment by blairconrad** [comment]
Very interesting examples, @thomaslevesque, and that last one _is_ confusing!

You're too fast for me. Before your insight, I had been on the verge of pointing out that my example isn't realistic. Nobody's going to write

```c#
var foo = A.Fake<IFoo>();
A.CallTo(() => foo.Bar).Throws(new Exception("wrong question"));
foo.Bar = 42;
foo.Bar.Dump();
```

They're going to write

```c#
public class TestClass
{
   [Test]
   public void SomeTest()
   {
       var foo = A.Fake<IFoo>();
       A.CallTo(() => foo.Bar).Throws(new Exception("wrong question"));
   
       var target = new Target(foo);
       var result = target.ProductionMethod();
      
       result.Should().Be("bother");
   }
}

…

public class Target
{
    public void Target(IFoo foo)
    {
        this.foo = foo;
        foo.Bar = 17;
    }
    public string  ProductionMethod()
    {
         try
         { 
             DoSomethingWith(this.Foo);
             return "yay";
         }
         catch
         {
              return "bother";
         }
    }
}
```

This is the kind of confusion I was anticipating. "I said the getter should throw! What's going on?".

**Comment by blairconrad** [comment]
(Oh, I polled the guy in the next cube. Sadly, he had the same expectation I did!)

**Comment by thomaslevesque** [comment]
> This is the kind of confusion I was anticipating. "I said the getter should throw! What's going on?".

Yes, and that's why I think the latest behavior I tried makes sense. But it's (very) confusing...

**Comment by blairconrad** [comment]
> I think the latest behavior I tried makes sense. 

Just to be clear, does that mean the one you described in https://github.com/FakeItEasy/FakeItEasy/issues/962#issuecomment-270382936 ?

If so, I think it's the better choice overall. There some possibility of confusion, but I doubt we'll have a problem.

**Comment by thomaslevesque** [comment]
> Just to be clear, does that mean the one you described in #962 (comment) ?

Yes

**Comment by thomaslevesque** [comment]
I just pushed the latest changes (still work in progress, need to add some tests and documentation)

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque. I've not taken a close look yet (perhaps after volleyball). I'd imagined what I think is a less dramatic change - just putting the `PropertyBehaviorRule` in the post-user rules. With this change, all the tests pass, and all the examples above work like we discussed. For your consideration: https://github.com/blairconrad/FakeItEasy/commit/7e9222dea706a047b65ca5e19cbda1e9f84957af
Maybe I'm off-base.

**Comment by thomaslevesque** [comment]
> I'd imagined what I think is a less dramatic change - just putting the PropertyBehaviorRule in the post-user rules

I thought about it, but it *is* a user rule, and should be removed when `ClearUserRules` is called. It seemed more logical to put it at the end of the user rules.

**Comment by thomaslevesque** [comment]
> (Really, I'm not a fan of Fake.ClearConfiguration, but that's another story.)

I don't think I ever used it, but if it's there, it should work as expected.

**Comment by blairconrad** [comment]
Sure. I think things that are there should work as expected too.
But I'd rather people just throw away their Fakes when they don't like what they've done to them.

(And one _could_ take the stance that remembered property values arising from interacting with the properties aren't "configuration". But I'm not trying to take that stance.)

**Comment by thomaslevesque** [comment]
Hey @adamralph, I know you're busy, but I'd really like to have your insight on this if you can spare some time. I'll try to recap the current situation and what we would like to change, so that you don't need to read the whole discussion(s).

Basically, the idea is to make the default behavior of read/write properties apply only to properties that haven't been configured explicitly.

For instance, consider this code:
```
    var foo = A.Fake<IFoo>();
    A.CallTo(() => foo.Bar).Returns(42);
    foo.Bar = 123;
    Console.WriteLine(foo.Bar);
```

Currently it prints 123, because setting `foo.Bar` overrides the previous configuration. This is an issue, because the property could be set by production code, changing the behavior of the fake with no way for the test code to prevent it. It's also confusing: "Hey, I said it should return 42, why does it return 123?"

With the proposed change, the assignment to `foo.Bar` won't override the explicitly configured rule; it will still store the assigned value, but that value won't be returned while the explicit rule is active (which is forever, unless specified otherwise).

Another scenario that is currently confusing:

```
    var foo = A.Fake<IFoo>();
    A.CallToSet(() => foo.Bar).DoesNothing();
    Console.WriteLine(foo.Bar);
    foo.Bar = 123;
    Console.WriteLine(foo.Bar);
```

This currently prints 0, then 123, even though we configured the setter to do nothing. This is because the first call to the getter creates a default value (a dummy) and inserts a rule (`PropertyBehaviorRule`) that
- initially holds the dummy default value
- stores the assigned value when the setter is called
- returns the stored value when the getter is called

This new rule overrides the `A.CallToSet(() => foo.Bar).DoesNothing()`, which no longer applies. While the previous scenario could arguably be considered correct, this one looks more like a bug (reading a property shouldn't override the setter's behavior).

With the proposed change, the rule inserted by calling the getter will no longer override explicit rules (it's still added to the fake, but at the end of the user rules, so that any explicit rule will override it).

If the property is not configured explicitly, it will keep its current "natural" behavior.

If you want more details, [this document](https://gist.github.com/thomaslevesque/f75fa12b3abc402ae4a24c665eaa6307) describes the current situation in terms of the fake rules involved in the read/write property behavior.

@blairconrad, please let me know if you see a mistake in this summary.
@adamralph does that make sense to you?

**Comment by blairconrad** [comment]
@thomaslevesque, that was perfect.

**Comment by adamralph** [comment]
Hi chaps, sorry being out of the loop for a while. I have a nice chunky email backlog to get through but I'm sure you've been doing a sterling job in my absence.

WRT this issue, when I read the code snippets in the summary, if I try and take the view of a naive user, the current behaviour seems to follow my intuition:

```C#
    var foo = A.Fake<IFoo>();
    A.CallTo(() => foo.Bar).Returns(42); // after this I'd expect foo.Bar to return 42
    foo.Bar = 123; // I would expect this to override the previous Returns config and calls to foo.Bar to now return 123
    Console.WriteLine(foo.Bar);
```

**Comment by adamralph** [comment]
Perhaps another way to consider this is by regarding a property as a pair of `get_Bar()`, `set_Bar(int value)` methods, which is actually what it is. That might colour things slightly differently. I'll give it some thought... 🤔

**Comment by blairconrad** [comment]
@adamralph, no need to apologize. Everyone has stuff going on.

Your point two comments ago is a good one, but the user is unlikely to ever see code like that. What they will see is my sample in https://github.com/FakeItEasy/FakeItEasy/issues/962#issuecomment-270386236, where the property is explicitly configured in the test but then maybe set in the production code. And this is where the confusion will arise. I should've pointed this out earlier.

**Comment by thomaslevesque** [comment]
>     // I'd expect this to override the previous Returns config and calls to foo.Bar to now return 123
>     // If the property is not set to the value provided that would break my
>     // understanding of the semantics of properties.

That's a good point. However, would you have the same expectation if the property was set by the system under test? In real test code, it's unlikely that a user would set the property after configuring the getter.

>     // I would expect that after this a call to foo.Bar = ... still sets the property
>     // to the value provided but nothing *else* happens,

OK, maybe `DoesNothing()` is not the best example; the way I see it, `DoesNothing()` means that it should do nothing at all, not even apply the default behavior, but I realize it can be interpreted differently. But what if it was `Throws(new Exception("oops"))` instead? You would then expect `foo.Bar = 123` to throw an exception, right? Regardless of the fact that the getter was called or not? Currently, calling the getter changes the behavior, which I think is not what the user would expect.

**Comment by thomaslevesque** [comment]
>     // I would expect that after this a call to foo.Bar = ... still sets the property
>     // to the value provided but nothing *else* happens,

Another thing: this interpretation implies that there would be no way to suppress the default behavior...

**Comment by thomaslevesque** [comment]
Now that Castle.Core 4.0.0 is released, I think we're almost ready to release 3.0.0. But the change proposed in this issue is breaking, so if we don't include it in 3.0.0, it will have to wait until the next major release.

Anyway, we haven't reached a consensus so far. @adamralph, did any of the latest arguments change your mind?

What bothers me the most is the fact that calling the getter changes the future behavior of the setter; this really feels like a bug (not one that users are very likely to run into, fortunately).

If we decide not to go ahead with this change, I think we should at least provide a way to disable the default behavior for read/write properties. Maybe something like this:

    var foo = A.Fake<IFoo>(o => o.DisableReadWritePropertyBehavior());

(the method name is a mouthful, I'm open to better ideas...)

**Comment by blairconrad** [comment]
@adamralph, I hate to be a nag, but have you had any time to consider the change again? It would be nice to reach a consensus sometime soon.
If it's any help, you needn't (IMO) take time to worry about the implementation; I think @thomaslevesque and I can evaluate that well enough.
It's all about whether you support the observed behaviour.
Thanks!

**Comment by adamralph** [comment]
@blairconrad no problem, I don't mind being nagged 😄 

WRT your [previous example](https://github.com/FakeItEasy/FakeItEasy/issues/962#issuecomment-270386236), perhaps I'm missing something, but I see the getter being configured to throw, but I don't see the getter being used in the SUT, so why should I be expecting a throw?

**Comment by blairconrad** [comment]
> I don't see the getter being used in the SUT, so why should I be expecting a throw?

This is true! Um… It's implicit in `DoSomethingWith(this.Foo)`? I really shouldn't've bothered with an extra method at all. Here it is!

```c#
void DoSomethingWith(IFoo foo)
{
   System.Console.Out.WriteLine(foo.Bar);
}
```

**Comment by adamralph** [comment]
@blairconrad that makes sense. In that case, yes, I would expect the exception to be thrown when `foo.get_Bar()` is called.

I have to be honest (apologies if this is just me) and say that I'm no longer sure exactly what change is being proposed here. [This comment](https://github.com/FakeItEasy/FakeItEasy/issues/962#issuecomment-270247144) proposes a solution but only terms of implementation details and not functionally. Would it be possible to summarise the proposed changes, in terms of the public API?

**Comment by thomaslevesque** [comment]
> Would it be possible to summarise the proposed changes, in terms of the public API?

There is no change in the public API shape, it's only the behavior that changes. The proposed changes are described in my summary [here](https://github.com/FakeItEasy/FakeItEasy/issues/962#issuecomment-274171160). Basically, if a property getter or setter has been configured explicitly, this configuration will never be overridden by the default read/write property behavior.

In the examples I gave earlier:

    var foo = A.Fake<IFoo>();
    A.CallTo(() => foo.Bar).Returns(42);
    foo.Bar = 123;
    Console.WriteLine(foo.Bar);

This currently prints 123, and will print 42 with the proposed changes (because the getter is explicitly configured to return 42, `foo.Bar = 123` will have no effect)

    var foo = A.Fake<IFoo>();
    A.CallToSet(() => foo.Bar).DoesNothing();
    Console.WriteLine(foo.Bar);
    foo.Bar = 123;
    Console.WriteLine(foo.Bar);

This currently prints 0 then 123, and will print 0 twice with the proposed changes (because the setter is explicitly configured to do nothing)

**Comment by adamralph** [comment]
@thomaslevesque thanks, and sorry that you had to repeat yourself.

I gave this some more thought and (in a u-turn from what I previously said) I think it's good if, effectively, the getter and setter behave just like any other methods, and what you are proposing is certainly a step in that direction.

If, for a moment we treat the getters and setters as what they actually are, i.e. `foo.Bar`  is actually `foo.GetBar()` and `foo.Bar = 123` is actually `foo.set_Bar(123)` then the only difference with these two "special" methods is that a newly constructed fake effectively has this configuration by default (in theoretical "property method" syntax):

```C#
A.CallTo(() => foo.set_Bar(A<int>._)).Invokes((int bar) =>
    A.CallTo(() => foo.get_Bar()).Returns(bar));
```

If any other configurations after that on either `get_Bar()` or `setBar(int)` behave just like configurations on any other method, i.e. configured independently, with all the usual things that can be done to methods, then I believe that is probably the correct behaviour. It also gives us a nice way to explain "unexpected" behaviour to users, i.e. "think of them as what they are (a pair of methods) and it should all make sense".

One slight wrinkle is that if I want to configure the setter to invoke something, but still effectively "set" the property, then I have to do something like (in theoretical syntax):

```C#
A.CallTo(() => foo.set_Bar(A<int>._)).Invokes((int bar) =>
    {
        // do something
        A.CallTo(() => foo.get_Bar()).Returns(bar);
    });
```

Is this something we can support in actual syntax? E.g. 

```C#
A.CallToSet(() => foo.Bar = A<int>._).Invokes((int bar) =>
    {
        // do something
        A.CallTo(() => foo.Bar).Returns(bar);
    });
```

I'm not sure if that's possible. If it is, it's awkward, but perhaps it's the price to pay for the leaky abstraction of properties?

**Comment by thomaslevesque** [comment]
> One slight wrinkle is that if I want to configure the setter to invoke something, but still effectively "set" the property, then I have to do something like this (in theoretical syntax):

Good point. And there are other cases where one might want to apply the default behavior, but do something else in addition. We currently provide no way to do that. With the current rule system, we always apply exactly one rule. Maybe we should, instead, use the "chain of responsibility" pattern, so that a rule can do something and optionally pass control to the next applicable rule. We could then do something like this:

    A.CallToSet(() => foo.Bar).Invokes((int bar) => { /* do something */ }).ApplyNextRule();

(obviously we would need to come up with a better name than `ApplyNextRule`...)

It would be a pretty big change, but it could enable interesting scenarios, and maybe simplify the overall architecture. For instance, call recording could be done by a simple "pass-through" pre-user rule. Anyway, this is just food for thought, and clearly out of scope for this discussion.

> Is this something we can support in actual syntax? E.g.
> 
>     A.CallToSet(() => foo.Bar = A<int>._).Invokes((int bar) =>
>     {
>         // do something
>         A.CallTo(() => foo.Bar).Returns(bar);
>     });

Yes, this approach already works

**Comment by blairconrad** [comment]
Yeah, @adamralph's scenario is awkward, but I think rarely comes up, and we're not making it worse, I don't think.

And the chain of responsibility feature that @thomaslevesque does sound interesting. I'm not entirely sure it's worth spending a lot of time on (that's code for "I'm not going to do it" :wink:), but might provide benefit in some very specialized cirtcumstances.

Okay, if I read everything right, we all feel like @thomaslevesque's change (as he described) should be included.
Me, I'm already happy with the implementation. @adamralph, do you want to take a look, or are you okay with us merging?

**Comment by adamralph** [comment]
I'll take a quick look at the PR.

**Comment by adamralph** [comment]
As a counterpart to [my comment on the PR](https://github.com/FakeItEasy/FakeItEasy/pull/961#pullrequestreview-20439924), is this issue correctly titled and described?

Also, it's currently marked as a discussion, but #962 is "fixing" it so I guess there's either an enhancement or bug fix happening?

**Comment by thomaslevesque** [comment]
> As a counterpart to my comment on the PR, is this issue correctly titled and described?

Mostly, but it can be improved. I'll change the title to something more accurate.

> Also, it's currently marked as a discussion, but #962 is "fixing" it so I guess there's either an enhancement or bug fix happening?

Well, it's not really a fix, since it wasn't really a bug... I'll rename the PR.

**Comment by adamralph** [comment]
OK, so this is an enhancement?

**Comment by thomaslevesque** [comment]
> OK, so this is an enhancement?

Yes. I'll add the label.

**Comment by blairconrad** [comment]
This issue has been released in FakeItEasy 3.0.0:
https://github.com/FakeItEasy/FakeItEasy/releases/3.0.0

**Comment by DanielRose** [comment]
> One slight wrinkle is that if I want to configure the setter to invoke something, but still effectively "set" the property, then I have to do something like this (in theoretical syntax):
> 
> ```cs
> A.CallTo(() => foo.set_Bar(A<int>._)).Invokes((int bar) =>
>     {
>         // do something
>         A.CallTo(() => foo.get_Bar()).Returns(bar);
>     });
> ```
> 
> Is this something we can support in actual syntax? E.g.
> 
> ```cs
> A.CallToSet(() => foo.Bar = A<int>._).Invokes((int bar) =>
>     {
>         // do something
>         A.CallTo(() => foo.Bar).Returns(bar);
>     });
> ```
> 
> I'm not sure if that's possible. If it is, it's awkward, but perhaps it's the price to pay for the leaky abstraction of properties?

I had this scenario:

```cs
interface IFoo
{
    int Bar { get; set; }
    event EventHandler BarChanged; // Should get called when Bar has changed
}

A.CallToSet(() => foo.Bar).Invokes(call => foo.BarChanged += Raise.With(foo, EventsArgs.Empty));
```

Part of the SUT sets `foo.Bar`, and the other part responds to the event, using the new value. However, the value of `foo.Bar` always was unchanged, which broke my tests. Previously, I sent the new value of `Bar` in the event arguments and used that value, so I never noticed that the property getter didn't work.

Anyway, with the above code I was able to fix it, i.e.

```cs
A.CallToSet(() => foo.Bar).Invokes(call =>
{
    var bar= call.GetArgument<int>(0);
    A.CallTo(() => foo.Bar).Returns(bar);
    foo.BarChanged += Raise.With(foo, EventsArgs.Empty);
});
```

Maybe it would be possible to add some documentation on `CallToSet()` to show this?

**Comment by thomaslevesque** [comment]
Hi @DanielRose,

You can make it a bit simpler:

```csharp
A.CallToSet(() => foo.Bar).Invokes((int bar) =>
{
    A.CallTo(() => foo.Bar).Returns(bar);
    foo.BarChanged += Raise.With(foo, EventsArgs.Empty);
});
```

It's true that the documentation could be more explicit. The fact that the "natural" property behavior no longer applies when the property is explicitly configured is mentioned here, but maybe we could elaborate on the implications.

**Comment by blairconrad** [comment]
Smashing idea, @DanielRose. I created #1783 to track the documentation effort!
