### ISSUE TITLE
document automatic fake injection into systems under test

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#964]
Because we should. And because @apacha [asked about it on StackOverflow](http://stackoverflow.com/q/41572966/1199).

**Comment by thomaslevesque** [comment]
Very interesting article in your SO answer :wink:

In fact, I no longer use this feature, because it's trying to do some of the work of an IoC container, but offers no control at all compared to a full blown container. Instead, I use an [auto-mocking extension for Unity](http://www.thomaslevesque.com/2015/06/14/create-an-auto-mocking-container-with-unity-and-fakeiteasy/) which I use like this:

```
public class BlogManagerTests
{
    [Dependency] public IBlogPostRepository BlogPostRepository { get; set; }
    [Dependency] public ISocialNetworkNotifier SocialNetworkNotifier { get; set; }
    [Dependency] public ITimeService TimeService { get; set; }
 
    [Dependency] public BlogManager BlogManager { get; set; }
 
    public BlogManagerTests()
    {
        new UnityContainer().WithAutoFakes().BuildUp(this);
    }
    ...
}
```
The drawback is that there's no visible difference between the SUT and the dependencies, but it lets me configure explicit dependencies if necessary, and supports the injection of collections (see #578). I think it would be interesting to enable IoC container integration with `Fake.InitializeFixture`.

**Comment by blairconrad** [comment]
> I think it would be interesting to enable IoC container integration with `Fake.InitializeFixture`.

I don't think I quite follow. You mean augment `Fake.InitializeFixture` so it knows about IoCs, to contrast with the approach taken by AutoFac's fakeiteasy integration, just to pick one example?

**Comment by thomaslevesque** [comment]
> I don't think I quite follow.

I don't really follow myself either 😛 
I haven't really thought it through yet, I was just thinking there might be a way to combine the advantages of `Fake.InitializeFixture` and of the approach I described above.

> You mean augment Fake.InitializeFixture so it knows about IoCs, to contrast with the approach taken by AutoFac's fakeiteasy integration, just to pick one example?

No, I don't mean that FakeItEasy should know about specific IoCs; there would have to be an abstraction. I haven't looked closely at the existing FIE integrations yet.

Anyway, this is completely off-topic, sorry for the digression :wink:

**Comment by adamralph** [comment]
Personally I would vote for removing this feature in a future major. IMHO it's half-baked bloat. If anyone wants automatic faking, they can use one of the dedicated libraries. As far as I can tell, neither Moq or NSub attempt to provide this.

**Comment by blairconrad** [comment]
I agree, @adamralph. I'd've suggested earlier, but I know that @thomaslevesque enjoys it. I'd say either "hey, you folk, use something like AutoFixture.AutoFakeItEasy" or maybe build an external package to do the same.

> As far as I can tell, neither Moq or NSub attempt to provide this.

Sure, but just because _they_ don't do something doesn't mean we can't. 😜

**Comment by thomaslevesque** [comment]
> Personally I would vote for removing this feature in a future major. IMHO it's half-baked bloat. If anyone wants automatic faking, they can use one of the dedicated libraries. As far as I can tell, neither Moq or NSub attempt to provide this.

I liked the feature when I discovered it, but I soon encountered annoying limitations. It's better to use an auto-mocking container such as [this](http://www.thomaslevesque.com/2015/06/14/create-an-auto-mocking-container-with-unity-and-fakeiteasy/).

If you guys want to drop it, I won't try to convince you otherwise :wink:

**Comment by blairconrad** [comment]
Supposing we did want to drop it, I assume we'd like  to deprecate in one major release, and remove in the next?
If so, are we in enough of a rush to squeeze the obsolescence into 3.0? I'm not in that much of a hurry.

**Comment by adamralph** [comment]
I don't think we should deprecate in 3.0.0. I think it's OK to deprecate in a 3.x minor, and remove in 4.0.0.

**Comment by blairconrad** [comment]
Okay. But if we decide to go that route, maybe we deprecate in an early 3.x?

**Comment by apacha** [comment]
No, I'd really come to love this feature. Please don't remove it. What exactly do you mean, that it is half-baked? I only wanted that it gets documented a little. 
Switching to AutoFixture.AutoFakeItEasy might be an option, but its even less documented. At least if you deprecate it, please provide a link to an article about AutoFixture.AutoFakeItEasy that explains how to do the same thing. That would be great.

**Comment by thomaslevesque** [comment]
> What exactly do you mean, that it is half-baked?

Well, it's trying to mimick what an IoC container would do (injecting dependencies automatically into classes), but it's much more limited than a real IoC container. You would be better off with an auto-mocking container (see the link in my previous message, or an IoC integration package such as AutoFac.Extras.FakeItEasy). AutoFixture.FakeItEasy would work too, but it would mean that you have to migrate your tests to use AutoFixture, which is a non-trivial amount of work.

**Comment by adamralph** [comment]
What @thomaslevesque said.

**Comment by blairconrad** [comment]
Marking as **on-hold** while we decide whether to remove the feature over at #992.

**Comment by blairconrad** [comment]
Closing, since we're going to remove the feature in #992, and it's already been deprecated in #1102.
