### ISSUE TITLE
Support for Profile7

### ISSUE THREAD

**Issue by jlnostr** [FakeItEasy/FakeItEasy#980]
I tried to install (the purely *awesome*) FakeItEasy on my PCL (to be exactly: `.NETPortable,Version=v4.5,Profile=Profile`) but unfortunately, VS (2017 RC) told me that FakeItEasy doesn't support it. But to quote #833, there IS support for this profile.

> Currently we produce a PCL Profile7 assembly (net40, dotnet and win8) and put it in a dotnet folder in the nupkg.

Could someone put some clarification on this?

**Comment by thomaslevesque** [comment]
Hi @jlnostr,

> Currently we produce a PCL Profile7 assembly (net40, dotnet and win8) and put it in a dotnet folder in the nupkg.

That quote is about the analyzer, not the main library. FakeItEasy itself supports .NET 4.0 and .NET Standard 1.6 (if you use the pre-release 3.0.0 version).

Why do you need to add FakeItEasy to a PCL? Unit tests don't usually need to be PCLs... Are you using it for something other than unit tests?

**Comment by jlnostr** [comment]
Nope, my unit test project is actually a PCL. Is there a better way of doing this for Xamarin.Forms apps? I've just used their unit test project template.

**Comment by jlnostr** [comment]
Actually, I copied a unit test project from another project. Now it works :D
Thanks anyway for the quick help!
