### ISSUE TITLE
Collapse netstd/framework packages

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#991]
I know that we're eventually going to move to a full csproj-based solution anyhow, but I wonder if we wouldn't be better off collapsing the netstd projects so we have a single set of projects, not unlike [xBehave.net](https://github.com/xbehave/xbehave.net) and [SelfInitializingFakes](https://github.com/blairconrad/SelfInitializingFakes).
It may even make migrating to the new `csproj`s easier.

----
**Update** after discussion below, we've decided to wait until after we switch to VS2017's new csproj format.

When we _do_ make this switch, though, we may also want to 

- [ ]  generate a .net45 lib, which will
    - [ ] allow event handlers whose event args don't extend `EventArgs` (#1008)

**Comment by thomaslevesque** [comment]
I'm not sure I understand... Are you saying that we should generate the .NET Standard and .NET 4.0 assemblies from the same project?

It makes sense, but it worries me a bit, because the IDE and tools have poor support for project.json.

**Comment by blairconrad** [comment]
That is exactly what I'm saying. Many projects (xUnit, xBehave, SelfInitializingFakes) do this.
I have noticed that it's harder to run unit tests in the IDE, but have been getting by with [Rocketship TestRunner](http://www.testdriven.net/default.aspx).

I don't mind us _not_ doing this either. Things seem to be working well enough as is.

I was thinking about picking up #645 and had just been wondering whether it would be easier before or after we made a move like this. I can easily work on #645 with the projects as is, though.

**Comment by blairconrad** [comment]
Then again, in #645, we suggest holding off.
Maybe I'll just look elsewhere for work!

**Comment by thomaslevesque** [comment]
> I have noticed that it's harder to run unit tests in the IDE, but have been getting by with Rocketship TestRunner.

I've seen problems with unit tests too. I'm using the R# runner. Maybe I'll give TestDriven a try.

**Comment by adamralph** [comment]
It may be better to wait for VS2017 RTM to bed-in a little, and make the switch to the new csproj, before doing this.

**Comment by blairconrad** [comment]
**on-hold** while we're waiting for VS2017

**Comment by adamralph** [comment]
> - [ ]  generate a .net45 lib, which will
>    - [ ] allow event handlers whose event args don't extend `EventArgs` (like #361 accomplished for the .NET Standard dll)

I raised #1008 to represent this enhancement.

**Comment by blairconrad** [comment]
I updated the description to refer to #1008. :tongue:

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).
