### ISSUE TITLE
Remove automatic fake injection into system under test (InitializeFixture) in 5.0.0

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy#992]
As suggested by @adamralph in https://github.com/FakeItEasy/FakeItEasy/issues/964#issuecomment-280834895. I'm creating this issue because if we go through with it, the decision deserves to be visible.

He suggested that the feature is "half-baked bloat". 

@thomaslevesque says

> I liked the feature when I discovered it, but I soon encountered annoying limitations. It's better to use an auto-mocking container such as [this](http://www.thomaslevesque.com/2015/06/14/create-an-auto-mocking-container-with-unity-and-fakeiteasy/).

and that

> Well, it's trying to mimick what an IoC container would do (injecting dependencies automatically into classes), but it's much more limited than a real IoC container. You would be better off with an auto-mocking container (see the link in my previous message, or an IoC integration package such as AutoFac.Extras.FakeItEasy). AutoFixture.FakeItEasy would work too, but it would mean that you have to migrate your tests to use AutoFixture, which is a non-trivial amount of work.

@adamralph agreed. @blairconrad (that's me) said nothing at the time, but agrees. An external mechanism (and several exist) seems like a better choice.

@apacha [says](https://github.com/FakeItEasy/FakeItEasy/issues/964#issuecomment-280915464)

> No, I'd really come to love this feature. Please don't remove it. What exactly do you mean, that it is half-baked? I only wanted that it gets documented a little. 
Switching to AutoFixture.AutoFakeItEasy might be an option, but its even less documented. At least if you deprecate it, please provide a link to an article about AutoFixture.AutoFakeItEasy that explains how to do the same thing. That would be great.

**Comment by blairconrad** [comment]
I'm marking #578 and #964 as **on-hold** until we make a decision, as it makes no sense to work on them if we decide to remove the feature.

**Comment by blairconrad** [comment]
@apacha, I've been poking about recently, and perhaps one of 

* [AutoFakeItEasyData](https://github.com/Socres/Socres/wiki/AutoFakeItEasyData) or
* [FakeItEasy.Auto](http://jamiehumphries.github.io/FakeItEasy.Auto/) (not an official FakeItEasy project) 

would be acceptable replacements?

**Comment by apacha** [comment]
@blairconrad, FakeItEasy.Auto looks like the thing I'm after. I will give it a try and if you remove the InitializeFixture-feature from FakeItEasy, I will just try to migrate to any of the proposed alternatives you and @thomaslevesque pointed out to, or stick with the current version of FakeItEasy on that particular project.

**Comment by blairconrad** [comment]
@apache, do let us know how you find FakeItEasy.Auto. I really don't want
to leave you hanging.

On May 21, 2017 09:11, "Alexander Pacha" <notifications@github.com> wrote:

@blairconrad <https://github.com/blairconrad>, FakeItEasy.Auto looks like
the thing I'm after. I will give it a try and if you remove the
InitializeFixture-feature from FakeItEasy, I will just try to migrate to
any of the proposed alternatives you and @thomaslevesque
<https://github.com/thomaslevesque> pointed out to, or stick with the
current version of FakeItEasy on that particular project.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FakeItEasy/FakeItEasy/issues/992#issuecomment-302935890>,
or mute the thread

**Comment by blairconrad** [comment]
Sorry. @apacha. Autocorrect, and I didn't notice.

**Comment by thomaslevesque** [comment]
This change has been released in FakeItEasy [5.0.0](https://github.com/FakeItEasy/FakeItEasy/releases/5.0.0).
