### ISSUE TITLE
Replace StyleCop.MSBuild with StyleCop.Analyzers

### ISSUE THREAD

**Issue by adamralph** [FakeItEasy/FakeItEasy#996]
StyleCop.MSBuild doesn't work with pure project.json projects, so in that respect, #991 is blocked by this. However, it may well work with the new csproj, so in that respect #991 may not be blocked by this.

While StyleCop.MSBuild _may_ work with the new csproj, I believe it's better to move to StyleCop.Analyzers. It uses the Roslyn analyzer infra, so no need for custom build targets, and no need for `Settings.StyleCop` and its custom editor (like any other Roslyn analyzer, StyleCop.Analyzers uses code analysis rulesets).

**Comment by blairconrad** [comment]
>(like any other Roslyn analyzer, StyleCop.Analyzers uses code analysis rulesets).

but doesn't respect them. For example, I can't disable SA1633. ☹️

**Comment by thomaslevesque** [comment]
According to https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1701, it should be possible to disable SA1633:

> Now the only way for us is to disable this rule for all files.

(the bug in that issue is that specific occurrences of this warning can't be suppressed)

**Comment by blairconrad** [comment]
It should be possible, but I've failed to do so. The entry in my ruleset was not respected.

**Comment by thomaslevesque** [comment]
> It should be possible, but I've failed to do so. The entry in my ruleset was not respected.

Is it respected for other rules?

**Comment by blairconrad** [comment]
I do not know off-hand. I haven't tried to disable many.

**Comment by blairconrad** [comment]
Not respected for SA1507 (the next one I tried).

**Comment by adamralph** [comment]
I'm not sure what the problem is. I do this in xbehave and it works perfectly: https://github.com/xbehave/xbehave.net/blob/fa59baba78a0ad93fd229318abbcceb3def7cd0a/src/Xbehave.ruleset#L7

**Comment by blairconrad** [comment]
That's under VS2017 with csproj, @adamralph? It looks like your project is still using xproj.

**Comment by adamralph** [comment]
😢 so this is yet another thing that is broken in VS2017?

**Comment by blairconrad** [comment]
Well, it could be my ineptitude. But I think it's broken.

**Comment by thomaslevesque** [comment]
> However, it may well work with the new csproj

[It doesn't](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/229-xeeeriry#L388) 😞

**Comment by thomaslevesque** [comment]
In fact, it works with Visual Studio or when building with MSBuild, but not when building with `dotnet build`.

**Comment by thomaslevesque** [comment]
StyleCop.Analyzers doesn't seem to be very active... The first stable release is more than 1 year old, and since then there has only been one beta release (in November).

**Comment by adamralph** [comment]
Not hugely active, but there was [a patch on 26 March](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases/tag/1.0.1).

**Comment by thomaslevesque** [comment]
> Not hugely active, but there was a patch on 26 March.

And it works pretty well anyway.

**Comment by blairconrad** [comment]
This change has been released as part of [FakeItEasy 3.4.0](https://github.com/FakeItEasy/FakeItEasy/releases/tag/3.4.0).
